### ISSUE TITLE
[Bug]: close HMR，devServer.liveReload also not work

### ISSUE THREAD

**Issue by ChenXplorer** [web-infra-dev/rsbuild#1031]
### Version

```sh
System:
    OS: macOS 13.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 220.59 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 120.0.6099.109
    Safari: 16.6
  npmPackages:
    @rsbuild/core: ^0.2.8 => 0.2.8 
    @rsbuild/plugin-react: ^0.2.8 => 0.2.8
```

### Details

close HMR，devServer.liveReload also not work,  

what is wrong

### Reproduce link

see DETAILS

### Reproduce Steps

1. npm create rsbuild@latest
2. choose react and ts
3. modify rsbuild.config.ts
```ts
  tools: {
    rspack: {
      devServer: {
        liveReload: true  // also not work
      }
    }
  },
  dev: {
    hmr:false
  },

**Comment by inottn** [comment]
Hi, you can give it a try like this.
```
  tools: {
    rspack: {
      devServer: {
        hot: false,
        liveReload: true,
      },
    },
  },
```

**Comment by SoonIter** [comment]
I tried to set hmr to false, it really didn't work, but I was surprised that it works when I set hmr to true.

```js
export default defineConfig({
  plugins: [pluginReact()],
  tools: {
    rspack: config => {
      (config.devServer ??= {})
      config.devServer.liveReload = true
      config.devServer.hot = false
    },
  },
  dev: {
    hmr: true,
  },
});

```

**Comment by inottn** [comment]
> I tried to set hmr to false, it really didn't work, but I was surprised that it works when I set hmr to true.

Because setting hmr to false will disable the react-refresh plugin, but liveReload depends on this plugin.

**Comment by chenjiahan** [comment]
`rspackConfig.devServer` can only be used with `@rspack/dev-server` (same as webpack / webpack-dev-server).

Rsbuild does not depend on `@rspack/dev-server`, so `rspackConfig.devServer` should not work. We can add some content about this in the Rspack/Rsbuild document, just like webpack:

![image](https://github.com/web-infra-dev/rsbuild/assets/7237365/2db6fe3b-24fd-486a-b417-026fee372dc0)

https://webpack.js.org/configuration/dev-server/

**Comment by ChenXplorer** [comment]
> I tried to set hmr to false, it really didn't work, but I was surprised that it works when I set hmr to true.
> 
> ```js
> export default defineConfig({
>   plugins: [pluginReact()],
>   tools: {
>     rspack: config => {
>       (config.devServer ??= {})
>       config.devServer.liveReload = true
>       config.devServer.hot = false
>     },
>   },
>   dev: {
>     hmr: true,
>   },
> });
> ```

it works， thx
