### ISSUE TITLE
[Feature]: Allow customizing the PUBLIC_ environment variable prefix for automatic injection

### ISSUE THREAD

**Issue by vacekj** [web-infra-dev/rsbuild#1037]
### What problem does this feature solve?

Currently, only environment variables prefixed with PUBLIC_ can be auto-injected. This presents a hurdle in migrating from CRA, as it injects all variables automatically. Additionally, Vite allows customizing this prefix via https://vitejs.dev/config/shared-options.html#envprefix. It would be great to be able to
 include this customization option in rsbuid.

### What does the proposed API look like?

```typescript
export default defineConfig({
	source: {
		envVarPrefix: "PUBLIC_"
	}
});
```

Setting this to an empty string or false would allow any environment variable from a corresponding `.env` file to be injected.

**Comment by chenjiahan** [comment]
Thanks for the suggestion, Rsbuild will support this feature to help CRA users migrate.

There are some differences between Rsbuild and Vite in the implementation of loading env:

- Rsbuild will load .env first and allow users to access these env vars in the `rsbuild.config.ts`. 
- Vite loads the .env file after loading the configuration file.

So it will be easier for Vite to implement this feature. For Rsbuild, we need to consider whether we should modify the env prefix through config, or maybe some other approches.

**Comment by chenjiahan** [comment]
Rsbuild will export `loadEnv` method to support loading env vars with different prefix.

> To be compatible with CRA's behavior, you can manually call Rsbuild's [loadEnv](https://rsbuild.dev/api/javascript-api/core#loadenv) method to read environment variables starting with `REACT_APP_`, and inject them into the client code through the [source.define](https://rsbuild.dev/config/source/define) config.

```ts title="rsbuild.config.ts"
import { defineConfig, loadEnv } from '@rsbuild/core';

const { publicVars } = loadEnv({ prefixes: ['REACT_APP_'] });

export default defineConfig({
  source: {
    define: publicVars,
  },
});
```
