### ISSUE TITLE
[Bug]: Check Syntax plugin not report errors as documented

### ISSUE THREAD

**Issue by Jungzl** [web-infra-dev/rsbuild#1058]
### Version

```sh
System:
    OS: Windows 11 10.0.22631
    CPU: (24) x64 13th Gen Intel(R) Core(TM) i7-13700
    Memory: 2.33 GB / 15.77 GB
  Browsers:
    Edge: Chromium (120.0.2210.91)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @rsbuild/core: ^0.2.9 => 0.2.9
    @rsbuild/plugin-check-syntax: ^0.2.9 => 0.2.9
    @rsbuild/plugin-vue: ^0.2.9 => 0.2.9
```

### Details

🔻expected:
![image](https://github.com/web-infra-dev/rsbuild/assets/35426360/9f7af9ba-fd90-4c58-933d-8c2c2276ee90)
🔻actual:
![image](https://github.com/web-infra-dev/rsbuild/assets/35426360/8f510430-25a2-44ab-ad17-284dcaccbae4)

source is more like an output and code is not formatted, which makes finding which module or code should be polyfilled hard.

### Reproduce link

https://github.com/Jungzl/rsbuild-plugin-syntax-demo

### Reproduce Steps

```bash
pnpm build
```

**Comment by chenjiahan** [comment]
Sorry the check syntax document provides an incorrect sourceMap demo 😂

With the following source map config, the error reports will be good:

![image](https://github.com/web-infra-dev/rsbuild/assets/7237365/79cd9015-eff4-4eaf-a0d3-e2532c769f85)

![image](https://github.com/web-infra-dev/rsbuild/assets/7237365/0553653c-4b54-4d77-a562-4ac2b20830ea)
