### ISSUE TITLE
[Bug]: ReferenceError: meta/title is not defined

### ISSUE THREAD

**Issue by 9aoy** [web-infra-dev/rsbuild#1059]
### Version

```sh
rsbuild: 0.2.9
```

### Details

get 'ReferenceError: meta is not defined' when custom html use meta / title params

index.html:

```diff
<!DOCTYPE html>
<html>
<head>
+  <%= meta %>
+  <title><%= title %></title>

</head>
<body>
  <div id="root" />
</body>

</html>

```

<img width="804" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/22373761/b1d7e014-921f-44cd-b665-a753cee32f25">

### Reproduce link

none

### Reproduce Steps

as above

**Comment by chenjiahan** [comment]
meta and title are injected via HtmlBasicPlugin, `<%= meta %>` and `<%= title %>` are no longer needed.
