### ISSUE TITLE
[Feature]: printURLs support configuration into rsbuild.config

### ISSUE THREAD

**Issue by lp0124** [web-infra-dev/rsbuild#1121]
### What problem does this feature solve?

Hope to disable the default URL output and be able to output a custom URL. Currently, as seen in the documentation, this configuration is only exposed on the JS API side, and I hope it can be exposed in the configuration file.

<img width="915" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/22974194/a3da8cb8-8985-435b-b986-8d4eefa12eee">

### What does the proposed API look like?

```js
export default {
  server: {
    printURLs: false,
  },
}
```
or
```js
export default {
  dev: {
    printURLs: false,
  },
}
```

**Comment by chenjiahan** [comment]
Rsbuild can add a new `server.printURLs` option, I will re-design the API to make it more flexible.

And the JS API side option should be deprecated in v0.3.0.
