### ISSUE TITLE
[Bug]: ElementUI Table display blank

### ISSUE THREAD

**Issue by Ttou** [web-infra-dev/rsbuild#1132]
### Version

```sh
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M2
    Memory: 5.44 GB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Safari: 17.2.1
  npmPackages:
    @rsbuild/core: ^0.2.13 => 0.2.13 
    @rsbuild/plugin-vue2: ^0.2.13 => 0.2.13
```

### Details

ElementUI 表格有数据时显示空白

https://github.com/web-infra-dev/rsbuild/assets/4298437/4abe3df6-67ca-41fd-8e66-28b51d274b85

### Reproduce link

https://github.com/Ttou/rsbuild-element-table

### Reproduce Steps

1. pnpm i
2. pnpm dev

**Comment by chenjiahan** [comment]
If using Vue 2.7, we need to add alias config, see: https://github.com/ElemeFE/element/issues/21968

@rsbuild/plugin-vue2 will add default alias config in the next version.
