### ISSUE TITLE
[Bug]: local dev hmr speed slow

### ISSUE THREAD

**Issue by coderbaozi** [web-infra-dev/rsbuild#1222]
### Version

```sh
mac
chrome
0.2.18
```

### Details

<img width="678" alt="截屏2024-01-10 02 10 28" src="https://github.com/web-infra-dev/rsbuild/assets/103836393/db7371c2-3dca-4d3a-ad01-cd2d5a3a025a">

### Reproduce link

null

### Reproduce Steps

menorepo workspace: *  
When using artifact referencing, the current project references the artifacts built from other sub-projects.
but the speed is so slowly

**Comment by chenjiahan** [comment]
Hi, can you provide more information for this issue, such as the content of `rsbuild.config.ts` or more details.

**Comment by chenjiahan** [comment]
As the issue was labeled with `need reproduce`, but no response in 3 days. This issue will be closed. Feel free to comment and reopen it if you have any further questions. For background, please refer to [Why reproductions are required](https://antfu.me/posts/why-reproductions-are-required).
