### ISSUE TITLE
[Bug]: close HMR， infinitely reload

### ISSUE THREAD

**Issue by ChenXplorer** [web-infra-dev/rsbuild#1231]
### Version

```sh
System:
    OS: macOS 13.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 220.59 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 120.0.6099.109
    Safari: 16.6
  npmPackages:
    @rsbuild/core: ^0.2.8 => 0.2.8 
    @rsbuild/plugin-react: ^0.2.8 => 0.2.8
```

### Details

open two same pages  http://localhost:8080/ ， infinitely reload will  happen

### Reproduce link

NONE

### Reproduce Steps

1. npm create rsbuild@latest
2. choose react and ts
3. modify rsbuild.config.ts
```
  dev: {
    hmr: false,
  },
4. open two same pages  http://localhost:8080/ ， infinitely reload will  happen
```

**Comment by chenjiahan** [comment]
Thanks for your feedback! I have reproduced this issue, we will fix it soon.
