### ISSUE TITLE
[MF]: plugin for module federation

### ISSUE THREAD

**Issue by douglaszaltron** [web-infra-dev/rsbuild#1234]
### What problem does this feature solve?

The feature addresses the need for a streamlined and efficient way to manage module federation configurations in ReactJS-based or other development environments. Specifically, the plugin for module federation would allow developers to:

- Automatically set up configurations related to module federation, enhancing the efficiency of the development process.
- Read a default configuration file named `modulefederation.config.js`, simplifying the initial setup.
- Provide flexibility by allowing developers to change the name of this default configuration file.

This feature solves the problem of manually configuring module federation settings, which can be time-consuming and prone to errors. By automating these processes and offering customization options, the plugin aims to improve the development workflow, maintainability, and scalability of applications using module federation in the rsbuild environment.

### What does the proposed API look like?

It would be interesting to have a plugin for module federation.

`import { pluginModuleFederation } from '@rsbuild/plugin-module-federation';
`
It already sets up the configurations and is able to read a file as the default `modulefederation.config.js`, and we can change this name.

@chenjiahan Is it feasible and does it make sense for rsbuild?"

**Comment by chenjiahan** [comment]
Thanks for your suggestion! We do plan to provide better support for module federation in Rsbuild, maybe even in Rsbuild core.

The design of the relevant API has not yet been determined. @ScriptedAlchemy and @2heal1  may be able to provide more input for this ❤️

**Comment by ScriptedAlchemy** [comment]
Yes. I also wanted to add http endpoint support to allow for APIs to configure the plugin. We need to have a larger discussion about what and how it should look.

File based was another possibility. Also reading exports field and mirroring it in MFP like a package would

**Comment by douglaszaltron** [comment]
@chenjiahan I'm testing with module federation, but with the new version (v0.3.8), it has stopped working. It halts at 70% sealing plugins. Do you know what could be the issue? Here's an example of my configuration.

![image](https://github.com/web-infra-dev/rsbuild/assets/4502670/2073dc60-f479-456e-a664-53feb734b582)

![image](https://github.com/web-infra-dev/rsbuild/assets/4502670/2eb97cff-1389-483a-a82f-8b5e09eea90f)

**Comment by chenjiahan** [comment]
@douglaszaltron Can you provide a repro that can help us troubleshoot? ❤️

**Comment by chenjiahan** [comment]
@ahabhgk It seems rspack 0.5.2 broke Rsbuild + module federation example, can you help check it.

Steps:

- https://github.com/web-infra-dev/rsbuild/tree/main/examples/module-federation
- cd examples/module-federation/host
- pnpm dev
