### ISSUE TITLE
我在本地起服务后，一些静态资源我放在了public文件夹下，然后访问这些静态文件返回的是index.html文件

### ISSUE THREAD

**Issue by wengjiacheng** [web-infra-dev/rsbuild#1240]
我在本地起服务后，一些静态资源我放在了public文件夹下，然后访问这些静态文件返回的都是是index.html文件
不是文件本身

_Originally posted by @wengjiacheng in https://github.com/web-infra-dev/rsbuild/discussions/1230_

**Comment by chenjiahan** [comment]
sorry，当前 issue 的格式过于不规范，麻烦通过 issue 模板创建，并尽量提供复现方式：https://github.com/web-infra-dev/rsbuild/issues/new/choose
