### ISSUE TITLE
[Bug]: 放在public下的css文件和js文件在开发环境下访问不到，返回index.html文件

### ISSUE THREAD

**Issue by wengjiacheng** [web-infra-dev/rsbuild#1242]
### Version

```sh
System:
    OS: macOS 13.3.1
    CPU: 2.5 GHz Intel Core i7
    Memory: 16 GB 2133 MHz LPDDR3
  Browsers:
    Chrome:  120.0.6099.109
  npmPackages:
    "@rsbuild/core": "^0.2.15",
    "@rsbuild/plugin-vue2": "^0.2.15",
```

### Details

我将一些静态文件放在了public文件夹下，在直接在html文件中通过标签引用，但是在开发环境请求这些资源返回的都是index.html
然后我将server. htmlFallback设置为false,再请求这些文件就变成404了,不知道是不是在开发环境下public下的文件没有复制到dist文件中
![12333](https://github.com/web-infra-dev/rsbuild/assets/24770388/4620d307-a612-4750-b9ca-e4286fcb1784)
配置
![121444](https://github.com/web-infra-dev/rsbuild/assets/24770388/d47de804-b526-45d0-a5a4-6e977b676cf0)
引用
![12555](https://github.com/web-infra-dev/rsbuild/assets/24770388/85c27bbb-6389-44e9-8f2d-63eb58da35b8)
![12666](https://github.com/web-infra-dev/rsbuild/assets/24770388/a5459756-2344-4fb7-b55b-7c0e3e0bb681)

### Reproduce link

NONE

### Reproduce Steps

npm run dev

**Comment by 9aoy** [comment]
不需要添加 assetPrefix,  public 中的资源对应的是 dist 根目录
https://rsbuild.dev/zh/config/server/public-dir#publicdir

![20240111-113028](https://github.com/web-infra-dev/rsbuild/assets/22373761/37cf8a8a-8c5a-446a-a7ff-939103453122)

**Comment by wengjiacheng** [comment]
我是需要打包放在同一放在cv3文件夹下，应该需要添加assetPrefix吧

**Comment by wengjiacheng** [comment]
我把dev下的assetPrefix去掉了，资源可以正常访问到了，但是好像并不是我想要的效果，
我想要打包到cv3目录下，所以应该output.assetPrefix设置成了/cv3 dev.assetPrefix也需要设置把，这样访问路径才一致吧
去掉了路径就变成'/'不是‘/v3’了
![1223334444](https://github.com/web-infra-dev/rsbuild/assets/24770388/8ea59516-c58b-40f6-bb71-10b7ea934e85)

**Comment by wengjiacheng** [comment]
> 不需要添加 assetPrefix, public 中的资源对应的是 dist 根目录 https://rsbuild.dev/zh/config/server/public-dir#publicdir
> 
> ![20240111-113028](https://private-user-images.githubusercontent.com/22373761/295781380-37cf8a8a-8c5a-446a-a7ff-939103453122.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NjQzNzYsIm5iZiI6MTcwNDk2NDA3NiwicGF0aCI6Ii8yMjM3Mzc2MS8yOTU3ODEzODAtMzdjZjhhOGEtOGM1YS00NDZhLWE3ZmYtOTM5MTAzNDUzMTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDA5MDc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1Y2NkMWIyMDYyYWRiOGMxOTkyYjU5ZjUyZGQyMmFkMmM0ZTZkNmY4YTc2OWZjMjZlNWRhZjZjMTg5YTQxYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zRHoenV9Pe_b-5zvqE4y6wGVpEkJM0BCHK8DauGeT-s)

我把dev下的assetPrefix去掉了，资源可以正常访问到了，但是好像并不是我想要的效果，
我想要打包到cv3目录下，所以应该output.assetPrefix设置成了/cv3 dev.assetPrefix也需要设置把，这样访问路径才一致吧
去掉了路径就变成'/'不是‘/v3’了
![1223334444](https://github.com/web-infra-dev/rsbuild/assets/24770388/8ea59516-c58b-40f6-bb71-10b7ea934e85)

**Comment by 9aoy** [comment]
> 我把dev下的assetPrefix去掉了，资源可以正常访问到了，但是好像并不是我想要的效果， 我想要打包到cv3目录下，所以应该output.assetPrefix设置成了/cv3 dev.assetPrefix也需要设置把，这样访问路径才一致吧 去掉了路径就变成'/'不是‘/v3’了 !

public assets 并不属于构建产物，它没有参与构建和任何转换，所以 dev.assetPrefix / output.assetPrefix 不会生效，我会在文档中更新这一点。在 rspack / webpack / vite 中同样是这个行为。

**Comment by wengjiacheng** [comment]
> > 我把dev下的assetPrefix去掉了，资源可以正常访问到了，但是好像并不是我想要的效果， 我想要打包到cv3目录下，所以应该output.assetPrefix设置成了/cv3 dev.assetPrefix也需要设置把，这样访问路径才一致吧 去掉了路径就变成'/'不是‘/v3’了 !
> 
> public assets 并不属于构建产物，它没有参与构建和任何转换，所以 dev.assetPrefix / output.assetPrefix 不会生效，我会在文档中更新这一点。在 rspack / webpack / vite 中同样是这个行为。

不好意思， 我还是有点不明白
可能我没有说清楚我想要的效果，我想要public的路径是'/cv3' 不是'/', 因为我想要打包后文件放在dist/cv3下
项目中也有很多地方用的baseUrl也是'/cv3'
现在是编译出来的路径是我想要的
<img width="424" alt="123333333" src="https://github.com/web-infra-dev/rsbuild/assets/24770388/77f46508-f4e4-4824-9659-6c6f5278065d">
问题是我本地开发，请求这几个静态文件，请求不到404直接返回了index.html

**Comment by wengjiacheng** [comment]
> > 我把dev下的assetPrefix去掉了，资源可以正常访问到了，但是好像并不是我想要的效果， 我想要打包到cv3目录下，所以应该output.assetPrefix设置成了/cv3 dev.assetPrefix也需要设置把，这样访问路径才一致吧 去掉了路径就变成'/'不是‘/v3’了 !
> 
> public assets 并不属于构建产物，它没有参与构建和任何转换，所以 dev.assetPrefix / output.assetPrefix 不会生效，我会在文档中更新这一点。在 rspack / webpack / vite 中同样是这个行为。

在npm run dev 时候是不会把public复制到dist目录下的
![12233333](https://github.com/web-infra-dev/rsbuild/assets/24770388/fab007f4-0049-4c1b-aaf8-4f78690c6ad1)
请问这有什么方式能够让他复制进去吗？

**Comment by 9aoy** [comment]
> 在npm run dev 时候是不会把public复制到dist目录下的
> 请问这有什么方式能够让他复制进去吗？

dev 的时候是服务器直接 serve public 目录的，通过 /xxx 可以直接访问，什么场景需要让它复制到 dist目录下么？

**Comment by vaesonshu** [comment]
按照你的需求，我理解的不知道对不对。

1. 首先，你可以把你需要的资源文件放到 `public/cv3` 目录中。
![1](https://github.com/web-infra-dev/rsbuild/assets/78685759/bd057e6b-19f4-4346-838e-e850bc2ccf2f)

2. 把 `public` 中 `cv3 `文件夹下的所有资源复制到` dist/cv3` 中，并且配置模板参数。
![2](https://github.com/web-infra-dev/rsbuild/assets/78685759/aa7afb38-dc84-480f-a569-4f4f5c535ef9)

3. 引用配置好的模板参数变量名。
![3](https://github.com/web-infra-dev/rsbuild/assets/78685759/15d64682-ad3b-4f88-9598-6656679d69f2)

4. 运行 `npm run dev`，查看是否正确读取。
![5](https://github.com/web-infra-dev/rsbuild/assets/78685759/fa18f4f0-bb39-41fa-a751-98406cf2b701)

5. 运行 `npm run build`，查看打包产物，你需要的资源都被复制到`dist/cv3`文件夹下了。
![4](https://github.com/web-infra-dev/rsbuild/assets/78685759/d8120929-fcef-4cd8-96a6-2d0a904e49b5)

6. 运行`npm run preview`，查看打包后的文件是否正确读取。
![6](https://github.com/web-infra-dev/rsbuild/assets/78685759/8f97303e-5ccc-40a2-bffa-918232cd04ac)

**Comment by wengjiacheng** [comment]
> > 在npm run dev 时候是不会把public复制到dist目录下的
> > 请问这有什么方式能够让他复制进去吗？
> 
> dev 的时候是服务器直接 serve public 目录的，通过 /xxx 可以直接访问，什么场景需要让它复制到 dist目录下么？

之前使用vue-cli 统一配置publicPath 是/cv3  所以想保持一样的的规则
我看build是我想要的，但是dev时候没有复制文件，有什么方式能把文件复制到dist, 以dist为public目录吗在dev的时候

**Comment by vaesonshu** [comment]
> ### Version
> ```shell
> System:
>     OS: macOS 13.3.1
>     CPU: 2.5 GHz Intel Core i7
>     Memory: 16 GB 2133 MHz LPDDR3
>   Browsers:
>     Chrome:  120.0.6099.109
>   npmPackages:
>     "@rsbuild/core": "^0.2.15",
>     "@rsbuild/plugin-vue2": "^0.2.15",
> ```
> 
> ### Details
> 我将一些静态文件放在了public文件夹下，在直接在html文件中通过标签引用，但是在开发环境请求这些资源返回的都是index.html 然后我将server. htmlFallback设置为false,再请求这些文件就变成404了,不知道是不是在开发环境下public下的文件没有复制到dist文件中 ![12333](https://private-user-images.githubusercontent.com/24770388/295779902-4620d307-a612-4750-b9ca-e4286fcb1784.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MDk5NzcsIm5iZiI6MTcwNTUwOTY3NywicGF0aCI6Ii8yNDc3MDM4OC8yOTU3Nzk5MDItNDYyMGQzMDctYTYxMi00NzUwLWI5Y2EtZTQyODZmY2IxNzg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDE2NDExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1ZDE5MTYzNDhiY2NlOGY0ODcwMWQzY2U4NTY1NjMzYzNiOWRjYTE1NGU0Mzk3MmFjYzM1ZDA3Y2NlMjU0MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Yf5XXiz4Kh_uB4C9t20nPg9vGGOcWu6gL72AEqiV5A4) 配置 ![121444](https://private-user-images.githubusercontent.com/24770388/295780195-d47de804-b526-45d0-a5a4-6e977b676cf0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MDk5NzcsIm5iZiI6MTcwNTUwOTY3NywicGF0aCI6Ii8yNDc3MDM4OC8yOTU3ODAxOTUtZDQ3ZGU4MDQtYjUyNi00NWQwLWE1YTQtNmU5NzdiNjc2Y2YwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDE2NDExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3N2ZlNDA3OWFiM2UxYjYyM2Y3NGRlZjJkZDcwMzYwOWEwYWMxOTU4YmI1YmE3NDNhNDJhOWVhYWYyNWI5OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J7ZW3u3EpNPZydsUGEidVHK4tCfMvHpvkWqQ57v5r4g) 引用 ![12555](https://private-user-images.githubusercontent.com/24770388/295780378-85c27bbb-6389-44e9-8f2d-63eb58da35b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MDk5NzcsIm5iZiI6MTcwNTUwOTY3NywicGF0aCI6Ii8yNDc3MDM4OC8yOTU3ODAzNzgtODVjMjdiYmItNjM4OS00NGU5LThmMmQtNjNlYjU4ZGEzNWI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDE2NDExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkNjYyYWM2ODQ0YWU4MjY2NWIzYzk3NGRhZDMwZmRiZGE1NzA0MTY3ZTNhNGU5MmNjODljODI5ZDU0MzEwMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QQdGhOAKXYGvYx_96hETpwhqgdOeMndHukLBton7MN4) ![12666](https://private-user-images.githubusercontent.com/24770388/295780795-a5459756-2344-4fb7-b55b-7c0e3e0bb681.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MDk5NzcsIm5iZiI6MTcwNTUwOTY3NywicGF0aCI6Ii8yNDc3MDM4OC8yOTU3ODA3OTUtYTU0NTk3NTYtMjM0NC00ZmI3LWI1NWItN2MwZTNlMGJiNjgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDE2NDExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1NTBmYWVmZTI2OWY0OGEyNTE5ZDQ5MDcwNTVhYTZmNjg3OGJjMTQ2NzhiMGU1OWU5YzNhZmQ4OWY0Zjk0MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KJgT_GSrIVuM_HNnI7bTN0qY8qv6RP_uOBkZ6PqOiaI)
> 
> ### Reproduce link
> NONE
> 
> ### Reproduce Steps
> npm run dev

大致明白你的意思了，开发环境和生产环境区分下就没问题了，说一下你需要改的部分。

1. 首先，把这个去掉

> ### Version
> ```shell
> System:
>     OS: macOS 13.3.1
>     CPU: 2.5 GHz Intel Core i7
>     Memory: 16 GB 2133 MHz LPDDR3
>   Browsers:
>     Chrome:  120.0.6099.109
>   npmPackages:
>     "@rsbuild/core": "^0.2.15",
>     "@rsbuild/plugin-vue2": "^0.2.15",
> ```
> 
> ### Details
> 我将一些静态文件放在了public文件夹下，在直接在html文件中通过标签引用，但是在开发环境请求这些资源返回的都是index.html 然后我将server. htmlFallback设置为false,再请求这些文件就变成404了,不知道是不是在开发环境下public下的文件没有复制到dist文件中 ![12333](https://private-user-images.githubusercontent.com/24770388/295779902-4620d307-a612-4750-b9ca-e4286fcb1784.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MTM3MTIsIm5iZiI6MTcwNTUxMzQxMiwicGF0aCI6Ii8yNDc3MDM4OC8yOTU3Nzk5MDItNDYyMGQzMDctYTYxMi00NzUwLWI5Y2EtZTQyODZmY2IxNzg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDE3NDMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiN2U3MGFiMTUxMmYxNTY3YzM0MDE3ZWYwNjc2OTZjYzc2OThlNGJjY2FlOWFiYjI2MzdiODJkODY2NmQ4MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OrThApL4z_f-kfCwWeQeP1B-gdhWQuYboVzLx3rYzuQ) 配置 ![121444](https://private-user-images.githubusercontent.com/24770388/295780195-d47de804-b526-45d0-a5a4-6e977b676cf0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MTM3MTIsIm5iZiI6MTcwNTUxMzQxMiwicGF0aCI6Ii8yNDc3MDM4OC8yOTU3ODAxOTUtZDQ3ZGU4MDQtYjUyNi00NWQwLWE1YTQtNmU5NzdiNjc2Y2YwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDE3NDMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmNDUwYjk0YTU3MGYzZWZmMTI2MDQyMDE3ZjcxOGYwZmY4Mjg3MGZlNjUwNWZmZWVhMjI3MThkYTI2MmJjZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7mIllHtdmiGSXpGe9uEWHetEpxaGa3w3CXcS5Kxa6AA) 引用 ![12555](https://private-user-images.githubusercontent.com/24770388/295780378-85c27bbb-6389-44e9-8f2d-63eb58da35b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MTM3MTIsIm5iZiI6MTcwNTUxMzQxMiwicGF0aCI6Ii8yNDc3MDM4OC8yOTU3ODAzNzgtODVjMjdiYmItNjM4OS00NGU5LThmMmQtNjNlYjU4ZGEzNWI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDE3NDMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1ZTBjM2UxNGNlZTk5YzM3ZjM4M2ZkN2QwZGY0YTlhNjM2Y2ZhZmU1ZDM0YzI5MTEzN2U0NWJkZTY5MWQ0ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.31vRAsKnDMm56w4su7MfI49Vp0hlYTHTmmjsP9XaNcg) ![12666](https://private-user-images.githubusercontent.com/24770388/295780795-a5459756-2344-4fb7-b55b-7c0e3e0bb681.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MTM3MTMsIm5iZiI6MTcwNTUxMzQxMywicGF0aCI6Ii8yNDc3MDM4OC8yOTU3ODA3OTUtYTU0NTk3NTYtMjM0NC00ZmI3LWI1NWItN2MwZTNlMGJiNjgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDE3NDMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlN2MwMTVkZWQxMjYxMWRiOWExZDdkZjYwMzU1OTNmMTdjZmE1OGM3MjA5NTJmNThhNTdlNjZjMGQ1ZmRmZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XIbBv-5u4HCypVxQyBb7TZCy7hPZxLM4PPsxyAW2XY0)
> 
> ### Reproduce link
> NONE
> 
> ### Reproduce Steps
> npm run dev

想了半天，大致明白你的问题了。`output.assetPrefix`的值，在开发环境和生产环境区分一下应该就没问题了，说一下你需要改的部分。

1. 首先，去掉`dev`这部分配置

![0](https://github.com/web-infra-dev/rsbuild/assets/78685759/34d9b89c-b720-4eec-a81e-ed07379271ea)

2. 然后，`output.assetPrefix`的值改为`process.env.NODE_ENV === 'production' ? '/cv3/' : '/'`

![1](https://github.com/web-infra-dev/rsbuild/assets/78685759/f6df6984-7161-46e2-94c6-68b320024190)

这样开发环境就能访问到了，不会返回index.html文件，生产环境也能满足你的需求。

**Comment by vaesonshu** [comment]
想了半天，大致明白你的问题了。`output.assetPrefix`的值，在开发环境和生产环境区分一下应该就没问题了，说一下你需要改的部分。

1. 首先，去掉`dev`这部分配置

![0](https://github.com/web-infra-dev/rsbuild/assets/78685759/34d9b89c-b720-4eec-a81e-ed07379271ea)

2. 然后，`output.assetPrefix`的值改为`process.env.NODE_ENV === 'production' ? '/cv3/' : '/'`

![1](https://github.com/web-infra-dev/rsbuild/assets/78685759/f6df6984-7161-46e2-94c6-68b320024190)

这样开发环境就能访问到了，不会返回index.html文件，生产环境也能满足你的需求。

**Comment by wengjiacheng** [comment]
> 想了半天，大致明白你的问题了。`output.assetPrefix`的值，在开发环境和生产环境区分一下应该就没问题了，说一下你需要改的部分。
> 
> 1. 首先，去掉`dev`这部分配置。
> 
> ![0](https://private-user-images.githubusercontent.com/78685759/297469717-34d9b89c-b720-4eec-a81e-ed07379271ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MjU2OTcsIm5iZiI6MTcwNTYyNTM5NywicGF0aCI6Ii83ODY4NTc1OS8yOTc0Njk3MTctMzRkOWI4OWMtYjcyMC00ZWVjLWE4MWUtZWQwNzM3OTI3MWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDAwNDk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzM2Q5Y2NkYWY3Y2RmMTEyN2FiZmUxYzIyYTdiMWRkYTJkYTFhM2U1ZDE2NzAwZjdhODkyNGM1NjllYzY3YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4CY7xwTF585sfcHI8LEWj-UaTrSs_IMFLLFRn7GMrBo)
> 
> 2. 然后，`output.assetPrefix`的值改为`process.env.NODE_ENV === 'production' ? '/cv3/' : '/'`。
> 
> ![1](https://private-user-images.githubusercontent.com/78685759/297472009-f6df6984-7161-46e2-94c6-68b320024190.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MjU2OTcsIm5iZiI6MTcwNTYyNTM5NywicGF0aCI6Ii83ODY4NTc1OS8yOTc0NzIwMDktZjZkZjY5ODQtNzE2MS00NmUyLTk0YzYtNjhiMzIwMDI0MTkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDAwNDk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhYWM2NmJlODZiMzY5ZGVkOWUwYzFkNjRiMDQ3OGZhNTgxYjE5YWRhNThlMDY3YzZhMGE1ZmFlNjA1OTMyY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WO0RTBMkfQ2lmcp_CiQfnDbcSfGeCwY1kW_JKlgbLUQ)
> 
> 因为你的需求是打包的时候文件放在`dist/cv3`下，只需要在生产环境下配置`assetPrefix`为`/cv3/`，开发环境不需要配置，因此不需要配置`dev`，默认`/`。
> 
> 这样放在public下的css文件和js文件，在开发环境就能访问到了，生产环境也能满足你的需求。

感谢给出的这个方案，确实可以绕过这个问题，但是我在尝试把老项目迁移，所以如果有办法做到开发环境和生成环境一致的路径是最好的

**Comment by vaesonshu** [comment]
在你原有的配置上加上这个，应该就行了，试一试。
![1](https://github.com/web-infra-dev/rsbuild/assets/78685759/74e10813-4da8-4705-8133-0d89324a033a)

**Comment by ultravires** [comment]
已认真阅读此 issue，但我认为此 issue 并没有得到很好的解决。我下面将从开发环境和生产环境的两个方面详细说一下目前遇到的问题。

在生产环境部署时，为了区分不同的应用，会对访问路径做区分。如：`/email/index.html`  和 `/disk/index.html`。静态服务器的目录结构如下：

```
root
|-- email
|-- -- index.html
|-- disk
|-- -- index.html
|-- index.html
```

`root` 是静态服务器根目录。

这个时候访问路径如：`http://<host>:<port>/email/index.html`。

我们期望在开发环境时访问路径也如此。于是做出如下配置：

```js
export default {
  dev: {
    assetPrefix: '/email/',
  },
  output: {
    assetPrefix: '/email/',
    distPath: 'dist/email/
  },
  server: {
    htmlFallback: false
  }
};
```

我们同样的在 `public` 下的 `index.html` 模板中直接引入了同目录下的 `.js` 文件。

**我们期望访问 `http://localhost:3000/email/index.html` 时，程序正常运行，但出现了 `/email/some.js` 404 的问题。**

你可能会疑惑：

Q: 为什么非得在开发环境使用 `/email/`？

A: 因为我们的页面代码中存在 `window.location.href = '/email/#/contact'` 类似的跳转。如果不配置 `dev: '/email/'`，则页面就无法正常访问。
