### ISSUE TITLE
[Bug]: Uncaught ReferenceError: antd_es_notification__WEBPACK_IMPORTED_MODULE_1__ is not defined

### ISSUE THREAD

**Issue by ChenXplorer** [web-infra-dev/rsbuild#1262]
### Version

```sh
System:
    OS: macOS 13.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 220.59 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 120.0.6099.109
    Safari: 16.6
  npmPackages:
    @rsbuild/core: ^0.2.8 => 0.2.8 
    @rsbuild/plugin-react: ^0.2.8 => 0.2.8
```

### Details

No issues in the dev environment, but errors occur in the production environment.

### Reproduce link

NONE

### Reproduce Steps

1. npm create rsbuild@latest
2. choose react and ts
3. yarn add antd
4. new file demo.js
```
import {message} from 'antd'
export default message;
```
5. new file demo2.js
```
import {notification} from 'antd'
export default notification
```
6. new file demoIndex.js
```
export { default as message } from './demo';
export { default as notification } from './demo2';
```
7. modify App.tsx add code 
```
import './App.less';
import { Button } from 'antd';
import {message,notification} from './demoIndex'
const info = () => {
  message.info('This is a normal message');
};
// const openNotification = () => {
//   notification.open({
//     message: 'Notification Title',
//     description:
//       'This is the content of the notification. This is the content of the notification. This is the content of the notification.',
//     onClick: () => {
//       console.log('Notification Clicked!');
//     },
//   });
// };
const App = () => {
  return (
    <div className="content">
    <Button type="primary" onClick={info}>
      Display normal message
     </Button>
     {/* <Button type="primary" onClick={openNotification}>
      Open the notification box
  </Button> */}
       <Button type="primary">Primary Button23</Button>
      <h1>Rsbuild with React</h1>
      <p>Start building amazing things with Rsbuild.</p>
    </div>
  );
};

export default App;

```
8. start server with dist,  error happened.
9. If the  comments code are removed, then there are no issues. or modify demoIndex.js as
```

import _message from './demo'
import _notification from './demo2'

export const message = _message
export const notification = _notification
```
there are no issues also

**Comment by chenjiahan** [comment]
Hi, I have followed the steps but can not reproduce the issue.

This is the repo: https://github.com/chenjiahan/rsbuild-repro-issue-1262

I use `pnpm build && pnpm preview` command.

![image](https://github.com/web-infra-dev/rsbuild/assets/7237365/04b39c9f-0387-462d-8d4e-6b3ebc2603ac)

**Comment by ChenXplorer** [comment]
> Hi, I have followed the steps but can not reproduce the issue.
> 
> This is the repo: https://github.com/chenjiahan/rsbuild-repro-issue-1262
> 
> I use `pnpm build && pnpm preview` command.
> 
> ![image](https://private-user-images.githubusercontent.com/7237365/296154523-04b39c9f-0387-462d-8d4e-6b3ebc2603ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNDU5NTksIm5iZiI6MTcwNTA0NTY1OSwicGF0aCI6Ii83MjM3MzY1LzI5NjE1NDUyMy0wNGIzOWM5Zi0wMzg3LTQ2MmQtOGQ0ZS02YjNlYmMyNjAzYWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTJUMDc0NzM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjkxZmVkYWU2MzQ5YjFmZWMzZjVkMTUwODdiYjgxZjZkMjljYjg2MjYzOTcwZGViZGEzODFlZTJhNWUzY2I5MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dFXJqPSFuQ-N0CobvdEB6QecJpDWPyECN5JvSbeXaC4)

modify version "antd": "4.24.12"

**Comment by chenjiahan** [comment]
Ok, please provide reproduce link next time

**Comment by chenjiahan** [comment]
Rsbuild will enable `newTreeshaking` by default soon.

**Comment by ChenXplorer** [comment]
> Rsbuild will enable `newTreeshaking` by default soon.

thx, which version is available for use

**Comment by chenjiahan** [comment]
> thx, which version is available for use

Maybe next week, still testing

**Comment by ChenXplorer** [comment]
> > thx, which version is available for use
> 
> Maybe next week, still testing

hello，i have a question : 
I have some custom babel plugins, now i use rsbuild, how can i refactor these custom plugins, for rsbuild

**Comment by chenjiahan** [comment]
Hi, you can still use babel plugins via [@rsbuild/plugin-babel](https://rsbuild.dev/plugins/list/plugin-babel).

Do you mean rewrite these plugins to SWC plugins? Custom SWC plugins are not supported yet, but Rspack will soon support the wasm SWC plugin, see https://github.com/web-infra-dev/rspack/issues/3451

**Comment by ChenXplorer** [comment]
> Hi, you can still use babel plugins via [@rsbuild/plugin-babel](https://rsbuild.dev/plugins/list/plugin-babel).
> 
> Do you mean rewrite these plugins to SWC plugins? Custom SWC plugins are not supported yet, but Rspack will soon support the wasm SWC plugin, see [web-infra-dev/rspack#3451](https://github.com/web-infra-dev/rspack/issues/3451)

thx， i want to rewrite these plugins  to SWC plugins
