### ISSUE TITLE
[Bug]: rsbuild discards the array deconstruction when setting browser compatibility to convert async to generator, causing problems.

### ISSUE THREAD

**Issue by linghaoSu** [web-infra-dev/rsbuild#1281]
### Version

```sh
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 113.56 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.8.1 - ~/.nvm/versions/node/v20.8.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.0/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.8.1/bin/npm
    pnpm: 8.14.1 - ~/Library/pnpm/pnpm
    bun: 1.0.4 - ~/.bun/bin/bun
  Browsers:
    Chrome: 120.0.6099.216
    Chrome Canary: 122.0.6247.0
    Safari: 17.2.1
```

### Details

before:

![image](https://github.com/web-infra-dev/rspack/assets/56526981/99aafdf0-ccbb-42f6-afd0-4bb6a984d5db)

after:

![image](https://github.com/web-infra-dev/rspack/assets/56526981/055045d9-7cb6-4706-99a9-8a76a2c61038)

### Reproduce link

https://github.com/linghaoSu/rust-async-browser-compat

### Reproduce Steps

1. pnpm install
2. pnpm run build

**Comment by chenjiahan** [comment]
Rsbuild uses SWC to transform the JavaScript code, you can reproduce this result in the SWC playground: 

![image](https://github.com/web-infra-dev/rsbuild/assets/7237365/87643dd9-b208-42fc-882a-294640501e37)

https://play.swc.rs/?version=1.3.100&code=H4sIAAAAAAAAA21RS26DMBTcc4rZYaTUByCiSFWrbqqoi3YVsXDNI0UCm9ombYS4e8EQQpt4Y2neeD7PZd1o49DBUIEehdE1wmNL4TYI6MfPpFbW4aslc9qJmmwjJNk3GrAEwp6UBMupEG3ldjaNYZ0p1SFCco8uAJw5%2BRuzjiE7vvsWpZtev2rrWDTYnTm6Il7pAwsfnx7en%2B%2F%2BnnDNdFD2pfRBhvhs7wcA53wJhBT7bsaBSnxQFSMMNwt0FFVLa6jPEGOfbS5iQ2SuluYpr0XDmLK%2BIrsSVxP5yuEf3kcR0nQxyoZel1pOmAONtaZ%2B3EvwolT5YjzIeRRJkmCpe95OTlY608rbm53kb03Wfj5RDymc%2FASjaPWNI52M0YbNrKDf%2FgI5KHlESgIAAA%3D%3D&config=H4sIAAAAAAAAA1WOzQrCMBCE7z5FyLl4sFVQ0EuliG8R6lQraVJ2t9IivruJrX%2B37MxkvrnPlNJXLvVG3cMzHOgF5Iw9wLYgDoZQh2Q0W0MM%2BoSDItz%2FRYLEgxMTVS1DCy6pbkWP7mPqETKOK0%2FNb1XH2KOqHQpPuTXMRQ17ei8Y%2F8%2BmDt34U2fxnR1REQle6U8I7vaTMHSGxDpd1ITK92q3Vdk6UfmFfIN4LbNpqC494fgKp%2FN08VYDdaQ4oWHiPJ6zUdRnRAEAAA%3D%3D

Can you submit an issue to the SWC repo? ❤️ https://github.com/swc-project/swc
