### ISSUE TITLE
[Bug]: error Cannot find module 'node:querystring'

### ISSUE THREAD

**Issue by coderew** [web-infra-dev/rsbuild#1284]
### Version

```sh
System:
    OS: macOS 14.1.1
    CPU: (10) x64 Apple M1 Pro
    Memory: 28.16 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 120.0.6099.216
    Safari: 17.1
  npmPackages:
    @rsbuild/core: 0.2.11 => 0.2.11 
    @rsbuild/plugin-vue2: 0.3.2 => 0.3.2
```

### Details

按照 https://rsbuild.dev/zh/guide/migration/vue-cli 迁移后，运行`rsbuild dev`命令报错：
> rsbuild dev

  Rsbuild v0.2.11

info    Port 8080 is in use, using port 8087.

  > Local:  

  > Network:  

  > Network:  

  > Network:  

error   Failed to start dev server.
error   Cannot find module 'node:querystring'

### Reproduce link

NONE

### Reproduce Steps

按照 https://rsbuild.dev/zh/guide/migration/vue-cli 迁移后，运行rsbuild dev命令报错：

**Comment by chenjiahan** [comment]
See: https://rsbuild.dev/plugins/list/plugin-node-polyfill
