### ISSUE TITLE
[Bug]: loader 不能匹配上前一个 loader 转换的内容

### ISSUE THREAD

**Issue by gzzhengbingyi** [web-infra-dev/rsbuild#1324]
### Version

```sh
mac os
"@rsbuild/core": "^0.3.2",
"@rsbuild/plugin-babel": "^0.3.3",
"@rsbuild/plugin-vue2": "^0.3.2",
"@rsbuild/plugin-vue2-jsx": "^0.3.3",
```

### Details

rspack: {
      module: {
        rules: [
          {
            resourceQuery: /blockType=i18n/,
            use: ['@xxxx/vue-i18n-loader'], // 内部的 loader
            type: 'javascript/auto',
          },
          {
            test: /\.csv$/,
            use: ['@xxxx/i18n-csv-loader'], // 内部的 loader
            type: 'javascript/auto',
          },
        ],
      },
    },

然后执行的时候 i18n-csv-loader 能够执行
但是经过 i18n-csv-loader 转换后的资源'@/i18n/csv/common/component.csv?vue&type=custom&index=0&blockType=i18n&issuerPath'却不会被'@xxxx/vue-i18n-loader'匹配上

### Reproduce link

none

### Reproduce Steps

none

**Comment by chenjiahan** [comment]
你好，由于缺少复现方式，我们很难帮你定位问题。从当前提供的信息来看，属于自定义的 loader 配置问题，建议你到 Rspack 仓库新建一个 issue 并提供复现方式
