### ISSUE TITLE
[Feature]: plugin-vue/vue2 添加 launch-editor-middleware

### ISSUE THREAD

**Issue by claneo** [web-infra-dev/rsbuild#1376]
### What problem does this feature solve?

用于在 vue devtool 中快速打开文件

### What does the proposed API look like?

vue-cli: 

https://github.com/vuejs/vue-cli/blob/f0f254e4bc81ed322eeb9f7de346e987e845068e/packages/%40vue/cli-service/lib/commands/serve.js#L243-L246

vite:

https://github.com/vitejs/vite/blob/639bbd65c0f7be6ad5d5d4fbe57bc15e778b7bea/packages/vite/src/node/server/index.ts#L788

**Comment by chenjiahan** [comment]
Thanks, we will consider integrating this middleware in core or the Vue plugin.
