### ISSUE TITLE
[Bug]: 部分第三方库在webpack4中引入正常，使用rsbuild后引入有问题

### ISSUE THREAD

**Issue by tiannengyu** [web-infra-dev/rsbuild#1389]
### Version

```sh
node 18
```

### Details

项目由webpack4升级至rsbuild，发现第三方包在webpack4下正常使用
`import watermark from 'watermark-dom';`
当mode为development时，改为`import  {watermark} from 'watermark-dom';`可正常使用
在mode为production生成产物或者使用preview功能时，`import watermark from 'watermark-dom';`打印出watermark为空
对应的watermark-dom包的地址：
github:https://github.com/saucxs/watermark-dom
npm:https://www.npmjs.com/package/watermark-dom

### Reproduce link

/

### Reproduce Steps

yarn
yarn add watermark-dom

import watermark from 'watermark-dom';
console.log(watermark)打印为空

**Comment by wChenonly** [comment]
看起来和这个有关         https://github.com/webpack/webpack/issues/16126

**Comment by chenjiahan** [comment]
嗯嗯，参考上述 issue 即可，Rspack / Rsbuild 的行为是和 Webpack 5 对齐的
