### ISSUE TITLE
[Bug]: vue2 external css module hmr not work as expected

### ISSUE THREAD

**Issue by worldzhao** [web-infra-dev/rsbuild#1425]
### Version

```sh
System:
    OS: macOS 13.2.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 85.17 MB / 16.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Browsers:
    Chrome: 120.0.6099.234
    Edge: 120.0.2210.144
    Safari: 16.3
  npmPackages:
    @rsbuild/core: ^0.3.7 => 0.3.7 
    @rsbuild/plugin-vue2: ^0.3.7 => 0.3.7
```

### Details

I'm unable to use style modules within the Vue template and have switched to importing styles using an external index.module.scss file. However, I've noticed that each time the style file is modified, it causes the component to remount.

<img width="830" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/25662450/7ba66c89-54b2-4c65-84e8-1b2265a0c8be">

I would like to ask:

How to configure CSS modules in a .vue file, i.e., <style module></style>
How to prevent the component from remounting when externally imported CSS module files are modified
It's not convenient to provide a GitHub repository at work (and Stackblitz can't use rsbuild), so I've included the minimal reproduction steps below, thanks.

---

无法使用 vue template 内的 style module，换成了外部的 index.module.scss 的形式引入样式，发现每次修改样式文件会导致组件重新挂载

<img width="830" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/25662450/7ba66c89-54b2-4c65-84e8-1b2265a0c8be">

想请教一下：
1. 如何配置 .vue 文件的 css module，即 `<style module></style>`
2. 外部引入的 css module 文件如何不重新写在挂载组件

在公司不好提供 github 仓库（stackblitz 无法使用 rsbuild），最小复现步骤贴在下面了，thx

### Reproduce link

todo

### Reproduce Steps

- npm create rsbuild@latest
- select vue2 template
- create index.module.scss and edit it

**Comment by chenjiahan** [comment]
I think it is as expected to re-mount the component when CSS modules changed.

When CSS modules change, the class name hash will change, so we need to re-mount the component to update the class name hash.

**Comment by worldzhao** [comment]
> I think it is as expected to re-mount the component when CSS modules changed.
> 
> When CSS modules change, the class name hash will change, so we need to re-mount the component to update the class name hash.

 You are correct, I tested it with vue-cli and the result was the same (although the hash did not change). However, when I tested with nuxt@2, this issue did not occur. I believe that Nuxt's behavior aligns more with the expectations during development. I do not want the components to remount and make requests simply because of style modifications.

---

你是正确的，我使用 vue-cli 进行测试，结果也是如此（虽然 hash 并不会变化），但是当我使用 nuxt@2 测试，没有出现这种场景，我认为 nuxt 的表现更符合开发时的预期，我并不想因为样式修改 => 组件重新挂载 => 请求重复发出(loading)

**Comment by worldzhao** [comment]
Using Vite also results in a remount... Well, that's that. It would be even better if you could add how to use <style module></style> in Vue. This is the last thing I'm struggling with in my migration...

---

使用 vite 也是会 remount...那就这样吧，如果能补充一下如何在 vue 中使用 <style module></style> 就更好了，我目前迁移就剩这一个整不了...

**Comment by chenjiahan** [comment]
Get, we will try to add guide for `<style module>` later 😄

**Comment by chenjiahan** [comment]
`<style module>` can be supported after Rspack supports mini-css-extract-plugin, see: https://github.com/web-infra-dev/rspack/issues/3210
