### ISSUE TITLE
[Bug]: preact HMR doesn't update before reload the page

### ISSUE THREAD

**Issue by scffs** [web-infra-dev/rsbuild#1434]
### Version

```sh
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
    Memory: 4.78 GB / 23.78 GB
  Browsers:
    Edge: Chromium (120.0.2210.144)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @rsbuild/core: ^0.3.6 => 0.3.6 
    @rsbuild/plugin-image-compress: ^0.3.7 => 0.3.7 
    @rsbuild/plugin-react: ^0.3.6 => 0.3.6
```

### Details

I use preact and rsbuild, after I change smth I don't see the updates but in devtools .update request looks fine

![image](https://github.com/web-infra-dev/rsbuild/assets/67464545/efc9cd35-6be7-475a-95cf-65046bf428a3)

![image](https://github.com/web-infra-dev/rsbuild/assets/67464545/4d8eced6-e866-4a25-b469-ae9357f77553)

but at the screen there is still old data

![image](https://github.com/web-infra-dev/rsbuild/assets/67464545/61230f5b-60ec-4d9b-b794-ac09e1ef3bb9)

### Reproduce link

maybe later sorry

### Reproduce Steps

see the details I guess

**Comment by chenjiahan** [comment]
I noticed that you are using `@rsbuild/plugin-react` in Preact project, can you replace it with `@rsbuild/plugin-preact`?

https://rsbuild.dev/plugins/list/plugin-preact

**Comment by scffs** [comment]
Thakns! I just did't see the preact plugin
