### ISSUE TITLE
Performance degradation in rspress website case in dev mode

### ISSUE THREAD

**Issue by Timeless0911** [web-infra-dev/rsbuild#1494]
### System Info

N / A

### Details

the devColdBootTime has increased when update rspack from 0.5.0 to 0.5.3

Related issue: https://github.com/web-infra-dev/rspress/issues/592

### Reproduce link

https://github.com/web-infra-dev/web-infra-QoS/tree/master/cases/rspress/rspress-website

### Reproduce Steps

Run dev scripts, and may be you need to config some rspack configurations to run with rspack directly.

Or you can replace the `"rspress": "workspace:*",` to an exact rspress version, and use overrides to change the rspack version.

**Comment by chenjiahan** [comment]
This may be related to the change in the hook execution timing of Rsbuild

**Comment by chenjiahan** [comment]
Related PR: https://github.com/web-infra-dev/rsbuild/pull/1289/files

This is caused by changes in hook execution timing, and there is no regression in performance.
