### ISSUE TITLE
[Bug]: transformImport isn't working well

### ISSUE THREAD

**Issue by JoseBuendiaDigio** [web-infra-dev/rsbuild#1521]
### Version

```sh
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 8.82 GB / 31.71 GB
  Browsers:
    Edge: Chromium (121.0.2277.98)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @rsbuild/core: 0.3.11 => 0.3.11
    @rsbuild/plugin-react: 0.3.11 => 0.3.11
    @rsbuild/plugin-type-check: 0.3.11 => 0.3.11
```

### Details

I want to transform `import { CssBaseline } from '@mui/material';` to `import CssBaseline  from '@mui/material/CssBaseline ';`

My config is 
```
{
                libraryName: '@mui/material',
}
```

And the output is 

```
 import Typography from "@mui/material/lib/typography";
```

If I disable `libraryDirectory` the result is the same if I set `libraryDirectory` to `''` the result is ` import Typography from "@mui/material//typography";`

And if I try the customName `customName: (member: string) => '@mui/material/${member}'` the result is the same.

How can I transform it? I think that there is a bug.

### Reproduce link

isnt necessary

### Reproduce Steps

build or dev

**Comment by xc2** [comment]
instead of function, please use string template like `customName: '@mui/materials/{{ member }}'`

ref: https://rsbuild.dev/config/source/transform-import#customname

btw, `import Typography from "@mui/material//typography"`  would work i think

**Comment by JoseBuendiaDigio** [comment]
This works, but the other no. This maybe confusing.

![image](https://github.com/web-infra-dev/rsbuild/assets/107539652/4fe728d0-ca0e-4c0e-9a71-d5629b913d59)

**Comment by chenjiahan** [comment]
This is not a valid import path:

![image](https://github.com/web-infra-dev/rsbuild/assets/7237365/fdc7006d-e74c-4fbd-a3c3-f9f6ce9a49a4)
