### ISSUE TITLE
[Bug]: webpack插件在rspack下引用，无法改变chunk的依赖关系，在webpack下可以

### ISSUE THREAD

**Issue by wengjiacheng** [web-infra-dev/rsbuild#1525]
### Version

```sh
System:
    OS: macOS 13.3.1
    CPU: 2.5 GHz Intel Core i7
    Memory: 16 GB 2133 MHz LPDDR3
  Browsers:
    Chrome:  120.0.6099.109
  npmPackages:
    "@rsbuild/core": "^0.2.15",
    "@rsbuild/plugin-vue2": "^0.2.15",
```

### Details

有个需求是css文件过大需要拆分，原项目里使用的是css-split-webpack-plugin这个插件，这个插件给出的方法是支持webpack5,  我使用插件给的办法在webpack5中做了尝试也是可以正常打包的，
而且css文件的引入也是正常的
![image](https://github.com/web-infra-dev/rsbuild/assets/24770388/64edd835-d102-4f04-95ec-a6b4ae5151cc)
上面两个css引用在是他拆分后打包的结果

然后我在rsbuild构建的项目下也引用了这个插件
<img width="575" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/24770388/ae50b778-fe0d-4209-8e00-c55d28c26dac">
这是我的配置，文件可以看到是打包出来了，但是并没有被引用
<img width="351" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/24770388/18ca8c16-20b6-463d-985a-2c4a53110e7d">
<img width="894" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/24770388/89130471-c14a-49ff-9519-7b2b9b01ad83">
插件中修改文件的方式
![image](https://github.com/web-infra-dev/rsbuild/assets/24770388/e08a3ecf-73e0-4fc2-bc7f-fa624d525278)

### Reproduce link

NONE

### Reproduce Steps

npm run build

**Comment by chenjiahan** [comment]
可以先升级 Rsbuild 到最新版（0.4.0）试一下，如果不行的话，可能是 Rspack 未支持这个插件所使用的 hooks，可以到 Rspack 仓库提个 issue。
