### ISSUE TITLE
[Bug]: module-federation

### ISSUE THREAD

**Issue by avkis** [web-infra-dev/rsbuild#1526]
### Version

```sh
System: Windows 10
Browser: Google Chrome
npmPackages: 
  "devDependencies": {
    "@rsbuild/core": "^0.3.11",
    "@rsbuild/plugin-react": "^0.3.11"
  }
```

### Details

Module-federation example doesn't work outside of the main project.
<img width="1097" alt="RsBuildModuleFederationRemote" src="https://github.com/web-infra-dev/rsbuild/assets/14841869/b6add313-4a3b-4fb7-8c88-f9ffed4c00eb">
<img width="1097" alt="RsBuildModuleFederationHost" src="https://github.com/web-infra-dev/rsbuild/assets/14841869/1cc38d5c-be60-4560-87b4-0eed4cae54a7">

### Reproduce link

The issue concerns of the code from your repo. 

### Reproduce Steps

1. Extract the module-federation folder from the examples directory of main repository (https://github.com/web-infra-dev/rsbuild) to a separate folder.
2. Install dependency for each projects (host and remote).
3. Run `pnpm run dev` in the remote folder (this project will run perfectly).
4. Run `pnpm run dev` in the host folder (this one throws an error: 
**error   Compile error:
Failed to compile, check the errors for troubleshooting.
File: ./src/App.js
  × Resolve error: Can't resolve 'remote/Button' in 'D:\Dev\Education\ModuleFederation\module-federation\host\src'    
   ╭─[1:1]
 1 │ import { jsxDEV as _jsxDEV } from "react/jsx-dev-runtime";
 2 │ import React from "react";
 3 │ const RemoteButton = /*#__PURE__*/ React.lazy(()=>import("remote/Button"));
   ·                                                   ───────────────────────
 4 │ _c = RemoteButton;
 5 │ const App = ()=>/*#__PURE__*/ _jsxDEV("div", {
   ╰────**
)

**Comment by avkis** [comment]
<img width="631" alt="RsBuildModuleFederationRsbuildConfigExport" src="https://github.com/web-infra-dev/rsbuild/assets/14841869/1adc32c4-e6db-4f3b-9eb9-2e62886d6808">

**Comment by chenjiahan** [comment]
Try Rsbuild 0.4.0

**Comment by avkis** [comment]
It works. Thank you.
