### ISSUE TITLE
[Feature]:  Support loglevel in rsbuild

### ISSUE THREAD

**Issue by 10Derozan** [web-infra-dev/rsbuild#1582]
### What problem does this feature solve?

We can custom loglevel in rsbuild and configure different level in different instance.

### What does the proposed API look like?

maybe dev.loglevel, output.loglevel.

**Comment by chenjiahan** [comment]
Try this:

```js
import { logger } from '@rsbuild/core';

logger.level = 'xxx';
```

- https://rsbuild.dev/api/javascript-api/core#logger
- https://github.com/rspack-contrib/rslog?tab=readme-ov-file#log-level

**Comment by chenjiahan** [comment]
The above method will affect all instances. We may need to provide a way to configure logLevel for different instances.

**Comment by 10Derozan** [comment]
I want that instance is independent, for example, I have created two rsbuild instance, if use 
```tsx
import { logger } from '@rsbuild/core';

logger.level = 'xxx';
```
The another will be influenced also.

**Comment by 10Derozan** [comment]
> The above method will affect all instances. We may need to provide a way to configure logLevel for different instances.

Yes, you are right.

**Comment by chenjiahan** [comment]
This may be difficult to achieve because the code in Rsbuild does not get the logger from the Rsbuild instance, but directly imports the logger module.
