### ISSUE TITLE
[Bug]:  Critical dependency: Accessing import.meta directly is unsupported (only property access or destructuring is supported)

### ISSUE THREAD

**Issue by zhuyuanmin** [web-infra-dev/rsbuild#1585]
### Version

```sh
lasted
```

### Details

![image](https://github.com/web-infra-dev/rsbuild/assets/23226876/74314870-c12c-477e-a758-dfb03e36ff63)

### Reproduce link

none

### Reproduce Steps

none

**Comment by chenjiahan** [comment]
The `import.meta.glob` is not supported by Rspack, you can use `require.context` instead:

- https://www.rspack.dev/api/modules.html#requirecontext
- https://webpack.js.org/guides/dependency-management/#requirecontext

**Comment by chenjiahan** [comment]
You can also use `import.meta.webpackContext`: https://webpack.js.org/api/module-variables/#importmetawebpackcontext

**Comment by radandevist** [comment]
Do we have a workaround for this?
