### ISSUE TITLE
[Bug]: hrm slow

### ISSUE THREAD

**Issue by liangyuetian** [web-infra-dev/rsbuild#1590]
### Version

```sh
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 217.88 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 121.0.6167.184
    Safari: 17.2.1
  npmPackages:
    @rsbuild/core: ^0.4.3 => 0.4.3 
    @rsbuild/plugin-vue: ^0.4.3 => 0.4.3
```

### Details

Slow speed when editing files with and without dependencies
<img width="333" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/22701373/d18cfc8a-198d-4c08-b4cd-7acbec3ad353">

related issues：
[https://github.com/web-infra-dev/rsbuild/issues/1397](https://github.com/web-infra-dev/rsbuild/issues/1397)

### Reproduce link

https://github.com/liangyuetian/rsbuild-hmr-slow-demo

### Reproduce Steps

1. pnpm install
2. npm run dev (Client compiled in 3.7 s)
3. edit src/pages/test_1.vue (Client compiled in 2.4 s)

**Comment by chenjiahan** [comment]
Get, we will track the performance issues in this repo.

**Comment by chenjiahan** [comment]
Half of the overhead is generated by html-webpack-plugin / html-rspack-plugin. If we try to set `tools.htmlPlugin` to false, the HMR time will be reduced by half.

**Comment by liangyuetian** [comment]
> Half of the overhead is generated by html-webpack-plugin / html-rspack-plugin. If we try to set `tools.htmlPlugin` to false, the HMR time will be reduced by half.

@chenjiahan set `tools.htmlPlugin` to false can reduce time， but it is not very helpful for hmr updates. For such a simple entry, the expected time should be 0.0x ms
<img width="276" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/22701373/3f04ebb7-ac70-488b-b7a3-50017c6f54a8">

**Comment by chenjiahan** [comment]
0.0x ms is not possible. Do you mean 0.0x second?

The HMR time may be reduced to less than 100ms after Rspack providing better incremental build and supporting persistent cache.

**Comment by liangyuetian** [comment]
> 0.0x ms is impossible. Do you mean 0.0x second?
> The HMR time may be reduced to less than 100ms after Rspack providing better incremental build and supporting persistent cache.

**reliable**

**Comment by liangyuetian** [comment]
<img width="537" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/22701373/e3173567-12cf-42cf-ac56-150ead743c4a">

v0.5.6 awesome

looking forward to version 1.0
