### ISSUE TITLE
[Bug]: The code packaged in the production environment is missing axios.interceptors.response.use(xxx)

### ISSUE THREAD

**Issue by Sermonizer** [web-infra-dev/rsbuild#1695]
### Version

```sh
OS: Windows 10
npmPackages:
@rsbuild/core: ^0.4.5 => 0.4.5
@rsbuild/plugin-rem: ^0.4.4 => 0.4.4
@rsbuild/plugin-vue2: ^0.4.5 => 0.4.5
```

### Details

vue2项目 在index.js文件中修改axios响应拦截处理代码：axios.interceptors.response.use(xxx)，使用vue-cli打包的生产代码正常，rsbuild开发环境正常，但是rsbuild生产环境打包后的代码中找不到这段代码了

### Reproduce link

empty

### Reproduce Steps

暂时没有复现成功，请问有什么排查的思路吗？

**Comment by chenjiahan** [comment]
Maybe the code is removed by tree shaking.

You can try enabling the Rspack newTreeshaking option to see if this fixes the problem.

https://www.rspack.dev/config/experiments.html#experimentsrspackfuturenewtreeshaking

```js
export default defineConfig({
  plugins: [pluginVue()],
  tools: {
    rspack: {
      experiments: {
        rspackFuture: {
          newTreeshaking: true,
        },
      },
    },
  },
});
```

**Comment by Sermonizer** [comment]
its not works for me, and i set `optimization.sideEffects = true` is not works for me too, when i try to use redoctor to watch code change ,it throw error...

**Comment by chenjiahan** [comment]
can you provide an reproduce repo? ❤️

**Comment by Sermonizer** [comment]
sorry, i havent reproduce in another repo, maybe i can try it later. but when i set `rspack: {
      optimization: {
        minimize: false
      },
    },` , everything is normal

**Comment by chenjiahan** [comment]
> when i set rspack: { optimization: { minimize: false }, }, , everything is normal

The code may have been removed by the SWC minimizer

**Comment by Sermonizer** [comment]
when i use custom minimizer:  
   `minimize: true,
    minimizer: [
      new minifyPlugin({
        minifier: 'terser',
      }),
    ],`, the code been removed too

**Comment by xc2** [comment]
`axios.interceptors.response.use(xxx)` 在文件代码最外层吗

请发一下：

1. 这个文件中与 axios 相关的 import 语句
2. 这段代码附近的代码

另外请检查一下这段代码附近的代码是不是也被移除了
