### ISSUE TITLE
[Bug]: changes in Relay artifacts not reflected

### ISSUE THREAD

**Issue by Godsenal** [web-infra-dev/rsbuild#1704]
### Version

```sh
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 204.45 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 122.0.6261.69
    Edge: 122.0.2365.59
    Safari: 17.2.1
  npmPackages:
    @rsbuild/core: ^0.4.8 => 0.4.8 
    @rsbuild/plugin-assets-retry: ^0.4.8 => 0.4.8 
    @rsbuild/plugin-image-compress: ^0.4.8 => 0.4.8 
    @rsbuild/plugin-react: ^0.4.8 => 0.4.8 
    @rsbuild/plugin-type-check: ^0.4.8 => 0.4.8
```

### Details

Hello,

I've encountered an issue using rsbuild with relay after updating rsbuild to a newer version. Previously, when running rsbuild in dev mode, if I modified a query and then compiled relay, the changes were reflected correctly. However, after updating rsbuild, this behavior no longer occurs. Considering the relay output seems to be correctly updated, I suspect there might be an issue with rsbuild.

Upon investigation, the issue seems to have started with rsbuild version 0.3.8, and it works correctly when the artifactDirectory option is given an absolute path, which leads me to believe there might be a problem related to path handling.

Thank you.

### Reproduce link

https://github.com/Godsenal/rsbuild-relay-repro

### Reproduce Steps

1. `npm run dev`
2. Check the console log for AppQuery in the src/App.tsx file
3. Modify AppQuery
4. Verify if the console log has changed

**Comment by chenjiahan** [comment]
I have reproduced this issue. This may be related to Rspack, we will continue to follow up.

**Comment by xc2** [comment]
thank you @Godsenal for digging into the problem.

a pr is open for it.

btw, `"artifactDirectory": "src/__generated__"` would work as well.
