### ISSUE TITLE
[Bug]: CheckSyntaxPlugin check inaccurate when content include object rest spread syntax

### ISSUE THREAD

**Issue by 9aoy** [web-infra-dev/rsbuild#1706]
### Version

```sh
rsbuild 0.4.8
```

### Background

rest spread syntax is supported in below range, but it will throw error when use checkSyntaxPlugin.
```file=.browserslistrc
chrome >= 61
edge >= 20
firefox >= 60
safari >= 12
ios_saf >= 12
```

<img width="798" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/22373761/a5a66cbf-7829-4966-a815-ca16197617db">

<img width="1083" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/22373761/9774d436-a30b-4832-b4c0-fd821a163a9a">

### Detail
checkSyntaxPlugin use acorn to parse syntax, in acorn issue, they said we need set `ecmaVersion` to 9. but checkSyntaxPlugin only support set  `ecmaVersion` to 5 or 6. 

By the way, the above browserslist scope supports the rest spread syntax, but not all ecmaVersion 9 syntax.

https://github.com/acornjs/acorn/issues/664

Rsbuild code: https://github.com/web-infra-dev/rsbuild/blob/v0.4.8/packages/plugin-check-syntax/src/helpers/getEcmaVersion.ts#L9

### Reproduce link

none

### Reproduce Steps

none

**Comment by chenjiahan** [comment]
See: https://rsbuild.dev/plugins/list/plugin-check-syntax#targets

![image](https://github.com/web-infra-dev/rsbuild/assets/7237365/0a232438-3032-463c-a2e1-cc6744ae342e)
