### ISSUE TITLE
[Bug]: 使用numeral处理数字，dev是正常，build后全是NaN

### ISSUE THREAD

**Issue by gcdxuzhiwei** [web-infra-dev/rsbuild#1708]
### Version

```sh
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 82.27 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 122.0.6261.94
    Safari: 17.2.1
  npmPackages:
    @rsbuild/core: ^0.4.5 => 0.4.5 
    @rsbuild/plugin-react: ^0.4.5 => 0.4.5
```

### Details

import numeral from "numeral";

console.log(numeral(123).format('0,0.00'));

在dev是正常打印出123.00，build后打印出NaN

### Reproduce link

https://github.com/gcdxuzhiwei/rebuildtest

### Reproduce Steps

pnpm install
pnpm run dev

pnpm run build
http-server --port 9000

**Comment by gcdxuzhiwei** [comment]
我参考另一个issue把压缩关了 build后是正常的 rspack: { optimization: { minimize: false }, },
https://github.com/web-infra-dev/rsbuild/issues/1695

**Comment by xc2** [comment]
@gcdxuzhiwei 试了下最新版本是 OK 的，请升级 rsbuild 到最新版本
