### ISSUE TITLE
[Bug]: 文档图片捉虫

### ISSUE THREAD

**Issue by Lionad-Morotar** [web-infra-dev/rsbuild#1715]
### Version

```sh
---
```

### Details

![Clip_2024-03-03_23-36-24](https://github.com/web-infra-dev/rsbuild/assets/26913795/4154eb6d-7bd8-4da5-b341-6dfcc8f07dd3)

### Reproduce link

https://rsbuild.dev/zh/guide/start/index

### Reproduce Steps

---

**Comment by chenjiahan** [comment]
can you provide more information for this issue?

**Comment by Priestch** [comment]
The picture shows Rsbuild use less time than Rspack, but the text describe ”性能
略微低于 Rspack“, they don't match.

**Comment by chenjiahan** [comment]
Get, this can be a little misleading.

In fact, the overall performance of Rsbuild is slightly lower than that of Rspack. However, for some secerios, the performance of Rsbuild may be better than Rspack. This is because the native Rspack configuration may not have been fully optimized.

**Comment by chenjiahan** [comment]
Document updated.
