### ISSUE TITLE
[Feature]: Support configuring include / exclude when using SVGR plguin

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rsbuild#1734]
### What problem does this feature solve?

Support configuring include / exclude rules when using the SVGR plguin, this allows us to enable SVGR transformation for certain files.

### What does the proposed API look like?

```ts
pluginSvgr({
  include: [/some-files/],
  exclude: [/other-files/],
});
```

**Comment by simpleAndElegant** [comment]
I tried something, maybe it's right？
<img width="1176" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/41931905/bc45a6a8-f1ff-4e3a-a273-3c0bc73b979d">

**Comment by chenjiahan** [comment]
We can not get the filename of each chunk in the `api.modifyBuilderChain` method.

The feasible solution is to modify the Rspack config and apply include/exclude rules to the loader's rules. But the loader rules for SVG are quite complex, so applying include / exclude has some difficulties.
