### ISSUE TITLE
Path problems occur when background-image: url() is used in CSS

### ISSUE THREAD

**Issue by wChenonly** [web-infra-dev/rsbuild#1748]
### Version

```sh
System:
    OS: macOS 14.3.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 47.80 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 122.0.6261.112
    Safari: 17.3.1
  npmPackages:
    @rsbuild/core: ^0.4.11 => 0.4.11 
    @rsbuild/plugin-vue: ^0.4.11 => 0.4.11
```

### Details

![image](https://github.com/web-infra-dev/rsbuild/assets/37658262/b819f158-34a3-45fe-8940-83d074fc2738)

When I use backarounda to enter an image in a css file, I get a path error after typing the sentence.

![image](https://github.com/web-infra-dev/rsbuild/assets/37658262/a60f59d6-20cb-4f75-b413-cd4a2fbcbbc0)

### Reproduce link

https://github.com/wChenonly/rsbuild-css-image-issue

### Reproduce Steps

pnpm install
pnpm preview

**Comment by liutongbin2017** [comment]
遇到了同样的问题

**Comment by chenjiahan** [comment]
This is caused by the relative assetPrefix (Rspack's publicPath), you can change `output.assetPrefix` from `'./'` to `/` to fix this.

We will see if Rsbuild can support the relative assetPrefix later.

**Comment by wChenonly** [comment]
> This is caused by the relative assetPrefix (Rspack's publicPath), you can change `output.assetPrefix` from `'./'` to `/` to fix this.
> 
> We will see if Rsbuild can support the relative assetPrefix later.


Since I'm deploying to a server, it is therefore necessary to  `'./'`， if you use  `/， then will all not open!
![image](https://github.com/web-infra-dev/rsbuild/assets/37658262/d22af3ae-89ce-4bf5-ac1f-83addce21e6f)

**Comment by chenjiahan** [comment]
You should set assetPrefix to the correct prefix, such as `/xxx/`, or include the CDN domain.

**Comment by wChenonly** [comment]
> You should set assetPrefix to the correct prefix, such as `/xxx/`, or include the CDN domain.

To be precise, this is a hybrid development, downloaded locally, and it is a virtual domain name, and ios and android are different. I can't configure something similar to a second-level domain name.

**Comment by xc2** [comment]
> > You should set assetPrefix to the correct prefix, such as `/xxx/`, or include the CDN domain.
> 
> To be precise, this is a hybrid development, downloaded locally, and it is a virtual domain name, and ios and android are different. I can't configure something similar to a second-level domain name.

how about `assetPrefix: 'auto'`?
