### ISSUE TITLE
[Bug]: resolve-url-loader build failed when path includes `[]`

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rsbuild#1794]
### Version

```sh
System:
    OS: macOS 13.6.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 994.91 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 122.0.6261.112
    Safari: 16.6
  npmPackages:
    @rsbuild/core: ^0.4.14 => 0.4.14
```

### Details

resolve-url-loader build failed when path include `[]`, such as "./[foo]/index.scss"

<img width="996" alt="Screenshot 2024-03-12 at 11 58 49" src="https://github.com/web-infra-dev/rsbuild/assets/7237365/d1cc054e-089b-4815-b539-99706a999087">

### Reproduce link

https://github.com/chenjiahan/rsbuild-repo-sass-invalid-path

### Reproduce Steps

1. pnpm i
2. pnpm build:rsbuild

**Comment by wxiaoyun** [comment]
I believe this issue is resolved with the latest version of Rsbuild an Rspack.

Just add pluginSass to the rsbuild config after updating the version of Rsbuild and Rspack and there will not be any errors

![image](https://github.com/user-attachments/assets/5c396c41-c9cd-4002-906f-60ff09e9b447)

**Comment by chenjiahan** [comment]
Nice 👍 I will close this isssue
