### ISSUE TITLE
[Bug]: 语言切换问题

### ISSUE THREAD

**Issue by yi-xiaobai** [web-infra-dev/rsbuild#1798]
### Version

```sh
rsbuild官网：https://rsbuild.dev/zh/config/index
```

### Details

中文模式下，点击配置-->框架
框架立马变成-->plugins 且其他中文汉字全部变成英文

### Reproduce link

no

### Reproduce Steps

1. 进入网址
2. 点击配置-->框架
3. 框架立马变成-->plugins

**Comment by chenjiahan** [comment]
Hi，这个页面上好像没有「框架」，你指的是「插件」吗？

**Comment by chenjiahan** [comment]
我们看到的文档内容似乎并不一致，你截图中的「开始」和「框架」并不是 Rsbuild 文档的内容，是不是有什么浏览器插件影响了

![image](https://github.com/web-infra-dev/rsbuild/assets/7237365/0df99136-1d8d-4bbf-ad82-589833588fe6)

**Comment by yi-xiaobai** [comment]
问题的原因还得请教你们了
复现概率不大 内容展示看起来不影响

**Comment by chenjiahan** [comment]
你换个浏览器试试看呢

**Comment by xc2** [comment]
@chenjiahan could you please bump up rspress to fix this issue

**Comment by chenjiahan** [comment]
Bumped 😄 https://github.com/web-infra-dev/rsbuild/pull/1826

Thanks for fixing that ❤️
