### ISSUE TITLE
[Bug]: hmr runtime was not transformed as expected

### ISSUE THREAD

**Issue by xc2** [web-infra-dev/rsbuild#1804]
### Details

Original post: https://discord.com/channels/977448667919286283/1215728156984610876

![image](https://github.com/web-infra-dev/rsbuild/assets/18117084/ebb25eb0-e2a3-4d2c-84cc-26536747ac76)

https://github.com/web-infra-dev/rsbuild/blob/8d3913483ef7ff561a2ee48e1a1eb563c8537905/packages/core/modern.config.ts?plain=1#L11-L23

the hmr runtime appears to be meant to target es5 but module-tools will strip it as esbuild don't support es5. This results in the  hmr runtime kept untransformed.

https://github.com/web-infra-dev/modern.js/blob/2e7585862237e957054ccfa37632c2a34ce6c881/packages/solutions/module-tools/src/builder/esbuild/index.ts?plain=1#L153

we have to update the target to es6 atm as it's the minimium target we can have with esbuild without an additional plugin.

### Reproduce link

https://www.npmjs.com/package/@rsbuild/core?activeTab=code

`@rsbuild/core/dist/client/hmr.mjs`

**Comment by chenjiahan** [comment]
Thanks! It is still necessary to transform client code to `es5`, as some apps may still need to be compatible with legacy browsers.

Actually, this is a bug of Modern.js Module, it should enable SWC transform when target is 'es5'. I have submit a PR to fix this: https://github.com/web-infra-dev/modern.js/pull/5527

**Comment by wChenonly** [comment]
I also encountered this problem today. Through investigation just now, I found that the target in baseBuildConfig in the modern.base.config.ts file is es2020.
<img width="1484" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/37658262/80a8ddf8-ed90-4271-946a-523563aa21c6">

**Comment by chenjiahan** [comment]
> I found that the target in baseBuildConfig in the modern.base.config.ts file is es2020.

Yeah, the `es2020` is for Node.js target, and client code should be transformed to es5 for compatibility.
