### ISSUE TITLE
[Document]: make the case of macOS correct

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rsbuild#1856]
> This is an issue created for first-time contributors, PR welcome! 😄

Correct the case of macOS in the document:

**MacOS → macOS**

![image](https://github.com/web-infra-dev/rsbuild/assets/7237365/6fc4e728-4049-4a0f-a033-ce1de3511782)

**Comment by bottlewook** [comment]
Can i work on this issue? kindly assign it to me!

**Comment by chenjiahan** [comment]
done 😄

**Comment by bottlewook** [comment]
done!
