### ISSUE TITLE
[Feature]: Add the possibility to not generate main.html file

### ISSUE THREAD

**Issue by neslinesli93** [web-infra-dev/rsbuild#1864]
### What problem does this feature solve?

We are using server side rendering from a Elixir/Phoenix application, so `index.html` is generated at runtime and served by our Elixir backend. We could not find a way to skip generating `main.html` file in the output directory, it would be useful to have said option

### What does the proposed API look like?

Don't know if this should be in `output.html` or something

**Comment by chenjiahan** [comment]
You can set `tools.htmlPlugin` to `false`:

https://rsbuild.dev/config/tools/html-plugin#disable-html
