### ISSUE TITLE
[Document]: add `rspack-examples` to `docs/en/guide/start/index.mdx`

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rsbuild#1867]
> This is an issue created for first-time contributors, PR welcome! 😄

Add the link of `rspack-examples` to `docs/en/guide/start/index.mdx` and `docs/zh/guide/start/index.mdx`, the content should be the same as:

- https://github.com/web-infra-dev/rsbuild/blob/main/README.md?plain=1#L78
- https://github.com/web-infra-dev/rsbuild/blob/main/README.zh-CN.md?plain=1#L78

**Comment by bottlewook** [comment]
I'll do this, assign it to me!

**Comment by chenjiahan** [comment]
done 😄
