### ISSUE TITLE
[Feature]: support `dev.watchFiles`

### ISSUE THREAD

**Issue by 9aoy** [web-infra-dev/rsbuild#1902]
### What problem does this feature solve?

support configure a list of globs/directories/files to watch for file changes, and these file changes will trigger a page reload.

```ts
export default {
  dev: {
    watchFiles: : ['src/**/*.php', 'public/**/*'],
  },
};
```

### What does the proposed API look like?

like [webpack#devServer.watchFiles](https://webpack.js.org/configuration/dev-server/#devserverwatchfiles)

**Comment by liyincode** [comment]
Hi, I finished the feature,It's working.😁

[code is here](https://github.com/liyincode/rsbuild/blob/761e9683508fb20711cecc883d6543666a4c82a8/packages/core/src/server/devServer.ts#L207)  
[e2e test is here](https://github.com/liyincode/rsbuild/blob/feat%2Fdev-watchFiles/e2e/cases/server/watch-files/index.test.ts)

### Usage
```typescript
export default { 
  dev: {
    watchFiles: 'assets/example.txt',
  }, 
};
```
```typescript
export default {
  dev: {
    watchFiles: 'assets/**/*',
  },
};
```
```typescript
export default { 
  dev: {
    watchFiles: ['assets/example.txt', 'static/example.txt']
  }, 
};
```
```typescript
export default { 
  dev: {
    watchFiles: 'assets',
  }, 
};
```
```typescript
export default {
  dev: {
    watchFiles: ['assets', 'static'],
  },
};
```
```typescript
export default { 
  dev: {
    // use chokidar options https://github.com/paulmillr/chokidar
    watchFiles: {
      paths: ['assets', 'static'],
      options: {
        usePolling: true,
      },
    },
  },
};
```

### But, I have one question.
#### 1.Which file should I put the [setupWatchFiles](https://github.com/liyincode/rsbuild/blob/761e9683508fb20711cecc883d6543666a4c82a8/packages/core/src/server/devServer.ts#L214) method in.
Since this file is used to create the `dev server` and `setupWatchFiles method` is used to setup watch files, I think it should be in another file, but I don't know which file it should be in, so I'll put it here first.

**Comment by chenjiahan** [comment]
@9aoy can you check this

**Comment by 9aoy** [comment]
@liyincode  Thanks for your contribution, I think you could create a PR ~
Regarding the question with setupWatchFiles method , personally, we should avoid a file that is too long. I think you can split setupWatchFiles into a new separate file and name  it `watchFiles.ts`.

**Comment by liyincode** [comment]
> @liyincode Thanks for your contribution, I think you could create a PR ~ Regarding the question with setupWatchFiles method , personally, we should avoid a file that is too long. I think you can split setupWatchFiles into a new separate file and name it `watchFiles.ts`.

Thanks for reply. I will split the method to new file, then create pr😀

**Comment by FaureWu** [comment]
> Hi, I finished the feature,It's working.😁
> 
> [code is here](https://github.com/liyincode/rsbuild/blob/761e9683508fb20711cecc883d6543666a4c82a8/packages/core/src/server/devServer.ts#L207) [e2e test is here](https://github.com/liyincode/rsbuild/blob/feat%2Fdev-watchFiles/e2e/cases/server/watch-files/index.test.ts)
> 
> ### Usage
> export default { 
>   dev: {
>     watchFiles: 'assets/example.txt',
>   }, 
> };
> export default {
>   dev: {
>     watchFiles: 'assets/**/*',
>   },
> };
> export default { 
>   dev: {
>     watchFiles: ['assets/example.txt', 'static/example.txt']
>   }, 
> };
> export default { 
>   dev: {
>     watchFiles: 'assets',
>   }, 
> };
> export default {
>   dev: {
>     watchFiles: ['assets', 'static'],
>   },
> };
> export default { 
>   dev: {
>     // use chokidar options https://github.com/paulmillr/chokidar
>     watchFiles: {
>       paths: ['assets', 'static'],
>       options: {
>         usePolling: true,
>       },
>     },
>   },
> };
> ### But, I have one question.
> #### 1.Which file should I put the [setupWatchFiles](https://github.com/liyincode/rsbuild/blob/761e9683508fb20711cecc883d6543666a4c82a8/packages/core/src/server/devServer.ts#L214) method in.
> Since this file is used to create the `dev server` and `setupWatchFiles method` is used to setup watch files, I think it should be in another file, but I don't know which file it should be in, so I'll put it here first.

When I modify the watchFiles in rsbuild by api.modifyRsbuildConfig, it's no effective

**Comment by chenjiahan** [comment]
@FaureWu can you create a new issue and provide a reproduction repo?
