### ISSUE TITLE
[Bug]: terser  options "manage.keep_fnames" can be RegExp

### ISSUE THREAD

**Issue by linzebingo** [web-infra-dev/rsbuild#1917]
### Version

```sh
@rsbuild/* 0.5.2
```

### Details

terser  options "manage.keep_fnames" can be RegExp

![image](https://github.com/web-infra-dev/rsbuild/assets/12185104/bc57c3ea-ab97-4e5d-9a66-d41972c24cee)

link https://terser.org/docs/options/#mangle-options

### Reproduce link

N/A

### Reproduce Steps

1、create a rsbuild project
2、modify rsbuild.config.ts
```js
    minify: {
      jsOptions: {
        mangle: {
          keep_fnames: /stringify/,
        },
      },
    },
```
3、got errror
![image](https://github.com/web-infra-dev/rsbuild/assets/12185104/a9c81ea3-7007-4bd8-9179-2c8d72e131f3)

**Comment by chenjiahan** [comment]
Rsbuild use SWC to minify the JS code, and SWC does not supports `keep_fnames` RegExp yet, see: 

- https://swc.rs/docs/configuration/minification#jscminifymangle
- https://github.com/search?q=repo%3Aswc-project%2Fswc+keep_fnames&type=code

You can submit an issue to the SWC repo to request this feature 😄

**Comment by chenjiahan** [comment]
Also, we plan to support using Terser as the JS minimizer in Rsbuild / Rspack projects, ref: https://github.com/web-infra-dev/rspack/issues/3639
