### ISSUE TITLE
[Bug]: 在vue单文件组件中使用less的问题

### ISSUE THREAD

**Issue by skymoonya** [web-infra-dev/rsbuild#1919]
### Version

```sh
System:
    OS: macOS 13.6.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 287.43 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
Browsers:
    Chrome: 123.0.6312.58
    Safari: 17.3.1
npmPackages:
    @rsbuild/core: ^0.5.2 => 0.5.2 
    @rsbuild/plugin-vue: ^0.5.2 => 0.5.2
```

### Details

在vue单文件组件中使用less `@import`了另一个`非同级目录`的less文件，并且这个less文件中存在`路径别名`如: `url('@/assets/logo.png')`时，在构建中会报如下类似的错误
<img width="888" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/13905873/2072f853-458e-44a1-a158-7833eae423eb">
在vue2和vue3中都能复现，sass没有这个问题，可能是less-loader的问题，很容易复现，下面是一个最小复现的demo
[demo.zip](https://github.com/web-infra-dev/rsbuild/files/14721046/demo.zip)

### Reproduce link

-

### Reproduce Steps

npm run dev

**Comment by chenjiahan** [comment]
I think this is a bug of less-loader, you can add a tilde to force less-loader to resolve correctly:

```diff
.a {
-  background: url('@/assets/nodejs.jpeg') no-repeat;
+  background: url('~@/assets/nodejs.jpeg') no-repeat;
}
```

see: 

- https://github.com/webpack-contrib/less-loader/issues/332
- https://github.com/webpack-contrib/css-loader/issues/914

**Comment by skymoonya** [comment]
@chenjiahan This solution doesn't work, there is a qualifier in the content of this issue: `non-sibling directory`. There is no such problem in the `sibling directory`
```
build error
- non-sibling directory/ 
  - src/
    - main.js
    - style.less      -- `url('@/assets/nodejs.jpeg')`
    - assets/
      - nodejs.jpeg
    - views/
      - App.vue       -- `@import '@/style.less';` or `@import '../style.less';`

build success
- sibling directory/
  - src/
    - main.js
    - assets/
      - nodejs.jpeg
    - views/
      - App.vue       -- `@import '@/views/style.less';` or `@import './style.less';`
      - style.less    -- `url('@/assets/nodejs.jpeg')`
 
And this bug only exists in vue SFC

build success
- non-sibling directory/ 
  - src/
    - main.js         -- `import '@/views/style.less'`
    - assets/
      - nodejs.jpeg
    - views/
      - App.vue
      - style.less    -- `url('@/assets/nodejs.jpeg')`
```

**Comment by chenjiahan** [comment]
Yes, the problem still exists at the moment. We need to further determine whether this is caused by Rspack or these loaders.
