### ISSUE TITLE
[Feature]: support icss-utils

### ISSUE THREAD

**Issue by royue** [web-infra-dev/rsbuild#1936]
### What problem does this feature solve?

support css modules and less modules[ icss-utils ](https://www.npmjs.com/package/icss-utils) 

### What does the proposed API look like?

output.cssModules.icss = true

**Comment by chenjiahan** [comment]
Is this equivalent to css-loader's `mode: 'icss'`?

https://github.com/webpack-contrib/css-loader?tab=readme-ov-file#mode

**Comment by chenjiahan** [comment]
This issue has no response in several days so it will be closed. Feel free to comment and reopen it if you have any further questions.
