### ISSUE TITLE
[Bug]: css/less中使用绝对路径引用线上资源(非本地资源)报错

### ISSUE THREAD

**Issue by tiannengyu** [web-infra-dev/rsbuild#1948]
### Version

```sh
rsbuild@0.4.6
```

### Details

`
@font-face {
  font-family: DingTalk;
  src: url('/amcp/image/font/DingTalkJinBuTi.ttf');
}
`
报错信息
`
error   Compile error: 
Failed to compile, check the errors for troubleshooting.
File: ./src/routes/InvestmentCalendar/components/index.less
  × Resolve error: Can't resolve '/amcp/image/font/DingTalkJinBuTi.ttf' in '/Users/tiannengyu/private/gitlab2/zgzx-trade-manager-front/src/routes/InvestmentCalendar/components'
   ╭─[1:1]
 1 │ @font-face{
 2 │   font-family: DingTalk;
 3 │   src: url(/amcp/image/font/DingTalkJinBuTi.ttf);
   ·        ─────────────────────────────────────────
 4 │ }
 5 │ .src-routes-InvestmentCalendar-components-index__calendar_common-_9cab1__zgtz {
   ╰────

start   Compiling...
`
构建时报错，在css和less中使用如上方式，src :url('线上资源绝对路径')会报错

### Reproduce link

/

### Reproduce Steps

/

**Comment by xc2** [comment]
please try out / 请尝试：

```js
{
  resolve: {
    alias: {
      "/amcp/image/font": false,
    },
  },
}
```

**Comment by xc2** [comment]
please try out / 请尝试：

```ts
export default defineConfig({
  // ...
  source: {
    // ...
    alias: {
      "/amcp/image/font": false,
    },
  },
  // ...
});
```

**Comment by tiannengyu** [comment]
> please try out / 请尝试：
> 
> ```ts
> export default defineConfig({
>   // ...
>   source: {
>     // ...
>     alias: {
>       "/amcp/image/font": false,
>     },
>   },
>   // ...
> });
> ```

尝试这么做，在mac下构建正常，但在部分windows系统机器下，会报如下错误
![clipbord_1711705567526](https://github.com/web-infra-dev/rsbuild/assets/20297933/f402de3a-84b4-4181-9962-b12666a9bb41)

**Comment by ChenXplorer** [comment]
the same as u

**Comment by tiannengyu** [comment]
@xc2 可以协助看下这个问题吗

**Comment by chenjiahan** [comment]
用 externals 也可以避免 resolve 这个模块，比如：

```ts
export default defineConfig({
  output: {
    externals: [/\/image\/font/g],
  },
});
```

**Comment by ChenXplorer** [comment]
但有个疑问，为何mac 没问题，win有问题。

**Comment by chenjiahan** [comment]
通常是路径分隔符的问题，Mac 和 Windows 采用了不同的路径分隔符

**Comment by ChenXplorer** [comment]
请问下，rsbuild 可以解决这个问题吗，不需要额外的配置（例如无额外配置，mac可以正常build）

**Comment by chenjiahan** [comment]
目前来说不会解决，这个路径会触发 webpack / Rspack 的 resolve 逻辑，在 create-react-app 中也能复现该问题
