### ISSUE TITLE
[Bug]: @swc/plugin-styled-jsx not working in rsbuild

### ISSUE THREAD

**Issue by uncaught** [web-infra-dev/rsbuild#1960]
### Version

```sh
System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 11.32 GB / 15.62 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  npmPackages:
    @rsbuild/core: ^0.5.4 => 0.5.4
    @rsbuild/plugin-react: ^0.5.4 => 0.5.4
```

### Details

All I did was using `npm create rsbuild@latest` and then tried to get styled-jsx with `resolve` to work. (Sass is a bonus here.)

Without any extra configuration, I run into this obvious error:

```
Uncaught Error: styled-jsx/css: if you are getting this error it means that your `resolve` tagged template literals were not transpiled.
```

After digging into the documentation, I've added this to the configuration:

```ts
  tools: {
    swc: {
      jsc: {
        experimental: {
          plugins: [
            [
              '@swc/plugin-styled-jsx',
              {
                plugins: ['@styled-jsx/plugin-sass'],
              },
            ],
          ],
        },
      },
    },
  },
```

As documented [here](https://rsbuild.dev/config/tools/swc#toolsswc) and then [here](https://swc.rs/docs/configuration/compilation#jscexperimentalplugins).

But that gives me this error:

```
Html Webpack Plugin:
Error: [html-rspack-plugin]: [html-rspack-plugin]:   × Module parse failed:
  ╰─▶   × JavaScript parsing error: Expression expected
         ╭────
       1 │  = this;
         ·  ─
         ╰────
      
  help: 
        File was processed with these loaders:
         * builtin:swc-loader??ruleSet[1].rules[3].use[0]
        You may need an additional loader to handle the result of these loaders.
```

I don't know where I'm going wrong here. I've not configured any HTML plugin and I can't find any issues regarding this problem.

-----

I'm totally new to rsbuild/rspack/swc, so please point me in the right direction if this is the wrong place for this issue.

### Reproduce link

https://github.com/uncaught/rsbuild-test

### Reproduce Steps

```
git clone git@github.com:uncaught/rsbuild-test.git
cd rsbuild-test
npm install
npm run dev
```

**Comment by chenjiahan** [comment]
This might be an issue of SWC version mismatch, see: https://github.com/web-infra-dev/rspack/issues/5921

**Comment by uncaught** [comment]
> This might be an issue of SWC version mismatch, see: [web-infra-dev/rspack#5921](https://github.com/web-infra-dev/rspack/issues/5921)

Thank you a lot! That was it. I locked the version to `@swc/plugin-styled-jsx@1.5.115` which works!
