### ISSUE TITLE
[Bug]: 开发调试预览效果与build preview 效果不一致

### ISSUE THREAD

**Issue by zhuyuanmin** [web-infra-dev/rsbuild#1980]
### Version

```sh
windows11
Chrome
node: 18
```

### Details

![image](https://github.com/web-infra-dev/rsbuild/assets/23226876/686ff057-ef11-45c2-82c6-d58841c63e48)

![image](https://github.com/web-infra-dev/rsbuild/assets/23226876/be89a1fa-50f9-405b-bbfd-5cd8f791cfe2)

### Reproduce link

none

### Reproduce Steps

npm run build && npm run preview

**Comment by zhuyuanmin** [comment]
由于公司内网安全性问题，我无法提供生产地址。但是通过我排查，找到了问题所在。开发模式下，本地服务会自动加载依赖库的css文件。形如：http://localhost:8080/static/cssvendors-node_modules_liveapps_antd-lowcode-materials_lib_index_js-node_modules_liveapps_antd--90a1f9.css，而build之后，组件库的样式文件没有导入，导致缺少样式。我尝试手动在代码中引入组件库的样式文件，结果build之后与预期一致。但是理论上，开发模式能自动加载，build也应该打进样式文件进去才是合理的。

**Comment by chenjiahan** [comment]
Rsbuild 默认不会自动加载 CSS 呢

**Comment by chenjiahan** [comment]
你可以尝试提供一个最小复现 demo
