### ISSUE TITLE
[Bug]: SCSS files not loaded

### ISSUE THREAD

**Issue by JoseBuendiaDigio** [web-infra-dev/rsbuild#1999]
### Version

```sh
System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 11.40 GB / 15.48 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  npmPackages:
    @rsbuild/core: 0.5.2 => 0.5.2 
    @rsbuild/plugin-eslint: ^0.5.2 => 0.5.2 
    @rsbuild/plugin-react: 0.5.2 => 0.5.2
```

### Details

I'm currently migrating from RsPack to RsBuild but SCSS seems to not be loaded.

Here is how I config it in RsPack

```
{
  test: /\.scss$/,
  use: [
    'style-loader',
    {
      loader: 'css-loader',
      options: {
        importLoaders: 3,
        sourceMap: false,
        modules: {
          mode: 'icss',
        },
      },
    },
    {
      loader: 'postcss-loader',
      options: {
        postcssOptions: {
          ident: 'postcss',
          config: false,
          sourceMap: false,
          
        },
      },
    },
    {
      loader: 'resolve-url-loader',
    },
    {
      loader: 'sass-loader',
      options: {
        sourceMap: true,
        
      },
    },
  ],
}
```

But in RsBuild I tried some things with styleLoader and postscss but is not loading scss files (it load it as undefined).

How should it load it?

### Reproduce link

https://github.com/JoseBuendiaDigio/rsbuild-scss

### Reproduce Steps

rsbuild build and rsbuild dev

**Comment by JoseBuendiaDigio** [comment]
Maybe I need to add css-loader and style-loader to scss rule but I don't know how to add it. I tried things like this, but without result.

`config.module.rules[10].oneOf[1].use.unshift(styleLoader, cssLoader);`

**Comment by chenjiahan** [comment]
Rsbuild provides builtin supports for SCSS, so user do not need to add the css-loader/scss-loader/postcss-loader.

If you want to use `style-loader` in Rsbuild, you can enable this option: https://rsbuild.dev/config/output/inject-styles

**Comment by JoseBuendiaDigio** [comment]
Yes, I tried activating this option but then fails the build becauses it can read the scss values when readed from js

**Comment by JoseBuendiaDigio** [comment]
Ok, I will attempt it

**Comment by JoseBuendiaDigio** [comment]
Reproduction: https://github.com/JoseBuendiaDigio/rsbuild-scss

**Comment by chenjiahan** [comment]
You can custom the css-loader config and it will work:

```diff
export default defineConfig({
  plugins: [pluginReact()],
  output: {
    injectStyles: true,
  },
+  tools: {
+    cssLoader() {
+      return {
+        modules: {
+          mode: "icss",
+        },
+      };
+    },
+  },
});
```

![image](https://github.com/web-infra-dev/rsbuild/assets/7237365/6238197c-ac25-4e1e-bc1b-b63d4ae7f402)

**Comment by JoseBuendiaDigio** [comment]
ah, thanks, interesting that I tried it but with object type and in this way isn't working, is this a bug? 
If not I will close this

**Comment by chenjiahan** [comment]
Need a reproduction repo

**Comment by JoseBuendiaDigio** [comment]
@chenjiahan 

Reproduction: https://codesandbox.io/p/devbox/beautiful-shockley-scct73?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clzqnwpdz0007356i7fhppgnz%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clzqnwpdy0002356ifvbdc9vf%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clzqnwpdz0004356i88rj40md%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clzqnwpdz0006356ixhwgiivf%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clzqnwpdy0002356ifvbdc9vf%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzqnwpdy0001356io5q2a4bu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clzqnwpdy0002356ifvbdc9vf%2522%252C%2522activeTabId%2522%253A%2522clzqnwpdy0001356io5q2a4bu%2522%257D%252C%2522clzqnwpdz0006356ixhwgiivf%2522%253A%257B%2522id%2522%253A%2522clzqnwpdz0006356ixhwgiivf%2522%252C%2522activeTabId%2522%253A%2522clzqnyyfu001v356ibqji1g16%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzqnwpdz0005356ibjozggs4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A3000%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clzqnyyfu001v356ibqji1g16%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clzqnwpdz0004356i88rj40md%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzqnwpdz0003356ijpe425vu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clzqnwpdz0004356i88rj40md%2522%252C%2522activeTabId%2522%253A%2522clzqnwpdz0003356ijpe425vu%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by witsaint** [comment]
@JoseBuendiaDigio  You can set `namedExport: false`  in `tools.cssLoader.modules` option

 `tools: {
    cssLoader() {
      return {
        modules: {
          mode: "icss",
          namedExport: false,
        },
      };
    },
  }`

Because if tools.cssLoader is a function type, the return value is the final configuration

Is right？ @chenjiahan

**Comment by JoseBuendiaDigio** [comment]
@witsaint With this seems to work, but this behaviour has changed?

**Comment by chenjiahan** [comment]
> Is right？

Yes, it is right.

> this behaviour has changed?

css-loader v7 changed the default behavior, see: https://github.com/webpack-contrib/css-loader/releases/tag/v7.0.0
