### ISSUE TITLE
[Feature]: Support for alias from jsconfig and eslint issue fix internally for alias

### ISSUE THREAD

**Issue by xettri** [web-infra-dev/rsbuild#2000]
### jsconfig handling
We would like to have jsconfig support internally like we have with tsconfig.

**Example 1:**
```json
{
  "compilerOptions": {
    "baseUrl": "./src",
  }
}
```

if src has folder my-components
```js
import component from 'my-components/some';
```

**Example 2:**
```
{
  "compilerOptions": {
    "paths": {
      "@my-components/*": ["./src/components/*"]
    }
  }
}
```
```js
import component from '@my-components/some';
```

**Example 3:**
```
{
  "compilerOptions": {
    "baseUrl": "./src",
    "paths": {
      "@my-components/*": ["./components/*"]
    }
  }
}
```
```js
import component from '@my-components/some';
```

### Eslint handling `@rsbuild/plugin-eslint`
Current behaviour: right now eslint does not internally resolve alias
Expected: Eslint with `@rsbuild/plugin-eslint` should resolve alias from `rsbuild.config` `tsconfig` and `jsconfig` based on configuration and priority

**Let me know if these things already available in build tool I will explore that.

### What does the proposed API look like?

I'm in search of a solution in JavaScript projects that handles jsconfig similarly to tsconfig, enabling alias resolution. Additionally, I'm interested in default alias handling within ESLint (`@rsbuild/plugin-eslint`), ensuring it's not overwritten by external configurations, or exploring ways to prevent such overwrites specifically for aliases.

**Comment by chenjiahan** [comment]
Compared to `jsconfig.json#paths`, the `package.json#imports` is a more standard approach, which is natively supported by Node.js. 

Can you try`package.json#imports` and see if it meets your needs? 

https://nodejs.org/docs/latest/api/packages.html#imports

**Comment by chenjiahan** [comment]
For the ESLint part, should ESLint support aliases?

I understand that `eslint-plugin-import` may contain implementations related to resolver or tsconfig paths, but ESLint itself does not need to care about aliases.

**Comment by xettri** [comment]
@chenjiahan
I'm looking for built-in support similar to Create React App (CRA) to fix this problem. Specifically, I want the build process to automatically find source files if there's either a tsconfig or jsconfig file present. I've tried some workarounds that are currently working, but I'm hoping for an built-in solution.
One common situation is when you set a baseUrl in your configuration, like `"baseUrl": "./src"`. This means everything inside the src folder can be treated as an alias, which users usually have to set up manually. Let me know if there's a simpler way to do this.

```diff
source: {
+  alias: {
+   api: './src/api',
+    components: './src/components',
+    hooks: './src/hooks',
+    // other alias
+  },
},
```

#### Hack: This is example how hack for for jsconfig 

```js
const root = process.cwd();

const resolve = (...args) => {
  return path.resolve(root, ...args);
};

const getJSConfig = () => {
  if (fs.existsSync(resolve("jsconfig.json"))) {
    const jsconfig = fs.readFileSync(resolve("jsconfig.json"), "utf8");
    return JSON.parse(jsconfig);
  } else {
    return {};
  }
};

const createAlias = (customAlias = {}) => {
  const { compilerOptions } = getJSConfig();
  const alias = { ...customAlias };
  try {
    let baseUrl = root;
    if (compilerOptions) {
      if (
        compilerOptions.baseUrl &&
        fs.existsSync(resolve(root, compilerOptions.baseUrl))
      ) {
        baseUrl = resolve(root, compilerOptions.baseUrl);
        // if only base url exist then create its all folders as alias
        // let src is base url so all its folders will become alias
        getAliasDefaultPaths(baseUrl).forEach((folder) => {
          const aliasPath = resolve(baseUrl, folder);
          if (fs.existsSync(aliasPath)) {
            alias[folder] = aliasPath;
          }
        });
      }
    }
    return alias;
  } catch (e) {
    console.error(e);
  }
  return alias;
};
```
```diff
export default defineConfig({
  source: {
    define: publicEnv,
+    alias: createAlias()
  },
  // other config here
});
```

Is it possible for a similar solution to be integrated as a built-in feature of rsbuild? This will be helpful who is migrating from **CRA** to **rsbuild**.

Following is builtin code in **CRA (ejected)** file: `config/modules.js`

<img width="914" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/31788510/6a5d44a4-c5ab-4b9e-ba26-e8c0c33ccf77">

**Comment by chenjiahan** [comment]
How about add this config to the `rsbuild.config.*` file? It should work:

```js
export default {
  source: {
    tsconfigPath: './jsconfig.json',
  },
};
```

https://rsbuild.dev/config/source/tsconfig-path

**Comment by xettri** [comment]
@chenjiahan, yes it will work with  `tsconfigPath: "./jsconfig.json"` and `source.aliasStrategy = "prefer-tsconfig"`(default with tsconfigPath), not sure might be possible issues can be seen as its backed by `tsconfig-paths-webpack-plugin`.
We can add this solution in doc if possible.

**Comment by chenjiahan** [comment]
Sure, I will add e2e case and document for this.

The `tsconfigPath` is backed by Rspack (see https://www.rspack.dev/config/resolve.html#resolvetsconfigpath), which is functionally equivalent to `tsconfig-paths-webpack-plugin`,
