### ISSUE TITLE
[Bug]: 使用rsbuild创建 antd@4.24.15时使用 source.transformImport 配置按需加载报错

### ISSUE THREAD

**Issue by wang-yi-bit64** [web-infra-dev/rsbuild#2014]
### Version

```sh
系统:win11
浏览器：Edge
{
  "name": "test-antdless",
  "private": true,
  "version": "1.0.0",
  "scripts": {
    "dev": "rsbuild dev --open",
    "build": "rsbuild build",
    "preview": "rsbuild preview"
  },
  "dependencies": {
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "@ant-design/icons": "1.0.0",
    "antd": "4.24.15"
  },
  "devDependencies": {
    "@rsbuild/core": "^0.5.7",
    "@rsbuild/plugin-react": "^0.5.7"
  }
}
```

### Details

运行的dev的时候报错
Failed to compile, check the errors for troubleshooting.
File: ./node_modules/antd/es/style/default.less
  × Module build failed:
  ╰─▶   ×
        │ SyntaxError
        │
        │ (43:16) D:\work-code\Vite\jsTest\test-antdless\node_modules\antd\es\style\default.less Double colon
        │
        │   41 |   color: #666;
        │   42 |   font-size: 14px;
        │ > 43 |   font-family: : "Hiragino Sans GB", Helvetica, "sans-serif";
        │      |                ^
        │   44 |   font-variant: tabular-nums;
        │   45 |   line-height: 1.5715;
        │
        │

  help: File was processed with this loader: 'D:\work-code\Vite\jsTest\test-antdless\node_modules\@rsbuild\shared\compiled\postcss-loader\index.js??ruleSet[1].rules[10].oneOf[1].use[0]$D:\work-
        code\Vite\jsTest\test-antdless\node_modules\@rsbuild\shared\compiled\less-loader\index.js??ruleSet[1].rules[10].oneOf[1].use[1]'

### Reproduce link

git@github.com:wang-yi-bit64/rsbuild-testantd4.git

### Reproduce Steps

dev 报错 
运行的dev的时候报错
Failed to compile, check the errors for troubleshooting.
File: ./node_modules/antd/es/style/default.less
  × Module build failed:
  ╰─▶   ×
        │ SyntaxError
        │
        │ (43:16) D:\work-code\Vite\jsTest\test-antdless\node_modules\antd\es\style\default.less Double colon
        │
        │   41 |   color: #666;
        │   42 |   font-size: 14px;
        │ > 43 |   font-family: : "Hiragino Sans GB", Helvetica, "sans-serif";
        │      |                ^
        │   44 |   font-variant: tabular-nums;
        │   45 |   line-height: 1.5715;
        │
        │

  help: File was processed with this loader: 'D:\work-code\Vite\jsTest\test-antdless\node_modules\@rsbuild\shared\compiled\postcss-loader\index.js??ruleSet[1].rules[10].oneOf[1].use[0]$D:\work-
        code\Vite\jsTest\test-antdless\node_modules\@rsbuild\shared\compiled\less-loader\index.js??ruleSet[1].rules[10].oneOf[1].use[1]'

**Comment by 9aoy** [comment]
<img width="733" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/22373761/e4a80a5b-8b4d-4c50-b920-3bf11344d524">

<img width="584" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/22373761/44f78ae7-50fc-43df-990d-5fb60d0f3df2">

@wang-yi-bit64  The key should be `font-family` not `font-family:` 😂
