### ISSUE TITLE
[Bug]: Using `rsbuild.createDevServer` within vitest cause rspack panic

### ISSUE THREAD

**Issue by colinaaa** [web-infra-dev/rsbuild#2057]
### Version

```sh
npmPackages:
    @rsbuild/core: ^0.6.0 => 0.6.0 
    @rsbuild/plugin-react: ^0.6.0 => 0.6.0
```

### Details

I'm using `rsbuild.createDevServer` with `vitest` and it crashed.

```
Message:  failed to receive tsfn value: RecvError
Location: crates/rspack_napi/src/threadsafe_function.rs:96
```

```ts
const devServer = await rsbuild.createDevServer(); // crash here
```

If I change from `createDevServer` to `build`, it works just fine.

Note that the crash also exists on `@rsbuild/core@0.5.7` in my real-world project, but with a different panic position.

```
Message:  should have module graph module
Location: crates/rspack_core/src/module_graph/mod.rs:1208
```

Add `tools: { htmlPlugin: false }` to `RsbuildConfig` to reproduce this panic.

### Reproduce link

https://github.com/colinaaa/rsbuild-vitest-crash-repro

### Reproduce Steps

1. pnpm install
2. pnpm vitest

**Comment by 9aoy** [comment]
The error occurred because ﻿close was called prematurely, interrupting the rspack compilation process and triggering a compilation exception.

Note that the ﻿rsbuild `createDevServer` / `listen` done does not mean the completion of compilation. Instead, rsbuild provides [onDevCompileDone](https://rsbuild.dev/api/javascript-api/instance#rsbuildondevcompiledone) hook for detecting when the development compilation finishes.


![20240410-155257](https://github.com/web-infra-dev/rsbuild/assets/22373761/5d507d24-b475-4222-b187-b11265b921a9)

**Comment by colinaaa** [comment]
Oh, Thanks! Awaiting a timeout works for me! But it seems like the `onDevCompileDone` is not called:

```ts

    let resolve: () => void;
    const p = new Promise<void>((r) => (resolve = r));
    rsbuild.onDevCompileDone(() => {
      console.log('onDevCompileDone'); // never calls
      resolve();
    });

    const devServer = await rsbuild.createDevServer();
    const { server } = await devServer.listen();
    await p; // <--- timeout
    await expect(server.close()).resolves.toBeUndefined();
```

**Comment by 9aoy** [comment]
This hook is called only when ﻿`NODE_ENV` is set to "development"; however, in your case, `﻿NODE_ENV` is already set to "test".

<img width="901" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/22373761/9a938ad5-cd59-4c60-af0c-b9df2b95dccc">

<img width="734" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/22373761/26245299-4027-4043-af02-28da4bb1f741">


<img width="613" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/22373761/c68a1752-63dd-4809-886a-b15110ce9ab7">

**Comment by colinaaa** [comment]
Thanks a lot, my problem solved.
