### ISSUE TITLE
[Bug]: "all-in-one" performance.chunkSplit.strategy creates more than one js chunk file

### ISSUE THREAD

**Issue by jesus-chacon** [web-infra-dev/rsbuild#2060]
### Version

```sh
System:
    OS: macOS 13.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 95.73 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 123.0.6312.107
    Safari: 16.6
  npmPackages:
    @rsbuild/core: ^0.6.0 => 0.6.0
    @rsbuild/plugin-image-compress: ^0.6.0 => 0.6.0
    @rsbuild/plugin-lightningcss: ^0.6.0 => 0.6.0
    @rsbuild/plugin-vue: ^0.6.0 => 0.6.0
```

### Details

I am using this config.

`
  performance: {
    chunkSplit: { strategy: "all-in-one" },
  },
`

But it not work properly the output is different if I am using the split-by-experience for example but the all-in-one stategy create like 45 chunks of js and 35 for css. This is working properly?

I have test this config for other versions (from 0.2.x to 0.6.0) has no difference in the output.

### Reproduce link

https://github.com/eidellev/rspack-bug-reproduction

### Reproduce Steps

Only is needed execute the buidl process of the project with the strategy all-in-one.

**Comment by SoonIter** [comment]
Actually, "all-in-one" corresponds to `optimization.splitChunk = false` in rspack

Related [webpack/optimization.splitchunks](https://webpack.js.org/plugins/split-chunks-plugin/#optimizationsplitchunks) and [rspack/optimization.splitchunks](https://www.rspack.dev/plugins/webpack/split-chunks-plugin.html#optimizationsplitchunks-1)

You can see the `rspack.config.js` inside Rsbuild with [`DEBUG=rsbuild`](https://rsbuild.dev/guide/debug/debug-mode#debug-mode) e.g `DEBUG=rsbuild  rsbuild build`, `optimization.splitChunk = false` has already been set by Rsbuild

When setting `optimization.splitChunk = false`, all chunks except asynchronous chunks will be bundled into one file.

If you want asynchronous chunk to be bundled too, you need to also set `output.asyncChunks = false`

Maybe `all-in-one` is easy to cause misunderstanding, and we will make corresponding changes in the document or code.

**Comment by chenjiahan** [comment]
> Maybe all-in-one is easy to cause misunderstanding, and we will make corresponding changes in the document or code.

Agreed, we can document this

**Comment by jesus-chacon** [comment]
ok, thanks you so much,  i am going to test it deeper and review this config. 👍
