### ISSUE TITLE
找不到名称“process” 

### ISSUE THREAD

**Issue by SheepYang1993** [web-infra-dev/rsbuild#2072]
### Version

```sh
{
  "name": "demo",
  "private": true,
  "version": "1.0.0",
  "scripts": {
    "dev": "rsbuild dev --open",
    "build": "rsbuild build",
    "preview": "rsbuild preview"
  },
  "dependencies": {
    "axios": "^1.6.8",
    "crypto-js": "^4.2.0",
    "jsencrypt": "^3.3.2",
    "qs": "^6.12.0",
    "ts-md5": "^1.3.1",
    "vant": "^4.8.10",
    "vue": "^3.4.19",
    "vue-router": "4"
  },
  "devDependencies": {
    "@rsbuild/core": "^0.5.9",
    "@rsbuild/plugin-rem": "^0.5.9",
    "@rsbuild/plugin-vue": "^0.5.9",
    "typescript": "^5.4.2"
  }
}
```

### Details

const baseURL = process.env.PUBLIC_BASE_URL ?? "";

找不到名称“process”。是否需要安装 Node.js 的类型定义? 请尝试运行 `npm i --save-dev @types/node`。

### Reproduce link

none

### Reproduce Steps

none

**Comment by chenjiahan** [comment]
报错信息已经很明确了

**Comment by SheepYang1993** [comment]
> 报错信息已经很明确了

我是用的pnpm，执行`pnpm add -D @types/node`装完后，process没报错了，但是`process.env.VUE_APP_BASE_URL`还是没读取到值。

console报错，`Uncaught ReferenceError: process is not defined`

有在src目录下配置`.env.development`和`.env.production`文件，里面只有一个值`VUE_APP_BASE_URL=http://xxx.xxx.xxx.xxx:xxxx`

**Comment by 9aoy** [comment]
.env 文件放在项目根目录下哈，不是 src 下
https://rsbuild.dev/zh/guide/advanced/env-vars#env-%E6%96%87%E4%BB%B6

**Comment by SheepYang1993** [comment]
> .env 文件放在项目根目录下哈，不是 src 下 https://rsbuild.dev/zh/guide/advanced/env-vars#env-%E6%96%87%E4%BB%B6

![image](https://github.com/web-infra-dev/rsbuild/assets/15150244/06f5d8a3-2c97-48e7-a841-9a9b8e41deb1)
已放置在根目录下，还是提示`Uncaught ReferenceError: process is not defined`

**Comment by SheepYang1993** [comment]
这是我的配置文件
![image](https://github.com/web-infra-dev/rsbuild/assets/15150244/f2239d38-986e-49d3-8cfd-646154779ae9)
![image](https://github.com/web-infra-dev/rsbuild/assets/15150244/96ef8f0e-8a85-4341-b709-819da65f2a7a)

**Comment by 9aoy** [comment]
要 PUBLIC_ 开头的自定义环境变量才可以在 client 代码中访问，你看下文档介绍
https://rsbuild.dev/zh/guide/advanced/env-vars#public-%E5%8F%98%E9%87%8F
