### ISSUE TITLE
[Bug]: 打包后警告 Conflicting order between

### ISSUE THREAD

**Issue by wengjiacheng** [web-infra-dev/rsbuild#2088]
### Version

```sh
System:
    OS: macOS 13.3.1
    CPU: 2.5 GHz Intel Core i7
    Memory: 16 GB 2133 MHz LPDDR3
  Browsers:
    Chrome:  120.0.6099.109
  npmPackages:
    "@rsbuild/core": "^0.6.1",
    "@rsbuild/plugin-vue2": "^0.6.1",
```

### Details

打包后会提示警告
<img width="1183" alt="Snipaste_2024-04-15_14-04-09" src="https://github.com/web-infra-dev/rsbuild/assets/24770388/2760a233-5aec-478d-a50d-886da14fb114">

### Reproduce link

NONE

### Reproduce Steps

pnpm run dev

**Comment by yangcore** [comment]
> ### Version
> ```shell
> System:
>     OS: macOS 13.3.1
>     CPU: 2.5 GHz Intel Core i7
>     Memory: 16 GB 2133 MHz LPDDR3
>   Browsers:
>     Chrome:  120.0.6099.109
>   npmPackages:
>     "@rsbuild/core": "^0.6.1",
>     "@rsbuild/plugin-vue2": "^0.6.1",
> ```
> 
> ### Details
> 打包后会提示警告 <img alt="Snipaste_2024-04-15_14-04-09" width="1183" src="https://private-user-images.githubusercontent.com/24770388/322368806-2760a233-5aec-478d-a50d-886da14fb114.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTE3NTUsIm5iZiI6MTcxMzUxMTQ1NSwicGF0aCI6Ii8yNDc3MDM4OC8zMjIzNjg4MDYtMjc2MGEyMzMtNWFlYy00NzhkLWE1MGQtODg2ZGExNGZiMTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA3MjQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkNWFiOGM5MmVkMWMxZDFlNWU0ZDdmMjc5ZjYwNWQxM2QyZjVhNTBlNzYxMjE1YzNjODY3MGM0ZWJmZGRmNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.me1N224EW1SyNLuppxNMClw4obI5d-qlrNCZefv642I">
> 
> ### Reproduce link
> NONE
> 
> ### Reproduce Steps
> pnpm run dev

同问，这个在webpack中是修改mini-css-extract的配置，可以忽略掉警告的，查了好久也没查到rspack怎么忽略掉这个警告 @chenjiahan

**Comment by chenjiahan** [comment]
See: https://www.rspack.dev/zh/blog/announcing-0.6.html#%E5%BD%93-css-%E7%9A%84%E9%A1%BA%E5%BA%8F%E5%9C%A8%E5%A4%9A%E4%B8%AA-chunk-%E4%B8%AD%E4%B8%8D%E4%B8%80%E8%87%B4%E6%97%B6%E5%8F%91%E5%87%BA%E8%AD%A6%E5%91%8A

Rsbuild will ignore it by default in the next version.
