### ISSUE TITLE
[Bug]: is "ua" in "output.polyfill" useless?

### ISSUE THREAD

**Issue by fi3ework** [web-infra-dev/rsbuild#2091]
### Version

```sh
latest
```

### Details

"ua" is a public option to user, but not documented in https://rsbuild.dev/config/output/polyfill. And it behaves the same as "off". Is it for some compatibility consideration, or can be removed?

<img width="295" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/12322740/6abbdd48-125f-4225-b985-d23871bce47e">

### Reproduce link

N/A

### Reproduce Steps

N/A

**Comment by chenjiahan** [comment]
It is used by Modern.js, we should remove it and extend the typing in Modern.js
