### ISSUE TITLE
[Bug]: Cannot capture SIGINT(Ctrl+C)

### ISSUE THREAD

**Issue by colinaaa** [web-infra-dev/rsbuild#2112]
### Version

```sh
npmPackages:
    @rsbuild/core: ^0.6.0 => 0.6.0 
    @rsbuild/plugin-react: ^0.6.0 => 0.6.0
```

### Details

I would like to capture the SIGINT(Ctrl+C) in my app built with Rsbuild. After adding `process.on('SIGINT', callback)`, it seems like the process still exits when Ctrl+C is pressed.

I took a look at the Rsbuild's code, Rsbuild is also listening to the 'SIGINT' signal and calls `process.exit` inside the callback.

https://github.com/web-infra-dev/rsbuild/blob/defa5d44def49862a21c40d2a9f17cb02bd44948/packages/shared/src/utils.ts#L289-L291

I could remove the listener **after** the call to `createRsbuild()` and `startDevServer()` using `process.removeAllListeners('SIGINT')`. But this makes the code handling process exit split into two places:

1. `src/exit.js`
```js
import { asyncExitHook, gracefulExit } from 'exit-hook';
const unsubscribe = asyncExitHook(onExit, { wait: 1000 });
// Cannot do process.on('SIGINT') here.
process.on('unhandledRejection', async (reason) => {
    unsubscribe();
    await onExit(1);
    process.exit(1);
});
```
2. `src/rsbuild.js`
```js
const rsbuild = await createRsbuild({ cwd, rsbuildConfig })

const server = await rsbuild.createDevServer()

// Rsbuild has an exit listener on `SIGINT` and directly call process.exit(0)
// We remove it from here
process.removeAllListeners('SIGINT')

let interrupted = false
process.on('SIGINT', () => {
  if (interrupted) {
    return process.exit(/** 128 + 2(kill) */ 130)
  }

  interrupted = true
  logger.info(
    `Gracefully shutting down. Please wait... (Press ${
      color.cyan('Ctrl+C')
    } again to force exit)`,
  )

  exit(/** 128 + 2(kill) */ 130)
})
```

It would be nice if Rsbuild could remove this `SIGINT` exit listener. So that  I could capture `SIGINT` in my `exit.js`.

### Reproduce link

https://github.com/web-infra-dev/rsbuild/tree/main/examples/react

### Reproduce Steps

1. Use the simplest example
2. Add a `SIGINT` listener in `rsbuild.config.ts`

E.g.: 
```js
import { logger } from '@rsbuild/core'

let interrupted = false
process.on('SIGINT', () => {
  if (interrupted) {
    return process.exit(/** 128 + 2(kill) */ 130)
  }

  interrupted = true
  logger.info(
    `Gracefully shutting down. Please wait... (Press Ctrl+ C again to force exit)`,
  )
})
```
3. Run `rsbuild dev` and try exit using Ctrl+C

Expected: the log is printed and the process is not exited
Actual: the process exited

**Comment by chenjiahan** [comment]
The SIGINT listener was added for Modern.js and I can't remember what it was used for..

I have tried to remove it locally and it looks fine. So I'm going to remove it in the next release.
