### ISSUE TITLE
[Bug]: Dev mode emits different content to the same filename when name is static

### ISSUE THREAD

**Issue by Whiled0S** [web-infra-dev/rsbuild#2113]
### Version

```sh
System:
  OS: macOS 14.4.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 3.76 GB / 16.00 GB
  Shell: 5.9 - /bin/zsh
Browsers:
  Chrome: 123.0.6312.123
  Edge: 123.0.2420.97
  Safari: 17.4.1
npmPackages:
  @rsbuild/core: ^0.6.2 => 0.6.2
```

### Details

I tried to migrate one of my projects to rsbuild and noticed I cannot name my output javascript file with static name like `bundle.js` in development mode with `npm run dev` command which uses `rsbuild dev`. I also would like to focus attention on `npm run build` command which works as expected (successfully build project). If I name my output file using name like `[name].js` or `[name].[contenthash:8].js` it works correctly. I suppose it works this way because in dev mode there are additional files generated and this rule also affects it, but It is not clear for me from documentation and logs.

I created simple template project with very scarce configuration you can run locally and see an error in console.

### Reproduce link

https://github.com/Whiled0S/rsbuild-template

### Reproduce Steps

1. Clone attached repository
2. Change active directory to the project folder
3. Run `npm install`
4. Run `npm run dev`
5. See error: "Conflict: Multiple assets emit different content to the same filename static/js/bundle.js"

**Comment by xc2** [comment]
if you are just to name the entry chunk `bundle`, please naming the entry `bundle via https://rsbuild.dev/config/source/entry

if you are to bundle the entry into single file named `bundle`, please setup an `all-in-one` splitting: https://rsbuild.dev/config/performance/chunk-split

**Comment by Whiled0S** [comment]
@xc2 , thank you so much, specifying `chunkSplit.strategy` to `all-in-one` completely solves issue. Looks logical now, but I think would be good to mention chunk split strategy in "Entry Module" section of "Quick start" guide. Anyway now everything works perfect!
