### ISSUE TITLE
[Bug]: Rsbuild will not process assets path inline style

### ISSUE THREAD

**Issue by Alkaidcc** [web-infra-dev/rsbuild#2125]
### Version

```sh
System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M2
    Memory: 67.91 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 123.0.6312.124
    Safari: 17.4.1
  npmPackages:
    @rsbuild/core: ^0.6.3 => 0.6.3 
    @rsbuild/plugin-vue2: ^0.6.3 => 0.6.3
```

### Details

```vue
// App.vue
<template>
  <div class="content">
    <div style="background-image: url('@/assets/image/bg.png'); background-size: cover; height: 500px; width: 1000px;">inline style background</div>
    <div class="bg">class background</div>
  </div>
</template>

<style scoped>
.content {
  display: flex;
  min-height: 100vh;
  line-height: 1.1;
  text-align: center;
  flex-direction: column;
  justify-content: center;
}

.bg {
  background-image: url('@/assets/image/bg.png');
  background-size: cover;
  height: 500px;
  width: 1000px;
}
</style>

```

![CleanShot 2024-04-17 at 17 11 42@2x](https://github.com/web-infra-dev/rsbuild/assets/54631354/f299b5e5-4777-49dd-9830-fc22f8115d91)
Rsbuild has not processed the inline style background image, but the class way works fine.

### Reproduce link

https://github.com/Alkaidcc/rsbuild-issue

### Reproduce Steps

1. pnpm install
2. pnpm run dev

**Comment by Alkaidcc** [comment]
I only tested Vue2.

**Comment by Alkaidcc** [comment]
Is there anything can explain why `<img src="@/assets/iamge/bg.png" />` will be converted, but `<div style="background-image: url('@/assets/image/bg.png')" />` won't? Very appreciated!

**Comment by chenjiahan** [comment]
The src if `<img>`  is handled by `vue-loader`, not but Rsbuild.

See: https://vue-loader.vuejs.org/guide/asset-url.html#asset-url-handling

I believe vue-loader does not yet support handling URL in the background-image. You can create an issue in the vue-loader repo if needed.

**Comment by chenjiahan** [comment]
You can try this usage, import the asset as URL and set it to `style`:

```html
<template>
  <div class="content">
    <div :style="{ backgroundImage: `url('${bgUrl}')` }">
      inline style background
    </div>
  </div>
</template>

<script setup>
import bgUrl from '@/assets/image/bg.png';
</script>
```

**Comment by Alkaidcc** [comment]
BTW, I found `<div style="background: linear-gradient(90deg,rgba(26, 122, 176, 0.1) 0%,rgba(26, 122, 176, 0) 100%);">`has an issue too,  I guess inline style background has been dropped by vue-loader and I can't see any background style on dom. 😿 but the class way work.

**Comment by chenjiahan** [comment]
The object syntax of `style` should work 😄

```js
<div
  :style="{
    background: 'linear-gradient(90deg,rgba(26, 122, 176, 0.1) 0%,rgba(26, 122, 176, 0) 100%)',
  }"
></div>
```
