### ISSUE TITLE
[Bug]: css/less中使用绝对路径引用线上资源(非本地资源)报错 ,使用externals仍无法解决

### ISSUE THREAD

**Issue by tiannengyu** [web-infra-dev/rsbuild#2146]
用 externals 也可以避免 resolve 这个模块，比如：

```ts
export default defineConfig({
  output: {
    externals: [/\/image\/font/g],
  },
});
```

_Originally posted by @chenjiahan in https://github.com/web-infra-dev/rsbuild/issues/1948#issuecomment-2034056431_

**Comment by tiannengyu** [comment]
在less文件中随机引用不在本地，线上的字体文件即可复现
`@font-face {
  font-family: xxxx;
  src: url('/image/font/xxx.ttf');
}`

**Comment by tiannengyu** [comment]
[react.zip](https://github.com/web-infra-dev/rsbuild/files/15056282/react.zip)
css文件引用也是一样，这个是例子，

**Comment by tiannengyu** [comment]
@chenjiahan reproduction已提供

**Comment by chenjiahan** [comment]
确实使用 externals 依然无法解决这个问题，换成 IgnorePlugin 可以解决：

```js
export default defineConfig({
  tools: {
    rspack(config, { rspack, appendPlugins }) {
      appendPlugins([
        new rspack.IgnorePlugin({
          resourceRegExp: /image\/font/,
        }),
      ]);
    },
  },
});
```

已在上述 demo 中验证通过
