### ISSUE TITLE
[Bug]: react-refresh breaks dev build if html template uses "require"

### ISSUE THREAD

**Issue by atsikov** [web-infra-dev/rsbuild#2185]
### Version

```sh
System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 158.58 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Browsers:
    Brave Browser: 103.1.40.105
    Chrome: 124.0.6367.62
    Safari: 17.4.1
  npmPackages:
    @rsbuild/core: 0.6.6 => 0.6.6 
    @rsbuild/plugin-react: 0.6.6 => 0.6.6
```

### Details

Whenever html template contains `<%= require('./some-module').someMethod() %>` directive, `pluginReact` causes error in dev server

**Actual**
`rsbuild dev` fails with
```
ReferenceError: $ReactRefreshRuntime$ is not defined
```

**Expected**
`rsbuild dev` starts dev server

Workaround from https://github.com/web-infra-dev/rsbuild/issues/1812#issuecomment-1994620105 works, and build passes if I exclude required js module (see commented out `bundlerChain` in repro, `rsbuild.config.ts`

### Reproduce link

https://github.com/atsikov/rsbuild-react-refresh-issue

### Reproduce Steps

```
yarn
yarn dev
```

**Comment by chenjiahan** [comment]
A similar troubleshooting guide for this: https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/main/docs/TROUBLESHOOTING.md#usage-with-indirection-like-workers-and-js-templates

**Comment by chenjiahan** [comment]
Exclude the JS templates should work:

```js
pluginReact({
  reactRefreshOptions: {
    exclude: [/some-module-to-exclude/],
  },
});
```
