### ISSUE TITLE
[Bug]: 无法解析html 标签

### ISSUE THREAD

**Issue by canyuegongzi** [web-infra-dev/rsbuild#2263]
### Version

```sh
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 327.68 MB / 15.69 G


"rspress": "^1.0.0"
```

### Details

因为要使用图片点击方法的插件，指定了selector , 在名 md 中插入img 无法指定classname, 故曲线救国打算用 img 渲染，结果吗发现无法渲染。
```
<img src="images/overview.png" />
![](./images/overview.png){.lowcode-doc}
```

### Reproduce link

无

### Reproduce Steps

不需要步骤

**Comment by canyuegongzi** [comment]
发现换行符也无用  
![image](https://github.com/web-infra-dev/rsbuild/assets/32031360/b6ff34dd-f946-4139-b7c4-23dc7fa1ecd5)

**Comment by SoonIter** [comment]
这个是 rspress 的 issue 的话，应该在 rspress 仓库提问

我在本地测试了这几种语法都是可以的

````md
![](/rspress-icon.png)
<img src="/rspress-icon.png" />

| hello | 123132 |
| ----  | -------- |
| 123   | 123123 |
````

另外 `![](./images/overview.png){.lowcode-doc}` 这个貌似不是标准的 md 语法，比如 Github 的评论就没有解析这个

![](./images/overview.png){.lowcode-doc}

可以看一下 rspress 的官方文档，应该有很多 mdx 的文档可以参考

**Comment by canyuegongzi** [comment]
> 这个是 rspress 的 issue 的话，应该在 rspress 仓库提问
> 
> 我在本地测试了这几种语法都是可以的
> 
> ```
> ![](/rspress-icon.png)
> <img src="/rspress-icon.png" />
> 
> | hello | 123132 |
> | ----  | -------- |
> | 123   | 123123 |
> ```
> 
> 另外 `![](./images/overview.png){.lowcode-doc}` 这个貌似不是标准的 md 语法，比如 Github 的评论就没有解析这个
> 
> ![](./images/overview.png){.lowcode-doc}
> 
> 可以看一下 rspress 的官方文档，应该有很多 mdx 的文档可以参考

不好意思，提错仓库了，先关掉了
