### ISSUE TITLE
[Bug]: less 低版本编译问题

### ISSUE THREAD

**Issue by quxiangs** [web-infra-dev/rsbuild#2267]
### Version

```sh
System:
    OS: macOS 14.3
    CPU: (11) arm64 Apple M3 Pro
    Memory: 154.31 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 124.0.6367.119
    Edge: 124.0.2478.80
    Firefox: 105.0.3
    Safari: 17.3
  npmPackages:
    @rsbuild/core: ^0.6.8 => 0.6.8 
    @rsbuild/plugin-node-polyfill: ^0.6.8 => 0.6.8 
    @rsbuild/plugin-react: ^0.6.8 => 0.6.8
```

### Details

antd 版本 "antd": "2.13.11",
Failed to compile, check the errors for troubleshooting.
File: /Users/sanfan/Desktop/project/by-aicc/node_modules/antd/es/alert/style/index.less:1:1
  × Module build failed:
  ╰─▶   ×
        │
        │     font-size: @font-size-lg;
        │     top: 8px + @font-size-base * @line-height-base / 2 - @font-size-lg / 2;
        │   ^
        │ Operation on an invalid type
        │       Error in /Users/sanfan/Desktop/project/by-aicc/node_modules/antd/es/alert/style/index.less (line 22, column 4) 

### Reproduce link

"antd": "2.13.11", 构建

### Reproduce Steps

只用 "antd": "2.13.11", 构建

**Comment by chenjiahan** [comment]
![image](https://github.com/web-infra-dev/rsbuild/assets/7237365/fcfbdcd0-bc5d-422f-9300-9201d3112288)


参考：https://rsbuild.dev/zh/guide/faq/exceptions#less-%E6%96%87%E4%BB%B6%E4%B8%AD%E7%9A%84%E9%99%A4%E6%B3%95%E4%B8%8D%E7%94%9F%E6%95%88
