### ISSUE TITLE
[Bug]: writeToDisk don't copy files in public directory to disk

### ISSUE THREAD

**Issue by wood3n** [web-infra-dev/rsbuild#2278]
### Version

```sh
System:
    OS: Linux 6.1 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (2) x64 AMD EPYC
    Memory: 2.03 GB / 4.01 GB
    Container: Yes
    Shell: Unknown
  npmPackages:
    @rsbuild/core: ^0.6.4 => 0.6.4 
    @rsbuild/plugin-react: ^0.6.4 => 0.6.4
```

### Details

writeToDisk don't copy files in public directory to disk, is this expected?
<img width="1181" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/31716713/4d4a47ce-4532-4fa7-8d6c-de852afa292c">

### Reproduce link

[![Edit rspack-contrib/rsbuild-codesandbox-example/csb-mpydj2/draft/optimistic-chatelet](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/github/rspack-contrib/rsbuild-codesandbox-example/csb-mpydj2/draft/optimistic-chatelet?file=%2Frsbuild.config.mjs&embed=1)

### Reproduce Steps

open codesandbox link and run `pnpm run dev`

**Comment by chenjiahan** [comment]
Yes, this is expected, Rsbuild only copy files from the public dir to the dist dir on the production build.

**Comment by wood3n** [comment]
Could this support in the development environment? Or I can only use `output.copy` to do this?

**Comment by chenjiahan** [comment]
Yeah you can use `output.copy` to do this. 

@9aoy Should we copy the public dir during development build if `writeToDisk` is `true?

**Comment by 9aoy** [comment]
`output.copy` and `server.publicDir` can achieve similar functions, but they are implemented in different ways.

From the perspective of `publicDir` feature implementation, it is not necessary to write to the disk during development build . I'm a little curious, what circumstances do you need to rely on copying files to disk? @wood3n

**Comment by chenjiahan** [comment]
Okay, so it is expected that public dir is not copied during dev build, I will document this.

**Comment by VictorPulzz** [comment]
I wrote like this:

<img width="603" alt="Image" src="https://github.com/user-attachments/assets/c5516ce8-6f66-41e1-8c95-dc1485544304" />
<img width="347" alt="Image" src="https://github.com/user-attachments/assets/f4b7d83c-88d7-42f9-abf6-9364edc05d52" />
But it dont working...

**Comment by 9aoy** [comment]
@VictorPulzz can you provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to help us address the issue?

**Comment by chenjiahan** [comment]
Feel free to create a new issue for this
