### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of undefined (reading 'async')

### ISSUE THREAD

**Issue by gary-Shen** [web-infra-dev/rsbuild#2319]
### Version

```sh
System:
  OS: macOS 14.4.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 722.27 MB / 32.00 GB
  Shell: 5.9 - /bin/zsh
Browsers:
  Chrome: 124.0.6367.201
  Safari: 17.4.1
npmPackages:
  @rsbuild/core: ^0.6.13 => 0.6.13 
  @rsbuild/plugin-react: ^0.6.13 => 0.6.13
```

### Details

Turn on the `manifest` option when using module federation plugin (v2). see the logs bellow:
<img width="1388" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/10260860/de2506fa-5299-4110-8863-fa76f5c3f9ea">

It's seems caused by the dynamic entry import.

### Reproduce link

https://stackblitz.com/~/github.com/gary-Shen/rsbuild-manifest?file=rsbuild.config.ts

### Reproduce Steps

Well, it's very simple to reproduce.

1. Create a react project by `rsbuild`
```bash
npm create rsbuild@latest
```

2. Turn on manifest:
```ts
export default defineConfig({
  output: {
    manifest: true,
  },
  plugins: [pluginReact()],
})

```

3. Change the entry index file to dynamic import:

```typescript
// bootstrap.tsx
import React from 'react'
import ReactDOM from 'react-dom/client'

import App from './App'

const root = ReactDOM.createRoot(document.getElementById('root')!)

root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
```

```typescript
// index.tsx
import('./bootstrap')
```

**Comment by chenjiahan** [comment]
Thanks, we will fix this issue in the next release
