### ISSUE TITLE
[Bug][Doc]: Wrong link in documentation: Source Build Plugin -> Configuring Sub-projects

### ISSUE THREAD

**Issue by konrazem** [web-infra-dev/rsbuild#2394]
### Version

```sh
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 32.31 GB / 63.74 GB
  Browsers:
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.22621.3527
```

### Details

In _If the sub-project uses [exports](https://nodejs.org/api/packages#package-entry-points) field, you also need to add the source field in the exports field._ exports has wrong link. 

I think it should be:
https://nodejs.org/api/packages.html#package-entry-points

### Reproduce link

https://rsbuild.dev/plugins/list/plugin-source-build#configuring-sub-projects

### Reproduce Steps

Check documentation and a link provided.

I didn't find bug type dedicated to documentation. I am sorry for such small issue it is not a BUG at the end just a documentation improvement

**Comment by SoonIter** [comment]
> I think it should be:
[nodejs.org/api/packages.html#package-entry-points](https://nodejs.org/api/packages.html#package-entry-points)

Yeah, I think it has something to do with the adjustment of node's official website. We can fix these wrong links. 

> I didn't find bug type dedicated to documentation. I am sorry for such small issue it is not a BUG at the end just a documentation improvement

Thank you for the contribution. It's an important feedback. Every step matters for the improvement of rsbuild

**Comment by chenjiahan** [comment]
Fixed, thanks ❤️
