### ISSUE TITLE
[Feature]: Support multiple public folders 

### ISSUE THREAD

**Issue by Zavieer** [web-infra-dev/rsbuild#2410]
### What problem does this feature solve?

The documentation mentions that similar configurations to `devServer` in `rspack` can be achieved using `server` and `dev`.
![image](https://github.com/web-infra-dev/rsbuild/assets/32351904/a3871124-3655-41af-970f-d5d5e7af972b)

rsbuild
![image](https://github.com/web-infra-dev/rsbuild/assets/32351904/18bd9118-a733-4aa7-9663-e6ef303a437c)

rspack/webpack
![image](https://github.com/web-infra-dev/rsbuild/assets/32351904/94ec2535-4e3f-4eb6-b3b8-0c4351904c02)

But it seems that even the type definitions do not match, for example, the `directory` configuration item does not exist in `rsbuild`. Additionally, the `static` option in `rspack/webpack` supports array types, while `rsbuild` only supports objects. Am I using it incorrectly? This is crucial for my project migration.

### What does the proposed API look like?

I hope to either fully override or open up the configuration of `rspack`

**Comment by SoonIter** [comment]
`fully override or open up the configuration of rspack`

Are there any special requirements that prevent your configuration from being translated to rsbuild configuration?

**Comment by Zavieer** [comment]
> `fully override or open up the configuration of rspack`
> 
> Are there any special requirements that prevent your configuration from being translated to rsbuild configuration?

Sorry, I mean I hope the configuration of rsbuild can be similar to the static option in rspack/webpack in terms of functionality. Currently, I cannot configure the directory, nor can I configure multiple static file entries through arrays, which prevents me from continuing my migration work (webpack -> rsbuild).

**Comment by SoonIter** [comment]
> Currently, I cannot configure the directory, nor can I configure multiple static file entries through arrays

Okay, let's try to narrow down this problem. The problem is to support multiple publicDir at the same time right?

I'm curious about the situation where there are multiple publicDir. Usually, the project will only have one public folder just like  https://vitejs.dev/guide/assets.html#the-public-directory

**Comment by Zavieer** [comment]
> 您可以写下您的 webpack 配置，以便我们帮助您迁移到 Rsbuild 的配置。 :)
> 
> 和下面的一样吗？
> 
> ```js
> const path = require('path');
> 
> module.exports = {
>   //...
>   devServer: {
>     static: [
>       {
>         directory: path.join(__dirname, 'assets'),
>         publicPath: '/serve-public-path-url',
>       },
>       {
>         directory: path.join(__dirname, 'css'),
>         publicPath: '/other-serve-public-path-url',
>       },
>     ],
>   },
> };
> ```

You're right, but my current project does indeed have multiple `publicDir` situations like that. I need to ensure that after migrating to `rsbuild`, the original project directory structure remains unchanged. I'm a bit frustrated about it 😂

Also, it seems that `rsbuild`'s `publicDir` can't be configured with `publicPath`. My webpack configuration looks something like this:
devServer: {
    static: [
      {
        directory: path.join(__dirname, 'assets'),
        publicPath: '/serve-public-path-url',
      },
      {
        directory: path.join(__dirname, 'css'),
        publicPath: '/other-serve-public-path-url',
      },
    ],
  },

**Comment by SoonIter** [comment]
<img width="400" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/79413249/857068e8-7b77-4525-926e-7c23007968d4">

https://rsbuild.dev/zh/guide/basic/static-assets#public-%E7%9B%AE%E5%BD%95

https://rsbuild.dev/zh/config/output/copy#outputcopy

You can use [`output.copy`](https://rsbuild.dev/zh/config/output/copy#outputcopy) and [`dev.setupMiddlewares`](https://rsbuild.dev/zh/config/dev/setup-middlewares#devsetupmiddlewares) to simulate this behavior.

**Comment by Zavieer** [comment]
> <img alt="图像" width="400" src="https://private-user-images.githubusercontent.com/79413249/332736090-857068e8-7b77-4525-926e-7c23007968d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjk3MzEsIm5iZiI6MTcxNjM2OTQzMSwicGF0aCI6Ii83OTQxMzI0OS8zMzI3MzYwOTAtODU3MDY4ZTgtN2I3Ny00NTI1LTkyNmUtN2MyMzAwNzk2OGQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDA5MTcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4NmRmMDUzNDgxYjkzZWU3NjkwOTcyMWU3NGI2MDFkZjg1YWVmOGQ3NmQ5ZmYzZDNiNjdmYjAxYzRhYzY1YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9FN71J6BPRXrQIbFvVPZ3ZfZCtgLu7lilE_75ZONi9Y">
> https://rsbuild.dev/zh/guide/basic/static-assets#public-%E7%9B%AE%E5%BD%95
> 
> https://rsbuild.dev/zh/config/output/copy#outputcopy
> 
> 您可以使用[`output.copy`](https://rsbuild.dev/zh/config/output/copy#outputcopy)和[`dev.setupMiddlewares`](https://rsbuild.dev/zh/config/dev/setup-middlewares#devsetupmiddlewares)来模拟这种行为。

Thanks, I'll try it first. Thanks to the rsbuild team for the quick response. 👍
