### ISSUE TITLE
[Bug]: MF breaks the asset path when more than one sub path

### ISSUE THREAD

**Issue by XavierLeTohic** [web-infra-dev/rsbuild#2482]
### Version

```sh
System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M1
    Memory: 41.70 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 125.0.6422.141
    Safari: 17.4.1
  npmPackages:
    @rsbuild/core: ^0.7.1 => 0.7.1 
    @rsbuild/plugin-react: ^0.7.1 => 0.7.1
```

### Details

When setting `moduleFederation.options` and reloading with more than one sub path (.i.e `/sub/path`) Rsbuild inject assets without the prefix `/` even setting `output.assetPrefix: "/"` resulting in a white page.

Commenting or removing the whole `moduleFederation` from rsbuild config and everything works well.

See the attached Codesandbox and repository to reproduce.

### Reproduce link

https://codesandbox.io/p/github/XavierLeTohic/rsbuild-mf-asset-path/main

### Reproduce Steps

The repo of the codesandbox is here:

https://github.com/XavierLeTohic/rsbuild-mf-asset-path

To reproduce:
1. Clone
2. `npm install` or `yarn install`
3. `npm run dev` or `yarn dev`
4. On `http://localhost:5050/example` everything will work as expected if you reload
5. Go to `http://localhost:5050/example/sub/path` and reload it will be broken
6. Comment the whole module federation in `rsbuild.config.ts` and try to reload it'll work

**Comment by chenjiahan** [comment]
`output.assetPrefix` is for production build, can you try the `dev.assetPrefix` config?

Note that when you use `moduleFederation.options`, Rsbuild will set the default value of Rspack's [output.publicPath](https://rspack.dev/config/output#outputpublicpath) configuration to 'auto', this is recommended by MF team.

**Comment by XavierLeTohic** [comment]
`dev.assetPrefix` helped me discover that the reason why it's not working it's that it does not find assets using `rsbuild dev` and with module federation no matter the prefix I use, I updated the [Codesandbox ](https://codesandbox.io/p/github/XavierLeTohic/rsbuild-mf-asset-path/main)to reproduce, any idea?

Note that `output.publicPath` does not exists according to the types in 0.7.1 even tho it's mentioned in the documentation.
 
![Screenshot 2024-06-03 at 10 14 07](https://github.com/web-infra-dev/rsbuild/assets/6340490/edb9a655-23ec-4d2c-a7b3-87c60fdaf210)
![Screenshot 2024-06-03 at 10 26 34](https://github.com/web-infra-dev/rsbuild/assets/6340490/fdf544de-75e7-4c2f-8b9d-b6343c844b94)

**Comment by chenjiahan** [comment]
`output.publicPath` is a config of Rspack, you can use Rsbuild's `tools.rspack` to configure it.

**Comment by ScriptedAlchemy** [comment]
Is public path set to auto?

**Comment by XavierLeTohic** [comment]
Was fixed in dev by setting `config.output.publicPath = '/'` since `config.output.publicPath = 'auto'` still break the injection of assets when more than one sub path is used and the page is reloaded.

Updated the codesandbox to demo when it fails with `auto` -> https://codesandbox.io/p/github/XavierLeTohic/rsbuild-mf-asset-path/main

**Comment by imzisy** [comment]
I tried to change publicPath to / in the remote app it works for me but it is not working for the host.

**Comment by XavierLeTohic** [comment]
> I tried to change publicPath to / but it is not working for the host app.

Did you setup MF via `appendPlugins` like below?

```js
tools: {
		rspack: (config, { appendPlugins }) => {
			// Will work in dev only if set to "/"
			config.output.publicPath = "auto";

			appendPlugins([
				new ModuleFederationPlugin({ // ...my options })
			]);
		},
	},
```

**Comment by XavierLeTohic** [comment]
No certain but I think you can find the plugin of the 1.5 from `@rspack/core`'s `container`

**Comment by nate-summercook** [comment]
maybe related to #2747 ?

**Comment by imzisy** [comment]
To resolve this issue, upgrade to the latest version of Module Federation.

**Comment by XavierLeTohic** [comment]
@imzisy this issue also happen with the built-in module federation in rspack, not only using the external plugin `@module-federation/enhanced/rspack`

**Comment by XavierLeTohic** [comment]
After upgrading to `^1.0.0-alpha.6` it fixed the issue using `tools.rspack` but the issue remain with the built-in `moduleFederation.options`

**Comment by qmakani** [comment]
this doesn't seem like an issue anymore. should be safe to close it?

**Comment by petrosD93** [comment]
@XavierLeTohic whats the resolution for this? It's not clear on how we can resolve this issue as I'm currently facing the same. By upgrading to @rsbuild/core latest, can we still use the built-in `moduleFederation.options`?

**Comment by XavierLeTohic** [comment]
@petrosD93 we ended up setting MF options using:

```ts
import { defineConfig } from '@rsbuild/core';

export default defineConfig({
  tools: {
    rspack: (config, { appendPlugins, rspack }) => {
      appendPlugins(
        [
          new rspack.container.ModuleFederationPlugin({ 
            // mf config 
          }),
        ],
      );
    }
  }
});
```

I thought that issue would have been fixed using `moduleFederation.options` since then, never tried it again

**Comment by ScriptedAlchemy** [comment]
Use module-federation/enhanced/rspack 

Https://module-federation.io

**Comment by petrosD93** [comment]
@ScriptedAlchemy thanks for pointing this out, I was following the documentation of RsBuild. My issue seems to be more complex though. I am trying to transform our projects from Webpack to RsBuild. Thing is I am using the API of MF to load remotes (that was done in order to be able to change MF Config of remotes at runtime, and to also ensure proper error handling of host application when one of the remotes are failing). I understand that the logic we used back then was depending on fetching remote js modules, where now we do fetch the mf-manifest.json. I wonder if there is any documentation on how to use the API of module federation with RsBuild and the module federation plugin

**Comment by ScriptedAlchemy** [comment]
Federation runtime might be useful? 

https://module-federation.io/guide/basic/runtime.html

Primarily the main thing is you should be using the package from us and not the builtin container object in the bundler. Since those just expose the base classes from rust side of rspack.

**Comment by VictorPulzz** [comment]
@ScriptedAlchemy 
I faced the same problem, when I used in rsbuild config this setting, publicPath : 'auto'
```ts
  tools: {
      ...config.tools,
      rspack: {
        ...config.tools?.rspack,
        output: {
          publicPath: 'auto',
          // clean: true,
        },
      },
    },
```
, everything worked, but then I started to configure react tanstack router and realized that internal routes do not work because the js script is inserted 
```
<script defer src="static/js/vendor. js“></script><script defer src=”static/js/index.js"></script>, 
```
so all internal routes, say /dashboard/edit, don't work. When I removed this, the router started working, but in production build, the microfrontend stopped working:

![Image](https://github.com/user-attachments/assets/baa86eeb-6597-47c0-9b9c-86f28152e6e5)
Please help....

**Comment by VictorPulzz** [comment]
@XavierLeTohic Can you help please?

**Comment by XavierLeTohic** [comment]
Have you tried using module federation directly getting it from the container like in my last comment above?

I haven't tried @module-federation/rsbuild-plugin yet.

**Comment by VictorPulzz** [comment]
@XavierLeTohic Yes, this is my config:
```ts
import type { moduleFederationPlugin } from '@module-federation/sdk';
import { loadEnv, RsbuildConfig } from '@rsbuild/core';
import { pluginReact } from '@rsbuild/plugin-react';
import { pluginSass } from '@rsbuild/plugin-sass';
import path from 'path';

// eslint-disable-next-line import/no-relative-packages
import packagesVersion from '../../../package.json' assert { type: 'json' };

const { parsed } = loadEnv();

const defaultPublicEnvList: (keyof ImportMetaEnv)[] = ['API_GATEWAY'];
const typedParsed = parsed as Record<keyof ImportMetaEnv, string>;

export const rsbuildConfig = (
  config: RsbuildConfig = {},
  moduleFederation: moduleFederationPlugin.ModuleFederationPluginOptions = {},
  publicEnvList: (keyof ImportMetaEnv)[] = [],
): RsbuildConfig => {
  const plugins = [...(config.plugins ?? [])];

  plugins.push(
    pluginReact(),
    pluginSass(),
    // pluginModuleFederation({
    //
    // }),
  );

  const resultConfig: RsbuildConfig = {
    ...config,
    server: {
      ...config.server,
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, PATCH, OPTIONS',
        'Access-Control-Allow-Headers': 'X-Requested-With, content-type, Authorization',
      },
      publicDir: [
        {
          name: 'public',
          watch: true,
        },
        {
          name: path.resolve(__dirname, '../../../libs/ui/public'),
          watch: true,
        },
      ],
    },

    source: {
      ...config.source,
      define: Object.keys(typedParsed)
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        .filter(item => publicEnvList.includes(item as any))
        .concat(defaultPublicEnvList as never)
        .reduce(
          (prev, key) => {
            const sanitizedKey = key.replace(/[^a-zA-Z0-9_]/g, '_');

            prev[`import.meta.env.${sanitizedKey}`] = JSON.stringify(parsed[key]);

            return prev;
          },
          {} as Record<string, string>,
        ),
    },

    output: {
      ...config.output,
      cleanDistPath: true,
    },

    tools: {
      ...config.tools,
      rspack: (config, { appendPlugins, rspack }) => {
        appendPlugins([
          new rspack.container.ModuleFederationPlugin({
            ...moduleFederation,
            dts: true,
            manifest: true,
            shared: {
              react: {
                singleton: true,
                requiredVersion: packagesVersion.dependencies.react,
              },
              'react-dom': {
                singleton: true,
                requiredVersion: packagesVersion.dependencies['react-dom'],
              },
              jotai: {
                singleton: true,
                requiredVersion: packagesVersion.dependencies['jotai'],
              },
              'jotai-effect': {
                singleton: true,
                requiredVersion: packagesVersion.dependencies['jotai-effect'],
              },
              clsx: {
                singleton: true,
                requiredVersion: packagesVersion.dependencies['clsx'],
              },
              zod: {
                singleton: true,
                requiredVersion: packagesVersion.dependencies['zod'],
              },
            },
            runtimePlugins: [
              path.resolve(__dirname, './module-federation-plugins/shared-strategy.ts'),
              path.resolve(__dirname, './module-federation-plugins/offline-remote.ts'),
            ],
          }),
        ]);
      },
    },

    html: {
      ...config.html,
      template: './template.html',
    },

    performance: {
      ...config.performance,
      chunkSplit: {
        ...config.performance?.chunkSplit,
        strategy: 'single-vendor',
      },
    },
  };

  return {
    ...resultConfig,
    plugins,
  };
};
```

Host app rsbuild.config.ts
```ts
import { rsbuildConfig } from '@platform/rsbuild-config';
import { defineConfig } from '@rsbuild/core';

// eslint-disable-next-line import/no-relative-packages
import mfConfigs from '../../.deploy/mf.json' assert { type: 'json' };

const env = process.env.ENV;
const appConfig = mfConfigs.mfs.app;

if (!appConfig) {
  throw new Error('You dont setup this mf in mf.json!');
}

export default defineConfig(
  rsbuildConfig(
    {
      server: {
        port: appConfig.ports[env],
      },
    },
    {
      name: appConfig.name,
      remotes: appConfig.mfs.reduce((acc, curr) => {
        return {
          ...acc,
          [curr.alias]: `${curr.name}@${curr.entry[process.env.NODE_ENV][env]}`,
        };
      }, {}),
    },
  ),
);

```

Remote app rsbuild.config.ts
```ts
import { rsbuildConfig } from '@platform/rsbuild-config';
import { defineConfig } from '@rsbuild/core';

// eslint-disable-next-line import/no-relative-packages
import mfConfigs from '../../.deploy/mf.json' assert { type: 'json' };

const env = process.env.ENV;
const appConfig = mfConfigs.mfs.tasks;

if (!appConfig) {
  throw new Error('You dont setup this mf in mf.json!');
}

export default defineConfig(
  rsbuildConfig(
    {
      server: {
        port: appConfig.ports[env],
      },
    },
    {
      name: appConfig.name,
      filename: 'remoteEntry.js',
      exposes: {
        './Tasks': './src/components/Tasks.tsx',
      },
    },
  ),
);
```

**Comment by XavierLeTohic** [comment]
What happens if you set the publicPath to "/" instead of auto?

I would recommend that you make either a reproducible example in a repository or a code sandbox

**Comment by VictorPulzz** [comment]
I wrote it like this:
```ts
    tools: {
      ...config.tools,
      rspack: {
        ...config.tools?.rspack,
        output: {
          publicPath: '/',
          // clean: true,
        },
      },
    },
```
Nothing has changed, I'm very tired:(

**Comment by XavierLeTohic** [comment]
I will have a look tomorrow, also why are you spreading the default rsbuild config everywhere? It's not gonna erase the whole config at the end but apply some kind of patch

**Comment by VictorPulzz** [comment]
I have a very large project and I want to unify:)

**Comment by petrosD93** [comment]
@VictorPulzz have a look at this https://github.com/module-federation/core/issues/3343

**Comment by VictorPulzz** [comment]
@XavierLeTohic @petrosD93 
Thanks a lot guys for your help, I made it easier, I just passed publicPath: 'auto' only for remote project,
```ts
import { rsbuildConfig } from '@platform/rsbuild-config';
import { defineConfig } from '@rsbuild/core';

// eslint-disable-next-line import/no-relative-packages
import mfConfigs from '../../.deploy/mf.json' assert { type: 'json' };

const env = process.env.ENV;
const appConfig = mfConfigs.mfs.tasks;

if (!appConfig) {
  throw new Error('You dont setup this mf in mf.json!');
}

export default defineConfig(
  rsbuildConfig(
    {
      server: {
        port: appConfig.ports[env],
      },
      tools: {
        rspack: {
          output: {
            publicPath: 'auto',
          },
        },
      },
    },
    {
      name: appConfig.name,
      filename: 'remoteEntry.js',
      exposes: {
        './Tasks': './src/components/Tasks.tsx',
      },
    },
  ),
);
```
Everything seems to work, locally dev/prod, as well as on amazon, I want to put my setup rsbuild+eslint+prettier+tailwind+mf in a separate monorepo, maybe it will help someone, as I will write here:))
