### ISSUE TITLE
[Feature]: Allow to require image assets dynamically

### ISSUE THREAD

**Issue by robertyclin** [web-infra-dev/rsbuild#2509]
### What problem does this feature solve?

图片支持动态加载。例如，<img src={require(`xx/xx/${a}.png`)}>，目前是不支持的

报[object promise]

### What does the proposed API look like?

加载正常

**Comment by SoonIter** [comment]
和 webpack 的使用方式是一样的

https://webpack.js.org/api/module-methods/#dynamic-expressions-in-import

另外不推荐这么使用，动态表达式引入资源，bundler 拿不到所有的信息，很有可能会打包不必要的文件

这里有如何引入图片的教程

https://rsbuild.dev/guide/basic/static-assets#import-assets-in-js-file

如果你图片太多，一定要配合运行时的变量来做，可以配合 publicDir 来做

```tsx
// Comp.tsx
const Comp = (props: { imgName: string }) => {
	return <img src={`${process.env.ASSET_PREFIX}/images/${props.imgName}.png`} />
}
```

```sh
├── public
│   ├── index.html
│   └── images
│          ├── a.png
│          └── b.png
├── rsbuild.config.ts
```

**Comment by robertyclin** [comment]
非常感谢，我用了最新rsbuild搭建的react项目确实是可以的。我的旧项目的react版本是16.8的，是因为版本低的原因吗

**Comment by chenjiahan** [comment]
React version should not affect the image require, anyway it is recommended to use React 18 now.
