### ISSUE TITLE
[Feature]: Allow output.filename to be a function

### ISSUE THREAD

**Issue by dartess** [web-infra-dev/rsbuild#2526]
### What problem does this feature solve?

I want to have dynamic output path for different entry points.
In webpack I used it this way:

```js
  output: {
    filename: ({ runtime }) => {
      switch (runtime) {
        case ENTRY_SW:
          return `${ENTRY_SW}.js`;
        case ENTRY_CHARTING_LIBRARY_CUSTOM_CSS:
          return `assets/lib/empty.js`;
        default:
          return `[name].[${hashType}].js`;
      }
    },
  },
```

I see that `rspack` can now accept a function for output: https://github.com/web-infra-dev/rspack/issues/3483 .
If I understand correctly how does it work, it seems that now this can be implemented in `rsbuild`?

### What does the proposed API look like?

```ts
type FilenameConfigValue = string | (pathData: JsPathData, assetInfo?: JsAssetInfo) => string;
type FilenameConfig = {
  js?: FilenameConfigValue;
  css?: FilenameConfigValue;
  svg?: FilenameConfigValue;
  font?: FilenameConfigValue;
  image?: FilenameConfigValue;
  media?: FilenameConfigValue;
};
```

```js
  output: {
    filename: {
      js: ({ runtime }) => {
        switch (runtime) {
          case ENTRY_SW:
            return `${ENTRY_SW}.js`;
          case ENTRY_CHARTING_LIBRARY_CUSTOM_CSS:
            return `assets/lib/empty.js`;
          default:
            return `[name].[${hashType}].js`;
        }
      },
    },
  },
```

**Comment by chenjiahan** [comment]
This looks feasible and we will support it

**Comment by SoonIter** [comment]
how about making the interface of this function be consistent with the utils in `tools.rspack` and reduce some costs.

https://rsbuild.dev/config/tools/rspack#utils


```ts
  output: {
    filename: {
      js: ({ env, target }) => {
			// ...
      },
    },
  },
```

**Comment by chenjiahan** [comment]
@SoonIter Usually we do not need so many context info to sett the filename, and Rsbuild plans to provide a different approach to override configs by targets.

**Comment by chenjiahan** [comment]
In Rsbuild [v0.7.4](https://github.com/web-infra-dev/rsbuild/releases/tag/v0.7.4), `output.filename.js` can be a function now.

For other options, such as `css`, `image`, this relies on Rspack for support:

![image](https://github.com/web-infra-dev/rsbuild/assets/7237365/74d6bbe2-369b-4018-858c-ed39ea44e6b0)

![image](https://github.com/web-infra-dev/rsbuild/assets/7237365/6c46ed56-af4d-425e-b6cd-1cb780e49b5d)
