### ISSUE TITLE
[Bug]: 0.7.3 Live reload crashes with module federation

### ISSUE THREAD

**Issue by swalker326** [web-infra-dev/rsbuild#2535]
### Version

```sh
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M2 Pro
    Memory: 131.89 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 125.0.6422.142
    Edge: 125.0.2535.85
    Safari: 17.5
```

### Details

App crashes on save when module federation is configured on fresh projects 

![image](https://github.com/web-infra-dev/rsbuild/assets/8460808/2f4e5922-7555-43b0-aefe-8a961eefda12)

### Reproduce link

https://github.com/swalker326/rsbuild-module-federation-live-reload-bug

### Reproduce Steps

from root `pnpm i`
from root `pnpm dev`

once the apps are running, confirm the host app is running with the remote app mounted on localhost:3000

![image](https://github.com/web-infra-dev/rsbuild/assets/8460808/3877bb18-10a8-4cbe-8b53-b1ef11528105)

From your editor save a file inside of the remote app (not rsbuild.config.ts) this will trigger the error above.

**Comment by chenjiahan** [comment]
Hi, this is a known issue of Rspack v0.7.1, please refer to: https://github.com/web-infra-dev/rspack/issues/6740
