### ISSUE TITLE
[Bug]: Compile Warning: 

### ISSUE THREAD

**Issue by whisper540** [web-infra-dev/rsbuild#2537]
### Version

```sh
macos
```

### Details

when i use like this:
lazy(()=>import(route.component)

ready   Client compiled in 0.22 s
warn    Compile Warning: 
File: /Users/dkal/workshop/rspack/ino-quick-pro-over-inocube/src/router/routerPaser.tsx:1:1
  ⚠ Module parse warning:
  ╰─▶   ⚠ Critical dependency: the request of a dependency is an expression
          ╭─[52:1]
       52 │     finalRoutes.map((route)=>{
       53 │         if (Array.isArray(route.children)) menuToRouter(route.children);
       54 │         else route.element = lazyLoad(/*#__PURE__*/ lazy(()=>import(route.component)));
          ·                                                                     ────────────────
       55 │     });
       56 │     return routes;

### Reproduce link

compile no support import(var)

### Reproduce Steps

pnpm run dev

**Comment by chenjiahan** [comment]
Rspack does not support to use a fully dynamic import statement, such as import(foo).

See: https://www.rspack.dev/api/modules/module-methods#dynamic-expressions-in-import

**Comment by boborua** [comment]
> Rspack does not support to use a fully dynamic import statement, such as import(foo).
> 
> See: https://www.rspack.dev/api/modules/module-methods#dynamic-expressions-in-import

@chenjiahan  链接失效了。。。

不支持动态导入参数为表达式，这个考虑是为了tree-shaking吗？项目中如果想实现文件路由，还是非常需要这个特性的，有没有替代方案呢。。

**Comment by chenjiahan** [comment]
See: https://rspack.dev/api/runtime-api/module-methods#dynamic-import
