### ISSUE TITLE
[Bug]: unplugin-vue-components causes styles to be lost

### ISSUE THREAD

**Issue by tsker** [web-infra-dev/rsbuild#2542]
### Version

```sh
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
    Memory: 3.45 GB / 15.91 GB
  Browsers:
    Edge: Chromium (122.0.2365.66)
    Internet Explorer: 11.0.19041.4355
```

### Details

配置unplugin-vue-component会导致样式丢失

### Reproduce link

.

### Reproduce Steps

使用`npm create rsbuild@latest`创建vue模板，此时启动正常

然后按照 https://rsbuild.dev/zh/config/plugins#unplugin 步骤，添加 unplugin-vue-components插件

此时，不管是dev还是build，src/index.css的样式都丢失，导致渲染错误的页面

添加配置 “output.injectStyles = true”， 可以解决样式问题，但是将不会再有css文件导出

**Comment by tsker** [comment]
`"devDependencies": {
    "@rsbuild/core": "^0.7.3",
    "@rsbuild/plugin-vue": "^0.7.3",
    "typescript": "^5.4.2",
    "unplugin-vue-components": "^0.27.0"
  }`

**Comment by GRAMMAC1** [comment]
This is not a bug of `rsbuild` or `rspack`.

 In the documentation of `unplugin-vue-components`, it is stated that the plugin of `rspack` is still in the experimental stage.

It seems that the loader in the code implementation of `unplugin-vue-components` is set to execute in the post stage, which may cause issues in `rspack`. **This could potentially be a bug in `rspack`.** It might be necessary to create an issue in the `unplugin-vue-components` repository to track and address this issue.

**Comment by GRAMMAC1** [comment]
```ts
import { defineConfig } from "@rsbuild/core";
import { pluginVue } from "@rsbuild/plugin-vue";
import Components from "unplugin-vue-components/rspack";
import { VantResolver } from "unplugin-vue-components/resolvers";

export default defineConfig({
  plugins: [pluginVue()],
  tools: {
    rspack: {
      plugins: [
        Components({
          // add any resolver
          resolvers: [VantResolver()],
        }),
      ],
    },
  },
});```

add any resolver can fix this issue

**Comment by tsker** [comment]
应该不全是 `unplugin-vue-components` 的问题，在`@rsbuild/core: 0.6.15`  `@rspack/core: 0.6.5` 的时候，该功能还是正常的，在升级到 `@rsbuild/core 0.7.x` 以后才会出现这样的问题。

而且我在尝试添加 resolvers后，貌似问题依旧

**Comment by GRAMMAC1** [comment]
> 应该不全是 `unplugin-vue-components` 的问题，在`@rsbuild/core: 0.6.15` ~`@rspack/core: 0.6.5`~ 的时候，该功能还是正常的，在升级到 `@rsbuild/core 0.7.x` 以后才会出现这样的问题。
> 
> 而且在 `@rsbuild/core 0.7.4`， 尝试添加 resolvers后，貌似问题依旧

Could you provide a reproduce demo for more details? In `Rsbuild Vue3 demo` add `VantResolver` works fine.

**Comment by PPPPigggg** [comment]
https://github.com/unplugin/unplugin-auto-import/issues/502#issue-2320854022

**Comment by PPPPigggg** [comment]
auto-import also has the same issue

**Comment by tsker** [comment]
不太确定还需要提供哪些信息，下面是我完整的动作
```
npm create rsbuild@latest
cd xxx
npm install -D  unplugin-vue-components
vim rsbuild.config.mjs  // 这里添加 Components 与 resolvers: [VantResolver()]
npm run dev
```
此时打开页面，显示的是

![Alt](https://s21.ax1x.com/2024/06/13/pkaw4mT.jpg)

查看控制台，也只有一个`src/index.css`样式被加载了，`App.vue`中的`style`标签丢失

<br />
<br />
<br />
但是按正常来说，应该显示的是 （比如不添加`unplugin-vue-components` ， 或者  `@rsbuild/core  0.7.4`）

![Alt](https://s21.ax1x.com/2024/06/13/pkawfXV.jpg)

**Comment by PPPPigggg** [comment]
2

**Comment by PPPPigggg** [comment]
Using unplugin-auto-import also results in the same issue

**Comment by PPPPigggg** [comment]
> Using unplugin-auto-import also results in the same issue

https://github.com/unplugin/unplugin-auto-import/issues/502#issue-2320854022

**Comment by tsker** [comment]
升级到 `rsbuild  0.7.7` 问题解决
