### ISSUE TITLE
[Bug]: When modifying files (occasionally) or rsbuild.config.ts (must be), the generated product has problems 

### ISSUE THREAD

**Issue by jameszhang2020** [web-infra-dev/rsbuild#2571]
### Version

```sh
System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M3
    Memory: 111.56 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.12.2/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
    pnpm: 9.1.4 - ~/.nvm/versions/node/v20.12.2/bin/pnpm
  Browsers:
    Chrome: 125.0.6422.142
    Safari: 17.4.1
```

### Details

I have shared multiple packages in the module federation host, and the configuration is as follows.
```ts
// rsbuild.config.ts
...
import { ModuleFederationPlugin } from '@module-federation/enhanced/rspack'
import pkgInfo from './package.json'
...

export default defineConfig(({env, command, envMode}) => {
  return {
    ...
    tools: {
      rspack: {
        plugins: [
          new ModuleFederationPlugin({
            name: 'runtime',
            shared: {
              react: { singleton: true, requiredVersion: pkgInfo.dependencies.react },
              'react-dom': {
                singleton: true,
                requiredVersion: pkgInfo.dependencies['react-dom']
              },
              '@cb/sdk': { singleton: true },
              '@cb/react-portal-provider': { singleton: true },
              '@cb/react-theme-provider': { singleton: true },
              '@cb/react-viewport-provider': { singleton: true },
              '@cb/react-box': { singleton: true },
              '@cb/react-flex': { singleton: true },
              '@cb/react-panel': { singleton: true },
              '@cb-app/workspace-context': { singleton: true },
              '@cb-app/common': { singleton: true },
              '@cb-app/core-api': { singleton: true },
              '@cb-app/points': { singleton: true },
              '@cb-app/messenger': { singleton: true },
              '@cb-app/components': { singleton: true },
              '@cb-app/shared-points': { singleton: true },
              '@cb/logger': { singleton: true },
              '@cb/editor': { singleton: true },
              lodash: { singleton: true },
              'styled-components': { singleton: true }
            }
          })
        ]
      }
    }
  }
})
```

On first startup, it will generate a set of configurations that can be found in the entry file (index.js), like this:
```ts
__webpack_require__.initializeSharingData = {
  scopeToSharingDataMapping: {
    "default": [
        {
            "name": "@cb/sdk",
            "version": "1.32.0",
            "factory": function(){
                     return __webpack_require__.e("verdors-node_module_cb_sdk_dist_sdk_index_js").then(function(){
                           return function(){ return __webpack_require__("../../node_modules/@cb/sdk/dist/index.js" }
                      })
             }
        },
       ...more
    ]
  }
}
```
However, when I edited a ts file or rsbuild.config.ts file, saved it, and then checked it again, I found that it became empty, as shown below:
```js
__webpack_require__.initializeSharingData = {
  scopeToSharingDataMapping: {
    "default": []
  }
}
```
Other remotes will depend on these shared packages, so this initializeSharingData.scopeToSharingDataMapping is very important

> I also created an [issue](https://github.com/module-federation/core/issues/2596) in module federation, but they asked me to create an issue here directly.

### Reproduce link

N/A

### Reproduce Steps

1. Based on an old webpack5 project (project using module federation) migrate to Rsbuild
2. Introduce the module federation plug-in and configure a host and remotes
3. Share multiple packages in the host (refer to the configuration example above, because it is an internal project, it is not convenient to show specific information)
4. yarn dev
5. Edit js/ts/tsx/jsx files or modify rsbuild.config.ts files, save and access the local, and find that the content of `__webpack_require__.initializeSharingData` in the index.js file generated after packaging is different before and after (as described above). If this variable has a normal value, our project can work normally, otherwise it will not work.
6. When a problem occurs, manually stop the process and re-execute yarn dev (rsbuild dev), the index.js file will be normal, but doing so will greatly affect the local development efficiency

**Comment by chenjiahan** [comment]
Hi, can you provide a minimal reproduction for this?

**Comment by TD-jameszhang** [comment]
Ok, I'll submit a repo later.

**Comment by jameszhang2020** [comment]
@chenjiahan https://github.com/TD-jameszhang/rsbuild-demo.git
In this repo, after I upgraded to the latest version of rsbuild/core, it reported this error first (which prevented me from reproducing the original problem)
Reproduce Steps:
1. yarn 
2. yarn workspace @demo/host run dev
3. yarn workspace @demo/remote run dev
4. Modify the App.tsx file in @demo/host, for example, add a console.log, it will correct the following error
<img width="989" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/50222173/3acbb849-23e8-46bd-b1c4-8b6c08d2bd33">

Maybe I need to fix this problem first before I can reproduce the abnormal phenomenon reported first.

**Comment by jameszhang2020** [comment]
By the way, Is this correct? It looks weird.  Because the current @rspack/core of this project is already version 0.7.1
<img width="1007" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/50222173/9dc81d6a-c846-41c8-8bb9-8cb1fd935e61">

**Comment by chenjiahan** [comment]
> In this repo, after I upgraded to the latest version of rsbuild/core, it reported this error first

**Comment by chenjiahan** [comment]
> By the way, Is this correct? It looks weird. Because the current @rspack/core of this project is already version 0.7.1

This is a devDependency, it will not affect your project, so you can just ignore it

**Comment by chenjiahan** [comment]
Can you try the latest Rsbuild version and check if the problem has been resolved?

**Comment by jameszhang2020** [comment]
OK, got it. 
I'll verify it later and contact you if I have any news.

**Comment by jameszhang2020** [comment]
The HMR problem should be fixed. However, the problem I mentioned at the beginning still exists. Here are the results after I ran it:
![image](https://github.com/web-infra-dev/rsbuild/assets/50222173/e3ee9492-ed5a-4b4c-93cd-73aa5f83cfd1)
But I expect it to work properly, as shown below:
<img width="868" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/50222173/8f9af32c-4f85-4ca7-80b5-e75b81b05385">

I have uploaded the code to the repo, could you please take a look at it?

**Comment by ScriptedAlchemy** [comment]
@chenjiahan bumping this. 
Could it be related to lazy compile? Not sure why the scope would reset like this

**Comment by chenjiahan** [comment]
I tried to modify .ts files or the rsbuild config file, but I can not reproduce the error:

![image](https://github.com/web-infra-dev/rsbuild/assets/7237365/3648975c-64dd-49bb-bdb3-d06585c8996c)


And the project does not have lazyCompilation enabled, so it should not be related to lazy

**Comment by ScriptedAlchemy** [comment]
I'll try playing with it too and see if I can reproduce anything

**Comment by TD-jameszhang** [comment]
any update regarding this issue? :kp-hello:

**Comment by ScriptedAlchemy** [comment]
Have you tried the latest version of rsbuild

**Comment by TD-jameszhang** [comment]
Thanks, I'll try to use the latest version and verify it again.

**Comment by chenjiahan** [comment]
Thank you for the update! I'm glad to hear that the problem has been resolved and I will close this issue.

**Comment by ScriptedAlchemy** [comment]
yeah i ran into this with pre v1 as well, sometimes it would reset some graph state but i saw a PR that solved a similar issue with HMR and assumed it would also fix this
