### ISSUE TITLE
[Bug]: pnpm install vue2 project error

### ISSUE THREAD

**Issue by djkloop** [web-infra-dev/rsbuild#2572]
### Version

```sh
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12400
    Memory: 16.28 GB / 31.78 GB
  Browsers:
    Edge: Chromium (125.0.2535.92)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    @rsbuild/core: ^0.7.5 => 0.7.5
    @rsbuild/plugin-babel: ^0.7.5 => 0.7.5
    @rsbuild/plugin-sass: ^0.7.5 => 0.7.5
    @rsbuild/plugin-vue2: ^0.7.5 => 0.7.5
```

### Details

When PNPM installation is dependent, it seems that there will be a lack of bags

#### codesanbox error
![image](https://github.com/web-infra-dev/rsbuild/assets/21050914/d59cae9a-b8fd-417c-af65-ce595a706ad8)

#### win10 error
![image](https://github.com/web-infra-dev/rsbuild/assets/21050914/98588aad-b7fc-4344-9326-95d98674fac7)

### Reproduce link

https://codesandbox.io/p/github/djkloop/rs-issue-vue2-demo/main?import=true

### Reproduce Steps

1. pnpm i
2. pnpm dev
3. error

**Comment by chenjiahan** [comment]
I deleted the node_modules and pnpm-lock file, reinstalled the dependencies, then it worked fine:

![image](https://github.com/web-infra-dev/rsbuild/assets/7237365/522d404f-0630-458b-91e3-ad59987fea52)

**Comment by djkloop** [comment]
@chenjiahan 找到问题了，貌似和淘宝源有点关系，用了官方源就能装上那个 `@rspack/binding-win32-x64-msvc`

**Comment by chenjiahan** [comment]
嗯，可能是淘宝源同步最新版本有延迟导致的
