### ISSUE TITLE
[Bug]: rspack sass-loader preload error

### ISSUE THREAD

**Issue by djkloop** [web-infra-dev/rsbuild#2577]
### Version

```sh
System:
    OS: Linux 6.1 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (2) x64 AMD EPYC
    Memory: 2.82 GB / 4.01 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  npmPackages:
    @rsbuild/core: ^0.7.5 => 0.7.6 
    @rsbuild/plugin-sass: ^0.7.6 => 0.7.6 
    @rsbuild/plugin-vue2: ^0.7.5 => 0.7.6
```

### Details

The pre -load of the sassfile has been loaded, but I have not introduced the sass file in other files, If I commemorate the comments introduced by the SCSS file introduced in the js file, it can run ...

#### error
![image](https://github.com/web-infra-dev/rsbuild/assets/21050914/8dc6d8dd-e19b-4d8b-bcaa-0d47424f29af)

![image](https://github.com/web-infra-dev/rsbuild/assets/21050914/b52165ce-8a6e-415a-8f89-0ba5317b8fdf)

#### no error
![image](https://github.com/web-infra-dev/rsbuild/assets/21050914/399ee89d-c612-4f01-a145-11531bb8c4ef)

### Reproduce link

https://codesandbox.io/p/github/djkloop/rs-issue-vue2-demo/main

### Reproduce Steps

1. pnpm i  -f
2. pnpm dev
3. error

**Comment by djkloop** [comment]
![image](https://github.com/web-infra-dev/rsbuild/assets/21050914/51f3b48d-4d80-448c-9485-2153d81a9955)
 
 感觉像是scss文件在.js文件导入有问题。

**Comment by chenjiahan** [comment]
I found that the `modern` Sass API no longer support this, but you can switch to the `legacy` Sass API to make it work:

```ts
pluginSass({
  sassLoaderOptions: {
    api: "legacy",
    additionalData: `@import '~@/style/preload.scss';`,
  },
})
```

![image](https://github.com/web-infra-dev/rsbuild/assets/7237365/92ced869-e085-4410-99d5-9022ca8f5a72)

> Reference: https://github.com/webpack-contrib/sass-loader?tab=readme-ov-file#api
