### ISSUE TITLE
[Bug]: publicDir cannot serve files end with `.gz`

### ISSUE THREAD

**Issue by SunriseFox** [web-infra-dev/rsbuild#2630]
### Version

```sh
System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i9-14900K
    Memory: 18.08 GB / 23.95 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  npmPackages:
    @rsbuild/core: ^0.7.8 => 0.7.8 
    @rsbuild/plugin-react: ^0.7.8 => 0.7.8
```

### Details

If any file in public folder ends with .gz, the served file is not the same as the original file.

It might be related to these issues:
[https://github.com/lukeed/sirv/issues/158](https://github.com/lukeed/sirv/issues/158)
[https://github.com/vitejs/vite/issues/12266](https://github.com/vitejs/vite/issues/12266)

### Reproduce link

newly created repo

### Reproduce Steps

```bash
pnpm create rsbuild@latest
cd my-project
pnpm i
pnpm run dev
```

place [some gz file like this](https://cdn.jsdelivr.net/npm/excelize-wasm@0.0.6/excelize.wasm.gz) into `/public`

access `localhost:3000/excelize.wasm.gz` and it's not the same file

``` bash
$ sha1sum public/*
88c26b8f731b1e1aea24deb3655d3ab6f15ab84d  public/downloaded.gz
99c6ce68e9ca57920cb1a629f53ae88cef509e49  public/original.gz
```

**Comment by chenjiahan** [comment]
Maybe you can use [output.copy](https://rsbuild.dev/config/output/copy) as a workaround

**Comment by chenjiahan** [comment]
This is an upstream issue, so I will close this issue and wait for `sirv` to fix it.
