### ISSUE TITLE
[Bug]: Sass imports the CSS file to report an error

### ISSUE THREAD

**Issue by djkloop** [web-infra-dev/rsbuild#2689]
### Version

```sh
System:
    OS: Linux 6.1 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (2) x64 AMD EPYC
    Memory: 2.56 GB / 4.01 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  npmPackages:
    @rsbuild/core: ^0.7.9 => 0.7.9 
    @rsbuild/plugin-sass: ^0.7.9 => 0.7.9 
    @rsbuild/plugin-vue2: ^0.7.9 => 0.7.9
```

### Details

Sass imports the CSS file to report an error. It can be used normally when using the aliases, but the console will report to warning. The SASS plug -in should support the introduction of CSS files

### Reproduce link

https://codesandbox.io/p/github/djkloop/rs-issue-vue2-demo/main

### Reproduce Steps

```sh
1. pnpm i -f
2. pnpm dev
3. terminal -> error/warning
```
#### test file path
![image](https://github.com/web-infra-dev/rsbuild/assets/21050914/803c3c1f-fa9f-4122-a705-58e6c68c5135)

#### run warning
![image](https://github.com/web-infra-dev/rsbuild/assets/21050914/9f0b7b58-0ccc-400c-87af-d1a5f8fb4043)

#### run error
![image](https://github.com/web-infra-dev/rsbuild/assets/21050914/6d9290b7-1a01-47dd-8580-95cc17d444e1)

**Comment by djkloop** [comment]
https://github.com/sass/sass/issues/3043 

sass里面应该是支持css文件导入的...看了sass的issue

**Comment by chenjiahan** [comment]
Yes, it is allowed to import `.css` file in a `.scss` file, but it seems not allowed to use this in `additionalData`.

The codesandbox link does not match the problem you describe. Could you check the link?

**Comment by djkloop** [comment]
> Yes, it is allowed to import `.css` file in a `.scss` file, but it seems not allowed to use this in `additionalData`.
> 
> The codesandbox link does not match the problem you describe. Could you check the link?

[codesanbox demo](https://codesandbox.io/p/github/djkloop/rs-issue-vue2-demo/main?embed=1&file=%2Fsrc%2Fstyle%2Fvar.css&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxb7nxbd00063j6mj3hk2ylj%2522%252C%2522sizes%2522%253A%255B57.48527825663487%252C42.51472174336513%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxb7nxbc00023j6m8zm39ur5%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxb7nxbd00043j6mrzwxxfu4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxb7nxbd00053j6mrt73vg3d%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B76.45462349116593%252C23.545376508834067%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxb7nxbc00023j6m8zm39ur5%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxb7nxbc00013j6mp918njc5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clxtsjsf400023j6qi52ekinw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fstyle%252Fpublic.scss%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxb7nxbc00023j6m8zm39ur5%2522%252C%2522activeTabId%2522%253A%2522clxtsjsf400023j6qi52ekinw%2522%257D%252C%2522clxb7nxbd00053j6mrt73vg3d%2522%253A%257B%2522id%2522%253A%2522clxb7nxbd00053j6mrt73vg3d%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clxb7nxbd00043j6mrzwxxfu4%2522%253A%257B%2522id%2522%253A%2522clxb7nxbd00043j6mrzwxxfu4%2522%252C%2522activeTabId%2522%253A%2522clxtrp5cn00ud3j6pqefaoydm%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clxtrp5cn00ud3j6pqefaoydm%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522id%2522%253A%2522clxts5s21015z3j6p1u0lauqd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clxts5sam001gdkfgarrvgzqj%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A10%257D)

**Comment by chenjiahan** [comment]
Where is `public.scss`? Do you forget to push the code or switch the branch?

![image](https://github.com/web-infra-dev/rsbuild/assets/7237365/7e90a443-04e0-4373-b7c0-1216b67e6e13)

**Comment by djkloop** [comment]
@chenjiahan 可能是那个代码只在codesandbox更新了但是没有push到源仓库，我现在重新从codesanbox上推上去代码了，
[demo](https://codesandbox.io/p/github/djkloop/rs-issue-vue2-demo/main?embed=1&file=%2Fsrc%2Fstyle%2Fvar.css)

**Comment by xc2** [comment]
@djkloop 

按照 sass 的规范，在 `@import` css 的时候，必须不能加 `.css` 后缀。

所以你应该写 `@import "./var3";` (同时存在 `var.scss` 和 `var.css` 的时候会加载 `var.scss`，所以我这里把 `var.css` 文件改名为 `var.css` 了）。

另外字体文件的报错是因为 `iconfont.woff` 这个文件确实不存在。

**Comment by djkloop** [comment]
@xc2 好的，谢谢
