### ISSUE TITLE
[Bug]: failed to compile dist jsx code

### ISSUE THREAD

**Issue by wxiaoyun** [web-infra-dev/rsbuild#2727]
### Version

```sh
System:
    OS: Linux 6.9 Arch Linux
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 24.42 GB / 31.25 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  npmPackages:
    @rsbuild/core: ^0.7.10 => 0.7.10
    @rsbuild/plugin-babel: ^0.7.10 => 0.7.10
    @rsbuild/plugin-solid: ^0.7.10 => 0.7.10
```

### Description
- Rsbuild faces compilation error when importing icons from [solid icons](https://solid-icons.vercel.app/)
- Not sure if its a rsbuild problem or [solid icons](https://solid-icons.vercel.app/) package problem. The problem goes away if I change the dist code to import from `index.js` instead of `index.jsx`

```
  Rsbuild v0.7.10

  > Local:    http://localhost:3000/
  > Network:  http://192.168.10.145:3000/

start   Compiling...
error   Compile error:
Failed to compile, check the errors for troubleshooting.
File: /home/wuxiaoyun/dev/solidjs-rsbuild/node_modules/.pnpm/solid-icons@1.1.0_solid-js@1.8.17/node_modules/solid-icons/lib/index.jsx:1:1
  × Module build failed:
  ├─▶   ×
  │     │   × Expected '>', got 'stroke'
  │     │     ╭─[/home/wuxiaoyun/dev/solidjs-rsbuild/node_modules/.pnpm/solid-icons@1.1.0_solid-js@1.8.17/node_modules/solid-icons/lib/index.jsx:10:1]
  │     │  10 │     onCleanup(() => {
  │     │  11 │         setContent("");
  │     │  12 │     });
  │     │  13 │     return (<svg stroke={iconSrc.a?.stroke} color={props.color || "currentColor"} fill={props.color || "currentColor"} stroke-width="0" style={{
  │     │     ·                  ──────
  │     │  14 │             ...props.style,
  │     │  15 │             overflow: "visible",
  │     │  16 │         }} {...svgProps} height={props.size || "1em"} width={props.size || "1em"} xmlns="http://www.w3.org/2000/svg" innerHTML={content()}>
  │     │     ╰────
  │     │
  │
  ╰─▶ Syntax Error
```

### Reproduce link

https://github.com/wxiaoyun/rsbuild-solidjs-icon-bug-reproduction.git

### Reproduce Steps

```bash
git clone https://github.com/wxiaoyun/rsbuild-solidjs-icon-bug-reproduction.git
cd rsbuild-solidjs-icon-bug-reproduction
pnpm i
pnpm dev
```

**Comment by chenjiahan** [comment]
You can remove the exclude option here: 

![image](https://github.com/web-infra-dev/rsbuild/assets/7237365/113617c2-f8c6-466c-a8db-e0158ec9d6c8)

**Comment by wxiaoyun** [comment]
> You can remove the exclude option here: 
> 
> 
> 
> ![image](https://github.com/web-infra-dev/rsbuild/assets/7237365/113617c2-f8c6-466c-a8db-e0158ec9d6c8)
> 
> 

Thanks a lot!

**Comment by wxiaoyun** [comment]
@chenjiahan It is hard to debug with just the compile error, without the stack trace. I didnt find any options in the Rsbuild CLI such as --verbose. Did I missing anything

**Comment by chenjiahan** [comment]
Try this:

- Debug mode: https://rsbuild.dev/guide/debug/debug-mode
- Build profiling: https://rsbuild.dev/guide/debug/build-profiling

**Comment by wxiaoyun** [comment]
> Try this:
> 
> 
> 
> - Debug mode: https://rsbuild.dev/guide/debug/debug-mode
> 
> - Build profiling: https://rsbuild.dev/guide/debug/build-profiling

Thanks a lot!
