### ISSUE TITLE
[Bug]: Compile error when I use Svelte style tags

### ISSUE THREAD

**Issue by fadrian06** [web-infra-dev/rsbuild#2744]
### Version

```sh
System:
    OS: Windows 7 6.1.7601
    CPU: (2) x64 Intel(R) Celeron(R) CPU 847 @ 1.10GHz
    Memory: 488.38 MB / 1.83 GB
  Browsers: {}
```

### Details

I love working Rsbuild with Svelte using the @rsbuild/plugin-svelte, sometimes I use global css extracted in css files, but in some cases for small practices I want to use inline style tags in svelte components, but the compiler begins to give me Compile errors like this...

![image](https://github.com/web-infra-dev/rsbuild/assets/109766973/8b4bb3c8-6b77-4663-91ae-6001f28f0e41)

I simply restart the rsbuild dev command, but each change throws again the compile error...

### Reproduce link

https://github.com/fadrian06-practices/aprendiendo-svelte/tree/main/projects/02-tic-tac-toe

### Reproduce Steps

1. Install the dependencies with `pnpm install`, although with npm I got the same error
2. Starts the local development server with `pnpm dev` and try to modify anything in any svelte components located in `src/**/*`.

3. If you get the error, restart the server or refresh the browser getting the same error each refresh.

**Comment by chenjiahan** [comment]
Thanks for the feedback, I think we misconfigured the `emitCss` option of svelte-loader, I will fix that

![image](https://github.com/web-infra-dev/rsbuild/assets/7237365/56116d2e-044a-4360-8d74-3c8b0079b270)

https://github.com/sveltejs/svelte-loader
