### ISSUE TITLE
[Bug]: Using html-loader will cause vue-loader to fail

### ISSUE THREAD

**Issue by aliothor** [web-infra-dev/rsbuild#2762]
### Version

```sh
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 19.14 GB / 31.86 GB
  Browsers:
    Edge: Chromium (126.0.2592.81), ChromiumDev (127.0.2610.3)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @rsbuild/core: ^0.7.10 => 0.7.10
    @rsbuild/plugin-vue: ^0.7.10 => 0.7.10
```

### Details

Using html-loader will cause vue-loader to fail
![rsbuild配置](https://github.com/web-infra-dev/rsbuild/assets/60435548/73fa9c50-c4ff-48e9-b224-5f4fc94138b0)
![报错信息](https://github.com/web-infra-dev/rsbuild/assets/60435548/f9c550eb-3834-4806-b648-2e9cfe557754)

### Reproduce link

https://github.com/aliothor/rsbuild-issue

### Reproduce Steps

1. pnpm i
2. pnpm dev

**Comment by xc2** [comment]
Please exclude `/\.vue\.html$/i`. e.g.,

```ts
      addRules({
        test: /\.html$/i,
        exclude: /\.vue.html$/,
        loader: 'html-loader',
      })
```

**Comment by aliothor** [comment]
> Please exclude `/\.vue\.html$/i`. e.g.,
> 
> ```ts
>       addRules({
>         test: /\.html$/i,
>         exclude: /\.vue.html$/,
>         loader: 'html-loader',
>       })
> ```
Thanks, this solved my problem

**Comment by xc2** [comment]
Btw, please exclude `/\/@rsbuild\/core\//` as well for rsbuild's builtin html template.
