### ISSUE TITLE
[Bug][1.0]: `@rsbuild/plugin-swc` has unmet peer dependencies

### ISSUE THREAD

**Issue by colinaaa** [web-infra-dev/rsbuild#2766]
### Version

```sh
npmPackages:
    @rsbuild/core: 1.0.0-alpha.0 => 1.0.0-alpha.0
    @rsbuild/plugin-react: 1.0.0-alpha.0 => 1.0.0-alpha.0
    @rsbuild/plugin-swc: 1.0.0-alpha.0 => 1.0.0-alpha.0
```

### Details

```
 WARN  Issues with peer dependencies found
.
└─┬ @rsbuild/plugin-swc 1.0.0-alpha.0
  └─┬ @modern-js/swc-plugins 0.6.7
    └── ✕ unmet peer @swc/helpers@0.5.3: found 0.5.11 in @rsbuild/plugin-swc
```

### Reproduce link

https://rsbuild.dev/guide/start/quick-start

### Reproduce Steps

1. `npm create rsbuild@alpha`
2. `pnpm add -D @rsbuild/plugin-swc`

**Comment by xc2** [comment]
@JSerFeng is the peer dependency `@swc/helpers` still needed for `@modern-js/swc-plugins`?

I don't think `@modern-js/swc-plugins` directly depends on `@swc/helpers`, and it doesn't seem to be restricted to work with a specific version of `@swc/helpers`. Could we just remove the peer dependency?

**Comment by JSerFeng** [comment]
@modern-js/swc-plugins has dependency of @swc/core, the output generated by @swc/core needs specific version of @swc/helpers.

If one user uses @modern-js/swc-plugins which depends on @swc/core@0.5(just for example), and @swc/core depends on @swc/helpers@1.0, if you use @swc/helpers@2.0, it will crash

**Comment by chenjiahan** [comment]
`@rspack/core` uses `"@swc/helpers": ">=0.5.1"` instead of pin to `0.5.1`.

How about making the same change for `@modern-js/swc-plugins`?

**Comment by JSerFeng** [comment]
That's fine I think.

Should we make @swc/helpers as an optional peer ?

**Comment by chenjiahan** [comment]
> Should we make @swc/helpers as an optional peer ?

LGTM 😄

**Comment by chenjiahan** [comment]
Fixed: https://github.com/web-infra-dev/rsbuild/releases/tag/v1.0.1-beta.4
