### ISSUE TITLE
[Bug]: Issues with the DefinePlugin and self-referencing

### ISSUE THREAD

**Issue by madiyetov** [web-infra-dev/rsbuild#2783]
### System Info

System:
    OS: macOS 14.4.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 84.16 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    npm: 9.9.3 - ~/projects-gh/repro/node_modules/.bin/npm
    pnpm: 8.15.4 - ~/.nvm/versions/node/v20.9.0/bin/pnpm

### Details

Having problems with running the app with `rspack.DefinePlugin` added in `rsbuild.config.ts`. `rsbuild dev` command fails with `TypeError: plugin.apply is not a function` error.

Second issue is happening with Node's self referencing feature.

Both issues are reproduced in the provided github repo link.

### Reproduce link

https://github.com/madiyetov/rspack-issue-repro

### Reproduce Steps

Provided in the github repo.

**Comment by xc2** [comment]
I'm transfering this issue to rsbuild repo as the project you just refered is using rsbuild.

for the first question, please use [source.define](https://rsbuild.dev/config/source/define) instead.

for the second question,  in nodejs, self referencing feature works only when there's `export` field in `package.json`. alternatively, in rsbuild, you could use [source.alias](https://rsbuild.dev/config/source/alias) instead.

**Comment by xc2** [comment]
in addition, if you have to add a rspack plugin from rspack, please refer: [rspack section in tools.rspack](https://rsbuild.dev/config/tools/rspack#rspack)

**Comment by madiyetov** [comment]
Great! Thanks for your help.
