### ISSUE TITLE
[Bug]: importing react-idle-timer causes SyntaxError

### ISSUE THREAD

**Issue by TheWeirdDev** [web-infra-dev/rsbuild#2819]
### Version

```sh
System:
    OS: Linux 6.9 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 10.94 GB / 19.29 GB
    Container: Yes
    Shell: 3.7.1 - /bin/fish
  Browsers:
    Chromium: 126.0.6478.126
  npmPackages:
    @rsbuild/core: 1.0.0-alpha.4 => 1.0.0-alpha.4 
    @rsbuild/plugin-react: 1.0.0-alpha.4 => 1.0.0-alpha.4
```

### Details

Using `react-idle-timer` in a react project causes SyntaxError:

```
vendors-node_modules…ack_c-32d00f.js:288 
 Uncaught  SyntaxError: Unexpected token ';' (at vendors-node_modules…32d00f.js:288:21525)
```

### Reproduce link

https://codesandbox.io/p/devbox/wqrg9x

### Reproduce Steps

1. Create a new react ts project using `pnpm create rsbuild@latest`
2. Add 'react-idle-timer' as a dependency: `pnpm i react-idle-timer`
3. Modify the App component to use idle timer:
 ```tsx
import { withIdleTimer } from "react-idle-timer";
import './App.css';

const App = () => {
  return (
    <div className="content">
      <h1>Rsbuild with React</h1>
      <p>Start building amazing things with Rsbuild.</p>
    </div>
  );
};

export default withIdleTimer(App);
```
4. Run the dev server: `pnpm run dev`
5. Observe the syntax error message in Chrome DevTools

**Comment by khangviet1996** [comment]
Same issue

**Comment by GiancarlosIO** [comment]
Same here. Happens after upgrading rsbuild to latest version

![image](https://github.com/web-infra-dev/rsbuild/assets/17274950/1ec4b1e8-56d3-4770-8f11-5072da151334)
![image](https://github.com/web-infra-dev/rsbuild/assets/17274950/04fd8ff0-843e-448e-a91a-e71fa3ea33e8)

**Comment by chenjiahan** [comment]
This should related to: https://github.com/web-infra-dev/rspack/issues/7049

@ahabhgk cc

**Comment by chenjiahan** [comment]
Fixed by Rspack, https://github.com/web-infra-dev/rsbuild/releases/tag/v1.0.0-alpha.6

**Comment by GiancarlosIO** [comment]
Thanks so much @chenjiahan !!!

**Comment by khangviet1996** [comment]
![Uploading image.png…]()

Issue1 is fixed, but i still got this issue @@
