### ISSUE TITLE
[Bug]: The order of CSS imports is not respected

### ISSUE THREAD

**Issue by wanqing19954** [web-infra-dev/rsbuild#2847]
### Version

```sh
System:
    OS: macOS 14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 59.99 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 126.0.6478.127
    Safari: 17.5
  npmPackages:
    @rsbuild/core: ^0.7.10 => 0.7.10 
    @rsbuild/plugin-less: 0.7.10 => 0.7.10 
    @rsbuild/plugin-react: ^0.7.10 => 0.7.10
```

### Details

CSS priority is not in accordance with the import order

My expectation is: tea.css > main.less

<img width="531" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/23456250/06a4d3c1-9d85-406d-9caf-cbc1439ba3b5">

<img width="745" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/23456250/32f1061a-9a09-4cbd-ba66-32b21d2e6eef">

<img width="1633" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/23456250/7ccd599d-5ded-46b5-be88-158a5519dc5c">

### Reproduce link

https://github.com/wanqing19954/rsbuild-css-order

### Reproduce Steps

pnpm dev

**Comment by chenjiahan** [comment]
I have tested this in webpack and got the same result.

The CSS order changed because `tea.css` was split into a separate chunk:

![image](https://github.com/web-infra-dev/rsbuild/assets/7237365/4352894b-7f5e-4840-b1cb-ebd2c2585db7)

You can configure chunk splitting rules to resolve it, for example, put `main.less` and `tea.css` to a single CSS chunk:

```ts
// rsbuild.config.ts
export default defineConfig({
  performance: {
    chunkSplit: {
      override: {
        cacheGroups: {
          baseStyle: {
            test: /main\.less|tea\.css/,
          },
        },
      },
    },
  },
});
```

**Comment by YLMC2017** [comment]
![image](https://github.com/web-infra-dev/rsbuild/assets/35885819/997114b8-5a40-44de-ad47-30dc74f81176)
Is there any way to adjust the CSS loading order? I would like to load index.css at the end.

**Comment by chenjiahan** [comment]
It is recommended to adjust the **CSS import order and selector specificity** instead of adjust the CSS link tags order.

See [Deep Dive Into Webpack CSS Order Issue](https://github.com/orgs/web-infra-dev/discussions/12) to learn more about CSS order issues.
