### ISSUE TITLE
[Bug]: `loadEnv` is not exported from `@rsbuild/core`

### ISSUE THREAD

**Issue by lamualfa** [web-infra-dev/rsbuild#2864]
### Version

```sh
node: 18.19.1
typescript: 4.9.5
@rsbuild/core: 1.0.0
```

### Details

`loadEnv` is not exported in `1.0.0`, but works fine in `v0.7.9`. Is there any breaking changes for `loadEnv`? I can't find any in the releases page.

### Reproduce Steps

![image](https://github.com/web-infra-dev/rsbuild/assets/39755201/780b242a-718e-4f48-8ea7-48363dfef5e4)

**Comment by lamualfa** [comment]
@chenjiahan Ok, it's work. Thanks.

I think the team should deprecated it manually using `npm deprecate`. Or in hardcore way unpublish the `v1.0.0`.

**Comment by chenjiahan** [comment]
npm does not allow to unpublish a version
