### ISSUE TITLE
[Bug]: Alias not working fully on webstorm.

### ISSUE THREAD

**Issue by adoin** [web-infra-dev/rsbuild#2876]
### Version

```sh
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 13.17 GB / 31.83 GB
  Browsers:
    Edge: Chromium (126.0.2592.87)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    @rsbuild/core: ^0.6.15 => 0.6.15
    @rsbuild/plugin-vue: ^0.6.15 => 0.6.15
```

### Details

![image](https://github.com/web-infra-dev/rsbuild/assets/20517172/106b39e7-111d-4892-9733-2bfc3d6075f5)
![image](https://github.com/web-infra-dev/rsbuild/assets/20517172/e800343e-3a5c-4998-ab3e-dcbe1a442c9e)
![image](https://github.com/web-infra-dev/rsbuild/assets/20517172/3829f530-3ce6-46f8-ad9b-1ff7621ad63d)
Is there anywhere mistake from me?

### Reproduce link

please open through webstorm

### Reproduce Steps

Open project with alias through webstorm.

**Comment by xc2** [comment]
please try:

```json
"baseUrl": "./",
"paths": {
  "@/*": ["./src/*"]
}
```

ref: https://www.typescriptlang.org/tsconfig/#paths

**Comment by adoin** [comment]
> please try:
> 
> ```json
> "baseUrl": "./",
> "paths": {
>   "@/*": ["./src/*"]
> }
> ```
> 
> ![](chrome-extension://annlhfjgbkfmbbejkbdpgbmpbcjnehbb/images/saveicon.png) Save
> ref: https://www.typescriptlang.org/tsconfig/#paths

not working
![image](https://github.com/web-infra-dev/rsbuild/assets/20517172/c06c9c1b-f9da-4bf0-8590-8f44c38f71b2)

**Comment by xc2** [comment]
@adoin did you set `baseUrl` as well?

**Comment by xc2** [comment]
@adoin, the error message has changed. It now states that there is no '.d.ts' file for 'use18n.js', which is not a TypeScript file.

For this situation, you can either create declarations for 'use18n.js' or change the filename to 'use18n.ts'. Another option is to add 'allowJs: true' to your tsconfig file.

**Comment by adoin** [comment]
> @adoin, the error message has changed. It now states that there is no '.d.ts' file for 'use18n.js', which is not a TypeScript file.
> 
> For this situation, you can either create declarations for 'use18n.js' or change the filename to 'use18n.ts'. Another option is to add 'allowJs: true' to your tsconfig file.

I see, it seems that there is a js file? WIll try it tomorrow. thx.

**Comment by xc2** [comment]
I'm closing this issue as it's rather than an rsbuild problem. 

Please feel free to continue this thread if you have any more questions about this problem.

**Comment by adoin** [comment]
> I'm closing this issue as it's rather than an rsbuild problem.
> 
> Please feel free to continue this thread if you have any more questions about this problem.

Resolved, thanks
