### ISSUE TITLE
[Bug]: @rsbuild/plugin-check-syntax Unable to output real file path normally

### ISSUE THREAD

**Issue by yangcore** [web-infra-dev/rsbuild#2884]
### Version

```sh
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 2.17 GB / 15.77 GB
  Browsers:
    Edge: Chromium (126.0.2592.81)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    @rsbuild/core: 1.0.0-alpha.8 => 1.0.0-alpha.8
    @rsbuild/plugin-check-syntax: 1.0.0-alpha.8 => 1.0.0-alpha.8
    @rsbuild/plugin-less: 1.0.0-alpha.8 => 1.0.0-alpha.8
    @rsbuild/plugin-vue2: 1.0.0-alpha.8 => 1.0.0-alpha.8
```

### Details

![image](https://github.com/web-infra-dev/rsbuild/assets/20217483/f33a74b8-e445-4676-aa5a-b108f010c430)
![image](https://github.com/web-infra-dev/rsbuild/assets/20217483/c278cdfc-e94b-4fad-ba18-a8700c79d714)
![image](https://github.com/web-infra-dev/rsbuild/assets/20217483/0e0c7582-5445-4452-9139-725e1aa70e0c)

### Reproduce link

Not available yet

### Reproduce Steps

npm run build

**Comment by chenjiahan** [comment]
We need a reproduction to debug this issue

**Comment by yangcore** [comment]
> We need a reproduction to debug this issue

https://codesandbox.io/p/github/rspack-contrib/rsbuild-codesandbox-example/csb-k3ny7y/draft/sweet-chatelet?layout=%257B%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clyme3kyd00073j6jrc2psco8%2522%252C%2522sizes%2522%253A%255B41.380846325167035%252C58.619153674832965%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clyme3kyd00023j6j9kjo1w92%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clyme3kyd00043j6jvynfu86i%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clyme3kyd00063j6jdydwpi3n%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clyme3kyd00023j6j9kjo1w92%2522%253A%257B%2522id%2522%253A%2522clyme3kyd00023j6j9kjo1w92%2522%252C%2522activeTabId%2522%253A%2522clymeilng004q3j6kwn8e5bzj%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyme3kyc00013j6jfsr80cy4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clyme5om7004g3j6j13b1ihy9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A8%252C%2522startColumn%2522%253A33%252C%2522endLineNumber%2522%253A8%252C%2522endColumn%2522%253A33%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Froot%252F.cache%252Fnpm%252F_logs%252F2024-07-15T03_04_38_146Z-debug-0.log%2522%252C%2522id%2522%253A%2522clymeilng004q3j6kwn8e5bzj%2522%252C%2522mode%2522%253A%2522temporary%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clyme3kyd00063j6jdydwpi3n%2522%253A%257B%2522id%2522%253A%2522clyme3kyd00063j6jdydwpi3n%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clyme3kyd00043j6jvynfu86i%2522%253A%257B%2522id%2522%253A%2522clyme3kyd00043j6jvynfu86i%2522%252C%2522activeTabId%2522%253A%2522clymedm5t00ac3j6kmtpiduml%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyme3kyd00033j6jiys18kjl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clymedm5t00ac3j6kmtpiduml%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clymedmcf0b49d9j23595dohj%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by chenjiahan** [comment]
I can not open the link, can you check it?

![Uploading image.png…]()
