### ISSUE TITLE
[Feature]: Add a configuration item to customize the directory used to load .env files

### ISSUE THREAD

**Issue by curlykay** [web-infra-dev/rsbuild#2888]
### What problem does this feature solve?

My project relies on multiple .env files to package multiple environments. Multiple .env files make the project root directory very bloated and inconvenient for finding and managing project files.
With this configuration item, I can keep my .env files out of the project root and manage them better.

### What does the proposed API look like?

Would like to have a config item like vite's 'envDir' to customize the .env load directory for rsbuild.
https://cn.vitejs.dev/config/shared-options.html#envdir

**Comment by chenjiahan** [comment]
There are some differences between Rsbuild and Vite in the implementation of loading env:

- Rsbuild will load .env first and allow users to access these env vars in the `rsbuild.config.ts`. 
- Vite loads the .env file after loading the configuration file.

The Rsbuild CLI will provide an option like `--env-path` to support this, you can also use the [loadEnv](https://rsbuild.dev/api/javascript-api/core#loadenv) method.

Related issue: https://rsbuild.dev/api/javascript-api/core#loadenv

**Comment by curlykay** [comment]
LoadEnvOptions['cwd'] should solve my problem, thanks for the answer.
