### ISSUE TITLE
[Bug]: @rsbuild/plugin-eslint@1.0.0 - `TypeError: Cannot destructure property 'distPath' of 'environment' as it is undefined.`

### ISSUE THREAD

**Issue by Kotpes** [web-infra-dev/rsbuild#2897]
### Version

```sh
System:
    OS: macOS 14.5
    CPU: (14) arm64 Apple M3 Max
    Memory: 118.88 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 126.0.6478.127
    Safari: 17.5
  npmPackages:
    @rsbuild/core: 0.7.10 => 0.7.10 
    @rsbuild/plugin-eslint: 1.0.0 => 1.0.0 
    @rsbuild/plugin-react: 0.7.10 => 0.7.10
```

### Details

Latest v1.0.0 of `@rsbuild/plugin-eslint` causes build to fail with: 
```sh
error   Failed to build.
error   TypeError: Cannot destructure property 'distPath' of 'environment' as it is undefined.
```
Works as before with `0.7.10`

### Reproduce link

don't have a public repo, but should be pretty straightforward to reproduce

### Reproduce Steps

rsbuild build

**Comment by chenjiahan** [comment]
Please use `@rsbuild/core` 1.0.0-alpha when using `@rsbuild/plugin-eslint` 1.0.0

![image](https://github.com/user-attachments/assets/e5e5aa78-4f0d-437d-b76c-8c3ab4497fc6)

https://github.com/rspack-contrib/rsbuild-plugin-eslint/blob/d72e7f28a0f1d5161399ac39255063a1b010c208/package.json#L53
