### ISSUE TITLE
[Bug]:  Webpack build fails when lang is set to "ts" in SFC

### ISSUE THREAD

**Issue by FlowingPond** [web-infra-dev/rsbuild#2927]
### Version

```sh
System:
    OS: macOS 14.4.1
    CPU: (11) arm64 Apple M3 Pro
    Memory: 54.88 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 126.0.6478.127
    Edge: 126.0.2592.102
    Safari: 17.4.1
  npmPackages:
    @rsbuild/core: 1.0.1-beta.1 => 1.0.1-beta.1 
    @rsbuild/plugin-vue: 1.0.1-beta.1 => 1.0.1-beta.1 
    @rsbuild/webpack: 1.0.1-beta.1 => 1.0.1-beta.1
```

### Details

I want to use TypeScript in Vue SFC with Webpack, but I get a compilation error after setting lang="ts":
```
File was processed with these loaders:
 * ./node_modules/.pnpm/vue-loader@17.4.2_vue@3.4.31_typescript@5.5.3__webpack@5.93.0/node_modules/vue-loader/dist/templateLoader.js
 * ./node_modules/.pnpm/vue-loader@17.4.2_vue@3.4.31_typescript@5.5.3__webpack@5.93.0/node_modules/vue-loader/dist/index.js
You may need an additional loader to handle the result of these loaders.
| import { createElementVNode as _createElementVNode, openBlock as _openBlock, createElementBlock as _createElementBlock, pushScopeId as _pushScopeId, popScopeId as _popScopeId } from "vue"
| 
> const _withScopeId = (n: any) => (_pushScopeId("data-v-7ba5bd90"),n=n(),_popScopeId(),n)
| const _hoisted_1 = { class: "content" }
| const _hoisted_2 = /*#__PURE__*/ _withScopeId(() => /*#__PURE__*/_createElementVNode("h1", null, "Rsbuild with Vue", -1 /* HOISTED */))
```

### Reproduce link

https://github.com/FlowingPond/rsbuild-webpack-vue-ts

### Reproduce Steps

pnpm i

pnpm dev

**Comment by chenjiahan** [comment]
The `@rsbuild/webpack` is provided for inner testing and does not supports Vue SFC.

![image](https://github.com/user-attachments/assets/90cfadf5-e83c-4a6a-b8e0-427b11f5de1e)

https://github.com/web-infra-dev/rsbuild/tree/main/packages/compat/webpack

**Comment by FlowingPond** [comment]
> The `@rsbuild/webpack` is provided for inner testing and does not supports Vue SFC.
> 
> ![image](https://private-user-images.githubusercontent.com/7237365/348632516-90cfadf5-e83c-4a6a-b8e0-427b11f5de1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMzE3MTgsIm5iZiI6MTcyMTAzMTQxOCwicGF0aCI6Ii83MjM3MzY1LzM0ODYzMjUxNi05MGNmYWRmNS1lODNjLTRhNmEtYjhlMC00MjdiMTFmNWRlMWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTVUMDgxNjU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzY4ODBmZWJlZGFiM2M5NjhkYTc5ZDhmMjkzMTNhMjIwMmNhNjI3YTFiYjc3ZjZjMDFhM2ZiMWIyNzFjNmE2MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DD7OZKnU3WGgIuhuaocDjRNMMM4uhIVpxXpbaCPd89I)
> 
> https://github.com/web-infra-dev/rsbuild/tree/main/packages/compat/webpack

Get, thanks~
