### ISSUE TITLE
[Bug]: module.less file reports an error when packaging (rsbuild build)

### ISSUE THREAD

**Issue by JayMo666** [web-infra-dev/rsbuild#2928]
### Version

module.less file reports an error when packaging (rsbuild build), @primary-color is a less variable in antd V4.

```sh
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1 Pro
    Memory: 123.38 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 126.0.6478.127
    Chrome Canary: 128.0.6596.0
    Safari: 17.5
  npmPackages:
    @rsbuild/core: 1.0.1-beta.1 => 1.0.1-beta.1 
    @rsbuild/plugin-less: 1.0.1-beta.1 => 1.0.1-beta.1 
    @rsbuild/plugin-react: 1.0.1-beta.1 => 1.0.1-beta.1 
    @rsbuild/plugin-svgr: 1.0.1-beta.1 => 1.0.1-beta.1
```

### Details

![image](https://github.com/user-attachments/assets/87380458-dc29-4c41-bf32-9fa03712353d)

### Reproduce link

无

### Reproduce Steps

pnpm run build

**Comment by chenjiahan** [comment]
Get, seems to be unrelated to Rsbuild, I will close this issue.
