### ISSUE TITLE
[Bug]:  Garfish 微前端，子应用在主应用中时，热更新失效

### ISSUE THREAD

**Issue by xlsama** [web-infra-dev/rsbuild#2935]
### Version

```sh
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 8.29 GB / 32.00 GB
    Shell: 3.7.0 - /opt/homebrew/bin/fish
  Browsers:
    Chrome: 126.0.6478.127
    Safari: 17.5
```

### Details

Garfish 微前端框架，主子应用本地启动，子应用独立运行，热更新正常，在主应用中运行，热更新失效。

依赖版本：
garfish：`1.19.2`
@garfish/bridge-react-v18：`1.19.2`
@rsbuild/core：`1.0.1-beta.1`
@rsbuild/plugin-react：`1.0.1-beta.1`

按照文档改了改，怎么都不好使，参考的文档：
- https://rsbuild.dev/zh/guide/faq/hmr#%E7%83%AD%E6%9B%B4%E6%96%B0%E9%97%AE%E9%A2%98
- https://www.garfishjs.org/blog/hmr#%E5%AD%90%E5%BA%94%E7%94%A8%E7%83%AD%E6%9B%B4%E6%96%B0%E6%9C%AA%E7%94%9F%E6%95%88

hot-update.js 中请求返回的内容是最新的代码，看起来像是没有符合 React 对热更新的要求，辛苦大佬帮忙看看，感谢 ❤️ 。

### Reproduce link

https://github.com/xlsama/rsbuild-demo

### Reproduce Steps

1.  启动主子应用 `pnpm dev`，主应用地址：`http://localhost:3000`，子应用地址：`http://localhost:3001`
2. 进入主应用地址 `http://localhost:3000`， 修改子应用 `react-sub/src/App.tsx` 中的代码，`http://localhost:3001` 热更新正常，`http://localhost:3000` 热更新失效。

**Comment by xlsama** [comment]
主应用关闭 hmr 就好了 🌚
```ts
  dev: {
    hmr: false,
  },
```

**Comment by xmsz-stu** [comment]
> 主应用关闭 hmr 就好了 🌚
> 
> ```ts
>   dev: {
>     hmr: false,
>   },
> ```

那主应用还可以热更新吗

**Comment by xlsama** [comment]
> > 主应用关闭 hmr 就好了 🌚
> > ```ts
> >   dev: {
> >     hmr: false,
> >   },
> > ```
> 
> 那主应用还可以热更新吗

主应用会降级为 liveReload，我感觉用起来和热更新区别不大
https://rsbuild.dev/zh/guide/advanced/hmr#hmr-%E5%BC%80%E5%85%B3

**Comment by xlsama** [comment]
上面这个可以解决 js 的热更新问题。

我发现 [Garfish 默认会把子应用的样式资源转换成 style 标签](https://www.garfishjs.org/api/registerApp#sandbox)，所以 css 热更新需要把 disableLinkTransformToStyle 改成 true

```ts
  Garfish.run({
    basename: '/',
    disablePreloadApp: true,
    sandbox: {
      // 解决子应用在微前端环境下的 css 热更新问题
      disableLinkTransformToStyle: true,
    },
  })
```

**Comment by xmsz-stu** [comment]
> 上面这个可以解决 js 的热更新问题。
> 
> 我发现 [Garfish 默认会把子应用的样式资源转换成 style 标签](https://www.garfishjs.org/api/registerApp#sandbox)，所以 css 热更新需要把 disableLinkTransformToStyle 改成 true
> 
> ```ts
>   Garfish.run({
>     basename: '/',
>     disablePreloadApp: true,
>     sandbox: {
>       // 解决子应用在微前端环境下的 css 热更新问题
>       disableLinkTransformToStyle: true,
>     },
>   })
> ```

能不能同时关闭sandbox和 disableLinkTransformToStyle: true,
