### ISSUE TITLE
[Bug]: After updating to Rsbuild v1.0.0, an error message appears: error: unknown option '--env-mode'

### ISSUE THREAD

**Issue by zhuyuanmin** [web-infra-dev/rsbuild#2983]
### Version

```sh
win11
chrome 126
rsbuild v1.0.0
```

### Details

$ npx rsbuild dev --env-mode beta

  Rsbuild v1.0.0

error: unknown option '--env-mode'

### Reproduce link

none

### Reproduce Steps

no

**Comment by chenjiahan** [comment]
Rsbuild v1.0.0 is a deprecated version, please use the latest version, see https://github.com/web-infra-dev/rsbuild/releases/tag/v1.0.1-beta.3
