### ISSUE TITLE
[Bug]: Page requests are always pending when a proxy request has an error

### ISSUE THREAD

**Issue by dingjiang-gao** [web-infra-dev/rsbuild#2988]
### Version

```sh
"@rsbuild/core": "1.0.0-alpha.6",
"@rsbuild/plugin-less": "1.0.0-alpha.6",
"@rsbuild/plugin-react": "1.0.0-alpha.6",
mac M1 Ventura13.4
```

### Details

背景：rsbuild配置了server.proxy, 进行api代理，通过router钩子进行重写指向mock服务或者后端服务
现象：当我本地mock，没有启动，本地页面服务开启，重新冷启动后，会有一些api请求打到代理服务上，会出现如下
![image](https://github.com/user-attachments/assets/45dad43f-bf39-44ef-9368-6412c27dc988)

这个其实能理解，正常打印，问题是当出现存留页面的api请求到代理服务发生error 后，正常的页面请求，发生阻塞，一直pending
![image](https://github.com/user-attachments/assets/960b0aaa-7e61-4606-a6e1-e93d9f235719)

### Reproduce link

xx

### Reproduce Steps

1: 版本如上，配置server.proxy
`{ '/api': { router: () => (url)}}` // 这个url对应的服务不存在

2:有存留页面，重写冷启动

3: 打开新页面

4:存留页面会导致控制台命令行的error打印，同时心页面的页面请求发生pending，

**Comment by 9aoy** [comment]
Need a reproducible demo . The proxy error can be reproduced, but the pending status cannot be reproduced.
