### ISSUE TITLE
[Feature]: provide cli shortcuts

### ISSUE THREAD

**Issue by Alkaidcc** [web-infra-dev/rsbuild#2991]
### What problem does this feature solve?

CLI shortcuts allow users to restart the server, show the server URL, clear the console, etc. It's very convenient.
in vite, we can 
```
press r + enter to restart the server
press u + enter to show server url
press o + enter to open in browser
press c + enter to clear console
press q + enter to quit
```
Does rsbuild have plans to support it?

### What does the proposed API look like?

same as vite

**Comment by chenjiahan** [comment]
Yes, Rebuild dev server should provide this feature, I will implement it soon.
