### ISSUE TITLE
[Bug]: can not access app via ipv4

### ISSUE THREAD

**Issue by 2heal1** [web-infra-dev/rsbuild#3017]
### Version

```sh
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.69 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 126.0.6478.183
    Safari: 17.5
  npmPackages:
    @rsbuild/core: 1.0.1-beta.5 => 1.0.1-beta.5 
    @rsbuild/plugin-react: 1.0.1-beta.5 => 1.0.1-beta.5
```

### Details

**current results**
* visit localhost
![image](https://github.com/user-attachments/assets/ffcce282-bd75-4c13-ae19-59cb76766ddb)
* visit ipv4 
![image](https://github.com/user-attachments/assets/2087b3e6-f6e4-4cf2-8e85-69dbcd00970f)

 

### Reproduce link

https://github.com/2heal1/rsbuild-demo

### Reproduce Steps

* pnpm install
* pnpm dev
* visit ipv4 url

**Comment by chenjiahan** [comment]
I can not reproduce this, can you try to restart your computer..

**Comment by 2heal1** [comment]
Ahh restart works , maybe it's something error in my proxy
