### ISSUE TITLE
[Bug]: Build file path error

### ISSUE THREAD

**Issue by bosens-China** [web-infra-dev/rsbuild#3019]
### Version

```sh
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1 Pro
    Memory: 96.94 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 126.0.6478.183
    Safari: 17.5
```

### Details

我在scss文件引入了一个字体文件，但是输出的路径不对，导致查找不到这个文件。
![image](https://github.com/user-attachments/assets/1698c008-a06d-4341-afb4-f945a79a2f8b)
![image](https://github.com/user-attachments/assets/91177d10-5e57-4f31-abfc-1a98ac628427)

这可能跟我设置的配置文件
` assetPrefix: './',` 有关，但是有没有办法能修复这个问题

### Reproduce link

none

### Reproduce Steps

none

**Comment by chenjiahan** [comment]
What is your expected output path?

**Comment by chenjiahan** [comment]
Have you tried `outpu.assetPrefix: 'auto'`? It is the same as webpack's `output.publicPath` and can emit relative path.

**Comment by bosens-China** [comment]
auto 也不成，老哥有啥其他办法吗

**Comment by chenjiahan** [comment]
Please provide a reproduction for this
