### ISSUE TITLE
[Bug]: Question about rsbuild.inspectConfig custom output path outputPath

### ISSUE THREAD

**Issue by cklwblove** [web-infra-dev/rsbuild#3023]
### Version

```sh
System:
    OS: macOS 13.4
    CPU: (12) arm64 Apple M2 Pro
    Memory: 117.38 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 126.0.6478.183
    Safari: 16.5
```

### Details

rsbuild.inspectConfig 的 outputPath（指定输出路径），这个值为什么要拼接 `output.distPath.root` ？难道只能支持在 `output.distPath.root ` 这里进行指定吗?

<img width="897" alt="image" src="https://github.com/user-attachments/assets/2d2cd2f6-f885-4e06-8c29-e5bd1f2ecaa7">

### Reproduce link

none

### Reproduce Steps

none

**Comment by chenjiahan** [comment]
It's just a convention, if you need to output to other folders, we can support passing an absolute path.

**Comment by cklwblove** [comment]
感谢回复。我个人觉得可以文档上加下这个说明。另外，以“输出路径”作为一个基本路径，为啥是一个惯例呢？不应该是以当前运行命令的目录作为基本路径吗

**Comment by chenjiahan** [comment]
The output files of `inspectConfig` are just temporary files and should not be committed to git.

**Comment by cklwblove** [comment]
好的，明白了。

**Comment by chenjiahan** [comment]
Absolute output path will be supported in the next release.
