### ISSUE TITLE
[Bug]: import.meta.env undefined since beta6

### ISSUE THREAD

**Issue by abenhamdine** [web-infra-dev/rsbuild#3029]
### Version

```sh
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 1.77 GB / 15.36 GB
  Browsers:
    Edge: Chromium (123.0.2420.65)
  npmPackages:
    @rsbuild/core: 1.0.1-beta.6 => 1.0.1-beta.6
    @rsbuild/plugin-eslint: 1.0.0 => 1.0.0
    @rsbuild/plugin-react: 1.0.1-beta.6 => 1.0.1-beta.6
    @rsbuild/plugin-type-check: 1.0.1-beta.6 => 1.0.1-beta.6
```

### Details

Since beta6, our app breaks because import.meta.env is no more accessible in the code at runtime :

The error occurs at the following code : 

```tsx
let isDialogOpened: boolean = false

// line 43 here after
if (import.meta.env.PUBLIC_SENTRY_DSN) {
	Sentry.init({
		dsn: import.meta.env.PUBLIC_SENTRY_DSN,
		environment: import.meta.env.PUBLIC_MODE,
// ...etc
```

```
App.tsx:43 Uncaught TypeError: Cannot read properties of undefined (reading 'PUBLIC_SENTRY_DSN')
    at ./src/App.tsx (App.tsx:43:1)
    at __webpack_require__ (validators.ts:82:1)
    at fn (validators.ts:82:1)
    at ./src/index.tsx (getInfosForValidationAbsence.ts:108:1)
    at __webpack_require__ (validators.ts:82:1)
    at validators.ts:82:1
    at __webpack_require__.O (validators.ts:82:1)
    at validators.ts:82:1
    at validators.ts:82:1
```
if we revert back to beta 5, everything works fine again.

### Reproduce link

Sorry I will try to post a reproduction later

### Reproduce Steps

yarn run dev

**Comment by chenjiahan** [comment]
This problem should be introduced in Rspack 1.0.0-beta.0. If there is a reproduction, it will be very helpful to fix the bug.

**Comment by abenhamdine** [comment]
I fail to reproduce the error in a basic project.
So the issues is probably triggered by a combination of modules/configs but I can't figure out where 

Any hint/help would be useful !

**Comment by chenjiahan** [comment]
You can try to remove all the source code in your project and only keep the related lines of code. Then check what will happen.

**Comment by abenhamdine** [comment]
> You can try to remove all the source code in your project and only keep the related lines of code. Then check what will happen.

Good idea : I succeed in reproducing the bug : https://github.com/abenhamdine/repro-rsbuild-beta6

Please pay attention that you have to be in the folder `/client` to install and start the app

**Comment by chenjiahan** [comment]
This `undefined` issue is introduced in Rspack's https://github.com/web-infra-dev/rspack/pull/7229. The current output is align with webpack v5.

- Input:

```js
if (import.meta.env.PUBLIC_SENTRY_DSN) {
```

- Output (Rspack 1.0 alpha): 

```js
if (undefined) {
```

- Output (Rspack 1.0 beta.0 and webpack v5):

```js
if (/* unsupported import.meta.env.PUBLIC_SENTRY_DSN */ undefined.PUBLIC_SENTRY_DSN) {
```

- Output (Vite v5)

```js
var define_import_meta_env_default = { BASE_URL: "/", MODE: "production", DEV: false, PROD: true, SSR: false };
if (define_import_meta_env_default.PUBLIC_SENTRY_DSN) {
  console.log(1);
}
```

@LingyuCoder Is `undefined.PUBLIC_SENTRY_DSN` expected? This will cause a runtime error, perhaps we should use a more robust output.

**Comment by chenjiahan** [comment]
@abenhamdine `PUBLIC_SENTRY_DSN` is not defined in your `.env.development` file. 

If this value is empty in development, it is recommended to define it as `PUBLIC_SENTRY_DSN=""` rather than leaving it undefined.

**Comment by abenhamdine** [comment]
> @abenhamdine `PUBLIC_SENTRY_DSN` is not defined in your `.env.development` file.
> 
> If this value is empty in development, it is recommended to define it as `PUBLIC_SENTRY_DSN=""` rather than leaving it undefined.

Oh yes you're right, it solves the issues, thx ! 

> it is recommended to define it as `PUBLIC_SENTRY_DSN=""` rather than leaving it undefined.

I would even say it's now required to define it  because of this new behaviour.

**Comment by LingyuCoder** [comment]
> Is `undefined.PUBLIC_SENTRY_DSN` expected? This will cause a runtime error, perhaps we should use a more robust output.

Just aligned with webpack. Perhaps this need more [dicussion](https://github.com/webpack/webpack/issues/15833).

**Comment by chenjiahan** [comment]
I understand that Rspack and webpack do not support import.meta.env by default because it is not part of the specification.

The question is, why replace `import.meta.env` with `undefined` instead of leaving it as is?

**Comment by chenjiahan** [comment]
Tracking in: https://github.com/web-infra-dev/rspack/issues/7364
