### ISSUE TITLE
[Bug]: ReferenceError: process is not defined

### ISSUE THREAD

**Issue by sagardwivedi** [web-infra-dev/rsbuild#3030]
### Version

```sh
System:
    OS: Linux 5.15 Ubuntu 24.04 LTS 24.04 LTS (Noble Numbat)
    CPU: (12) x64 AMD Ryzen 5 4600H with Radeon Graphics
    Memory: 1.58 GB / 3.57 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  npmPackages:
    @rsbuild/core: ^1.0.1-beta.6 => 1.0.1-beta.6 
    @rsbuild/plugin-react: ^1.0.1-beta.6 => 1.0.1-beta.6
```

### Details

I am encountering an error in the following code. I was getting this error before the update as well, so I hardcoded some values previously. However, now that I am trying to host it and use environment variables, I am still facing the issue. Could someone help me troubleshoot this?

``` javascript
OpenAPI.BASE = process.env.BACKEND_URL || "http://localhost:8000"
```

``` console
index.tsx:10 Uncaught 
ReferenceError: process is not defined
    at ./src/index.tsx (index.tsx:10:1)
    at __webpack_require__ (signup.tsx:34:1)
    at signup.tsx:34:1
    at __webpack_require__.O (signup.tsx:34:1)
    at signup.tsx:34:1
    at signup.tsx:34:1
```

### Reproduce link

I don't have yet

### Reproduce Steps

bun dev

**Comment by chenjiahan** [comment]
Have you defined this variable in "source.define"?

**Comment by sagardwivedi** [comment]
No. I haven't. I thought it will done automatically.

**Comment by chenjiahan** [comment]
Have you read the environment variables documentation? https://rsbuild.dev/guide/advanced/env-vars

**Comment by sagardwivedi** [comment]
I did and create .env.development and .env.production

**Comment by chenjiahan** [comment]
Check this:

![image](https://github.com/user-attachments/assets/b48824af-a932-4a16-9ec4-b357fc810952)

![image](https://github.com/user-attachments/assets/317ff6cd-9dd3-411b-9245-849f1fa7b4ab)

https://rsbuild.dev/guide/advanced/env-vars#public-variables
