### ISSUE TITLE
[Bug]: ReferenceError: Cannot access 'nS' before initialization

### ISSUE THREAD

**Issue by zero9527** [web-infra-dev/rsbuild#3056]
### Version

```sh
System:
    OS: macOS 13.6.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 351.57 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 126.0.6478.183
    Safari: 17.5
  npmPackages:
    @rsbuild/core: 1.0.1-beta.6 => 1.0.1-beta.6 
    @rsbuild/plugin-less: 1.0.1-beta.6 => 1.0.1-beta.6 
    @rsbuild/plugin-vue: 1.0.1-beta.6 => 1.0.1-beta.6
```

### Details

使用`rsbuild/core@1.0beta` 版本，构建后会报错，开发启动正常

`"ant-design-vue": "3.2.15"` 会报错 `ReferenceError: Cannot access 'nS' before initialization`

`rsbuild/core@0.6`或者`rsbuild/core@0.7`正常

### Reproduce link

无

### Reproduce Steps

- vue-cli+vue3项目
- ant-design-vue@3.2.15 依赖
- 构建项目

**Comment by SoonIter** [comment]
Could you self-check again with https://github.com/web-infra-dev/rsbuild/issues/2862 ?

**Comment by zero9527** [comment]
> Could you self-check again with #2862 ?

Thanks, my problem was with browser access after production build, but it worked fine in development mode. I just downgraded the dependency to `rsbuild/core@0.7` to fix this

I will provide the reproduction project as soon as possible
