### ISSUE TITLE
[Bug]: Failed to mount component: template or render function not defined.  found in  ---> <App> at src/App.vue        <Root>

### ISSUE THREAD

**Issue by tongSir-shuai** [web-infra-dev/rsbuild#3058]
### Version

```sh
System:
    OS: macOS 14.3
    CPU: (8) arm64 Apple M1 Pro
    Memory: 124.39 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 126.0.6478.183
    Safari: 17.3
```

### Details

`const path = require('path');
import { defineConfig, loadEnv } from '@rsbuild/core';
import { pluginVue2 } from '@rsbuild/plugin-vue2';
import { pluginSass } from '@rsbuild/plugin-sass';
const { publicVars } = loadEnv({ prefixes: ['VUE_APP_'] });

export default defineConfig({
  plugins: [pluginVue2(), pluginSass({
    sassLoaderOptions: {
      api: 'legacy',
      implementation: require.resolve('sass'),
    },
  })],
  html: {
    template: './public/index.html',
  },
  source: {
    entry: {
      index: './src/main.js',
    },
    alias: {
      '@': path.resolve(__dirname, 'src'),
    },
    define: publicVars,
  },
  tools: {
    bundlerChain: (chain, { CHAIN_ID }) => {
      chain.module
        .rule(CHAIN_ID.RULE.VUE)
        .test(/\.vue$/)
        .use('vue-loader')
        .loader('vue-loader')
        chain.module
        .rule(CHAIN_ID.RULE.SASS)
        .test(/\.scss$/)
        .use('sass-loader')
        .loader('sass-loader');
    },
  },
  server: {
    port: 9527
  }
});`

`<template>
  <div id="app">
    <vue-watermark :text="watermarkText" :opacity="opacity" />
    <router-view />
  </div>
</template>

<script>
import VueWatermark from 'vue-watermark'
import { mapGetters } from 'vuex'

export default {
  name: 'App',
  components: {
    VueWatermark
  },
  mounted() {
  },
  computed: {
    ...mapGetters([
      'user_info',
      'device'
    ]),
    watermarkText() {
      return this.user_info.nickname
    },
    opacity() {
      return 0.1
    }
  }

}
</script>
`

![WechatIMG88058](https://github.com/user-attachments/assets/4a3ac98b-277c-4860-802e-c936f8316735)
![WechatIMG88057](https://github.com/user-attachments/assets/6d060b46-6ac0-4bd0-82e6-9f3274181ea3)

### Reproduce link

in development

### Reproduce Steps

in development

**Comment by tongSir-shuai** [comment]
<img width="447" alt="Snipaste_2024-07-30_18-03-22" src="https://github.com/user-attachments/assets/5f0edf84-b29c-4127-a4d5-041fb07919ff">
<img width="469" alt="Snipaste_2024-07-30_18-03-56" src="https://github.com/user-attachments/assets/e11ce306-44f7-4d10-aeae-b2b5a7b45189">

**Comment by chenjiahan** [comment]
Please provide an reproduction repo

**Comment by tongSir-shuai** [comment]
> Please provide an reproduction repo

https://gitee.com/An_ordinary_day/rsbuild.git

**Comment by tongSir-shuai** [comment]
> Please provide an reproduction repo

https://gitee.com/An_ordinary_day/rsbuild

**Comment by chenjiahan** [comment]
I tried to replace `/deep/` with `:deep()` and it worked:

![image](https://github.com/user-attachments/assets/7f373acb-973e-4c3c-9532-50df54e2440c)

See: https://rsbuild.dev/zh/plugins/list/plugin-vue2#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by tongSir-shuai** [comment]
> I tried to replace `/deep/` with `:deep()` and it worked:
> 
> ![image](https://private-user-images.githubusercontent.com/7237365/354174969-7f373acb-973e-4c3c-9532-50df54e2440c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1Njg2NzcsIm5iZiI6MTcyMjU2ODM3NywicGF0aCI6Ii83MjM3MzY1LzM1NDE3NDk2OS03ZjM3M2FjYi05NzNlLTRjM2MtOTUzMi01MGRmNTRlMjQ0MGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDJUMDMxMjU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDk5Mjg1ZWI5N2JjMWQxMmY4MjcxNjJjYWMxNjgyNTk0MDQ2MGMwZjY3NGI3ZjBmOGY3ZmJhZjEzMDY4MjIxZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Vz72sPWtq_Ava9_9bAyZi-INitsAe7P_vORr5r0ZZgU)
> 
> See: https://rsbuild.dev/zh/plugins/list/plugin-vue2#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

<img width="1198" alt="image" src="https://github.com/user-attachments/assets/9b4a5727-9573-4620-b290-6ebde989826a">
I deleted /deep/ but still got the error: "Failed to mount component: template or render function not defined". Did you change anywhere else?

**Comment by chenjiahan** [comment]
Can you try to remove `dev.lazyCompilation`?

**Comment by tongSir-shuai** [comment]
> Can you try to remove `dev.lazyCompilation`?

<img width="1299" alt="image" src="https://github.com/user-attachments/assets/459dc4cf-c75f-4ed1-b245-6bf1806e3091">
After deleting it, I still get an error when I run it again

**Comment by tongSir-shuai** [comment]
> Can you try to remove `dev.lazyCompilation`?

Help, can you help me take a look?

**Comment by chenjiahan** [comment]
Yes, the `tools.bundlerChain` should be removed, I forgot to mention that.

**Comment by tongSir-shuai** [comment]
> Clear your `tools.bundlerChain` option, as they are unnecessary.

Big Wig
