### ISSUE TITLE
[Bug]: resourceQuery not work in 

### ISSUE THREAD

**Issue by ouzhou** [web-infra-dev/rsbuild#3070]
### System Info

 System:
    OS: macOS 13.3
    CPU: (10) arm64 Apple M2 Pro
    Memory: 90.48 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    Yarn: 1.22.22 - ~/npm_global/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
    pnpm: 8.6.3 - ~/npm_global/bin/pnpm
    bun: 1.1.4 - ~/npm_global/bin/bun
  Browsers:
    Chrome: 126.0.6478.185
    Edge: 127.0.2651.74
    Safari: 16.4

### Details

I want to import a ts type file to use as a string, to inject typing to monaco editor

The following code will report an error

i have tried enforce:'pre' and config.module!.noParse = /myType.ts/;
not work

```
// myType.ts
export type a = string;
```

```
// App.tsx
import str from "./myType.ts?raw";

console.log(str);

export default () => {
  return <div>{str}</div>;
};
```

```
// rsbuild.config.ts
import { defineConfig } from "@rsbuild/core";
import { pluginReact } from "@rsbuild/plugin-react";

export default defineConfig({
  plugins: [pluginReact()],
  tools: {
    rspack: (config, { addRules }) => {
      addRules({
        resourceQuery: /raw/,
        type: "asset/source",
      });
    },
  },
});
```

### Reproduce Steps

just run code

**Comment by xc2** [comment]
I'm transfering this issue to [rsbuild](https://github.com/web-infra-dev/rsbuild) as it pertains to rsbuild.

I'm closing this issue as won't fix because it appears to be usage question, a suggestion has been provided and `resourceQuery` is actually working.

Please feel free to continue this discussion if you have any further question on it.

--

BTW, `addRules` should be documented more detailed as it is actually prepending rules to the rule list.

**Comment by ouzhou** [comment]
![image](https://github.com/user-attachments/assets/4dabf95c-203f-4872-97f2-4f9478397979)

I don't think this is a document issue
Even when your method is applied, the result is still incorrect
@xc2 @chenjiahan

**Comment by chenjiahan** [comment]
If you want to get the TypeScript source code instead of the transformed JavaScript code, you should exclude the assets with `?raw` from the Rsbuild built-in TypeScript transformation rules.

```js
export default defineConfig({
  tools: {
    rspack: {
      module: {
        rules: [
          {
            resourceQuery: /raw/,
            type: 'asset/source',
          },
        ],
      },
    },
    bundlerChain(chain, { CHAIN_ID }) {
      chain.module.rule(CHAIN_ID.RULE.JS).resourceQuery({
        not: /raw/,
      });
    },
  },
});
```

**Comment by ouzhou** [comment]
ok 
by the way,  vite or webpack can easily use `?raw` No additional exclusion configuration is required

**Comment by chenjiahan** [comment]
I never knew that webpack supported this, can you provide some references?

**Comment by ouzhou** [comment]
https://stackblitz.com/edit/vitejs-vite-z7xhqz?file=src%2FApp.tsx

**Comment by ouzhou** [comment]
webpack demo

https://stackblitz.com/edit/vitejs-vite-3kfqqu?file=src%2FmyType.ts

**Comment by ouzhou** [comment]
seems incorrect
![image](https://github.com/user-attachments/assets/7f38b371-89e9-430e-b8cf-c9e834a67705)


> If you want to get the TypeScript source code instead of the transformed JavaScript code, you should exclude the assets with `?raw` from the Rsbuild built-in TypeScript transformation rules.
> 
> ```js
> export default defineConfig({
>   tools: {
>     rspack: {
>       module: {
>         rules: [
>           {
>             resourceQuery: /raw/,
>             type: 'asset/source',
>           },
>         ],
>       },
>     },
>     bundlerChain(chain, { CHAIN_ID }) {
>       // add this line
>       chain.module.rule(CHAIN_ID.RULE.JS).resourceQuery({ not: /raw/ });
>     },
>   },
> });
> ```

**Comment by xc2** [comment]
please try `import str from "!./myType.ts?raw";`

**Comment by ouzhou** [comment]
You are right , it works
[webpack-enforce](https://webpack.js.org/configuration/module/#ruleenforce)

So any plan to use `import str from "./myType.ts?raw";` instands of ` import str from "!./myType.ts?raw" ;` make migrating to rsbuild easily from webpack ?

> Ecosystem compatibility: Rsbuild is compatible with most webpack plugins and all Rspack plugins, while Vite is compatible with Rollup plugins. If you're currently using more plugins and loaders from the webpack ecosystem, migrating to Rsbuild would be relatively easy.

**Comment by chenjiahan** [comment]
You may have confused a concept. CRACO and webpack are not tools of the same level. The demo you provided above is based on CRACO, not webpack.

Rspack / Rsbuild is compatible with webpack, not all upper-level tools based on webpack. We cannot make Rsbuild compatible with the behaviors of all different tools.

As for the raw feature, we plan to implement it in Rsbuild, but it significantly impacts the Rspack configuration within Rsbuild. We are still evaluating it.

**Comment by ouzhou** [comment]
Yes, craco is not the same level
 I'll try using only webpack to see if it supports raw feature like craco way

**Comment by ouzhou** [comment]
```
export default defineConfig({
  tools: {
    rspack: {
      module: {
        rules: [
          {
            resourceQuery: /raw/,
            type: 'asset/source',
          },
        ],
      },
    }
  },
});
```

From the document, it seems that as long as I configure it this way, no matter what file it is, as long as it is? The endings of raw should all be strings, and disabling the loader through hacking doesn't seem intuitive

https://github.com/web-infra-dev/rspack/blob/9e235b08ee7654df72e3a1c1caf6fe3d5eae1db0/packages/rspack-test-tools/tests/configCases/module/rspack-issue-2791/index.js

https://github.com/web-infra-dev/rspack/issues/2791

**Comment by ouzhou** [comment]
![image](https://github.com/user-attachments/assets/1fbe3ab9-c4d0-4eeb-ba3f-97bb6a258c78)
According to the documentation of rspack, after configuring it here, it should return a string
