### ISSUE TITLE
[Feature]: Support `<port>` placeholder in `dev.assetPrefix`

### ISSUE THREAD

**Issue by colinaaa** [web-infra-dev/rsbuild#3094]
### What problem does this feature solve?

We want to specify a custom `dev.assetPrefix` with hostname and port. But when the port is occupied, Rsbuild will automatically bump up the port by default, making the `dev.assetPrefix` incorrect.

It would be great if the `dev.assetPrefix` supports using the `<port>` placeholder.

BTW, I'm not sure if `output.assetPrefix` needs this.

### What does the proposed API look like?

The same as `dev.client.port` and `server.open`:

```js
// rsbuild.config.js
export default {
  dev: {
    assetPrefix: 'http://hostname:<port>/',
    client: {
      hostname: 'hostname',
      port: '<port>',
    },
  },
  server: {
    open: 'http://hostname:<port>/',
  },
}

**Comment by chenjiahan** [comment]
PR welcome 😄
