### ISSUE TITLE
[Feature]: How to reuse `createSnapshotSerializer` in test helper

### ISSUE THREAD

**Issue by fi3ework** [web-infra-dev/rsbuild#3099]
### What problem does this feature solve?

The `createSnapshotSerializer` (https://github.com/web-infra-dev/rsbuild/blob/main/scripts/test-helper/src/index.ts#L17C17-L50) is battle tested and not coupled with Rsbuild. If possible, I could help to extract it to a new package and put it under `rspack-contrib` organization, and reuse it in Rslib 🤗.

### What does the proposed API look like?

N/A.

**Comment by SoonIter** [comment]
I'm curious if this serializer can be used by both vitest and jest. 
https://github.com/web-infra-dev/rspack/issues/7156

Rspack also needs this

**Comment by fi3ework** [comment]
I used to use a Jest serializer plugin in Vitest in other project. "Jest as a spec, Vitest as a implementaion", I believe so.

**Comment by chenjiahan** [comment]
LGTM 👍

**Comment by fi3ework** [comment]
Any suggestion for the package name? `rsserializer`? 🤣

**Comment by chenjiahan** [comment]
Maybe it doesn't need the rs keyword, just use anything you want 😄
