### ISSUE TITLE
[Bug]: Enabling performance.profile in development mode will cause infinite compilation loop

### ISSUE THREAD

**Issue by itmanyong** [web-infra-dev/rsbuild#3116]
### Version

```sh
win10 pro x64
@rsbuild/core 1.0.1-beta.8
```

### Details

开发环境下 performance.profile=true 生成的产物 dist/stats.json 会导致一直循环编译,貌似监听了很多不属于预期之内的目录或文件,是否可以进行配置或减少这类非源码非框架配置类文件
![image](https://github.com/user-attachments/assets/c244a747-0a3d-4e0e-9f12-4f622b7fabb4)

### Reproduce link

无

### Reproduce Steps

1.初始化一个rsbuild项目模板
2.配置 performance.profile 的值为true
3.启动项目
4.修改源码文件触发热更新

**Comment by chenjiahan** [comment]
I can not reproduce this issue, can you provide a reproduction repo?

![image](https://github.com/user-attachments/assets/100700cf-783a-4123-bcea-435a4d84d2a6)
