### ISSUE TITLE
[Bug]: `Choose a Framework` selector not clearing correctly.

### ISSUE THREAD

**Issue by ALEXWARELLC** [web-infra-dev/rsbuild#3122]
### Version

```sh
System:
    OS: Linux 5.15 Freedesktop SDK 23.08 (Flatpak runtime)
    CPU: (2) x64 Intel(R) Celeron(R) CPU  N2820  @ 2.13GHz
    Memory: 641.93 MB / 3.71 GB
    Container: Yes
    Shell: 5.2.26 - /bin/sh
```

### Details

When running `npm create rsbuild@latest`, on the step of choosing a framework, _on Visual Studio Code at least_ the choose a framework menu doesn't clear and redraw but instead redraws without clearing first causing a very confusing look.

![rspack_error](https://github.com/user-attachments/assets/9b733ca9-97b5-460a-aef8-bc245b649541)

### Reproduce link

N/A

### Reproduce Steps

1. execute `npm create rsbuild@latest`
2. Go to Pick A Framework
3. See not so fun time ahead.

**Comment by ALEXWARELLC** [comment]
UPDATE: This seems to happen randomly so take this issue with a grain of salt :)

**Comment by chenjiahan** [comment]
Thanks for your feedback, sadly I can't reproduce this issue.

Rsbuild uses [clack](https://github.com/bombshell-dev/clack) to print prompts. I have searched the clack issues and cannot find any related issues. If this problem still bothers you, you can try to submit an issue to clack ❤️
