### ISSUE TITLE
[Feature]: Hope to add support for node-sass

### ISSUE THREAD

**Issue by k4281613** [web-infra-dev/rsbuild#3133]
### What problem does this feature solve?

以下是优化后的GitHub issue格式：

---

### 问题描述

在使用 **rsbuild 0.65** 时，我希望将 SASS 配置替换为 **node-sass**。目前，Element UI 使用的是 **node-sass**，但 rsbuild 默认配置为 **sass**，并且在文档中没有找到关于 **node-sass** 的配置说明。

### 预期行为

希望能够配置 rsbuild 使用 **node-sass**，以避免在使用 Element UI 时出现偶发的图标乱码问题。

### 实际行为

- 使用默认的 **sass** 配置时，Element UI 的图标偶尔出现乱码。
- 没有找到关于如何将 SASS 配置为 **node-sass** 的相关文档或示例。
- 默认sass配置和elemen-ui的node-sass不兼容，icon出现乱码，编译的问题。
- 
![image](https://github.com/user-attachments/assets/dc90975f-3de8-4903-aa75-88ca073518c3)

### 环境信息

- **rsbuild 版本**: 0.65
- **Element UI 版本**: 2.15.14 (vue2)

### 其他信息

如果有任何解决方法或配置示例，请提供指导。谢谢！

### What does the proposed API look like?

增加node-sass的支持

**Comment by chenjiahan** [comment]
Here is an example: https://rsbuild.dev/zh/plugins/list/plugin-sass#%E4%BF%AE%E6%94%B9-sass-%E7%89%88%E6%9C%AC
