### ISSUE TITLE
[Bug]: html.meta is not working

### ISSUE THREAD

**Issue by zoolsher** [web-infra-dev/rsbuild#315]
### Version

```sh
System:
  OS: macOS 14.0
  CPU: (10) arm64 Apple M1 Pro
  Memory: 59.56 MB / 16.00 GB
  Shell: 5.9 - /bin/zsh
Browsers:
  Chrome: 119.0.6045.105
  Edge: 117.0.2045.47
  Safari: 17.0
npmPackages:
  @rsbuild/core: ^0.0.12 => 0.0.12
  @rsbuild/plugin-react: ^0.0.12 => 0.0.12
```

### Details

I'm working on my project and adding a meta to the html file so it can be displayed as twitter card on the twitter platform. To achieve this I need to add some `<meta property="og:url" content="https://rspack.dev"/>` you can also see from [here](https://ogp.me/).

According to the [website](https://rsbuild.dev/config/options/html.html#htmlmeta) I added this to my config file.

```js
import { defineConfig } from "@rsbuild/core";
import { pluginReact } from "@rsbuild/plugin-react";

export default defineConfig({
  plugins: [pluginReact()],
  html: {
    meta: {
      foo: "bar",
    },
    template: "./src/index.html",
  },
});
```

but I can't find `foo` or `bar` in my output fiiles.

I made a reproduce repo for your convenience. https://github.com/zoolsher/rsbuild-meta-repro/blob/main/rsbuild.config.ts

### Reproduce link

https://github.com/zoolsher/rsbuild-meta-repro/blob/main/rsbuild.config.ts

### Reproduce Steps

1. pnpm install
2. pnpm run build
3. you can't find `foo` in the html file

**Comment by zoolsher** [comment]
Why did rsbuild convert the meta config object to string? https://github.com/web-infra-dev/rsbuild/blob/main/packages/core/src/utils/generateMetaTags.ts#L67-L69

**Comment by chenjiahan** [comment]
This is a bug of Rsbuild v0.0.12, the current implementation relies on template params, for example:

```html
<!DOCTYPE html>
<html>
<head>
  <%= meta %>
  <title><%= title %></title>
</head>
<body>
  <div id="<%= mountId %>"></div>
</body>
</html>
```

So the `html.meta` option will be broken if the template does not contain a `<%= meta %>`, we should refactor the implementation and find a better way.

**Comment by chenjiahan** [comment]
Fixed
