### ISSUE TITLE
[Bug]: An error is occurs when the third-party package is imported from the specific path

### ISSUE THREAD

**Issue by witsaint** [web-infra-dev/rsbuild#3160]
### Version

```sh
System: MacOS 13.4 
Browers: Chrome 126.0.6478.183 arm64
env: "@rsbuild/core": "1.0.1-beta.10",
    "@rsbuild/plugin-react": "1.0.1-beta.10",
```

### Details

An error occurs when you import the third-party package from the specific path. However, the compiled code can run properly after the third-party package resources are stored in node_module

 [code path](https://github.com/witsaint/rsbuild-issue/blob/master/src/App.tsx)
![image](https://github.com/user-attachments/assets/e9bd3db1-f6fc-452c-bfc8-e4927c0b0ac8)

the err
![image](https://github.com/user-attachments/assets/be459299-5964-43c6-904d-bf97f8be8210)

Print code in third-party dependent
path：node_modules/@svgdots/svg.js/src/main.js
![image](https://github.com/user-attachments/assets/b8ad0889-30c7-472a-9ea9-cc3160bcdedd)

Web is fine
![image](https://github.com/user-attachments/assets/85bad761-d6e0-4a1b-90a8-7f7554b95247)

### Reproduce link

https://github.com/witsaint/rsbuild-issue/tree/master

### Reproduce Steps

1: Clone the project

2: yarn install or pnpm install

3: open web page ,you can find the err message in devtool

4: Edit node_modules/@svgdots/svg.js/src/main file , 

5: Web page is fine

**Comment by chenjiahan** [comment]
This is usually due to modules having circular references in their source code.

You should import `dist/svg.esm.js` as this is the bundled code for package users.

**Comment by Fitz6** [comment]
It appears to be a code generation issue with rspack.

When using rspack:

```javascript
const SVG = _utils_adopter_js__WEBPACK_IMPORTED_MODULE_7__.makeInstance

// ↓ Missing a semicolon
    (0,_utils_adopter_js__WEBPACK_IMPORTED_MODULE_7__.extend)([_elements_Svg_js__WEBPACK_IMPORTED_MODULE_37__["default"], _elements_Symbol_js__WEBPACK_IMPORTED_MODULE_38__["default"], _elements_Image_js__WEBPACK_IMPORTED_MODULE_19__["default"], _elements_Pattern_js__WEBPACK_IMPORTED_MODULE_27__["default"], _elements_Marker_js__WEBPACK_IMPORTED_MODULE_22__["default"]], (0,_utils_methods_js__WEBPACK_IMPORTED_MODULE_8__.getMethodsFor)('viewbox'))
```
and we will encounter an error:
```
TypeError: _utils_adopter_js__WEBPACK_IMPORTED_MODULE_7__.makeInstance(...) is not a function
```


When using webpack, everything works fine.

**Comment by chenjiahan** [comment]
Get, we can track the progress in https://github.com/web-infra-dev/rspack/issues/7527
