### ISSUE TITLE
[Bug]: Sass deprecation warnings display even though `quietDeps` is set to true

### ISSUE THREAD

**Issue by Atmos4** [web-infra-dev/rsbuild#3201]
### Version

```sh
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 14.09 GB / 31.68 GB
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @rsbuild/core: 1.0.1-beta.11 => 1.0.1-beta.11
    @rsbuild/plugin-react: 1.0.1-beta.11 => 1.0.1-beta.11
    @rsbuild/plugin-sass: 1.0.1-beta.11 => 1.0.1-beta.11
    @rsbuild/plugin-type-check: 1.0.1-beta.11 => 1.0.1-beta.11
```

### Details

Using `@rsbuild/plugin-sass`, deprecation warnings started showing up when upgrading from `alpha.9` to `beta.11`.

![image](https://github.com/user-attachments/assets/a2ad51e9-37db-4010-91e3-76bf742272c9)

### Reproduce link

https://www.google.com/search?q=no+need+for+a+url+the+issue+is+self+explanatory

### Reproduce Steps

- use Sass plugin with quietDeps
- use a deprecated syntax like https://sass-lang.com/documentation/breaking-changes/mixed-decls/
- see a warning in the console

_Note: maybe this is unrelated to rsbuild and just something that the Sass team really want to push_

**Comment by chenjiahan** [comment]
Yes, this is unrelated to Rsbuild.

https://github.com/element-plus/element-plus/issues/17487
https://sass-lang.com/documentation/breaking-changes/mixed-decls/

**Comment by Atmos4** [comment]
Thanks for responding 🎉 keep up the good work

**Comment by MattGXT** [comment]
it's not a bug.
try import sass and add these to config:
```
import sass from 'sass';

pluginSass({
    sassLoaderOptions: {
        sassOptions: {
            logger: sass.Logger.silent
        }
    }
})
```
