### ISSUE TITLE
[Bug]: There is a chance that the compilation will get stuck

### ISSUE THREAD

**Issue by wengjiacheng** [web-infra-dev/rsbuild#3229]
### Version

```sh
System:
    OS: macOS 13.3.1
    CPU: 2.5 GHz Intel Core i7
    Memory: 16 GB 2133 MHz LPDDR3
  Browsers:
    Chrome:  120.0.6099.109
  npmPackages:
       "@rsbuild/core": "^0.7.3",
    "@rsbuild/plugin-babel": "^0.7.3",
    "@rsbuild/plugin-css-minimizer": "^0.7.3",
    "@rsbuild/plugin-less": "^0.7.3",
    "@rsbuild/plugin-vue2": "^0.7.3",
    "@rsbuild/plugin-vue2-jsx": "^0.7.3",
    "@rsdoctor/rspack-plugin": "^0.3.10",
```

### Details

在连续编译的时候会卡住，但是不是每次有概率会卡停止执行，卡在/Users/jxrt/Desktop/cbmc-corp-static-v2/node_modules/@rspack/core/dist/builtin-plugin/css-extract/loader.js!commonjs这里，把配置设置成样式内敛，编译就没问题了
感觉上像是抽离css文件时候出错了，由于不好复现，所以暂时提供不了demo

### Reproduce link

NONE

### Reproduce Steps

NONE

**Comment by chenjiahan** [comment]
Can you try the Rsbuild 1.0.1 beta?

**Comment by wengjiacheng** [comment]
> Can you try the Rsbuild 1.0.1 beta?

试过1.0.1版本的  情况是一样的 ， 但是确实不太好复现出demo

**Comment by chenjiahan** [comment]
If there's no reproduction, it's hard to debug 😂

**Comment by wengjiacheng** [comment]
> If there's no reproduction, it's hard to debug 😂

我尝试复现出demo

**Comment by MattGXT** [comment]
@chenjiahan have same issue here. It's hard to provide a reproduction.
The compilation will get stuck at 64% sometimes. I guess the problem is caused by stylesheets.

**Comment by wengjiacheng** [comment]
> @chenjiahan have same issue here. It's hard to provide a reproduction. The compilation will get stuck at 64% sometimes. I guess the problem is caused by stylesheets.

![1233333](https://github.com/user-attachments/assets/751b57a3-a610-43b9-930d-3243ade38d2f)

**Comment by chenjiahan** [comment]
Sorry, we still need an reproduction

**Comment by wengjiacheng** [comment]
> @chenjiahan have same issue here. It's hard to provide a reproduction. The compilation will get stuck at 64% sometimes. I guess the problem is caused by stylesheets.

Have you configured  pluginBabel({include: /\.(?:jsx|tsx)$/,}), and pluginVue2Jsx()?

**Comment by chenjiahan** [comment]
yes

**Comment by wengjiacheng** [comment]
> Have you configured pluginBabel({include: /.(?:jsx|tsx)$/,}), and pluginVue2Jsx()?

When configuring pluginBabel and adding {include: /.(?:jsx|tsx)$/,}), there may be a problem of freezing. Removing {include: /.(?:jsx|tsx)$/,} will solve the problem
