### ISSUE TITLE
[Feature]: Inline async JS chunks when using `inlineScripts: true`

### ISSUE THREAD

**Issue by zardoy** [web-infra-dev/rsbuild#3240]
### What problem does this feature solve?

Hi! I want to create a single-file HTML file so everything is inline into one HTLM file. As far as I can say everything works good (all assets & styles are inlined without any problems), but not async js chunks. Maybe it's just docs, but the [docs of `inlineScript`](https://rsbuild.dev/config/output/inline-scripts) say:

> Note that, with this option on, the scripts files will no longer be written in dist directory, they will only exist inside the HTML file instead.

Howerver when importing web workers and other modules with `import('...')` it always creates a second JS file along the HTML file like so:

```log
File                                       Size       Gzipped    
  dist/static/js/async/js/588.487dabea.js    0.34 kB    0.23 kB
  dist/index.html                            13.1 kB    4.8 kB
```

### What does the proposed API look like?

I cant say anything of enabling this by default, but there should be a way to actually inline all the scripts into HTML (this feature is actually useful). For example add a new flag/option config into `inlineScripts` object config.
```[tasklist]
### Tasks
```

**Comment by zardoy** [comment]
About the web worker part: it seems rsbuild doesn't support bundling it. I'm coming from Vite which supports these imports:

```

**Comment by chenjiahan** [comment]
Rspack provides a [module.parser.javascript.dynamicImportMode](https://rspack.dev/config/module#moduleparserjavascriptdynamicimportmode) option to avoid generating async chunks of dynamic imports:

```js
export default {
  output: {
    inlineScripts: true,
  },
  tools: {
    rspack: {
      module: {
        parser: {
          javascript: {
            dynamicImportMode: 'eager',
          },
        },
      },
    },
  },
};
```

**Comment by zardoy** [comment]
Thanks a lot for a quick response and improving the docs by a lot!
I'm still struggling with inlining webworkers into HTML (and I think it's worth mentioning webworker part in the Vite migration guide), but that's the matter of another issue.

**Comment by chenjiahan** [comment]
Yeah webworker inlining is another issue and we should provide a guide for it
