### ISSUE TITLE
[Bug]: rsbuild injectStyles: true and chunkSplit: all-in-one will inject lots \n and blank space with cssnano useless

### ISSUE THREAD

**Issue by sbyps** [web-infra-dev/rsbuild#3247]
### Version

```sh
System:
    OS: macOS 14.6.1
    CPU: (11) arm64 Apple M3 Pro
    Memory: 50.20 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 127.0.6533.120
    Safari: 17.6
  npmPackages:
    @rsbuild/core: ^1.0.1-beta.14 => 1.0.1-beta.14 
    @rsbuild/plugin-check-syntax: ^1.0.1 => 1.0.1 
    @rsbuild/plugin-sass: ^1.0.1-beta.14 => 1.0.1-beta.14 
    @rsbuild/plugin-vue2: ^1.0.1-beta.14 => 1.0.1-beta.14
```

### Details

following the official docs: https://rsbuild.dev/zh/config/output/inject-styles#%E4%BD%BF%E7%94%A8%E5%9C%BA%E6%99%AF
then set config like
injectStyles: true,
chunkSplit: all-in-one

will inject lots \n and blank space with cssnano useless in js files

### Reproduce link

https://github.com/sbyps/rspack-demo

### Reproduce Steps

npm run build

cat the js files, search "\n ", will find lots of it
<img width="1523" alt="image" src="https://github.com/user-attachments/assets/bc19368a-f47a-4fc4-af3d-84543e3232b6">

**Comment by sbyps** [comment]
@chenjiahan this PR resolves some case with \n; but we can found lots of \n in sourcemap and js files;
rsbuild version: 1.0.1-rc.4
https://github.com/sbyps/rspack-demo
<img width="911" alt="image" src="https://github.com/user-attachments/assets/1b3d2875-21c7-4b5a-94ba-73e3b03c8479">
<img width="919" alt="image" src="https://github.com/user-attachments/assets/86c3a497-9589-4b2e-bb5c-67c5e22441fb">

**Comment by chenjiahan** [comment]
This is as expected, the source map contains the source code

**Comment by sbyps** [comment]
> This is as expected, the source map contains the source code

![image](https://github.com/user-attachments/assets/dd9b57ec-4799-4ae5-be45-ee0bc031318b)
this image is not sourcemap but production file, also has \n

**Comment by chenjiahan** [comment]
Can you provide a reproduction?

**Comment by sbyps** [comment]
> Can you provide a reproduction?

https://github.com/sbyps/rspack-demo/tree/main

pnpm run build

cat dist/504.js  dist/record-portrait.js

**Comment by chenjiahan** [comment]
Fixed in https://github.com/web-infra-dev/rsbuild/releases/tag/v1.0.1-rc.5, can you have a try?

**Comment by sbyps** [comment]
> Fixed in https://github.com/web-infra-dev/rsbuild/releases/tag/v1.0.1-rc.5, can you have a try?

after bump rc.5, the css files don't have \n any more, but js files has \n as same;

https://github.com/sbyps/rspack-demo/tree/main

pnpm run build

cat dist/record-portrait.js

**Comment by chenjiahan** [comment]
You mean this one?

![image](https://github.com/user-attachments/assets/baaad361-7c65-4ca6-b380-eceb2ab1eb36)

It is a string, not CSS.

**Comment by sbyps** [comment]
> You mean this one?
> 
> ![image](https://private-user-images.githubusercontent.com/7237365/366335288-baaad361-7c65-4ca6-b380-eceb2ab1eb36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyODI4NTUsIm5iZiI6MTcyNjI4MjU1NSwicGF0aCI6Ii83MjM3MzY1LzM2NjMzNTI4OC1iYWFhZDM2MS03YzY1LTRjYTYtYjM4MC1lY2ViMmFiMWViMzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTRUMDI1NTU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGVjYTBiZjVmMjdlY2QzMTlhNThiYzhkYzczODQyZWUwZmI1MmVjMTE5MWZhMTQyNGIwNDY4MmU1NTU2YzM0OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LtHdOcNUgOuuVlrjCEJc-qGIb8N-YtyJKUO3f4JZdog)
> 
> It is a string, not CSS.

it's vue template expression; should these \n &nbsp; be minified?
<img width="395" alt="image" src="https://github.com/user-attachments/assets/9362d24d-b17e-480c-b853-d68c99406a0a">

@chenjiahan

**Comment by chenjiahan** [comment]
I think it's unrelated to Rsbuild
