### ISSUE TITLE
[Bug]:  sentry sourcemap can't locate the right position in sourcemap in vue error stack

### ISSUE THREAD

**Issue by sbyps** [web-infra-dev/rsbuild#3335]
### Version

```sh
System:
    OS: macOS 14.6.1
    CPU: (11) arm64 Apple M3 Pro
    Memory: 39.80 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 128.0.6613.114
    Safari: 17.6
  npmPackages:
    @rsbuild/core: ^1.0.1-rc.0 => 1.0.1-rc.0 
    @rsbuild/plugin-check-syntax: ^1.0.1 => 1.0.1 
    @rsbuild/plugin-sass: ^1.0.1-rc.0 => 1.0.1-rc.0 
    @rsbuild/plugin-vue2: ^1.0.1-rc.0 => 1.0.1
```

### Details

vue2.7  rsbuild 配置 output.sourceMap: 'source-map'
当 vue 上下文中发生报错时，sentry sourcemap 不能定位到准确位置；js jsx ts tsx 中报错可以定位到准确位置；使用 vue-cli 的也可以定位到准确位置;
使用https://sourcemaps.io/进行检查含有vue 代码的 sourcemap提示不匹配，检查 js 如 lib-axios、lib-vue 的 sourcemap 能够匹配；
其他的一个报错：
<img width="775" alt="image" src="https://github.com/user-attachments/assets/806a1ca3-1eee-47e0-9b06-f494f63d71c7">
<img width="889" alt="image" src="https://github.com/user-attachments/assets/c3250b73-9afe-4559-bdc2-0f2420e1af59">

### Reproduce link

https://github.com/sbyps/rspack-demo

### Reproduce Steps

npm run build 
上传 sourcemap 到 sentry 服务器
访问网页、发现报错，查看 sentry issue，发现报错信息不能匹配
使用https://sourcemaps.io/进行检查record-replay.js.map也提示不匹配；
检查 lib-vue.js.map能够匹配

**Comment by chenjiahan** [comment]
I tried a Vue 2 demo and the source map worked as expected:

![image](https://github.com/user-attachments/assets/0085cc50-60e5-4097-8b1f-3fc1c278d943)

I have also tried the [demo](https://github.com/sbyps/rspack-demo), uploading the source map to https://evanw.github.io/source-map-visualization/, and cannot find an invalid source map:

![image](https://github.com/user-attachments/assets/52dae18c-dfe0-4df8-bf0f-d3e3962e17ee)

**Comment by sbyps** [comment]
@chenjiahan this case is for error stack matches invalid location in sourcemap, can be found in sourcemap;
in demo, throw an error in vue created, but it canot matches sourcemap in right location lines

**Comment by chenjiahan** [comment]
I tried to throw an error in the Vue `created()` and Chrome devtools can parse the source map as expected in both development and production mode:

![image](https://github.com/user-attachments/assets/0da81dca-ef9b-4daf-ae19-6f3248a93e31)

![image](https://github.com/user-attachments/assets/2deff669-425f-47f3-90c8-ca753e307cde)

**Comment by yuantongkang** [comment]
beta 版本不行，试了最新的 rc-4 可以了
