### ISSUE TITLE
[Bug]: Potential Typo on the Rsbuild website

### ISSUE THREAD

**Issue by aryan1306** [web-infra-dev/rsbuild#3363]
### Version

```sh
System:
    OS: macOS 14.6.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 447.89 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 128.0.6613.114
    Safari: 17.6
```

### Details

<img width="1478" alt="Screenshot 2024-09-03 at 2 27 38 PM" src="https://github.com/user-attachments/assets/ec453858-0760-45dd-9981-a6c73f5dc52e">
Should "EasyToConfigure" have spaces in between or is it intentional? if it's a bug i would be happy to fix it.

### Reproduce link

https://rsbuild.dev/

### Reproduce Steps

go to https://rsbuild.dev/ and scroll down to the cards that highlight features of rsbuild

**Comment by chenjiahan** [comment]
This is a typo, PR welcome 😄

**Comment by aryan1306** [comment]
Hi there, I have created a PR for this.

**Comment by chenjiahan** [comment]
👍
