### ISSUE TITLE
[Bug]: Static resources in the public directory cannot be accessed normally in the source code

### ISSUE THREAD

**Issue by itmanyong** [web-infra-dev/rsbuild#3374]
### Version

```sh
System:
    OS: Windows 10 10.0.19045
    CPU: (24) x64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
    Memory: 42.60 GB / 63.91 GB
  Browsers:
    Edge: Chromium (128.0.2739.54)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    @rsbuild/core: 1.0.1-rc.3 => 1.0.1-rc.3
    @rsbuild/plugin-assets-retry: 1.0.1-rc.3 => 1.0.1-rc.3
    @rsbuild/plugin-babel: 1.0.1-rc.3 => 1.0.1-rc.3
    @rsbuild/plugin-image-compress: ^1.0.2 => 1.0.2
    @rsbuild/plugin-sass: 1.0.1-rc.3 => 1.0.1-rc.3
    @rsbuild/plugin-vue: 1.0.1-rc.3 => 1.0.1-rc.3
    @rsbuild/plugin-vue-jsx: 1.0.1-rc.3 => 1.0.1-rc.3
```

### Details

在目录`/public/assets/fonts/`下存放一个`font.woff2`文件
源代码css中注册该字体文件，css属性`src:url(/assets/fonts/font.woff2)`无法正常访问
![image](https://github.com/user-attachments/assets/40ea7744-c9f4-40e5-9b0f-b14b8001af00)
![image](https://github.com/user-attachments/assets/47c83bb1-6c53-4e5d-ad40-b5dbf113a6c5)

### Reproduce link

无

### Reproduce Steps

无

**Comment by chenjiahan** [comment]
Similar to this issue: https://github.com/facebook/create-react-app/issues/9937

We will try to provide a solution for this

**Comment by chenjiahan** [comment]
A common practice is to put the image in the `src` folder and use a relative path to reference it:

![image](https://github.com/user-attachments/assets/a86581af-9ebe-420b-8a64-e304bebe884b)

**Comment by itmanyong** [comment]
> A common practice is to put the image in the `src` folder and use a relative path to reference it:
> 
> ![image](https://private-user-images.githubusercontent.com/7237365/364609956-a86581af-9ebe-420b-8a64-e304bebe884b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MTY4ODMsIm5iZiI6MTcyNTUxNjU4MywicGF0aCI6Ii83MjM3MzY1LzM2NDYwOTk1Ni1hODY1ODFhZi05ZWJlLTQyMGItOGE2NC1lMzA0YmViZTg4NGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDVUMDYwOTQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWRmMzM5NGZkZTQ3MzMyM2I1ODNmYzBlODU0ODc1OWU1Nzc5YzBkNWFhZjhmODdiY2I4ZWZjZmY4YjhhZmYyNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MUQJsm6Vgq3pJpXv5J2I-MR5xUwZqUS_aDqXQVDihZo)

It seems that in this case, static resources in non-source code can only be obtained by way of request, and cannot be handled by internal parsing

**Comment by jackchoumine** [comment]
> A common practice is to put the image in the `src` folder and use a relative path to reference it:
> 
> ![image](https://private-user-images.githubusercontent.com/7237365/364609956-a86581af-9ebe-420b-8a64-e304bebe884b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MzIyNTEsIm5iZiI6MTcyNTkzMTk1MSwicGF0aCI6Ii83MjM3MzY1LzM2NDYwOTk1Ni1hODY1ODFhZi05ZWJlLTQyMGItOGE2NC1lMzA0YmViZTg4NGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTBUMDEzMjMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWE1NDIyMzUwNmMxOWQ1NDM2MjBiYzllNDdmZGZhOTVmZmUxYjEwOTdiYTMxODFlMDU5MDdiZjA4OTNkMzFmMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.K2CD0W9skqHWvD-0JCYE8ax7CaSlCt5G23i0aXFYrvo)

rsbuild/core@^0.4.6 is work well but ^1.0.1-rc.5 can not work.

This paractice is bad. And what's more it is a barrier for migration from vite.
