### ISSUE TITLE
[Feature]: Support for svelte５

### ISSUE THREAD

**Issue by 6643** [web-infra-dev/rsbuild#3399]
### What problem does this feature solve?

支持svelte５

### What does the proposed API look like?

支持svelte５

**Comment by chenjiahan** [comment]
Rsbuild v1.0.1 provides basic support for Svelte 5, see: https://github.com/web-infra-dev/rsbuild/pull/3403

Since Svelte 5 has not yet released a stable version, Rsbuild's support for it is currently experimental. If you encounter any problems, feel free to submit an new issue.
