### ISSUE TITLE
[Bug]: incorrect npm command in docs

### ISSUE THREAD

**Issue by CamelJohn** [web-infra-dev/rsbuild#3401]
### Version

```sh
Latest
```

### Details

In the docs page, when looking at migration from vite to rsbuild seems like the commands for removing and vite dependencies and adding rsbuild dependencies are for yarn. You don't run add or remove with npm, as far as I know.

### Reproduce link

Yuor docs

### Reproduce Steps

Go to your docs page.

**Comment by chenjiahan** [comment]
npm CLI supports add and remove too, they are aliases.

https://docs.npmjs.com/cli/v10/commands/npm-install#synopsis
