### ISSUE TITLE
[Bug]: modifying `resolve.extensions` in Rspack config object doesn't work

### ISSUE THREAD

**Issue by mdrobny** [web-infra-dev/rsbuild#3410]
### Version

```sh
System:
  OS: macOS 14.6.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 269.59 MB / 32.00 GB
  Shell: 5.9 - /bin/zsh
Browsers:
  Chrome: 128.0.6613.120
  Safari: 17.6
npmPackages:
  @rsbuild/core: workspace:* => 1.0.1-rc.5 
  @rsbuild/plugin-react: workspace:* => 1.0.1-rc.5
```

### Details

when using Rsbuild, I noticed that modifying `resolve.extensions`property in Rspack config object doesn't work.
Luckily it works when modifying the Rspack config with a function so I it's possible to workaround the problem currently.
But I expected to achieve it by just modifying the object like the [docs](https://rsbuild.dev/guide/basic/configure-rspack#modify-config-object)

### Reproduce link

https://codepen.io/mdrobny/pen/KKjJVwN

### Reproduce Steps

1. try to modify `resolve.extensions` in [example rsbuild.config.ts](https://github.com/web-infra-dev/rsbuild/blob/main/examples/react/rsbuild.config.ts) like this 
```ts
export default defineConfig({
  plugins: [pluginReact()],
  tools: {
    rspack: {
      resolve: {
        extensions: ['.jsx', '.tsx', '.ts', '.js'],
      },
    }
  }
});
```
2. add `App.jsx` component in `src` folder
```jsx
const App = () =>  <div>App JSX</div>

export default App;
```
3. run `rsbuild dev`
4. open website and you can still see content from `App.tsx`. Rsbuild should use `App.jsx` file because `jsx` extension has priority over `tsx` but it doesn't
   - <img width="557" alt="image" src="https://github.com/user-attachments/assets/9ba956f7-a5a5-4fe5-80ac-6be2e9520347">

6. Change rsbuild.config.ts to
```ts
export default defineConfig({
  plugins: [pluginReact()],
  tools: {
    rspack: config => {
      config.resolve ||= {};
      config.resolve.extensions = ['.jsx', '.tsx', '.ts', '.js'];
    }
  }
});
``` 
7. run `rsbuild dev`
8. open website and now content is `App JSX` so it worked
   - <img width="275" alt="image" src="https://github.com/user-attachments/assets/11cd9323-2b48-4eb4-842e-4eb149355e25">

**Comment by chenjiahan** [comment]
Rsbuild uses [webpack-merge](https://github.com/survivejs/webpack-merge) to merge Rspack config objects, so the `extensions` array is merged instead of overwritten.

![image](https://github.com/user-attachments/assets/70cefc99-574e-4c6f-8290-86b9dcde2ea8)

https://rsbuild.dev/config/tools/rspack

**Comment by mdrobny** [comment]
@chenjiahan thanks for mentioning this in the docs 💪 it will save people some trouble.

Great job with rsbuild BTW 🚀
