### ISSUE TITLE
[Bug]: Conflict with bits-ui only in dev mode

### ISSUE THREAD

**Issue by melMass** [web-infra-dev/rsbuild#3411]
### Version

```sh
System:
    OS: Windows 11 10.0.22631
    CPU: (24) x64 12th Gen Intel(R) Core(TM) i9-12900K
    Memory: 100.58 GB / 127.75 GB
Browsers:
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.22621.3527
npmPackages:
    @rsbuild/core: 1.0.1-rc.5 => 1.0.1-rc.5
    @rsbuild/plugin-svelte: 1.0.1-rc.5 => 1.0.1-rc.5
```

### Details

I have this client error only in the dev server when importing bits-ui, builds work fine:

`Uncaught TypeError: _callbacks_js__WEBPACK_IMPORTED_MODULE_16__ is undefined` 

![image](https://github.com/user-attachments/assets/6140e433-35b6-45e4-8ad8-6f0738bae4cd)

### Reproduce link

https://github.com/melMass/reproduction/tree/js/rsbuild-bitsui

### Reproduce Steps

- Bootstrap my reproduction:
  ```sh
  git clone https://github.com/melMass/reproduction
  cd reproduction
  git checkout js/rsbuild-bitsui
  pnpm install
  pnpm run dev
  ```
- Open the client and check the console

**Comment by witsaint** [comment]
Circular dependency causes this error, and `webpack` behaves the same as `rsbuild`, A large number of Circular dependency detected through the `CircularDependencyPlugin` in the `@melt-ui`

It might be better to let @melt-ui fit webpack or rspack/ rsbuild

**Comment by melMass** [comment]
Thanks I will cross the issue with bits-ui's repo.
Are bits-ui and melt-ui related? I don't see any link between the two

**Comment by melMass** [comment]
Thanks @witsaint !
I will bubble it up to both projects as I still don't get the "traceback" of the error.
I will keep this issue open for reference until solved

**Comment by chenjiahan** [comment]
Since it is a problem with the third-party library, this issue will be closed. If it involves changes to Rsbuild, please feel free to open it.

**Comment by melMass** [comment]
Np! I'll post here if there is a resolution. My project is a desktop app using Webview so dev mode isn't as crucial for me but it would be a DX improvement still
