### ISSUE TITLE
[Bug]: `tools.swc.jsc.transform.react` config overrides takes no effect

### ISSUE THREAD

**Issue by SoonIter** [web-infra-dev/rsbuild#3418]
### Version

```sh
System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 67.98 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 128.0.6613.120
    Chrome Canary: 130.0.6702.0
    Safari: 17.6
  npmPackages:
    @rsbuild/core: 1.0.1-rc.5 => 1.0.1-rc.5 
    @rsbuild/plugin-react: 1.0.1-rc.5 => 1.0.1-rc.5
```

### Details

1. `rsbuild.config.ts`

```ts
export default defineConfig({
  plugins: [pluginReact()],
  tools: {
    swc: {
      jsc: {
        transform: {
          react: {
            runtime: 'classic',
          },
        },
      },
    },
  },
});
```

2. `DEBUG=rsbuild rsbuild build`

<img width="689" alt="image" src="https://github.com/user-attachments/assets/ea61ec9d-3c32-403d-aba1-f0204b82a779">

### Reproduce link

https://github.com/SoonIter/rsbuild-tools-swc-issue-repro

### Reproduce Steps

https://github.com/web-infra-dev/rsbuild/blob/14c5a9e3bedba919244818792c238a51f2acefe5/packages/core/src/plugins/swc.ts#L158

1. pnpm install
2. DEBUG=rsbuild npx rsbuild build

**Comment by SoonIter** [comment]
overrided by `@rsbuild/plugin-react`

fixed by

```typescript
export default defineConfig({
  plugins: [pluginReact({
    swcReactOptions: {
      runtime: 'classic'
    }
  })],
  tools: {
    // swc(config) {
    //   (((config.jsc ??= {}).transform ??= {}).react ??= {}).runtime =
    //     'classic';
    // },
  },
});
```

**Comment by SoonIter** [comment]
`tools.swc` should execute in the final stage just like `tools.bundlerChain` and `tools.rspack`

so pluginSwc should execute after pluginReact?

modernjs has no entry for modifying the options of pluginReact

@chenjiahan cc

**Comment by chenjiahan** [comment]
This is an order issue, I think we can try to let `pluginReact` to use `tools.swc` instead of using `modifySwcLoaderOptions`

**Comment by SoonIter** [comment]
> This is an order issue, I think we can try to let `pluginReact` to use `tools.swc` instead of using `modifySwcLoaderOptions`

I cannot get `isDev` `usingHMR` in `modifyRsbuildConfig` 😂...

**Comment by chenjiahan** [comment]
Yes, let me think if there is a better way...
