### ISSUE TITLE
[Bug]: static resource can not resolve from public path in css file.

### ISSUE THREAD

**Issue by jackchoumine** [web-infra-dev/rsbuild#3429]
### Version

version info:

```bash
"@rsbuild/core": "^1.0.1-rc.5",
```

### Details

There are some img in public:

```bash
public/imgs/wms-0-params.png
```
use it in vue3 component:
```html
<template>
  <div class="main-wrapper flex flex-1 flex-col">
    <p>hello world</p>
    <!-- NOTE  work well -->
    <img src="/imgs/wms-0-params.png" alt="" srcset="" />
  </div>
</template>

<style lang="scss" scoped>
p {
  color: red;
  /* NOTE can not work Error: HookWebpackError: Cannot find module '/imgs/wms-0-params.png' */
  background-image: url('/imgs/wms-0-params.png');
}
</style>
```

in css part, it can not reslove  img path:

> Error: HookWebpackError: Cannot find module '/imgs/wms-0-params.png'

### rsbuild/core@^0.4.6  work well

Related issue: #3374 

Someone say put img into `src/assets` path then use img by relative path.   It is not good migration way.

### Reproduce link

无

### Reproduce Steps

无

**Comment by liu-collab** [comment]
you can do this 
```ts
tools: {
      cssLoader: { url: { filter: (url) => !url.includes('imgs') } },
    },
```

**Comment by 9aoy** [comment]
Rsbuild uses css-loader by default to handle CSS resources.You can use the `cssLoader.url` option to filter the public resource path like the example above.

If you use experiments.css, you can use `rspack.IgnorePlugin` to ignore public resources path. https://github.com/webpack/webpack/issues/14893#issuecomment-2301653521
