### ISSUE TITLE
[Bug]: sourcemaps being generated after 1.0.1-rc.2 through 1.0.1 (latest) do not work with Sentry to decode stack traces

### ISSUE THREAD

**Issue by canopus1io** [web-infra-dev/rsbuild#3433]
### Version

```sh
  System:
    OS: Linux 6.1 Amazon Linux 2023
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
    Memory: 5.97 GB / 7.63 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 127.0.6533.88
  npmPackages:
    @rsbuild/core: 1.0.1 => 1.0.1
    @rsbuild/plugin-css-minimizer: ^1.0.2 => 1.0.2
    @rsbuild/plugin-mdx: ^1.0.2 => 1.0.2
    @rsbuild/plugin-node-polyfill: ^1.0.4 => 1.0.4
    @rsbuild/plugin-react: 1.0.1 => 1.0.1



key versions:
@rsbuild/core@1.0.1
@rspack/core@1.03
@rspack/cli@1.03

@sentry/browser@8.29.0
@sentry/webpack-plugin@2.22.4
```

### Details

![Screenshot 2024-09-09 at 9 20 30 PM](https://github.com/user-attachments/assets/887db678-3227-48c7-af90-580a63555681)
![image](https://github.com/user-attachments/assets/f1c9603c-223f-460a-a815-8f74c7686156)
stack traces do no resolve correctly

I first discovered this issue with:
@rsbuild/core@1.0.1-rc.5

I confirmed it works fine on:
@rsbuild/core@1.0.1-rc.2
![image](https://github.com/user-attachments/assets/0cecb9c2-8267-4695-8ba5-8dd2405af2ee)

### Reproduce link

not yet available

### Reproduce Steps

not yet available

**Comment by chenjiahan** [comment]
Maybe related to https://github.com/web-infra-dev/rspack/pull/7647

Can you provide more information for debugging?

**Comment by SyMind** [comment]
@canopus1io Can you check the correctness of the generated source map? Check where the source map is problematic.

**Comment by gitim** [comment]
I have the same issue after https://github.com/web-infra-dev/rspack/pull/7647. Source map genereated by rspack@1.0.0 is about ~28MB, by rspack@1.0.1 the source map is incomplete and only ~5MB.

**Comment by SyMind** [comment]
@gitim Please provide the a demo to reproduce the issue.

**Comment by chenjiahan** [comment]
Ref: https://github.com/web-infra-dev/rspack/issues/7914#issuecomment-2368719283

**Comment by chenjiahan** [comment]
Should be fixed in the next release, see: https://github.com/web-infra-dev/rspack/pull/7991
