### ISSUE TITLE
[Feature]: support `?raw` for ts

### ISSUE THREAD

**Issue by ouzhou** [web-infra-dev/rsbuild#3435]
### What problem does this feature solve?

import LODASH_array from '@types/lodash/common/array.d.ts?raw';

I want to return a string

### What does the proposed API look like?

As intuition suggests, any file should only return a string after concatenating this suffix
The current situation is that this suffix function only supports files other than ts like 'txt' etc....

**Comment by SoonIter** [comment]
you could try use `tools.rspack` or `tools.bundlerChain` to support `resourceQuery` like svgr plugin

https://rsbuild.dev/plugins/list/plugin-svgr#svgroptionsexporttype
https://github.com/web-infra-dev/rsbuild/tree/main/packages/plugin-svgr

**Comment by ouzhou** [comment]
see https://github.com/web-infra-dev/rsbuild/issues/3070

**Comment by SoonIter** [comment]
could you add `enforce: 'pre'` to your rule? @ouzhou

**Comment by ouzhou** [comment]
I tried all the parameters of `enforce` from the beginning

**Comment by eatfishs** [comment]
![Image](https://github.com/user-attachments/assets/926a0f02-1b4e-433c-bb2b-0e528012e6bd)
![Image](https://github.com/user-attachments/assets/98145adc-3f11-440b-bed1-f449002d357a)
我主动为“?raw”结尾的链接添加了“!”，折中的实现了和vite类似的效果

**Comment by chenjiahan** [comment]
This feature will be tracked here: https://github.com/web-infra-dev/rsbuild/issues/3778

Closed as duplicate.
