### ISSUE TITLE
[Bug]: Configuring sourceMap: { js: 'source-map' } in the production environment cannot decode stack traces.

### ISSUE THREAD

**Issue by wendy0512** [web-infra-dev/rsbuild#3447]
### Version

```sh
System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11500 @ 2.70GHz
    Memory: 12.17 GB / 31.71 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @rsbuild/core: ^1.0.4 => 1.0.4
    @rsbuild/plugin-less: ^1.0.1 => 1.0.1
    @rsbuild/plugin-react: ^1.0.2 => 1.0.2
    @rsbuild/plugin-styled-components: ^1.0.1 => 1.0.1
```

### Details

In the output configuration, setting sourceMap: { js: 'source-map' } results in inconsistent source code parsing behavior between the development and production environments, with the production environment not working as expected.
The development environment interface is as follows:
![image](https://github.com/user-attachments/assets/03845caf-44eb-4bba-b804-4187b61845ec)
![image](https://github.com/user-attachments/assets/c843c356-6833-4cca-9ad1-b8cc97afdf31)

The production environment interface is as follows:
![image](https://github.com/user-attachments/assets/6b9d337a-ef5a-4873-820c-9abe343632f4)
![image](https://github.com/user-attachments/assets/e759e470-a276-4a2e-84c9-65b337ba5d6d)

### Reproduce link

https://github.com/wendy0512/rsbuild-sourcemap-repro

### Reproduce Steps

1. In the output configuration, set sourceMap: { js: 'source-map' }.

1. Run rsbuild dev and observe the network resources in the development environment.

1. Run rsbuild build and observe the network resources in the production environment.

**Comment by wendy0512** [comment]
Minimal reproduction has been added.

**Comment by wendy0512** [comment]
Sorry, after upgrading @rsbuild/core from 1.0.4 to 1.0.8, the example still does not display as expected. @chenjiahan

**Comment by GiancarlosIO** [comment]
Hi there!
It's also affecting modern.js framework. I notice this when trying to implement sentry in my app.

**Comment by chenjiahan** [comment]
Fixed in https://github.com/web-infra-dev/rspack/releases/tag/v1.0.10
