### ISSUE TITLE
[Bug]: Command failed with exit code 3221225501

### ISSUE THREAD

**Issue by Elsicast** [web-infra-dev/rsbuild#3457]
### Version

```sh
System:Win10 21H2
```

### Details

报错信息如下
![Screenshot from 2024-09-12 08-07-59](https://github.com/user-attachments/assets/58f8a2a7-e77a-4f32-aeaf-90bd422317c2)
在去除掉代码（只保留react初始化代码）时可以正常运行，但是加入项目代码后就报错，没有任何错误信息。
以下是package.json

![Screenshot from 2024-09-12 08-32-33](https://github.com/user-attachments/assets/95544c53-9b3a-40d2-8caa-0f7f193246d8)
![Screenshot from 2024-09-12 08-32-46](https://github.com/user-attachments/assets/58789d4b-d241-4736-b659-c32762e46c2f)
![Screenshot from 2024-09-12 08-32-55](https://github.com/user-attachments/assets/bf563870-b426-44a5-9558-c56d06e03f6e)
![Screenshot from 2024-09-12 08-33-06](https://github.com/user-attachments/assets/b5fee4de-e667-4003-b694-a3ddc1fc2099)
![Screenshot from 2024-09-12 08-33-10](https://github.com/user-attachments/assets/cd588a02-1036-4771-aba0-d3a837abf67f)

### Reproduce link

无法在其他代码环境重现

### Reproduce Steps

无法在其他代码环境重现

**Comment by Elsicast** [comment]
rsbuild 0.6.13版本能正常运行，升级后就不行了

**Comment by Elsicast** [comment]
使用了旧版装饰器导致的报错

**Comment by chenjiahan** [comment]
I think using the legacy decorator should not cause process exit. If anyone else encounters this issue, please feedback to [SWC](https://github.com/swc-project/swc).
