### ISSUE TITLE
[Bug]: Setting open to false in server configuration does not take effect

### ISSUE THREAD

**Issue by xmgzrqk** [web-infra-dev/rsbuild#3458]
### Version

```sh
System: win11  node@16.13.0
```

### Details

在进行断点调试时，为了避免每次都自动打开页面，将serve配置里的open设为了false，发现不生效

### Reproduce link

no

### Reproduce Steps

server：{
     open：false
}

**Comment by chenjiahan** [comment]
Are you using the "--open" CLI flag? It has a higher priority.

**Comment by xmgzrqk** [comment]
thanks. It is used in dev in the script, which occurs when using npm create rsbuild@latest In the newly created demo project, I think we can remove the -- open in dev and place the configuration in the config file for clearer clarity

**Comment by chenjiahan** [comment]
Thanks for the suggestion. I currently prefer to keep the `--open` CLI flag. I will update the documentation to make their priorities clearer.
