### ISSUE TITLE
[Bug]: Exception when opening in IE browser in development mode

### ISSUE THREAD

**Issue by wengjiacheng** [web-infra-dev/rsbuild#3463]
### System Info

System:
    OS: macOS 13.3.1
    CPU: 2.5 GHz Intel Core i7
    Memory: 16 GB 2133 MHz LPDDR3
  Browsers:
    Chrome:  120.0.6099.109
  npmPackages:
    "@rsbuild/core": "^1.0.1-rc.2",
    "@rsbuild/plugin-babel": "^1.0.1-rc.2",
    "@rsbuild/plugin-vue2": "^1.0.1",
    "@rsbuild/plugin-vue2-jsx": "^1.0.1",

### Details

开发模式下在IE浏览器下打开会报错

### Reproduce link

https://github.com/wengjiacheng/build-demo

### Reproduce Steps

npm run dev

**Comment by chenjiahan** [comment]
Can you share a screenshot of the exception?

**Comment by G1King** [comment]
> Can you share a screenshot of the exception?
I also have the same problem, as shown in the picture

<img width="382" alt="Image" src="https://github.com/user-attachments/assets/9a3a5904-0431-41b1-8f72-81374bbf373c" />

I installed the grammar check package（[@rsbuild/plugin-check-syntax](https://github.com/rspack-contrib/rsbuild-plugin-check-syntax)） provided by the official documentation and did not receive any grammar errors
