### ISSUE TITLE
[Bug]: use @rsbuild/plugin-svgr to import svg as ReactComponent will throw HarmonyLinkingError

### ISSUE THREAD

**Issue by Yukiniro** [web-infra-dev/rsbuild#3468]
### Version

```sh
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12400
    Memory: 15.65 GB / 31.75 GB
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    @rsbuild/core: ^1.0.2 => 1.0.2 
    @rsbuild/plugin-react: ^1.0.1 => 1.0.1 
    @rsbuild/plugin-svgr: ^1.0.1 => 1.0.1
```

### Details

rsbuild.config.mjs
```
import { defineConfig } from "@rsbuild/core";
import { pluginReact } from "@rsbuild/plugin-react";
import { pluginSvgr } from "@rsbuild/plugin-svgr";

export default defineConfig({
  plugins: [pluginReact(), pluginSvgr()],
});
```

App.jsx
```
import { ReactComponent as PlayIcon } from "./assets/play.svg";
```

It will throw HarmonyLinkingError when run dev.
![error](https://github.com/user-attachments/assets/99fb2255-266d-41a7-ad83-331421cdb565)

### Reproduce link

https://github.com/Yukiniro/reproduce/tree/master/rsbuild-issue-svgr-harmonylinkingerror

### Reproduce Steps

1. install deps `pnpm i`
2. run dev `rsbuild dev`
3. Compilation failed: × HarmonyLinkingError:

**Comment by chenjiahan** [comment]
Sorry it is a mistake of Rsbuild documentation, I will fix it.

By default, the pluginSvgr supports the `?react` query:

```js
import Logo from './logo.svg?react';

export const App = () => <Logo />;
```

To use the `ReactComponent` named export, the `exportType: 'named'` option is required:

```js
pluginSvgr({
  svgrOptions: {
    exportType: 'named',
  },
})
```

**Comment by Yukiniro** [comment]
It works. Thanks! Should I close this issue?

**Comment by chenjiahan** [comment]
Let me close it after fixing the doc 😄
