### ISSUE TITLE
[Bug]: rsbuild + typescript 5.0 + vue2 + vue-property-decorator will throw error

### ISSUE THREAD

**Issue by sbyps** [web-infra-dev/rsbuild#3479]
### Version

```sh
System:
    OS: macOS 14.6.1
    CPU: (11) x64 Apple M3 Pro
    Memory: 27.82 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 128.0.6613.138
    Safari: 17.6
  npmPackages:
    @rsbuild/core: 1.0.2 => 1.0.2 
    @rsbuild/plugin-check-syntax: ^1.0.1 => 1.0.1 
    @rsbuild/plugin-sass: ^1.0.1 => 1.0.1 
    @rsbuild/plugin-vue2: ^1.0.1 => 1.0.1
```

### Details

using rsbuild + typescript 5.0 + vue2 + vue-property-decorator will throw error, maybe related to swc-loader

using rsbuild + typescript 4.5.5 + vue2 + vue-property-decorator is fine

./src/pages/ts-page/index.vue?vue&type=script&lang=ts!=!builtin:swc-loader??clonedRuleSet-3.use[0]!../../../node_modules/.pnpm/vue-loader@15.11.1_css-loader@7.1.2_@rspack+core@1.0.5_@swc+helpers@0.5.13__webpack@5.93.0__l_mgkntxmtzqpjtw4ibdpjnhyoji/node_modules/vue-loader/lib/index.js??vue-loader-options!./src/pages/ts-page/index.vue?vue&type=script&lang=ts | @ | index.vue:10

<img width="1430" alt="image" src="https://github.com/user-attachments/assets/69c2a695-4b19-4e6d-80ea-c4cdc0e738d3">

### Reproduce link

https://github.com/sbyps/rspack-demo

### Reproduce Steps

pnpm i
pnpm dev
http://localhost:3000/ts-page

**Comment by hatedMe** [comment]
You should set decorators.version: 'legacy' to get support for property decorators.
https://rsbuild.dev/config/source/decorators#legacy
您应该设置为获取对属性装饰器的支持。https://rsbuild.dev/config/source/decorators#legacy
