### ISSUE TITLE
[Feature]: Support viewing served files via `/rsbuild-dev-server` route

### ISSUE THREAD

**Issue by 9aoy** [web-infra-dev/rsbuild#3519]
### What problem does this feature solve?

When the product writes to memory (execute rsbuild dev), it is difficult to find out which files were generated and what their paths are.

### What does the proposed API look like?

like [webpack-dev-server](https://webpack.js.org/configuration/dev-server/#root:~:text=If%20you%27re%20having%20trouble%2C%20navigating%20to%20the%20/webpack%2Ddev%2Dserver%20route%20will%20show%20where%20files%20are%20served.%20For%20example%2C%20http%3A//localhost%3A9000/webpack%2Ddev%2Dserver.), visit `/rsbuild-dev-server` route will show where files are served. For example, 
http://localhost:3000/rsbuild-dev-server.

<img width="708" alt="image" src="https://github.com/user-attachments/assets/9409c164-144f-4cf1-8161-3ff98e15370e">

**Comment by hangCode2001** [comment]
I want to try it.
