### ISSUE TITLE
[Bug]: import.meta.webpackContext

### ISSUE THREAD

**Issue by xcxiao7710** [web-infra-dev/rsbuild#3520]
### Version

```sh
版本14.5 (23F79)
```

### Details

<img width="788" alt="image" src="https://github.com/user-attachments/assets/a04cfd84-a616-411a-a59a-2fe4962c6e4d">
官方是说可以但是并找不到相关文档麻烦抓紧答复
<img width="489" alt="image" src="https://github.com/user-attachments/assets/506448a8-0f29-43b2-82e7-82acbf471148">
<img width="1426" alt="image" src="https://github.com/user-attachments/assets/baabd3ce-1f1e-4326-b63e-74d56f783a74">

### Reproduce link

https://rsbuild.dev/zh/guide/migration/vite

### Reproduce Steps

[1](https://rspack.dev/zh/api/modules/module-variables#importmetawebpackcontext)

**Comment by chenjiahan** [comment]
Updated: https://rspack.dev/api/runtime-api/module-variables#importmetawebpackcontext
