### ISSUE TITLE
[Bug]: Additional title tag is added

### ISSUE THREAD

**Issue by Teraqz** [web-infra-dev/rsbuild#3546]
### Version

```sh
System:
    OS: Windows 11 10.0.22631
    CPU: (32) x64 AMD Ryzen 9 7950X 16-Core Processor
    Memory: 16.70 GB / 31.16 GB
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @rsbuild/core: ^1.0.1 => 1.0.6
    @rsbuild/plugin-react: ^1.0.1 => 1.0.2
```

### Details

`rsbuild.config.ts` is configured with template option `./index.html`
In template there is a custom <title> tag, after launching dev server and looking at element you will get two <title> tags.
![title](https://github.com/user-attachments/assets/17fce64d-5e86-4373-94bb-3ce61a6fae66)

### Reproduce link

https://github.com/Teraqz/rsbuild-title-demo

### Reproduce Steps

1. npm install
2. npm run dev

**Comment by 9aoy** [comment]
`tools.htmlPlugin` is the configuration of the underlying `htmlPlugin`. It is recommended to use rsbuild [html.template](https://rsbuild.dev/config/html/template) configuration, which will help rsbuild determine whether title is added repeatedly.

```diff
export default defineConfig({
  plugins: [pluginReact()],
  html: {
+    template: "./index.html",
  },
  tools: {
-    htmlPlugin: {
-      template: "./index.html",
-    },
  },
});
```
