### ISSUE TITLE
[Feature]: option to disable escape char transformation to display char in scss/css

### ISSUE THREAD

**Issue by mbohovic** [web-infra-dev/rsbuild#3583]
### What problem does this feature solve?

I have scss or css file in which, for example, this

```
.icomoon-calendar:before {
  content: '\e94e';
}
```

and rsBuild transforms it to this for me

```
.icomoon-calendar:before {
    content: "";
}
```

How to prevent it, I want it to stay in flood shape

### What does the proposed API look like?

Add a property to the rsBuild configuration for scss processing that disables this transformation

**Comment by chenjiahan** [comment]
Ref: https://github.com/web-infra-dev/rsbuild/issues/3328

**Comment by chenjiahan** [comment]
Issue closed because this is a LightningCSS downstream issue
