### ISSUE TITLE
[Bug]: Invalid Route Causes Dev Server to Crash

### ISSUE THREAD

**Issue by amirsarfarW** [web-infra-dev/rsbuild#3588]
### Version

```sh
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 7.62 GB / 15.85 GB
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    @rsbuild/core: ^1.0.1 => 1.0.7
    @rsbuild/plugin-react: ^1.0.1 => 1.0.2
```

### Details

Just try to reach `http://localhost:3000//someroute`

![image](https://github.com/user-attachments/assets/77a47bc8-a668-4671-8ca1-d35d931d16f9)

### Reproduce link

no link

### Reproduce Steps

1. `npx create-rsbuild -d some-project -t react`
2. `cd some-project`
3. `npm i`
4. `npm run dev`
5. open browser and goto `http://localhost:3000//someroute`

**Comment by amirsarfarW** [comment]
Thank you guys for fixing it

Have a nice journey developing such a wonderful tool

**Comment by chenjiahan** [comment]
Our pleasure 😄
