### ISSUE TITLE
[Bug]: ModuleFederation needs globalThis but polyfill chunks executed later

### ISSUE THREAD

**Issue by nanianlisao** [web-infra-dev/rsbuild#3593]
### Version

```sh
latest
```

### Details

The minimum configuration is as follows:

```
moduleFederation: {
    options: {},
  },
  output: {
    polyfill: 'entry',
    overrideBrowserslist: ['chrome 70'],
  },
```

At this time, corejs injection does not take effect.

In addition, this seems to be a problem with rspack, webpack is ok

### Reproduce link

no

### Reproduce Steps

 no

**Comment by chenjiahan** [comment]
You can find the `core-js` code in this chunk:

![image](https://github.com/user-attachments/assets/3a5f5b1e-d4fc-4695-9c85-cd378230decd)


The default `lib-polyfill` chunk will not be generated when using `moduleFederation.options`, see https://rsbuild.dev/config/module-federation/options

![image](https://github.com/user-attachments/assets/141dd8ff-d7ed-4a9e-9f30-cc508d0fbc52)

**Comment by nanianlisao** [comment]
@chenjiahan  You need to run it under chrome 70, and then the following error will appear.

![image](https://github.com/user-attachments/assets/c5c09c42-33c5-40cc-8bb8-1abaf065bc6c)

The problem is that the polyfill does not take effect, not the splitChunk rule.

**Comment by nanianlisao** [comment]
Any new progress？ @chenjiahan

**Comment by chenjiahan** [comment]
Any reproduction?

**Comment by nanianlisao** [comment]
Sorry, my description is wrong, in fact the problem is that mf requires globalThis. However, after rsbuild turns on mf, corejs will be additionally divided into chunks and executed later, thus causing an error.

```text
Uncaught ReferenceError: globalThis is not defined
```

https://github.com/nanianlisao/rsbuild-repro/tree/main

pnpm run dev 

Open it in chrome 70 and you'll find the error

![Image](https://github.com/user-attachments/assets/c4639cae-2506-467f-852f-a267dde3c966)

**Comment by chenjiahan** [comment]
Get, I have reproduced this problem. The MF runtime runs earlier than core-js, so the core-js globalThis polyfill cannot work as expected.

I will discuss with MF members how to fix this.

**Comment by chenjiahan** [comment]
A workaround is to use `polyfill: "usage"`, this ensures that the polyfills can run before the MF runtime code.

```js
export default defineConfig({
  plugins: [
    pluginReact({
      fastRefresh: false,
    }),
  ],
  moduleFederation: {
    options: {},
  },
  output: {
    polyfill: "usage",
    overrideBrowserslist: ["chrome 70"],
  },
});
```

**Comment by nanianlisao** [comment]
Yes, it works. But I would like to inject polyfill via entry, for example for compatibility with some third-party packages, and it works fine in webpack.

**Comment by chenjiahan** [comment]
Do you mean webpack's Module Federation v1 plugin or Module Federation enhanced?

Module Federation v1 does not use `globalThis`.

**Comment by chenjiahan** [comment]
I have discussed this with @2heal1 and MF will consider adding a minimal `globalThis` polyfill to the runtime code.

**Comment by 2heal1** [comment]
Try `@module-federation/runtime-tools@0.7.1`  by setting [implementation](https://rspack.dev/plugins/webpack/module-federation-plugin#implementation) options
