### ISSUE TITLE
[Feature]: `metaByEntries` config by function or regex

### ISSUE THREAD

**Issue by zoolsher** [web-infra-dev/rsbuild#360]
### What problem does this feature solve?

I'm working on support for the [Open Graph Protocol (OGP)](https://ogp.me/) in `rspress`. My goal is to fill in the appropriate meta tags based on the language of the page. Here are examples of how the `og:description` tag would be filled in for English and Chinese versions of the `/get-start` page:

For the English version:

```html
<!--in /en/get-start.html-->
<html>
  <head>
    <meta property="og:description"  value="Out-of-box Rspack build tools">
  </head>
</html>
```

And for the Chinese version:

```html
<!--in /zh/get-start.html-->
<html>
  <head>
    <meta property="og:description" value="开箱即用的 Rspack 构建工具">
  </head>
</html>
```

### What does the proposed API look like?

Please note that configuring the metaByEntries feature in this scenario can be a bit complex. So is it possible to provide a function for metaByEntries like this:

```js

function metaByEntries(entry: string){
   if(entry.startsWith('zh')){
      return {
        "og:description": "开箱即用的 Rspack 构建工具"
      };
   }else{
      return {
        "og:description": "Out-of-box Rspack build tools"
      };
  }
}

```

**Comment by zoolsher** [comment]
@sanyuan0704 do you have any suggestion on this?

**Comment by chenjiahan** [comment]
This is a good idea, I prefer remove the `metaByEntries` config, and support function type in `meta` config:

- Example for i18n:

```ts
export default {
  html: {
    meta({ entryName }) {
      if (entryName.startsWith('zh')) {
        return {
          'og:description': '开箱即用的 Rspack 构建工具',
        };
      } else {
        return {
          'og:description': 'Out-of-box Rspack build tools',
        };
      }
    },
  },
};
```

- Example for replace the `metaByEntries` config:

```ts
export default {
  html: {
    meta({ entryName }) {
      const metaByEntries = {
        foo: { charset: 'utf-8' },
        bar: { charset: 'xxx' },
      };
      return metaByEntries[entryName];
    },
  },
};
```

### Why remove `metaByEntries`

Rsbuild have too many `xxxByEntries` config, this results in each HTML configuration having to provide duplicate configuration options, `title` and `titleByEntires`, `meta` and `metaByEntries`....

If we can unify the `xxx` and `xxxByEntries` config, HTML configuration options will be simpler and easier to understand.

### Compatibility

Although `xxxByEntries` options are removed from Rsbuild, it can still be used by Modern.js users, we will add some compatible code for it.

**Comment by zoolsher** [comment]
TBO, I don't like xxxByEntries either

**Comment by chenjiahan** [comment]
Yes, that makes sense 😂

**Comment by sanyuan0704** [comment]
Apart from what the `meta` config should be like, it is not very appropriate to add meta in rsbuild config layer because the entrypoint is the same file(`client-entry.js`/`ssr-entry.js`) in `@rspress/runtime` instead of the md file path.

It is more recommended to implement the different meta tags in Helmet component, which is exported from `@rspress/runtime`.And in a custom component, you can get current language by `useLang` API, which is very convenient to dispatch different meta tag content.

**Comment by chenjiahan** [comment]
@sanyuan0704 Can we add some document for `Helmet` usages in Rspress document?

**Comment by sanyuan0704** [comment]
> @sanyuan0704 Can we add some document for `Helmet` usages in Rspress document?

done. https://rspress.dev/zh/api/client-api/api-components.html#helmet

**Comment by zoolsher** [comment]
Great! let me try it in the rspack website

**Comment by chenjiahan** [comment]
`html.meta` now supports function usage in Rsbuild v0.0.16.

- Document: https://rsbuild.dev/config/options/html.html#function-usage
- And `html.metaByEntries` has been moved to uni-builder (the compat package for Modern.js)

Other html options will be refactored in later versions.
