### ISSUE TITLE
[Bug]: should not append  a trailing /  when output.assetPrefix is empty string

### ISSUE THREAD

**Issue by chenyuan-new** [web-infra-dev/rsbuild#3616]
### Version

```sh
latest
```

### Details

When set `output.assetPrefix` to `''`, the output publicPath starts with `/`.
Maybe it'll be better not to append a trailing `/` when `assetPrefix` is `''`

Why would i set `assetPrefix` to `''`:
- i want to set `output.publicPath`  so in rsbuild i should set `assetPrefix`
- Our project use `<base>` element to determine the soure path of js file, the `href` value is dynamically set when start docker 

The source code related to this issue:
[related code](https://github.com/web-infra-dev/rsbuild/blob/main/packages/core/src/helpers/index.ts#L118)

### Reproduce link

no

### Reproduce Steps

no

**Comment by chenjiahan** [comment]
You can set `assetPrefix` to `./`, it is equivalent to `''`.

Rsbuild should always add a trailing slash to `output.assetPrefix`. This ensures consistent behavior, and changing this behavior is a potential breaking change.
