### ISSUE TITLE
[Bug]: PostCSS plugins gets reinitialized on compile

### ISSUE THREAD

**Issue by sibbng** [web-infra-dev/rsbuild#3618]
### Version

```sh
System:
    OS: Windows 10 10.0.19045
  npmPackages:
    @rsbuild/core: ^1.0.1 => 1.0.7
    @rsbuild/plugin-vue: ^1.0.1 => 1.0.1
```

### Details

Rsbuild re-initializes  PostCSS plugins on each compile step. Both TailwindCSS and UnoCSS plugins expect it to be initialized only once.

https://github.com/tailwindlabs/tailwindcss/blob/6a50e6e1605cd8c4e071970211ae6254cc1c6313/packages/%40tailwindcss-postcss/src/index.ts#L40-L52

https://github.com/unocss/unocss/blob/55b505917d49865d1720d9819bf6ae5a0beb014f/packages/postcss/src/index.ts#L9-L10

When plugins gets reinitialized, they lose global state and this slows down compile step significantly. As far as I know, Vite, initialize PostCSS plugins body only once. 

In the following reproduction, it gets even worse and plugins gets initialized twice on each re-compile.

### Reproduce link

https://github.com/sibbng/rsbuild-vue3

### Reproduce Steps

1. pnpm i
2. pnpm dev

**Comment by chenjiahan** [comment]
The reproduce link is 404:

![image](https://github.com/user-attachments/assets/e68a0b27-b56d-4832-a82c-8446c4c3413e)

I tried to reproduce this issue with tailwindcss v3, but I can not reproduce it:

![image](https://github.com/user-attachments/assets/1eeb8195-41a8-471a-9054-1f4adcc96665)

**Comment by inottn** [comment]
It appears to behave consistently with Vite, invoking the plugin for each module.

**Comment by chenjiahan** [comment]
This issue is caused by `postcss-load-config`, see https://github.com/postcss/postcss-load-config/issues/225

A simple workaround is invoking the tailwindcss plugin in the postcss config file:

```js
module.exports = {
  plugins: [require('@tailwindcss/postcss')()],
};
```

I will further investigate other solutions.
