### ISSUE TITLE
[Bug]: Alias resolution problem in common parent project

### ISSUE THREAD

**Issue by aadi58002** [web-infra-dev/rsbuild#3630]
### Version

  System:
    OS: Linux 6.9 Void
    CPU: (12) x64 AMD Ryzen 5 7530U with Radeon Graphics
    Memory: 1.18 GB / 14.46 GB
    Container: Yes
    Shell: 3.7.1 - /usr/bin/fish
  Browsers:
    Chromium: 129.0.6668.58
  npmPackages:
    @rsbuild/core: ^1.0.1 => 1.0.9 
    @rsbuild/plugin-react: ^1.0.1 => 1.0.3 

### Details

In a recent migration of a project from vite to rsbuild. There was a problem in alias resolution from `tsconfig.json`

Intended behavior in the minimal reproducable example is that the import in `concat.ts` resolves correctly to `misc.ts` in common-utils. 

# Related Question
`rsbuild-project/tsconfig.json` and `tsconfig.json` specifies $ as the alias for the parent. The current assumption is that rsbuild is only using the `rsbuild-project/tsconfig.json` to find alias and ignore the parent `tsconfig.json`.

### Reproduce link

https://github.com/aadi58002/rsbuild-alias-troubleshoot-minimal-example

### Reproduce Steps

1. Go to the `rsbuild-project` folder and run `pnpm dev`

![Image](https://github.com/user-attachments/assets/f9e7866c-d3b0-4b92-aeaf-8aa5b397617c)

**Comment by 9aoy** [comment]
rsbuild/rspack will not use parent's tsconfig.json by default. You can configure [tsConfig.references](https://rspack.dev/config/resolve#resolvetsconfigreferences) as follows:

```ts
export default defineConfig({
  tools: {
    rspack: {
      resolve: {
        tsConfig: {
          configFile: path.join(__dirname, "./tsconfig.json"),
          references: [path.join(__dirname, "../tsconfig.json")],
        },
      },
    },
  },
});
```

**Comment by aadi58002** [comment]
The alias is defined in the rsbuild tsconfig as well.

https://github.com/aadi58002/rsbuild-alias-troubleshoot-minimal-example/blob/main/rsbuild-project/tsconfig.json
