### ISSUE TITLE
[Bug]: Does Vue 2 plugin have a solution to support Vue 2.6? Currently the official website prompts that Vue 2 plugin only supports Vue >= 2.7.0 version

### ISSUE THREAD

**Issue by Dengpei1688** [web-infra-dev/rsbuild#3633]
### Version

@rsbuild/plugin-vue2 的最新版本

import { pluginVue2 } from "@rsbuild/plugin-vue2";

### Details

pluginVue2 编译项目Vue2.6版本上vue文件提示语法错误

目前Vue2.6版本项目在webpack5上编译正常，请问pluginVue2有好的方案能够支持Vue2.6版本吗？

### Reproduce link

暂无

### Reproduce Steps

目前Vue2.6版本项目在webpack5上编译正常，

请问pluginVue2有好的方案能够支持Vue2.6版本吗？

或者有方案支持Rspack正常编译Vue2.6版本项目吗？

![Image](https://github.com/user-attachments/assets/4c5c9268-8e2b-4cf7-be6f-182d29842cb7)

**Comment by chenjiahan** [comment]
Try this plugin: https://github.com/skymoonya/rsbuild-plugin-vue-legacy

**Comment by Dengpei1688** [comment]
Thank you.
