### ISSUE TITLE
[Bug]: How to remove the built-in vue-loader v17 version of the Vue plugin provided by rspack official website and use the user-specified vue-loader version

### ISSUE THREAD

**Issue by Dengpei1688** [web-infra-dev/rsbuild#3641]
### System Info

rspack官网提供的vue插件
![Image](https://github.com/user-attachments/assets/f3a6ada3-5f13-4d45-8716-b739d53ae0a9)

### Details

Vue 插件如何移除内置的vue-loader v17版本,采用用户指定的vue-loader版本？

尝试多种方式，好像没有生效

bundlerChain: (chain, { env, isProd, target, CHAIN_ID }) => {

chain.module
    .rule(CHAIN_ID.RULE.VUE)
    .test(/\.vue$/)
    .use("vue-loader")
    .loader("vue-loader");

}

看到sass插件有提供配置用户指定的版本，代替rspack sass插件内置的版本
![Image](https://github.com/user-attachments/assets/4afd0130-5c0a-4968-b6ac-bce3460a50bd)

请问Vue插件是否也能够像Sass插件一样提供配置用户指定的版本？
这种配置API
pluginVue2({
        vueLoaderOptions: {
             implementation: require.resolve('vue-loader'),
        },
    }),

### Reproduce Steps

Vue 插件如何移除内置的vue-loader v17版本,采用用户指定的vue-loader版本？

是否也能够像Sass插件一样提供配置用户指定的版本？
pluginSass({
  sassLoaderOptions: {
    implementation: require.resolve('sass'),
  },
});

能否实现以下配置参数来采用用户指定的vue-loader版本？
pluginVue2({
        vueLoaderOptions: {
             implementation: require.resolve('vue-loader'),
        },
    }),

**Comment by chenjiahan** [comment]
The current issue has been moved to the Rsbuild repo.

If you are using Vue 2, you should always use vue-loader v15, as vue-loader v17 only supports Vue 3.
