### ISSUE TITLE
[Bug]: should output json asset to static folder, imported by `new URL`

### ISSUE THREAD

**Issue by SoonIter** [web-infra-dev/rsbuild#3650]
### Version

  System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 185.28 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 129.0.6668.90
    Chrome Canary: 131.0.6763.0
    Safari: 17.6
  npmPackages:
    @rsbuild/core: ^1.0.1 => 1.0.10 
    @rsbuild/plugin-react: ^1.0.1 => 1.0.3 

### Details

If a json file is imported in the way of `asset` e.g: `new URL`, it will not be placed in the static directory, so it won't be uploaded to CDN and cause the error.

```ts
import './App.css';

const testJson = new URL('./assets/test.json', import.meta.url).href;
```

actual

```
./dist
├── 0e97e3ce1fa8f304.json
├── index.html
└── static
    ├── css
    │   └── index.e56a3ec6.css
    └── js
        ├── index.566b5367.js
        └── lib-react.a7f62b4e.js
```

expected

```
./dist
├── index.html
└── static
    ├── css
    │   └── index.e56a3ec6.css
    ├── js
    │   ├── index.566b5367.js
    │   └── lib-react.a7f62b4e.js
    └── json
        └── 0e97e3ce1fa8f304.json
```

### Reproduce link

https://github.com/sooniter/rsbuild-dist-json-issue

### Reproduce Steps

1. pnpm install
2. pnpm run build

**Comment by SoonIter** [comment]
1.  should deal the distPath of `json` with `module.rules`
2. should set `tools.rspack.output.assetModuleFilename` to `dist/static/others` for backup

![Image](https://github.com/user-attachments/assets/be45915e-2f95-4484-bcad-b7c65d3dd407)

**Comment by chenjiahan** [comment]
> should deal the distPath of json with module.rules

Which rule, can you give an example?

> should set tools.rspack.output.assetModuleFilename

How about output to `dist/static/assets` instead of `dist/static/others`, and we can provide `distPath.assets` to configure the path.

**Comment by chenyuan-new** [comment]
@chenjiahan i encountered the same problem. It'll be good to have `distPath.assets` config
