### ISSUE TITLE
[Bug]: peerDependencies not work

### ISSUE THREAD

**Issue by hellobq** [web-infra-dev/rsbuild#3671]
### Version

Mac m1
chrome lastest
@rsbuild/core@1.0.1

### Details

Package-B used in project-A (imported through the [file protocol](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#local-paths) ), react is introduced in package-B through `peerDependencies`, and an error `×Module not found: Can't resolve 'react' ...` will be reported in the development environment

### Reproduce link

no

### Reproduce Steps

use `npx create-rsbuild --dir my-project --template react ` create project-A
then use package-B(peerDependencies include react)
then npm run dev
then throw error...

**Comment by SoonIter** [comment]
This problem seems to have nothing to do with rsbuild, but with pnpm.
Please provide a minimum reproduction repo.

**Comment by SoonIter** [comment]
this problem seems very common in monorepo and soft-link (`ln -s`) and it is a known problem

...However, it has nothing to do with rsbuild

**Comment by hellobq** [comment]
> This problem seems to have nothing to do with rsbuild, but with pnpm. Please provide a minimum reproduction repo.

 no, i installed the dependencies locally using npm not pnpm. 😊  But webpack can handle this scenario...

**Comment by hellobq** [comment]
> Hello [@hellobq](https://github.com/hellobq). Please provide a reproduction repository or online demo. For background, see [Why reproductions are required](https://antfu.me/posts/why-reproductions-are-required). Thanks ❤️

https://github.com/hellobq/rsbuild-lib

**Comment by hellobq** [comment]
I tried it and the problem can be solved through the [git protocol](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#repository). now you can close this issue. Thank you. ❤️
