### ISSUE TITLE
[Feature]: When multiple entries are configured in source.entry, the generated entry address should end with /

### ISSUE THREAD

**Issue by hestudy** [web-infra-dev/rsbuild#3675]
### What problem does this feature solve?

我有一个vite搭建的mpa react应用，有十几个入口，都使用的是hash路由，在尝试迁移至rsbuild时，发现配置了source.entry后，只能匹配到不带/结束的路由地址。

例如：
迁移前应用地址是：http://localhost:3333/h5/customer/#/home
迁移后的地址变成：http://localhost:3333/h5/customer#/home，且无法通过现有api兼容上面的地址

由于一些业务是通过消息分发分享出去的地址，所以还是需要兼容旧地址，避免一些业务无法正常运行

### What does the proposed API look like?

或许source配置中可以新增一个api？
用于匹配/结尾的入口地址

**Comment by 9aoy** [comment]
Try `html.outputStructure: 'nested'` https://rsbuild.dev/zh/config/html/output-structure

**Comment by hestudy** [comment]
> Try `html.outputStructure: 'nested'` https://rsbuild.dev/zh/config/html/output-structure尝试 `html.outputStructure: 'nested'` https://rsbuild.dev/zh/config/html/output-structure

thanks，After configuration, the address can match normally.
