### ISSUE TITLE
[Bug]: Using the virtual file system interface[compiler.inputFileSystem], prompt that the virtual file does not exist when referenced in the project

### ISSUE THREAD

**Issue by Dengpei1688** [web-infra-dev/rsbuild#3681]
### Version

最新rsbuild版本

### Details

编写rspack虚拟文件插件，然后添加到rspack配置中去，项目中引入虚拟文件，提示路径下不存在。

// RspackVirtualModulesPlugin.js
class RspackVirtualModulesPlugin {
  constructor(modules) {
    this.modules = modules || {};
  }

  apply(compiler) {
    compiler.hooks.beforeCompile.tapAsync(
      "RspackVirtualModulesPlugin",
      (params, callback) => {
        const fs = compiler.inputFileSystem;
        Object.keys(this.modules).forEach((modulePath) => {
          // 如果虚拟模块已经存在，则更新它
          if (fs._virtualFiles) {
            fs._virtualFiles[modulePath] = this.modules[modulePath];
          } else {
            // 创建一个虚拟文件系统并添加虚拟模块
            fs._virtualFiles = { ...this.modules };
          }
        });
        callback();
      }
    );
  }
}

export default RspackVirtualModulesPlugin

// 在rsbuild.config.js文件中注册RspackVirtualModulesPlugin
const RspackVirtualModulesPlugin = require('./RspackVirtualModulesPlugin');

rspack: (config, { rspack, HtmlPlugin }) => {

config.plugins.push(
        new RspackVirtualModulesPlugin({
            [`node_modules/home-main-modules.js`]: `module.exports = require("@modules/home-main");`,
        })
      );

return config

}

// 项目中引用
require('home-main-modules'); 

// 结果提示：
Uncaught Error: Cannot find module 'home-main-modules'
![Image](https://github.com/user-attachments/assets/c1bc49c0-9e2f-416a-a531-fceac9691dfb)

### Reproduce link

no

### Reproduce Steps

1、编写rspack虚拟文件插件RspackVirtualModulesPlugin

2、在rsbuild.config.js文件中tools.rspack方法中注册虚拟文件插件RspackVirtualModulesPlugin

new RspackVirtualModulesPlugin({
[node_modules/home-main-modules.js]: module.exports = require("@modules/home-main");,
})

3、项目引入注册的虚拟文件路径 require('home-main-modules');

结果：<strong>提示Uncaught Error: Cannot find module 'home-main-modules'</strong>

备注：控制台有显示虚拟文件插件注册成功
RspackVirtualModulesPlugin {
  modules: {
    'node_modules/home-main-modules.js': 'module.exports = require("@modules/home-main");'
  }
}

**Comment by Dengpei1688** [comment]
## Hello, I am create the demo, please see  https://github.com/Dengpei1688/RspackVirtualModulesPlugin/

## You can download and run it to reproduce this issue

![Image](https://github.com/user-attachments/assets/91cd6139-7f81-4ec1-81d3-a8da588193c5)


![Image](https://github.com/user-attachments/assets/1722eabb-cb6b-4ec1-b529-d37b6f725cec)

**Comment by Dengpei1688** [comment]
Hello, @chenjiahan  the reproduction  https://github.com/Dengpei1688/RspackVirtualModulesPlugin/

**Comment by 9aoy** [comment]
![Image](https://github.com/user-attachments/assets/de1b26c3-d97d-4df0-afc5-a676f0b17b8d)

`_virtualFiles` does not seem to be a standard api of inputFileSystem, you may need to implement it yourself or rspack does not support it yet.
You can use https://github.com/rspack-contrib/rspack-plugin-virtual-module

**Comment by Dengpei1688** [comment]
Good, Thank you for your answer ！
