### ISSUE TITLE
[Bug]: Some debugger breakpoints are not bound

### ISSUE THREAD

**Issue by tonisives** [web-infra-dev/rsbuild#3687]
### Version

System:
    OS: macOS 15.0
    CPU: (12) arm64 Apple M3 Pro
    Memory: 4.86 GB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Brave Browser: 129.1.70.126
    Chrome: 125.0.6422.142
    Safari: 18.0
  npmPackages:
    @rsbuild/core: ^1.0.13 => 1.0.13
    @rsbuild/plugin-node-polyfill: ^1.0.4 => 1.0.4
    @rsbuild/plugin-react: ^1.0.3 => 1.0.3

### Details

As you can see from the picture, some lines are greyed out in the debugger. They cannot be bound. However, the first lines in the same function can be bound and debugging works.

![Image](https://github.com/user-attachments/assets/cdb1cb86-67e0-4e2f-912f-1ecbee710d0a)

When I change the function code a little bit(remove cast), then the breakpoints work for the whole function

![Image](https://github.com/user-attachments/assets/ea52aabd-56c5-407a-8acb-f536c0d72c85)

My rsbuild config has sourceMap enabled:

```ts
import { defineConfig } from "@rsbuild/core"
import {} from "@rsbuild/core"
import { pluginReact } from "@rsbuild/plugin-react"
import { dependencies } from "./package.json"
import { pluginNodePolyfill } from "@rsbuild/plugin-node-polyfill"

let toSingleton = (dep: keyof typeof dependencies) => ({
  [dep]: {
    singleton: true,
    requiredVersion: dependencies[dep],
    eager: process.env.NODE_ENV === "development",
  },
})

export default defineConfig({
  plugins: [pluginReact(), pluginNodePolyfill()],
  tools: {
    rspack: {
      resolve: {},
    },
  },
  server: {
    port: 3002,
  },
  output: {
    minify: false,
    sourceMap: {
      js: "source-map",
    },
  },
  html: {
    template: "./index.html",
  },
  source: {
    entry: {
      index: "./src/main.tsx",
    },
  },
  moduleFederation: {
    options: {
      name: "checklist_view",
      filename: "remoteEntry.js",
      exposes: {
        "./Checklist": "./src/checklist/Checklist",
      },
      remotes: {
        finding_view: "finding_view@https://....net/remoteEntry.js",
        debug_view: "debug_view@http://localhost:3004/remoteEntry.js",
      },
      shared: {
        ...toSingleton("react"),
        ...toSingleton("react-dom"),
        ...toSingleton("react-simple-code-editor"),
      },
    },
  },
})
```

tsconfig.json

```json
{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ES2022",
    "outDir": "./dist",
    "rootDir": "./src",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "moduleResolution": "Bundler",
    "resolveJsonModule": true,
    "sourceMap": true,
    "declaration": true,
    "declarationMap": true,
    "jsx": "react-jsx",
  },
}
```

### Reproduce link

empty

### Reproduce Steps

I run the app with `rsbuild dev`. Also tried with `rsbuild build && rsbuild preview`

**Comment by chenjiahan** [comment]
Maybe related to SWC, the same as https://github.com/web-infra-dev/rspack/issues/8108
