### ISSUE TITLE
[Bug]: css rules may disappear while using postcss-px-to-viewport-8-plugin landscape: true configuration

### ISSUE THREAD

**Issue by sbyps** [web-infra-dev/rsbuild#3692]
### Version

System:
    OS: macOS 14.6.1
    CPU: (11) arm64 Apple M3 Pro
    Memory: 39.13 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 129.0.6668.91
    Safari: 17.6
  npmPackages:
    @rsbuild/core: ^1.0.13 => 1.0.13 
    @rsbuild/plugin-check-syntax: ^1.0.1 => 1.0.1 
    @rsbuild/plugin-less: ^1.0.1 => 1.0.1 
    @rsbuild/plugin-sass: ^1.0.2 => 1.0.2 
    @rsbuild/plugin-vue2: ^1.0.1 => 1.0.1 

### Details

run pnpm dev several times

sometimes is right
![Image](https://github.com/user-attachments/assets/170a066a-b463-4cd7-bd55-08457e05e9e5)

lightningcssLoader: false,
sometimes got no landscape css rules
![Image](https://github.com/user-attachments/assets/fe193542-16a2-4ea1-a84e-dfe351055e85)

lightningcssLoader: true
sometimes got no landscape css rules
![Image](https://github.com/user-attachments/assets/16dab836-090f-44e6-b2de-a7922464cdd3)

sometimes will repeat and generate error rules
![Image](https://github.com/user-attachments/assets/7c6476f6-8a5e-4928-80c4-65887474c869)

### Reproduce link

https://github.com/sbyps/rspack-demo

### Reproduce Steps

run pnpm dev several times

check the test-page.css in devtool sources

set lightningcssLoader: false
run pnpm dev several times

check the test-page.css in devtool sources

**Comment by sbyps** [comment]
> This is probably a problem with the postcss plugin. I see they have several open issues.
> 
> [lkxian888/postcss-px-to-viewport-8-plugin#30](https://github.com/lkxian888/postcss-px-to-viewport-8-plugin/issues/30) [lkxian888/postcss-px-to-viewport-8-plugin#32](https://github.com/lkxian888/postcss-px-to-viewport-8-plugin/issues/32)

change to another plugin cnjm-postcss-px-to-viewport, this will generate useless and error css rules
![Image](https://github.com/user-attachments/assets/8b467021-eee4-4dd9-8fe6-cf0d8cefd00f)

**Comment by chenjiahan** [comment]
I tried to use Vite build and get the same result:

![Image](https://github.com/user-attachments/assets/13d418f3-86b9-4451-8ff5-0e29b98d3df4)

So it's still a bug of the PostCSS plugin, not the build tools.

My reproduction: https://github.com/chenjiahan/rsbuild-repro-3692
