### ISSUE TITLE
[Bug]: transformImport.customName not support a function just like babel-plugn-import customName

### ISSUE THREAD

**Issue by qsk000** [web-infra-dev/rsbuild#3696]
### Version

transformImport.customName not support a function just like babel-plugn-import customName

### Details

transformImport.customName not support a function just like babel-plugn-import customName

### Reproduce link

aaa

### Reproduce Steps

transformImport.customName not support a function just like babel-plugn-import customName

**Comment by chenjiahan** [comment]
This is not a bug. Rspack does not support `customName` function because it will slow down the build performance when performing Rust and JS communication. Currently we have no plan to support it.

**Comment by 9aoy** [comment]
`customName` supports some template strings, such as `kebabCase`, `camelCase`, etc. 
You can use `customName: "foo/es/{{ member }}"` instead of  `` customName: (member) => `foo/es/${member}` ``, for more details, see [rspack - rspackExperiments.import](https://rspack.dev/guide/features/builtin-swc-loader#rspackexperimentsimport).

**Comment by shengye233** [comment]
> `customName` supports some template strings, such as `kebabCase`, `camelCase`, etc. You can use `customName: "foo/es/{{ member }}"` instead of `` customName: (member) => `foo/es/${member}` ``, for more details, see [rspack - rspackExperiments.import](https://rspack.dev/guide/features/builtin-swc-loader#rspackexperimentsimport).

how to operate `member`?

`babel-plugn-import` :
```
customName: member => `foo/es/${member.replace('test', '')}`
```

**Comment by actake** [comment]
Template strings do not fulfill the implementation in some special scenarios, such as when the target component has a public prefix (e.g. XX):.
* When specifying customName as {{ kebabCase member }}/{{ member }}, the result is 
import { XXUEditor } 'libName' ---> import { XXUEditor } from 'libName/xxu-editor/XXUEditor' ;
* Whereas the actual desired correct result should be: 
import { XXUEditor } 'libName' ---> import { XXUEditor } from 'libName/xx-ueditor/XXUEditor'; 
I think we need a more liberal way of dealing with similar scenarios
