### ISSUE TITLE
[Feature]: output.filename.css should allow a function

### ISSUE THREAD

**Issue by hustcer** [web-infra-dev/rsbuild#3701]
### What problem does this feature solve?

`output.filename.css` should allow a function, rspack has already support this feature: https://github.com/web-infra-dev/rspack/issues/6215

### What does the proposed API look like?

`output.filename.css` should allow a function

**Comment by gaoachao** [comment]
Can I try this?

**Comment by chenjiahan** [comment]
Sure, you can refer to this PR: https://github.com/web-infra-dev/rsbuild/pull/2549
