### ISSUE TITLE
[Bug]: `printUrls` doesn't have any effect when `htmlPlugin` is disabled

### ISSUE THREAD

**Issue by ainursharaev** [web-infra-dev/rsbuild#3731]
### Version

  System:
    OS: macOS 15.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 3.47 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Brave Browser: 126.1.67.123
    Chrome: 129.0.6668.101
    Firefox: 131.0.2
    Safari: 18.0.1
 npmPackages:
    @rsbuild/core: ^1.0.14 => 1.0.14
    @rsbuild/plugin-node-polyfill: ^1.0.4 => 1.0.4,
    @rsbuild/plugin-react: ^1.0.4 => 1.0.4
    @rsbuild/plugin-sass: ^1.0.3 => 1.0.3
    @rsbuild/plugin-svgr: ^1.0.4 => 1.0.4

### Details

Hi there! I think [one fix](https://github.com/web-infra-dev/rsbuild/pull/2659) applied on `printServerURLs` broke one use case that I have – I don't output any HTML files as well, because the assets are just served from php server, but I still want to somehow print the nice urls in the console. Before it was possible, but now because of the additional `routes` [check](https://github.com/web-infra-dev/rsbuild/blob/35d5ffd917a4cfb8ea6f04576e68dc0bd7edbf95/packages/core/src/server/helper.ts#L203) this functionality is not usable in my case. Perhaps you could advice how to do url printing in other way?

### Reproduce link

–

### Reproduce Steps

1. set `htmlPlugin` to false
2. see that urls logs are not output, even with custom function in `printUrls`

**Comment by chenjiahan** [comment]
If `htmlPlugin` is `false`, Rsbuild will not generate HTML files, so the server urls will not be accessible.

When using the printUrls custom function, I think the URL can be printed, I will fix this in the next release.
