### ISSUE TITLE
[Bug]: Module Federation breaks publicPath / assetsPrefix

### ISSUE THREAD

**Issue by danantal** [web-infra-dev/rsbuild#3751]
### Version

  System:
    OS: Windows 11 10.0.22631
    CPU: (32) x64 AMD Ryzen 9 3950X 16-Core Processor
    Memory: 28.51 GB / 63.92 GB
  Browsers:
    Edge: Chromium (128.0.2739.42)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @rsbuild/core: 1.0.15 => 1.0.15 
    @rsbuild/plugin-react: 1.0.5 => 1.0.5 

### Details

Adding an empty module federation configuration to a basic RSBuild app breaks the publicPath / assetsPrefix by removing the leading slash.

```
moduleFederation: {
  options: {
    name: 'app',
  }
}
```

With moduleFederation:
![Image](https://github.com/user-attachments/assets/174627db-4699-46d2-bd3c-37830b8eaa74)

Without moduleFederation:
![Image](https://github.com/user-attachments/assets/14acef66-0da7-4320-8a76-5f032630386f)

### Reproduce link

https://github.com/danantal/rsbuild-demo

### Reproduce Steps

1. Run pnpm i
2. Run pnpm dev
3. Navigate to localhost:3000/foo/

Expected: page loads correctly
Actual: blank page due to assets referenced incorrectly

If you comment out the `moduleFederation` configuration in `rsbuild.config.ts` then it works as expected.

**Comment by danantal** [comment]
It seems that this is a problem that occurs due to the defaults that rsbuild applies when configuring module federation. According to docs, when using module federation it does set output.PublicPath to 'auto'.

However, even with an explicit `server.base`, and `dev.assetsPrefix` / `output.assetsPrefix`, the underlying configuration passed to `rspack.output.publicPath` is still 'auto'...

Without module federation:
![Image](https://github.com/user-attachments/assets/9777c517-7d6c-40df-8415-7ad88059d834)

With module federation:
![Image](https://github.com/user-attachments/assets/47474d80-d40a-4801-a28c-1456dd6f2379)

**Comment by chenjiahan** [comment]
As mentioned in the documentation, Rsbuild set the default value of Rspack's [output.publicPath](https://rspack.dev/config/output#outputpublicpath) configuration to 'auto' when using `moduleFederation.options`, see https://rsbuild.dev/config/module-federation/options#introduction

I have tried the reproduction, and considering that there is no `foo.html `page in this demo, we should visit `localhost:3000/` instead of `localhost:3000/foo/` to get the correct response from the dev server.

**Comment by NikaBuligini** [comment]
@chenjiahan Let's assume we're using a single page application that has a client side routing and the server always returns the same `index.html` for any page client navigates to. The server is configured to serve static assets only from `localhost:3000/static`

- User navigates to `localhost:3000/`
- Browser loads `localhost:3000/static/js/index.js`
- Then the user clicks on a link to navigate to a different route (`/foo/bar`) using history API
- Web app still works fine because it was a client side routing, URL was changed to `localhost:3000/foo/bar`
- Now user reloads the page
- Browser makes a request to `localhost:3000/foo/bar`
- This time index.js file is loaded from `localhost:3000/foo/static/js/index.js` instead of `localhost:3000/static/js/index.js` and it breaks the app because the server doesn't serve asset files from `/foo/static`

**Comment by danantal** [comment]
I've tried to keep it simple, but if I add an SPA router and a path `/foo` and use a deeplink to navigate, the app won't load as [NikaBuligini](https://github.com/NikaBuligini) explained above.

**Comment by chenjiahan** [comment]
Thanks for the info. I have discussed this with @2heal1 from the Module Federation team and I will be submitting some patches to fix this issue soon.

**Comment by danantal** [comment]
Thanks a lot for the quick reactions @chenjiahan @2heal1

**Comment by siddjellali** [comment]
> [@chenjiahan](https://github.com/chenjiahan) Let's assume we're using a single page application that has a client side routing and the server always returns the same `index.html` for any page client navigates to. The server is configured to serve static assets only from `localhost:3000/static`
> 
> * User navigates to `localhost:3000/`
> * Browser loads `localhost:3000/static/js/index.js`
> * Then the user clicks on a link to navigate to a different route (`/foo/bar`) using history API
> * Web app still works fine because it was a client side routing, URL was changed to `localhost:3000/foo/bar`
> * Now user reloads the page
> * Browser makes a request to `localhost:3000/foo/bar`
> * This time index.js file is loaded from `localhost:3000/foo/static/js/index.js` instead of `localhost:3000/static/js/index.js` and it breaks the app because the server doesn't serve asset files from `/foo/static`

I'm facing the same issue: the project works fine when I run it with `rsbuild preview` (I can refresh my screen without problems), but it doesn't work when I serve it with `server ./dist` or inside a Docker container with Nginx (I get a 404 page). Do you have any explanation?

**Comment by chenjiahan** [comment]
If Rsbuild preview works fine but Ngnix does not, it sounds like an issue with the Ngnix configuration, not Rsbuild. If you consider it to be a problem with Rsbuild, can you give more details and the expected behaviour?

**Comment by siddjellali** [comment]
Unfortunately, I have no debug information in rsbuild.

The main URL works in the application, and the sub-URLs (routes) also function correctly. 
However, when using a `server`, refreshing the page with F5 in the browser results in a **404 error.**

What's strange is that it works when using `rsbuild preview`. 
It's as if some elements are missing in the dist generated by rsbuild.

Please find the result of rsbuild inspect

```
export default {
  tools: {
    swc: {
      jsc: {
        parser: {
          syntax: 'typescript',
          tsx: true
        },
        transform: {
          react: {
            development: false,
            refresh: false,
            runtime: 'automatic'
          }
        }
      }
    },
    cssExtract: {
      loaderOptions: {},
      pluginOptions: {
        ignoreOrder: true
      }
    },
    rspack: {
      output: {
        uniqueName: 'settings'
      },
      plugins: [
        false
      ]
    }
  },
  html: {
    meta: {
      charset: {
        charset: 'UTF-8'
      },
      viewport: 'width=device-width, initial-scale=1.0'
    },
    title: 'Rsbuild App',
    inject: 'head',
    mountId: 'root',
    crossorigin: false,
    outputStructure: 'flat',
    scriptLoading: 'defer'
  },
  source: {
    alias: {
      '@types': './src/types.d.ts',
      '@utils': './src/utils',
      '@components': './src/components',
      '@request': './src/utils/request',
      '@hook': './src/utils/request/hook'
    },
    define: {
      'import.meta.env.APP_API_ENDPOINT_URI': '"/api"',
      'import.meta.env.APP_API_HOSTNAME': '"dev.intra.com"',
      'process.env': {}
    },
    aliasStrategy: 'prefer-tsconfig',
    preEntry: [],
    decorators: {
      version: '2022-03'
    },
    entry: {
      index: './src/index.tsx'
    },
    tsconfigPath: 'C:\\Users\\sdj\\WebstormProjects\\web-settings\\app\\tsconfig.json',
    include: [
      /@module-federation[\\/]sdk/,
      /@module-federation[\\/]runtime/
    ]
  },
  output: {
    target: 'web',
    cleanDistPath: 'auto',
    distPath: {
      root: 'dist',
      css: 'static/css',
      svg: 'static/svg',
      font: 'static/font',
      html: './',
      wasm: 'static/wasm',
      image: 'static/image',
      media: 'static/media',
      js: 'static/js'
    },
    assetPrefix: '/',
    filename: {},
    charset: 'utf8',
    polyfill: 'off',
    dataUriLimit: {
      svg: 4096,
      font: 4096,
      image: 4096,
      media: 4096
    },
    legalComments: 'linked',
    injectStyles: false,
    minify: true,
    manifest: false,
    sourceMap: {
      js: undefined,
      css: false
    },
    filenameHash: true,
    inlineScripts: false,
    inlineStyles: false,
    cssModules: {
      auto: true,
      namedExport: false,
      exportGlobals: false,
      exportLocalsConvention: 'camelCase'
    },
    emitAssets: true
  },
  security: {
    nonce: '',
    sri: {
      enable: false
    }
  },
  performance: {
    profile: false,
    buildCache: true,
    printFileSize: true,
    removeConsole: false,
    removeMomentLocale: false,
    chunkSplit: {
      strategy: 'custom'
    }
  },
  mode: 'production',
  plugins: [
    {
      name: 'rsbuild:react',
      setup: function () { /* omitted long function */ }
    },
    {
      name: 'rsbuild:basic-ssl',
      setup: function () { /* omitted long function */ }
    }
  ],
  moduleFederation: {
    options: {
      name: 'settings',
      filename: 'settings.js',
      exposes: {
        './main': './src/main.tsx'
      },
      shared: {
        react: {
          singleton: true,
          eager: true,
          requiredVersion: '^18.3.1'
        },
        'react-dom': {
          singleton: true,
          eager: true,
          requiredVersion: '^18.3.1'
        },
        'socket.io-client': {
          singleton: true,
          eager: true,
          requiredVersion: '^4.8.0'
        },
        'react-router-dom': {
          requiredVersion: '^6.26.2'
        },
        'react-redux': {
          singleton: true,
          eager: true,
          requiredVersion: '^9.1.2'
        },
        '@reduxjs/toolkit': {
          singleton: true,
          eager: true,
          requiredVersion: '^2.2.7'
        }
      },
      dts: true
    }
  },
  _privateMeta: {
    configFilePath: 'C:\\Users\\sdj\\WebstormProjects\\web-settings\\app\\rsbuild.config.ts'
  },
  root: 'C:\\Users\\sdj\\WebstormProjects\\web-settings\\app',
  dev: {
    hmr: true,
    assetPrefix: 'https://localhost:3006',
    liveReload: true,
    writeToDisk: false,
    client: {
      path: '/rsbuild-hmr',
      port: 3006,
      host: '',
      overlay: true,
      reconnect: 100
    }
  },
  server: {
    port: 3006,
    host: '0.0.0.0',
    open: false,
    htmlFallback: 'index',
    compress: true,
    printUrls: true,
    strictPort: true,
    headers: {
      'Access-Control-Allow-Origin': 'https://localhost:3000',
      'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, PATCH, OPTIONS',
      'Access-Control-Allow-Headers': 'X-Requested-With, content-type, Authorization'
    },
    https: {
      key: '-----BEGIN RSA PRIVATE KEY-----\r\nMIIEowIBAAKCAQEAkQNJ0aZGOz<LIMITED>QEAkQRJt\r\n-----END CERTIFICATE-----\r\n',
      cert: '-----BEGIN RSA PRIVATE KEY-----\r\nMIIEowIBAAKCAQEAkQNJ0aOzll7<LIMITED>zyBRRJt\r\n-----END CERTIFICATE-----\r\n'
    }
  },
  pluginNames: [
    'rsbuild:basic',
    'rsbuild:entry',
    'rsbuild:cache',
    'rsbuild:target',
    'rsbuild:output',
    'rsbuild:resolve',
    'rsbuild:file-size',
    'rsbuild:clean-output',
    'rsbuild:asset',
    'rsbuild:html',
    'rsbuild:app-icon',
    'rsbuild:wasm',
    'rsbuild:moment',
    'rsbuild:node-addons',
    'rsbuild:define',
    'rsbuild:css',
    'rsbuild:minimize',
    'rsbuild:progress',
    'rsbuild:swc',
    'rsbuild:externals',
    'rsbuild:split-chunks',
    'rsbuild:inline-chunk',
    'rsbuild:rsdoctor',
    'rsbuild:resource-hints',
    'rsbuild:performance',
    'rsbuild:bundle-analyzer',
    'rsbuild:server',
    'rsbuild:manifest',
    'rsbuild:module-federation',
    'rsbuild:rspack-profile',
    'rsbuild:lazy-compilation',
    'rsbuild:sri',
    'rsbuild:nonce',
    'rsbuild:react',
    'rsbuild:basic-ssl'
  ]
}
```
