### ISSUE TITLE
[Bug]: Upgrade sass-embedded to 1.80.3 or pin to 1.79.4

### ISSUE THREAD

**Issue by hustcer** [web-infra-dev/rsbuild#3759]
### Version

@rsbuild/* latest version

### Details

More details could be found here: https://github.com/sass/dart-sass/issues/2397#event-14728321070

### Reproduce link

https://github.com/sass/dart-sass/issues/2397#event-14728321070

### Reproduce Steps

https://github.com/sass/dart-sass/issues/2397#event-14728321070

**Comment by chenjiahan** [comment]
Thanks for the report, Rsbuild will bump the sass-embedded to 1.80.3 in the next release

https://github.com/web-infra-dev/rsbuild/pull/3763
