### ISSUE TITLE
[Bug]: Rsbuild compiled vuex-module-decorators error，Normal vuex-module-decorators on webpack 5

### ISSUE THREAD

**Issue by Dengpei1688** [web-infra-dev/rsbuild#3779]
### Version

最新Rsbuild 版本

chrome浏览器

"vuex-module-decorators": "^0.9.9"

### Details

项目为vue2.7  + vuex + ts的项目，在webpack5上运行正常，

迁移到rsbuild上vuex-module-decorators运行报错，

![Image](https://github.com/user-attachments/assets/4953b15d-dcad-44fd-9161-fd6aa1722945)

### Reproduce link

暂无,请问rsbuild的SWC模式是否有提供对于 vuex-module-decorators 的支持？

### 请问rsbuild的SWC模式是否有提供对于 vuex-module-decorators 的支持？

```
import { defineConfig,loadEnv } from '@rsbuild/core'
import { pluginVue2 } from '@rsbuild/plugin-vue2'
import { pluginSass } from '@rsbuild/plugin-sass';
import vueLegacy from 'rsbuild-plugin-vue-legacy'

const path = require("path");
const { getPlatInfo } = require('./config')
getPlatInfo()
const { publicVars } = loadEnv({ prefixes: ['VUE_APP_'] });
export default defineConfig({
    output:{
        assetPrefix: '/',
        distPath:{
            root: 'static-center',
        }
    },
    server:{
        open: true,
        proxy: 
    },
    plugins: [pluginVue2(), vueLegacy(), pluginSass(
        {
        sassLoaderOptions: {
            implementation: require.resolve('sass'),
        },
        }
    )],
    html: {
        mountId: 'app',
        template: './public/index.html',
    },
    source: {
        define: publicVars,
        // 指定入口文件
        entry: {
            index: './src/main.ts',
        },
        include: ['vuex-module-decorators'],
        alias: {
            '@': path.resolve(__dirname, 'src'), // './src',
        },
    },
})

```

**Comment by 9aoy** [comment]
try `source.decorators: 'legacy'`, it's equivalent to TypeScript's `experimentalDecorators: true`.
https://rsbuild.dev/config/source/decorators#legacy

**Comment by Dengpei1688** [comment]
> try `source.decorators: 'legacy'`, it's equivalent to TypeScript's `experimentalDecorators: true`. https://rsbuild.dev/config/source/decorators#legacy

I have tried, but I have found new errors in the project

![Image](https://github.com/user-attachments/assets/8e865946-4e9f-4d23-9b39-251e0780dc9b)

**Comment by Dengpei1688** [comment]
Thank you for your guidance, source.decorators: 'legacy'
It is effective. 

The issue with the screenshot is due to a TS version problem, which resulted in only valid syntax becoming invalid
