### ISSUE TITLE
[Feature]: Multi-Environment Builds suport config dev.writeToDisk

### ISSUE THREAD

**Issue by me9rez** [web-infra-dev/rsbuild#3781]
### What problem does this feature solve?

During the electron application development phase, the main process code needs to be written to disk, but the rendering process does not need to be written to disk. It is hoped that the dev.writeToDisk option can be configured separately according to different environments. Currently, rsbuild v1.0.16 only supports global configuration of this option.

electron应用开发阶段时需要将主进程代码写入到磁盘，但渲染进程可以不写入磁盘，希望可以允许根据不同环境分开配置dev.writeToDisk选项，目前rsbuild v1.0.16版本仅支持全局配置该选项

### What does the proposed API look like?

![Image](https://github.com/user-attachments/assets/cbe52126-b23e-4495-9815-5a3c65a02a3c)

**Comment by chenjiahan** [comment]
@9aoy Is it possible for the Rsbuild dev server to support this?

**Comment by 9aoy** [comment]
It needs to be supported in `rsbuild-dev-middleware`, I can take a look.
