### ISSUE TITLE
[Bug]: Rsbuild cannot parse jsx syntax appearing in js files in vue2

### ISSUE THREAD

**Issue by Dengpei1688** [web-infra-dev/rsbuild#3794]
### Version

rsbuild最新版本

项目vue2

### Details

在vue2项目，js文件中采用jsx语法，在webpack5中运行正常，

接入rsbuild后，提示语法错误： Expected '>', got 'class'

### Reproduce link

May I ask what specific configuration is required ？

### Reproduce Steps

In the Vue2 project, the jsx syntax is used in the js file, and it runs normally in webpack 5,

After connecting rsbuild, a syntax error message appears

**Comment by chenjiahan** [comment]
See: https://github.com/web-infra-dev/rsbuild/issues/2599
