### ISSUE TITLE
[Bug]: Does rsbuild support parsing Vux developed with Vue2? Does it also support vux-cli3-loader?

### ISSUE THREAD

**Issue by Dengpei1688** [web-infra-dev/rsbuild#3796]
### Version

rsbuild最新版本

UI框架：vux (vue2开发的)
按需打包插件： vux-cli3-loader

### Details

Does rsbuild support parsing Vux developed with Vue2? 

Does it also support vux-cli3-loader?

Currently, there are parsing errors in the project

![Image](https://github.com/user-attachments/assets/efa98bc2-b976-4eff-a4da-9b1424005a31)

![Image](https://github.com/user-attachments/assets/93b3b152-c008-4679-abc3-e508f79d58a2)

### Reproduce link

https://github.com/airyland/vux

### Reproduce Steps

Does rsbuild support parsing Vux developed with Vue2? 

Does it also support vux-cli3-loader ?

Thank you to help

**Comment by chenjiahan** [comment]
We have not tested this loader and have no plans to do so, you can ask the loader maintainer.
