### ISSUE TITLE
[Bug]:  it cant works, process is not defined

### ISSUE THREAD

**Issue by 0x083X** [web-infra-dev/rsbuild#3834]
### Version

System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
    Memory: 4.47 GB / 15.42 GB
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @rsbuild/core: ^1.0.17 => 1.0.17 
    @rsbuild/plugin-babel: ^1.0.2 => 1.0.2 
    @rsbuild/plugin-less: ^1.0.2 => 1.0.2 
    @rsbuild/plugin-react: ^1.0.5 => 1.0.5 
    @rsbuild/plugin-vue2: ^1.0.1 => 1.0.1 
    @rsbuild/plugin-vue2-jsx: ^1.0.2 => 1.0.2

### Details

i want to replace vue/cli with rsbuild

see some data in [define](https://rsbuild.dev/zh/guide/advanced/env-vars#%E4%BD%BF%E7%94%A8-define), which can let me use process in browser

i follow it, but i fail and the error is 'process is not defined'

![Image](https://github.com/user-attachments/assets/ae4dc644-9ca2-4863-b572-ffb450c3eb8e)

but i use  

``` js
define: {
      'process.env': JSON.stringify(process.env),
 }
```

it works

### Reproduce link

no

### Reproduce Steps

no

**Comment by chenjiahan** [comment]
See https://rsbuild.dev/guide/advanced/env-vars#identifiers-matching

![Image](https://github.com/user-attachments/assets/aee7c544-756e-4ae2-874a-2325bd03cee7)
