### ISSUE TITLE
[Bug]: plugin-less@1.0.3 not have include option

### ISSUE THREAD

**Issue by 729993031** [web-infra-dev/rsbuild#3848]
### Version

npmPackages: 1.0.3

### Details

# Bug
The newly versions, index.d.ts not have include options
![Image](https://github.com/user-attachments/assets/863069d6-cdd9-4937-9604-cb0cd2da8a8d)

### Reproduce link

https://github.com/web-infra-dev/rsbuild/blob/735ec4d492db2046c8a112fe657120b2b39505c2/packages/plugin-less/src/index.ts#L57

### Reproduce Steps

 empty

**Comment by chenjiahan** [comment]
The new `include` option hasn't been released yet.

![Image](https://github.com/user-attachments/assets/0ff2ad1c-9552-4a4c-8956-8ae72fd0ac81)
