### ISSUE TITLE
[Bug]: worker-rspack-loader is doesnt work

### ISSUE THREAD

**Issue by curlykay** [web-infra-dev/rsbuild#3851]
### Version

  System:
    OS: macOS 14.7
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 30.73 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 130.0.6723.70
    Edge: 130.0.2849.56
    Safari: 18.0.1
  npmPackages:
    @rsbuild/core: ^1.0.16 => 1.0.18 
    @rsbuild/plugin-vue2: ^1.0.1 => 1.0.1 

### Details

I use vue-pdf in my project, and vue-pdf uses work-loader inline.
```js
// node_modules/vue-pdf/src/vuePdfNoSss.vue

...
var PdfjsWorker = require('worker-loader!pdfjs-dist/es5/build/pdf.worker.js');
PDFJS.GlobalWorkerOptions.workerPort = new PdfjsWorker();
...
```

I used the worker-rspack-loader in reference to the [rsbuild documentation](https://rsbuild.dev/zh/guide/basic/web-workers#%E4%BD%BF%E7%94%A8-worker-loader) 
```ts
// rsbuild.config.ts
import { defineConfig } from '@rsbuild/core';
import { pluginVue2 } from '@rsbuild/plugin-vue2';
import path from 'path';

export default defineConfig({
  source: {
    include: [path.dirname(require.resolve('vue-pdf'))],
    alias: {
      'worker-loader': require.resolve('worker-rspack-loader')
    },
    define: {
      'process.env.VUE_ENV': JSON.stringify('browser'),
    },
  },
  plugins: [pluginVue2()],
  tools: {
    rspack(config, { addRules }) {
      addRules([
        {
          test: /\.pdf$/,
          // 将资源转换为单独的文件，并且导出产物地址
          type: 'asset/resource',
        },
        {
          test: /\.worker\.js$/,
          loader: 'worker-rspack-loader',
        },
      ]);

    }
  }
});
```

But when I run `rsbuild dev`, the terminal still throws the error
```zsh
# error
error   Compile error: 
Failed to compile, check the errors for troubleshooting.
File: /Users/user/Space/fiddle/vue-pdf/node_modules/.pnpm/pdfjs-dist@2.6.347/node_modules/pdfjs-dist/es5/build/pdf.worker.js:1:1
  × Module build failed:
  ╰─▶   × Worker Loader
        │
        │ This loader is only usable with webpack
        │
        │
```

I'm temporarily using a pnpm patch to modify the vue-pdf source code to fix the problem, but I have a lot of projects that I want to migrate to rsbuild, and duplicating the pnpm patch is a pain in the ass .
So what is the correct way to use vue-pdf if configured via rsbuild?

### Reproduce link

https://github.com/curlykay/issue-rsbuild-and-vue-pdf

### Reproduce Steps

1. run 'pnpm i && pnpm run dev'
2. check the error log

**Comment by 9aoy** [comment]
If you want to use `vue-pdf`(which depends on `worker-loader`), in rsbuild project, you currently need to do the following:
- Use `pnpm overrides` to replace `worker-loader` with `worker-rspack-loader` (peerDeps is set to webpack 4 in `worker-loader`, which will cause resolve exception)
- Use `resolveLoader` to replace `worker-loader` with `worker-rspack-loader` (not `source.alias`). And the `esModule:false` parameter is required. see https://rspack.dev/guide/features/web-workers#worker-loader


![Image](https://github.com/user-attachments/assets/9008da0d-4141-4d60-84f6-b539bc31b5ba)


![Image](https://github.com/user-attachments/assets/5c56898f-39e3-4b86-bda5-c40a89d542b0)



It seems like maybe `worker-rspack-loader` should not be compatible with webpack4, which would save a lot of trouble.

**Comment by curlykay** [comment]
Thank you for your answer, it work


> Use pnpm overrides to replace worker-loader with worker-rspack-loader (peerDeps is set to webpack 4 in worker-loader, which will cause resolve exception)

In my tests it seems to work successfully with vue-pdf (with work-loader) without the need for `pnpm overrides`, can you tell me what edge cases the addition of `pnpm overrides` is meant to handle?

**Comment by 9aoy** [comment]
When worker-rspack-loader (worker-loader) checks the webpack version, it is possible to solve webpack 4. This depends on the dependency installation of pnpm and may not necessarily be present.
https://github.com/rspack-contrib/worker-rspack-loader/blob/master/src/index.js#L18

**Comment by curlykay** [comment]
Thank you very mach ! I see, the pnpm overrides here are an insurance policy to stabilize the correct parsing of the worker-rspack-loader

One more thing I would like to ask, I checked the documentation for [source.alias](https://rsbuild.dev/zh/config/source/alias) and [resolveLoader.alias](https://rspack.dev/zh/config/resolve-loader)  and did a simple test.
Is it true that source.alias only works for user code and not for dependent code in node_modules? Even though source.include contains dependencies that need to take effect.
```js
source: {
    include: [path.dirname(require.resolve('vue-pdf'))],
    alias: {
      'worker-loader': `${require.resolve('worker-rspack-loader')}?esModule=false`
    },
    define: {
      'process.env.VUE_ENV': JSON.stringify('browser'),
    },
  },
```

comparison

```js
config.resolveLoader = {
         alias: {
          'worker-loader': `${require.resolve('worker-rspack-loader')}?esModule=false`
        }
     }
}
```

source.alias does fail anyway

**Comment by 9aoy** [comment]
`source.alias` can work for dependent code in `node_Modules`, but not for `loaders`. only `resolveLoader` can affect the resolution of `loaders`.

**Comment by curlykay** [comment]
Ok, I see the instructions in the resolveLoader documentation for rspack, but I don't see the instructions in reslove, maybe a two-way note is needed for the loader's proprietary parsing api usage.

![Image](https://github.com/user-attachments/assets/d9a57b7a-9984-42f0-981f-61177e46e719)
![Image](https://github.com/user-attachments/assets/02b4014d-deed-40d5-b55c-43004d8374a7)

Finally, thank you so much for helping me out and patiently answering my questions!

**Comment by curlykay** [comment]
> When worker-rspack-loader (worker-loader) checks the webpack version, it is possible to solve webpack 4. This depends on the dependency installation of pnpm and may not necessarily be present. https://github.com/rspack-contrib/worker-rspack-loader/blob/master/src/index.js#L18

You are right, in our ci worker-rspack-loader solve webpack 4, solved the problem using your suggested pnpm override🫡, looking forward to the release of a new version of worker-rspack-loader carrying this pr.
