### ISSUE TITLE
[Bug]: Compile Errors

### ISSUE THREAD

**Issue by tongSir-shuai** [web-infra-dev/rsbuild#3856]
### Version

  System:
    OS: macOS 15.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 555.02 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 130.0.6723.70
    Safari: 18.0
  npmPackages:
    @rsbuild/core: ^1.0.1-beta.6 => 1.0.18 
    @rsbuild/plugin-sass: ^1.0.1-beta.6 => 1.0.4 
    @rsbuild/plugin-vue2: ^1.0.1-beta.6 => 1.0.1 

### Details

Very strange problem, after migration, at least dozens of files cannot be compiled, I don't know where the problem lies
![Image](https://github.com/user-attachments/assets/64f30adf-b93d-47a7-ad59-008ac920a94b)
The configuration of rsbuild.config.mjs is as follows
![Image](https://github.com/user-attachments/assets/31dd1e00-8fb1-4c2d-87c9-a3925c69c25c)

### Reproduce link

https://gitee.com/An_ordinary_day/rspack.git

### Reproduce Steps

run cnpm i && cnpm dev

**Comment by 9aoy** [comment]
The Rsbuild Vue 2 plugin only supports Vue >= 2.7.0, Please upgrade to Vue 2.7 and try again. see https://github.com/web-infra-dev/rspack/issues/6768

**Comment by tongSir-shuai** [comment]
> The Rsbuild Vue 2 plugin only supports Vue >= 2.7.0, Please upgrade to Vue 2.7 and try again. see [web-infra-dev/rspack#6768](https://github.com/web-infra-dev/rspack/issues/6768)

Thanks, solved it
