### ISSUE TITLE
[Bug]: Build Compile Warning

### ISSUE THREAD

**Issue by tongSir-shuai** [web-infra-dev/rsbuild#3859]
### Version

System:
    OS: macOS 15.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 71.88 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 130.0.6723.70
    Safari: 18.0
  npmPackages:
    @rsbuild/core: ^1.0.1-beta.6 => 1.0.18 
    @rsbuild/plugin-sass: ^1.0.1-beta.6 => 1.0.4 
    @rsbuild/plugin-vue2: ^1.0.1-beta.6 => 1.0.1 

### Details

![Image](https://github.com/user-attachments/assets/002efa5d-c982-4e2c-8ff1-dec0b0e0cc9a)
![Image](https://github.com/user-attachments/assets/59a73fc6-7367-4f24-9a4e-0dd2c3851b2e)
warn    Compile Warning: 
⚠ Unsupported pseudo class or element: export at static/css/index.bf08089e.css:15180:2

⚠ Unsupported pseudo class or element: export at static/css/index.bf08089e.css:15477:2

⚠ Unsupported pseudo class or element: export at static/css/index.bf08089e.css:16604:19

File: /Users/tonghao/Documents/GitHub/abroad_advertise_view/src/views/material/components/index.css:1:1
  ⚠ ModuleWarning: resolve-url-loader: webpack misconfiguration
  │   webpack or the upstream loader did not supply a source-map (from: /Users/tonghao/Documents/GitHub/abroad_advertise_view/node_modules/_@rsbuild_plugin-sass@1.0.4@@rsbuild/plugin-sass/compiled/resolve-url-loader/index.js??clonedRuleSet-22.use[4])
  │     at encodeError (/Users/tonghao/Documents/GitHub/abroad_advertise_view/node_modules/_@rsbuild_plugin-sass@1.0.4@@rsbuild/plugin-sass/compiled/resolve-url-loader/index.js:910:18)
  │     at handleAsWarning (/Users/tonghao/Documents/GitHub/abroad_advertise_view/node_modules/_@rsbuild_plugin-sass@1.0.4@@rsbuild/plugin-sass/compiled/resolve-url-loader/index.js:901:32)
  │     at Object.resolveUrlLoader (/Users/tonghao/Documents/GitHub/abroad_advertise_view/node_modules/_@rsbuild_plugin-sass@1.0.4@@rsbuild/plugin-sass/compiled/resolve-url-loader/index.js:847:11)
  │     at LOADER_EXECUTION (/Users/tonghao/Documents/GitHub/abroad_advertise_view/node_modules/_@rspack_core@1.0.14@@rspack/core/dist/index.js:10363:18)
  │     at runSyncOrAsync2 (/Users/tonghao/Documents/GitHub/abroad_advertise_view/node_modules/_@rspack_core@1.0.14@@rspack/core/dist/index.js:10364:6)
  │     at node:internal/util:364:7
  │     at new Promise (<anonymous>)
  │     at runSyncOrAsync2 (node:internal/util:350:12)
  │     at runLoaders (/Users/tonghao/Documents/GitHub/abroad_advertise_view/node_modules/_@rspack_core@1.0.14@@rspack/core/dist/index.js:10833:54)

### Reproduce link

https://gitee.com/An_ordinary_day/rspack.git

### Reproduce Steps

npm i && npm dev

**Comment by 9aoy** [comment]
This problem cannot be reproduced through the repository you provided. It seems that the rsbuild configuration is different.

![Image](https://github.com/user-attachments/assets/f7e26db4-ac67-4a4b-b7d9-9bc5845155c7)

**Comment by tongSir-shuai** [comment]
h

> This problem cannot be reproduced through the repository you provided. It seems that the rsbuild configuration is different.
> 
> ![Image](https://github.com/user-attachments/assets/f7e26db4-ac67-4a4b-b7d9-9bc5845155c7)

Thank you, I have solved this problem. Now I have a new problem. The S3Plugin plugin does not perform upload during the build process. Can you please help me check whether my way of registering the plugin is wrong, or is S3 upload not supported yet?
![Image](https://github.com/user-attachments/assets/c0d992fb-4901-42d3-aeb9-812b78792427)

**Comment by 9aoy** [comment]
s3Plugin can get the files, so it doesn't seem to be a build problem.

https://github.com/MikaAK/s3-plugin-webpack/blob/master/src/s3_plugin.js#L127

![Image](https://github.com/user-attachments/assets/7657be0d-069b-4e68-8b86-4d7daeb9fdbb)

**Comment by tongSir-shuai** [comment]
> s3Plugin can get the files, so it doesn't seem to be a build problem.
> 
> https://github.com/MikaAK/s3-plugin-webpack/blob/master/src/s3_plugin.js#L127
> 
> ![Image](https://github.com/user-attachments/assets/7657be0d-069b-4e68-8b86-4d7daeb9fdbb)

![Image](https://github.com/user-attachments/assets/8513d806-d41f-4dac-af5e-f52c9a952509)
This is the packaged index.html file, but when I visit the address https://material.kwmobi.com/advertise_frontend_prod/dist/public/static/js/2254.3a4032e5.js, there is no data, and no related files are found in the AWS backend. What is the reason?

**Comment by tongSir-shuai** [comment]
Is it true that the upload will not be executed in a non-webpack build environment? Because I can successfully upload it when I build in a webpack environment

**Comment by chenjiahan** [comment]
Based on the information provided, this issue does not appear to be caused by Rsbuild, so this issue will be closed.
