### ISSUE TITLE
[Feature]: Support extending the default value of `resolve.*`

### ISSUE THREAD

**Issue by colinaaa** [web-infra-dev/rsbuild#3864]
### What problem does this feature solve?

A common use case for `resolve.*` would be extends the default value.

E.g.: I would like to add `.foo.js` at the beginning of the `resolve.extensions`:

```js
// rspack.config.js
export default {
  resolve: {
    extensions: ['.foo.js', '.ts', '.tsx', '.mjs', '.js', '.jsx', '.json'],
  },
}
```

I cannot do that by using a plain object in `tools.rspack`:

```js
// rsbuild.config.js
export default {
  tools: {
    rspack: {
      resolve: {
        extensions: ['.foo.js'] // Results `['.ts', '.tsx', '.mjs', '.js', '.jsx', '.json', '.foo.js']`
      }
    }
  }
}
```

Currently, I could make a workaround by using `tools.bundleChain` or `tools.rspack` as a function:

```javascript
  tools: {
    bundlerChain(chain) {
      chain
        .resolve
        .extensions
        .prepend('.foo.jsx')
    },
  },
```

```javascript
  tools: {
    rspack(config) {
      config.resolve ??= {}
      config.resolve.extensions ??= []
      config.resolve.extensions = [
        '.foo.jsx',
        ...config.resolve.extensions,
      ]
    },
  },
```

### What does the proposed API look like?

> [!CAUTION]
> This is a breaking change to the current behavior

1. `tools.rspack.resolve.*` should override other than extends the default value

```js
// rsbuild.config.js
export default {
  tools: {
    rspack: {
      resolve: {
        extensions: ['.foo.js'] // Results in `['.foo.js']`
      }
    }
  }
}
```

2. If **extends** is preferred, use `...` instead

```js
// rsbuild.config.js
export default {
  tools: {
    rspack: {
      resolve: {
        extensions: ['.foo.js', '...'] // Results in `['.foo.js', '.ts', '.tsx', '.mjs', '.js', '.jsx', '.json']`
      }
    }
  }
}
```

```js
// rsbuild.config.js
export default {
  tools: {
    rspack: {
      resolve: {
        extensions: [ '...', '.foo.js'] // Results in `['.ts', '.tsx', '.mjs', '.js', '.jsx', '.json', '.foo.js']`
      }
    }
  }
}
```

**Comment by chenjiahan** [comment]
As this is a breaking change and is the default behavior of [webpack-merge](https://github.com/survivejs/webpack-merge), we currently have no plans to change it.

The [tools.rspack](https://rsbuild.dev/config/tools/rspack) documentation already explains this behavior:

![Image](https://github.com/user-attachments/assets/c70565e6-9599-47b9-92ae-8b70d88eebac)

**Comment by chenjiahan** [comment]
Rsbuild now provides https://rsbuild.dev/config/resolve/extensions to align with Rspack/Vite and it can override the default value.
