### ISSUE TITLE
[Feature]: Support using `ProvidePlugin` with configuration

### ISSUE THREAD

**Issue by colinaaa** [web-infra-dev/rsbuild#3875]
### What problem does this feature solve?

Just like [`source.define`](https://rsbuild.dev/config/source/define) uses [`DefinePlugin`](https://rspack.dev/plugins/webpack/define-plugin), `source.provide` uses [`ProvidePlugin`](https://rspack.dev/plugins/webpack/provide-plugin).

This is useful for plugin to override other plugin's provides.

## Real world use case

We have 2 plugins. 

- `pluginA` which provides `Foo` and `Bar`
- `pluginB` which also provides `Foo`, but overrides `pluginA`

Currently, the only way to override the `Foo` in `pluginB` is to use `bundlerChain`:

```js
// pluginA
api.modifyBundlerChain(chain => {
  chain.plugin('provide.foo').use(ProvidePlugin, [{ Foo: 'path/to/foo' }])
  chain.plugin('provide.bar').use(ProvidePlugin, [{ Foo: 'path/to/foo' }])
})

// pluginB
api.modifyBundlerChain(chain => {
  chain.plugin('provide.foo').use(ProvidePlugin, [{ Foo: 'path/to/overrided-foo' }])
})
```

### What does the proposed API look like?

A new configuration `source.provide` is added.

```js
export default {
  source: {
    provide: {
      Foo: [require.resolve('foo'), 'default'],
      Bar: require.resolve('bar'),
    },
  },
}
```

**Comment by chenjiahan** [comment]
Rsbuild added support for `source.define` because it is a popular feature and almost every application uses it.

But for `ProvidePlugin`, I think only a few applications or tools use this plugin, so I prefer to keep it as an opt-in plugin rather than wrap it as an Rsbuild configuration option.

**Comment by lanten** [comment]
@chenjiahan 
If I want to use ProvidePlugin , I need to add `webpack` dependency to `package.json`, because it's built-in.
And this plugin has a wide range of usage scenarios. For me, it is a must
