### ISSUE TITLE
[Bug]: Rsbuild handles inline style errors

### ISSUE THREAD

**Issue by coderwyd** [web-infra-dev/rsbuild#3917]
### Version

  System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 7.87 GB / 31.72 GB
  Browsers:
    Edge: Chromium (127.0.2651.105)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @rsbuild/core: ^1.1.0 => 1.0.19
    @rsbuild/plugin-vue2: ^1.0.1 => 1.0.1

### Details

When I used inline styles in my vue2 project, I found that when I formatted the code through prettier, line breaks caused the styles to be lost.

![Image](https://github.com/user-attachments/assets/b16585c0-2cc9-4cf2-b02d-76fa41dac373)
![Image](https://github.com/user-attachments/assets/daadeb9a-76a3-457b-9b18-6fbf7547d302)

### Reproduce link

https://github.com/coderwyd/rsbuild-repo

### Reproduce Steps

pnpm i 
pnpm dev

**Comment by chenjiahan** [comment]
I tried Vite and got the same result.

![Image](https://github.com/user-attachments/assets/0a24adef-5a47-4621-a5ad-d74af18962d6)

So this should be a problem with the Vue 2 compiler itself rather than Rsbuild.

To fix this, I would recommend using Vue's object syntax to define `style`:

```html
<div
  :style="{
    background: 'linear-gradient(270deg,rgba(0, 0, 0, 0.8) 1%,rgba(0, 0, 0, 0.6) 97%)',
  }"
>
  test
</div>
```
