### ISSUE TITLE
[Bug]: Window system compilation error Cannot find module 'webpack/lib/rules/BasicEffectRulePlugin'

### ISSUE THREAD

**Issue by tongSir-shuai** [web-infra-dev/rsbuild#3925]
### Version

  System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 12th Gen Intel(R) Core(TM) i3-12100
    Memory: 1.77 GB / 15.78 GB
  Browsers:
    Edge: Chromium (128.0.2739.42)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @rsbuild/core: ^1.0.1-beta.6 => 1.1.0
    @rsbuild/plugin-node-polyfill: ^1.2.0 => 1.2.0
    @rsbuild/plugin-sass: ^1.0.1-beta.6 => 1.1.0
    @rsbuild/plugin-vue2: ^1.0.1-beta.6 => 1.0.1

### Details

![Image](https://github.com/user-attachments/assets/e28b7204-8cda-4a0e-a72b-7ad335222f33)
I tried on several computers, but none of them worked. They all reported the same error. The node version is 16. How can I solve this problem?

### Reproduce link

https://gitee.com/An_ordinary_day/rspack_test

### Reproduce Steps

npm i && npm run dev

**Comment by 9aoy** [comment]
webpack is vue-loader's peerDeps, it looks like you should install webpack.

**Comment by tongSir-shuai** [comment]
> webpack is vue-loader's peerDeps, it looks like you should install webpack.

What is the specific reason? Why doesn't the Mac system need to be installed separately? Does Windows need to be installed? How troublesome is that? Is there a solution?

**Comment by tongSir-shuai** [comment]
> webpack is vue-loader's peerDeps, it looks like you should install webpack.

There is another question. After packaging, all the styles are gone in the production environment. What is the reason?

**Comment by wllcyg** [comment]
webpack 未安装,或者webpack 低于 5.0 版本,需要升级新版本

**Comment by chenjiahan** [comment]
> After packaging, all the styles are gone in the production environment. What is the reason?

As this is an independent question, you can create a new issue and provide a reproduction repo, thanks.
