### ISSUE TITLE
[Bug]: source.include node_modules makes package worker.js bundled

### ISSUE THREAD

**Issue by WangLeto** [web-infra-dev/rsbuild#3953]
### Version

```sh
System:
  OS: macOS 15.1
  CPU: (11) arm64 Apple M3 Pro
  Memory: 1.02 GB / 36.00 GB
  Shell: 5.9 - /bin/zsh
Browsers:
  Chrome: 130.0.6723.117
  Edge: 129.0.2792.89
  Safari: 18.1
npmPackages:
  @rsbuild/core: ^1.1.0 => 1.1.0 
  @rsbuild/plugin-react: ^1.0.6 => 1.0.7
```

### Details

[rsbuild-pdfjs-demo-main.zip](https://github.com/user-attachments/files/17725824/rsbuild-pdfjs-demo-main.zip)
 
There is a project zip for reproduction. My goal is to compile the worker.js from the indirect dependency pdfjs-dist, for better browser compatibility, but the `source.input` configuration causes it to be bundled with the main JS asset.

To restore a standard worker.js usage, comment out the `source.input` configuration item.

### Reproduce link

https://github.com/user-attachments/files/17725824/rsbuild-pdfjs-demo-main.zip

### Reproduce Steps

```shell
pnpm i
pnpm dev
```
1. See the network request, worker.js disappeared.
2. Comment out the `source.input` configuration
3. worker.js restored

**Comment by chenjiahan** [comment]
When the `pdf.worker.mjs` is added to the `source.include`, it will matches the JS transform rule and adds the "javascript/auto" module type, so that Rspack will treat it as a JavaScript module rather than a static asset.

**Comment by GRAMMAC1** [comment]
add
```ts
source: {
    include: [{ not: /[\\/]core-js[\\/]|[\\/]pdfjs-dist[\\/]/ }],
 }```
to `rsbuild.config.ts` will work. Based on the docs, Rsbuild will compile the `node_module` code if `source:{inlcude}` is added. Is there any approach to aviod this behaviour? @chenjiahan I tried rspack worker config `worker: ["pdfjs.GlobalWorkerOptions.workerSrc*"]`, but It doesn't work,

**Comment by chenjiahan** [comment]
@GRAMMAC1 The original goal is to "compile the worker.js", so we should not exclude `pdfjs-dist`
