### ISSUE TITLE
[Bug]: The hash of the script tag from the plugin hook is not the final hash of the JS asset

### ISSUE THREAD

**Issue by ChuHoMan** [web-infra-dev/rsbuild#3955]
### Version

```sh
System:
    OS: macOS 14.5
    CPU: (12) arm64 Apple M2 Pro
    Memory: 115.36 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 130.0.6723.119
    Edge: 112.0.1722.39
    Safari: 17.5
  npmPackages:
    @rsbuild/core: ^1.1.0 => 1.1.0 
    @rsbuild/plugin-react: ^1.0.7 => 1.0.7
```

### Details

My original idea was to get the path of the JS asset from the HTML plugin's hook, but I noticed that the hash of the JS asset I get in the plugin  is not the final hash of the JS asset in the dist. Could you let me know why this is happening? Is there any other way to get the correct path of the JS asset?

I've tried: `alterAssetTagGroups`,`api.modifyHTMLTags`, `beforeEmit`

![Image](https://github.com/user-attachments/assets/71da5d5f-97a5-45f6-b05a-07205a318e27)

### Reproduce link

https://codesandbox.io/p/devbox/djddtm

### Reproduce Steps

1. run   `pnpm i && pnpm build`
2. check the logs

**Comment by chenjiahan** [comment]
This is a known issue with the `html-webpack-plugin`, see https://github.com/jantimon/html-webpack-plugin/issues/1638

A workaround is to disable the [realContentHash](https://rspack.dev/config/optimization#optimizationrealcontenthash) optimization of Rspack and the hash value will remain unchanged.

```js
export default defineConfig({
  tools: {
    rspack: {
      optimization: {
        realContentHash: false,
      }
    }
  }
});
```

**Comment by chenjiahan** [comment]
To get the final hash of the JS assets, you can use the [Stats](https://rspack.dev/api/javascript-api/stats) object of Rspack:

```js
const myPlugin: RsbuildPlugin = {
  name: 'my-plugin',
  setup(api) {
    api.onAfterBuild(({ stats }) => {
      if (stats) {
        const { assets } = stats.toJson({ assets: true });
        console.log(assets);
      }
    });
  },
};
```

![Image](https://github.com/user-attachments/assets/49ee6753-3fe2-4f88-8547-24df21014ca8)

**Comment by ChuHoMan** [comment]
Okay, I understand what’s going on now. Thank you!
