### ISSUE TITLE
[Bug]: Migrate vue3 [vue-cli] to Rsbuild

### ISSUE THREAD

**Issue by runkobe24** [web-infra-dev/rsbuild#3968]
### System Info

  System:
    OS: Windows 11 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700
    Memory: 11.49 GB / 31.68 GB
  Binaries:
    Node: 18.20.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527

### Details

This is my current 【rsbuild.config.ts】 configuration:

```
import { defineConfig } from '@rsbuild/core';
// const path = require('path')
import { pluginVue } from '@rsbuild/plugin-vue';
import { pluginStylus } from '@rsbuild/plugin-stylus';
const { VueLoaderPlugin } = require("vue-loader");

export default defineConfig({
  dev: {
    assetPrefix: './'
  },

  
  html: {
    template: './public/index.html',
  },

  source: {
    // 指定入口文件
    entry: {
      index: './src/main.ts',
    },

    alias: {
      // '@': './src',
      antd: 'ant-design-vue'
    },
  },

  plugins: [
    pluginVue(),
    pluginStylus()
  ],
  
  tools: {
    rspack: {
      plugins: [new VueLoaderPlugin()],
      module: {
        rules: [
          {
            test: /\.styl(us)?$/,
            use: ['stylus-loader'],
          },
        ],
        
      },
    },
  },
});
```

### Reproduce Steps

1. yarn dev
2.  × Module build failed:
  ╰─▶   × Error: HookWebpackError:   × Module build failed:
        │   ╰─▶   × Error: RspackResolver(NotFound("/views/print/core/icomoon/style.styl"));
3. TypeError: expected rgba or hsla, but got ident:$primary-color； My variable style doesn't work either

**Comment by chenjiahan** [comment]
There is an invalid configuration, it does not configure the required `css-loader` and css-extract loader:

![Image](https://github.com/user-attachments/assets/3b815763-e03e-4544-92a9-64d323b91885)

You should delete it, because `@rsbuild/plugin-stylus` already has stylus-loader configured and everything is expected to be out-of-the-box.

**Comment by runkobe24** [comment]
> There is an invalid configuration, it does not configure the required `css-loader` and css-extract loader:
> 
> ![Image](https://github.com/user-attachments/assets/3b815763-e03e-4544-92a9-64d323b91885)
> 
> You should delete it, because `@rsbuild/plugin-stylus` already has stylus-loader configured and everything is expected to be out-of-the-box.

Okay, I have deleted it, but my stylus custom variable file is not referenced;
 **TypeError: expected rgba or hsla, but got ident:$primary-color**


![Image](https://github.com/user-attachments/assets/4e672f2a-fe71-48ce-8d53-94448e0ca98b)

**Comment by chenjiahan** [comment]
https://github.com/web-infra-dev/rsbuild/issues/3971
