### ISSUE TITLE
[Bug]: swc wrongly compiles ts decorator when developing

### ISSUE THREAD

**Issue by s-elo** [web-infra-dev/rsbuild#3973]
### Version

```sh
System:
    OS: macOS 13.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 160.67 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Brave Browser: 128.1.69.162
    Chrome: 130.0.6723.119
    Safari: 16.6
  npmPackages:
    @rsbuild/core: ^1.0.19 => 1.1.1 
    @rsbuild/plugin-vue2: ^1.0.1 => 1.0.2
```

### Details

[vue2-ts.zip](https://github.com/user-attachments/files/17745924/vue2-ts.zip)
looks like swc provides the ts decorator parameters wrongly for property decorator

snippet of @Prop decorator in vue-class-component:
![Image](https://github.com/user-attachments/assets/6ff21124-251d-4c36-b55c-598e1ff71266)

swc helper snippet:
![Image](https://github.com/user-attachments/assets/5be83abf-8c72-4245-80ae-245c497978ba)

### Reproduce link

https://github.com/user-attachments/files/17745924/vue2-ts.zip

### Reproduce Steps

pnpm i
pnpm dev

**Comment by 9aoy** [comment]
You should set `decorators.version: 'legacy'` to get support for property decorators.
https://rsbuild.dev/config/source/decorators#legacy

**Comment by s-elo** [comment]
> You should set `decorators.version: 'legacy'` to get support for property decorators. https://rsbuild.dev/config/source/decorators#legacy

oh I see, thx a lot master~
