### ISSUE TITLE
[Bug]: Uncaught ReferenceError: process is not defined when trying to use an Env variable

### ISSUE THREAD

**Issue by alex-vukov** [web-infra-dev/rsbuild#3975]
### Version

```sh
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 20.63 GB / 31.70 GB
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @rsbuild/core: ^1.1.1 => 1.1.1
    @rsbuild/plugin-react: ^1.0.7 => 1.0.7
```

### Details

Environment variables are not getting replaced in a clean Rsbuild project. You can check the reproduction repo. The env file is loaded using `loadEnv` but the `process.env.TEST_ENV_VAR` used in `App.tsx` is not found and I get an `Uncaught ReferenceError: process is not defined` error.

### Reproduce link

https://github.com/alex-vukov/rsbuild-issue

### Reproduce Steps

1. npm install
2. npm run dev
3. See the error in the browser

**Comment by hangCode2001** [comment]
But I think the explanation on the official website may not be clear enough.
In the following tutorial, only variables starting with **PUBLIC_** will be replaced.
If there is no PUBLIC_ prefixed variable in your **.env**, it will have no effect.
![Image](https://github.com/user-attachments/assets/ac68fcce-622d-42ca-b635-cc3ab46864b5)

**Comment by alex-vukov** [comment]
Thank you for responding! I don't understand why I need to specify the name of the variable in loadEnv. I can see that it's loaded inside the `parsed` object so it made sense to just pass it to `define`. Indeed the documentation is confusing about the usage.
