### ISSUE TITLE
[Bug]: Migrate vue3 [vue-cli] to Rsbuild 【HMR】

### ISSUE THREAD

**Issue by runkobe24** [web-infra-dev/rsbuild#3980]
### Version

```sh
System:
    OS: Windows 11 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700
    Memory: 11.77 GB / 31.68 GB
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @rsbuild/core: ^1.0.14 => 1.1.2
    @rsbuild/plugin-stylus: ^1.0.3 => 1.0.6
    @rsbuild/plugin-vue: ^1.0.2 => 1.0.5
```

### Details

yarn dev
运行成功后，打开网页并成功展示；
此时本地随便修改个代码并保存运行，此时控制台显示成功的编译了；![Image](https://github.com/user-attachments/assets/282da76c-e1a1-4aa7-8737-4892cff6b2aa)

但是网页白屏，并且打开控制台可以看到报错；
![Image](https://github.com/user-attachments/assets/64f6c458-6011-499e-b971-253fe6f3ae78)

### Reproduce link

https://codesandbox.io/p/devbox/exciting-mopsa-7jhpsw?file=%2Frsbuild.config.ts%3A26%2C30

### Reproduce Steps

yarn install;
yarn dev;
building成功后，打开网页，并修改本地文件，页面白屏+控制台报错；

**Comment by runkobe24** [comment]
![Image](https://github.com/user-attachments/assets/9dcafade-2db5-404b-a6c6-484e34f862ca)
不知道为什么是webpack的报错，我项目已经没用到了

**Comment by runkobe24** [comment]
必须要重新启动项目

**Comment by liuye1296** [comment]
我跑了下你  codesandbox 的代码没什么问题 
![Image](https://github.com/user-attachments/assets/ad7c4191-00de-4ad2-8098-c9358ea3175d)

**Comment by liuye1296** [comment]
因为没复现不好确定是什么问题。但是  代码 猜测 是 HOT 问题   看文档  rspack  在 HOT 那块是使用了 webpack的代码。你这可能是 HOT  版本没对上

**Comment by runkobe24** [comment]
> 因为没复现不好确定是什么问题。但是 代码 猜测 是 HOT 问题 看文档 rspack 在 HOT 那块是使用了 webpack的代码。你这可能是 HOT 版本没对上

有没有什么建议可以进行修改呢，卡在这搞不了了；

**Comment by runkobe24** [comment]
将rsbuild.config.ts中的这个 moduleIds 注释了就正常热更了
```
optimization: {
 //  moduleIds: 'deterministic',
}
```

**Comment by chenjiahan** [comment]
Since the issue cannot be reproduced, it will be closed.
