### ISSUE TITLE
[Bug]: cannot append third party scripts into html by using html tags while set config html inject: false

### ISSUE THREAD

**Issue by sbyps** [web-infra-dev/rsbuild#4015]
### Version

```sh
System:
    OS: macOS 14.6.1
    CPU: (11) arm64 Apple M3 Pro
    Memory: 90.97 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 130.0.6723.117
    Safari: 17.6
```

### Details

when we set config html inject: false, build scripts will not append into html;
but we also want to append third party scripts, and cannot work well while set config html inject: false;

### Reproduce link

https://github.com/sbyps/rspack-demo/tree/test

### Reproduce Steps

pnpm i
pnpm build
cat dist/index.html
cannot append eruda script file

**Comment by chenjiahan** [comment]
This is as expected, I have updated the documentation to make it clearer: https://github.com/web-infra-dev/rsbuild/pull/4049
