### ISSUE TITLE
[Bug]: assetPrefix to './' and font cannot load

### ISSUE THREAD

**Issue by linghaoSu** [web-infra-dev/rsbuild#4033]
### Version

```sh
System:
    OS: macOS 15.1.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 97.66 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 131.0.6778.71
    Chrome Canary: 133.0.6848.0
    Safari: 18.1.1
  npmPackages:
    @rsbuild/core: ^1.0.19 => 1.1.4 
    @rsbuild/plugin-sass: ^1.1.1 => 1.1.1 
    @rsbuild/plugin-vue: ^1.0.3 => 1.0.5
```

### Details

After setting assetPrefix to './', the corresponding font resources cannot be found, resulting in font loading failure.

### Reproduce link

https://github.com/linghaoSu/rsbuild-test-repo

### Reproduce Steps

pnpm i & pnpm dev

![Image](https://github.com/user-attachments/assets/90f0a135-6ddf-46fd-9f82-7cefbed5f8a7)

**Comment by huleiEthan** [comment]
In fact, we have some scenarios where the access link of the front - end link already includes a sub - directory, such as `https://test.com/a/b/index.html`. Here, we can only set the assetPrefix to a relative path. And our expectation for the prefix of static resources is to set it to a path like `./productA/assets/`. So using `auto` also cannot meet our needs. May I ask if there is any solution?

**Comment by huleiEthan** [comment]
> See https://rsbuild.dev/config/dev/asset-prefix#path-types
> 
> ![Image](https://github.com/user-attachments/assets/146cec50-7dbc-4000-a870-8048f7f74ab5)

In fact, we have some scenarios where the access link of the page link already includes a sub - directory, such as `https://test.com/a/b/index.html`. Here, we can only set the assetPrefix to a relative path. And our expectation for the prefix of static resources is to set it to a path like `./productA/assets/`. So using `auto` also cannot meet our needs. May I ask if there is any solution?
