### ISSUE TITLE
[Feature]: specify .env files

### ISSUE THREAD

**Issue by MuyianKing** [web-infra-dev/rsbuild#4040]
### What problem does this feature solve?

当存在多环境情况目前无法配置
![Image](https://github.com/user-attachments/assets/b211c7dd-97ee-481b-8d95-ef5a6f46770f)
图上开发环境和生产环境分别有三个配置

### What does the proposed API look like?
![Image](https://github.com/user-attachments/assets/9bdd61bc-44c9-4af2-be64-a90aca195f07)
希望可以对齐vite的启动和打包配置

**Comment by chenjiahan** [comment]
Rsbuild CLI provides the --env-mode option to specify env file, see: https://rsbuild.dev/guide/advanced/env-vars#env-mode

**Comment by MuyianKing** [comment]
> Rsbuild CLI provides the --env-mode option to specify env file, see: https://rsbuild.dev/guide/advanced/env-vars#env-mode
--mode 改为--env-mode就可以了，我是vite切过来的，这里有点不一样
