### ISSUE TITLE
[Feature]: Ability to exclude files from `printFileSize` plugin

### ISSUE THREAD

**Issue by mogelbrod** [web-infra-dev/rsbuild#4041]
### What problem does this feature solve?

Our rsbuild configuration outputs a large number of files, including many images of varying file sizes. This causes the arguably more interesting JS/CSS assets to be lost in the long list. It would be great if it was possible to provide a filtering function that allow users to exclude items from the printed list. The printed total size would ideally only sum the printed (included) files as well.

### What does the proposed API look like?

Suggested API:
```js
{
  performance: {
    printFileSize: {
      include: (filePath) => /\.(js|css)\b/.test(filePath)
    }
  }
}
```

**Comment by chenjiahan** [comment]
LGTM, Rsbuild will provide this option in the next release.
