### ISSUE TITLE
[Bug]: When unknown browser version used, all polyfills are added to the bundle

### ISSUE THREAD

**Issue by erykpiast** [web-infra-dev/rsbuild#4070]
### Version

```sh
System:
    OS: macOS 14.6.1
    CPU: (11) arm64 Apple M3 Pro
    Memory: 874.61 MB / 36.00 GB
    Shell: 3.7.1 - /opt/homebrew/bin/fish
  Browsers:
    Chrome Canary: 133.0.6860.0
    Safari: 17.6
    Safari Technology Preview: 18.0
  npmPackages:
    @rsbuild/core: ^1.1.4 => 1.1.6
```

### Details

First of all, I'm sorry if it's a bug in Rspack or SWC - I use RSBuild (and I love it ❤️), I didn't check if the issue occurs in these tools. A quick search across all three issue trackers doesn't reveal already known bug.

The issue is when I use a browser version unknown for RSBuild in my `.browserlistrc`, instead of adding no transipilation and polyfills (this is the default `@babel/preset-env` behavior), everything is transpilled and polyfilled. That's a bit unfortunate, as the `browserslist-rs` tool used under the hood recognizes only browsers released before June 2024. [I've already submitted a PR updating the data in that repo](https://github.com/browserslist/browserslist-rs/pull/25). I'm afraid changing how to handle defaults it's beyond my Rust knowledge 😅

### Reproduce link

https://github.com/erykpiast/rsbuild-test

### Reproduce Steps

1. Install the dependencies:

    ```bash
    pnpm install
    ```

2. Build the app for production:

    ```bash
    pnpm build
    ```

3. Observe the JavaScript output artifact contains the generator polyfill.

4. Go to the `.browserslistrc` file and change the Chrome version to 125.

5. Build the app for production:

    ```bash
    pnpm build
    ```

6. Observe the JavaScript does not contain any polyfill.

**Comment by chenjiahan** [comment]
Thanks for your feedback! Rsbuild should ignore unknown values ​​like Babel does. We will fix this issue soon.

**Comment by chenjiahan** [comment]
I think this is a SWC issue. 

When you pass in the browserslist (targets) array, it should contain at least one recognized value. If all values are unknown, SWC will use the default browserslist (seems to be ES5).

- SWC + Chrome >= 130: https://play.swc.rs/?version=1.9.3&code=H4sIAAAAAAAAA0vOzysuUchPylKwVajmUlDQ09MDcox0uGoBdJ5oUBoAAAA%3D&config=H4sIAAAAAAAAA3VRQYrDMAy89xVG5x627K2HQukD9gFLWYyttC6yHSwnNJT8vYpJ3aSwPlkzo7E0fmyUAu%2BCawbYq0YT43aCMPRSP%2BQqRdbpgpkF%2BIXTNUWP6qB2319wFn4s%2Bhubt75NyJh6PBKdovcYSm9OXfGeBDqJoDYIwkPI%2Bi4IoPGaTXJthu2LvfF9NijIONvUuauN1%2BFCuNykwE1MXueF8HVAnnLuJ9Dw2SOcec8OLEvDTI3VVxTTrrxyBouN7qj0fVjOgi50jHYVyYK1qO2fiRb%2FE%2BTYEvZIy0hkqlU0FCPXHKZf2oxPuR%2FOf%2BsBAAA%3D

- SWC + Chrome >= 100: https://play.swc.rs/?version=1.9.3&code=H4sIAAAAAAAAA0vOzysuUchPylKwVajmUlDQ09MDcox0uGoBdJ5oUBoAAAA%3D&config=H4sIAAAAAAAAA3VRQY7CMAy884rIZw7sdQ9IiAfwALRaRYkLQU5SxWlFhfp33KiEFomc4pnxxJ48NkqBd8E1A%2FyqRhPjdoIw9FI%2F5CpF1umCmQU4w%2FGaoke1Vz%2B7HfwJPxb9jc1b3yZkTD0eiI7RewylN6eueE8CnURQGwThIWR9FwTQeM0muTbD9sXe%2BD4bFGScberc1cbrcCFcblLgJiav80L4OiBPOXcKNHz2CGfeswPL0jBTY%2FUVxbQrr5zBYqM7Kn0flrOgCx2jXUWyYC1q%2B2%2BixW%2BCHFvCHmkZiUy1ioZi5JrD9Eub8QlfI6GU6wEAAA%3D%3D

**Comment by chenjiahan** [comment]
Considering this an upstream issue, I will close the current issue.

Feel free to create an issue for SWC to discuss this.

**Comment by erykpiast** [comment]
Gotcha, thanks for checking that. 

I've reopened the discussion here https://github.com/swc-project/swc/issues/9778.
