### ISSUE TITLE
Feedback on HTML Title Configuration with TanStack Router in rsbuild

### ISSUE THREAD

**Issue by sagardwivedi** [web-infra-dev/rsbuild#4103]
### Discussed in https://github.com/web-infra-dev/rsbuild/discussions/3582

<div type='discussions-op-text'>

<sup>Originally posted by **sagardwivedi** September 27, 2024</sup>
I'm currently working on a project using TanStack Router and rsbuild, and I've set up dynamic HTML titles based on entry names. Here’s a snippet of my configuration:

```typescript
import { defineConfig } from "@rsbuild/core";
import { pluginReact } from "@rsbuild/plugin-react";
import { TanStackRouterRspack } from "@tanstack/router-plugin/rspack";

// Define title mapping
const titles = {
  home: 'Home Page',
  profile: 'User Profile',
  recipes: 'Recipes List',
  foo: 'Foo Page',
  bar: 'Bar Page',
};

export default defineConfig({
  plugins: [pluginReact()],
  tools: {
    rspack: {
      plugins: [TanStackRouterRspack({ disableManifestGeneration: true })],
    },
  },
  html: {
    title: ({ entryName, value = "YumBook" }) => {
      return titles[entryName] || value; // Fallback to default title
    },
  },
});
```

**Questions**:
1. Am I implementing the dynamic title functionality correctly with the given configuration because the title is not changing?
2. Are there any best practices or improvements you would recommend?
3. Is there anything else I should consider when managing titles in a React application with routing?

Thanks in advance for your feedback!</div>

**Comment by 9aoy** [comment]
`html.title` will inject the title tag into the generated html template during compile, and does not have the dynamic setting capability of runtime.
According to your description, you should refer to `@tanstack/router-plugin` documentation, get routing information through `@tanstack/router-plugin` hook & set title at runtime

**Comment by sagardwivedi** [comment]
### Issue: Changing HTML Page Titles on Different Links

I can't quite figure out how to change the HTML page title on different links on my website. Currently, it shows a single title across all pages. I tried using the following approach:

![Code Example](https://github.com/user-attachments/assets/2bae75ec-a724-4252-8f80-adbb1e2c414b)

However, I couldn't get it to work. How can I set different titles for each page?

Can we have a setup guide added to the [rsbuild.dev docs](https://rsbuild.dev) for setting different titles on different pages? It would make it easier for other developers as well.

**Comment by 9aoy** [comment]
Rsbuild does not support changing the HTML page title on different links, it supports generating different html titles in different html templates.
Different titles are effective for different html templates in MPA scenarios. You only have one html template, which is a SPA.
