### ISSUE TITLE
[Bug]: Missing content-length in headers when loading fbx files.

### ISSUE THREAD

**Issue by puxiao** [web-infra-dev/rsbuild#4112]
### Version

```sh
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 1.02 GB / 15.89 GB
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    @rsbuild/core: ^1.1.4 => 1.1.7
    @rsbuild/plugin-sass: ^1.1.1 => 1.1.1
    @rsbuild/plugin-vue: ^1.0.5 => 1.0.5
```

### Details

.fbx 位于 项目的 public 目录下，当本地调试启动服务后，加载 .fbx 文件头部缺失 content-length 字段，导致我的 loading 动画失效。
我试过其他文件，例如 .gltf，都没有问题。

![Image](https://github.com/user-attachments/assets/db5d476d-9807-45b3-b494-27e050216039)

### Reproduce link

null

### Reproduce Steps

null

**Comment by 9aoy** [comment]
Content-Length does not always exist.  If your content has a transfer encoding of gzip for example, the content-length should be ignored.
reference: 
- https://stackoverflow.com/questions/14903404/why-is-the-content-length-header-omitted-from-server-response-when-using-httpcli
- https://www.rfc-editor.org/rfc/rfc9110.html#name-content-length
