### ISSUE TITLE
[Bug]: Polyfill:"Usage",but the packaged product es5 syntax has a scope problem, causing my variables to be contaminated.

### ISSUE THREAD

**Issue by PropersonCyber** [web-infra-dev/rsbuild#4143]
### Version

```sh
System:
    OS: macOS 14.5
    CPU: (8) x64 Apple M1
    Memory: 42.29 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 131.0.6778.87
    Safari: 17.5
```

### Details

I used polyfill:'usage' to configure compatibility with my browser, but the packaged product es5 syntax has a scope problem, causing my variables to be contaminated. In my code, show_type in 3 should be used instead of show_type in 1（figure 1  is the compiled code ）. How do I fix this, Or is this a bug in rsbuild? 
![Image](https://github.com/user-attachments/assets/fa5c7cdd-d7b9-4d3b-80d5-01ae819568bd)
![Image](https://github.com/user-attachments/assets/db41cf79-3fd9-4fdd-8fa7-ecbdd78664fc)

### Reproduce link

https://codesandbox.io/p/github/rspack-contrib/rsbuild-codesandbox-example/csb-zktgdv/draft/great-flower?file=%2Fsrc%2FApp.jsx%3A11%2C54

### Reproduce Steps

npm run build

checkout index.[hash].js , search "show_type" the result will be appear！！

**Comment by chenjiahan** [comment]
The codesandbox link is invalid, can you have a look at it?

![Image](https://github.com/user-attachments/assets/c9fca1b2-ebff-48f7-bf0f-65a4ddd628e7)

**Comment by chenjiahan** [comment]
Duplicated: https://github.com/web-infra-dev/rspack/issues/8637
