### ISSUE TITLE
[Feature]: Is there a plan to support entriesDir?

### ISSUE THREAD

**Issue by tmkx** [web-infra-dev/rsbuild#4161]
### What problem does this feature solve?

Automatically scan entries in a specific directory.

### What does the proposed API look like?

https://modernjs.dev/configure/app/source/entries-dir.html

**Comment by chenjiahan** [comment]
No plans yet. This can easily be done with glob or a custom rsbuild plugin.

Ref: https://stackoverflow.com/questions/34907999/best-way-to-have-all-files-in-a-directory-be-entry-points-in-webpack/45827671#45827671
