### ISSUE TITLE
[Bug]: The long titles of the website are outside the screen on mobile.

### ISSUE THREAD

**Issue by xbzhang2020** [web-infra-dev/rsbuild#4166]
### Version

```sh
System: iPhone13 pro
Browser: chrome
```

### Details

![Image](https://github.com/user-attachments/assets/b5e4c39a-e4f0-4763-a69c-ae5178dc2af7)

### Reproduce link

https://rsbuild.dev/config/output/override-browserslist

### Reproduce Steps

Open the reproduce link on mobile.

**Comment by chenjiahan** [comment]
Thanks. This will be fixed by https://github.com/web-infra-dev/rspress/pull/1650
