### ISSUE TITLE
[Bug]: Not getting URL when I import SVG

### ISSUE THREAD

**Issue by SheikhSajid** [web-infra-dev/rsbuild#4167]
### Version

```sh
System:
    OS: Windows 11 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 5600 6-Core Processor
    Memory: 11.24 GB / 31.95 GB
  Browsers:
    Chrome: 131.0.6778.109
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @rsbuild/core: ^1.1.8 => 1.1.9 
    @rsbuild/plugin-react: ^1.0.7 => 1.1.0 
    @rsbuild/plugin-svgr: ^1.0.6 => 1.0.6
```

### Details

The SVGR plugin docs mention that when an SVG is imported without the ?react suffix, we'll get a URL:
![Image](https://github.com/user-attachments/assets/0ef6d224-2bc4-4aa4-a2d0-0a348037df44)

My react component:
```
import './App.css';
import folderSelected from './assets/images/folder-selected.svg';

/**
 * According to SVGR plugin documentation, the console.log on line 11
 * should print the path to the image: 
 *   "/assets/images/folder-selected.svg".
 * However, it prints (truncated):
 *   "data:image/svg+xml;base64,PHN2ZyBpZD0iaWN43OD...ISIvPgo8L3N2Zz4="
 */
console.log(folderSelected);

const App = () => {
  return (
    <div className="content">
      <h1>Rsbuild with React</h1>
      <p>Start building amazing things with Rsbuild.</p>
    </div>
  );
};

export default App;
```

Rsbuild config:
```
import { defineConfig } from '@rsbuild/core';
import { pluginReact } from '@rsbuild/plugin-react';
import { pluginSvgr } from '@rsbuild/plugin-svgr';

export default defineConfig({
  plugins: [
    pluginReact(),
    pluginSvgr()
  ]
});
```

In my console instead of seeing the URL logged, I see this:
`data:image/svg+xml;base64,PHN2ZyBpZD0iaWNvbiIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iMjgiIGhlaWdodD0iMjgiIHZpZXdCb3g9IjAgMCAyOCAyOCIgZmlsbD0ibm9uZSI+CiAgPHBhdGggZmlsbC1ydWxlPSJldmVub2RkIiBjbGlwLXJ1bGU9ImV2ZW5vZGQiIGQ9Ik0yMS44MDUxIDkuMjgzNzdIMjMuMDQ3NkwyMy4wMzg4IDkuMjc1MDJDMjQuNDgyNiA5LjI3NTAyIDI1LjY2MzggMTAuNDU2MyAyNS42NjM4IDExLjlWMjAuNzU1QzI1LjY2MzggMjIuMTk4OCAyNC40ODI2IDIzLjM4IDIzLjAzODggMjMuMzhIOS40NTg4MkM4LjAxNTA3IDIzLjM4IDYuODMzODIgMjIuMTk4OCA2LjgzMzgyIDIwLjc1NVYxOS43NTc1TDUuOTkzODIgMTkuODhDNS45MTUwNyAxOS44OTc1IDUuODI3NTcgMTkuODk3NSA1Ljc0ODgyIDE5Ljg5NzVDNC43MTYzMiAxOS44OTc1IDMuNzk3NTcgMTguOTM1IDMuNTk2MzIgMTcuNTg3NUwyLjI0ODgyIDguNTQ4NzdDMi4wMzg4MiA3LjExMzc3IDMuMDI3NTcgNS43NzUwMiA0LjQ2MjU3IDUuNTY1MDJMMTguMjg3NiAzLjUwODc3QzE4Ljk4NzYgMy40MDM3NyAxOS42Nzg4IDMuNTc4NzcgMjAuMjM4OCAzLjk5ODc3QzIwLjc5ODggNC40MTg3NyAyMS4xNjYzIDUuMDMxMjcgMjEuMjcxMyA1LjcyMjUyTDIxLjgwNTEgOS4yODM3N1pNMjMuOTIyNiAxNy4zNjg4VjExLjkwODhDMjMuOTIyNiAxMS40Mjc1IDIzLjUyODggMTEuMDMzOCAyMy4wNDc2IDExLjAzMzhIOS40Njc1N0M4Ljk4NjMyIDExLjAzMzggOC41OTI1NyAxMS40Mjc1IDguNTkyNTcgMTEuOTA4OFYxNi43NDc1QzkuNzM4ODIgMTUuNzkzOCAxMS4zMzEzIDE0Ljg5MjUgMTIuNzU3NiAxNS41NEMxMy42MzI2IDE1LjkzMzggMTQuMjgwMSAxNi42MzM4IDE0Ljg0ODggMTcuMjU1QzE1Ljg1NTEgMTguMzQ4OCAxNi4yODM4IDE4LjY5ODggMTcuMTE1MSAxOC4zNzVDMTcuOTExMyAxOC4wNjg4IDE4LjUwNjMgMTcuNzcxMyAxOS4wMzEzIDE3LjVDMjAuMDU1MSAxNi45NzUgMjAuODY4OCAxNi41NjM4IDIyLjExMTMgMTYuNjc3NUMyMi43OTM4IDE2LjczIDIzLjQwNjMgMTcuMDE4OCAyMy45MjI2IDE3LjM2ODhaTTUuMzM3NTcgMTcuMzMzOEM1LjQwNzU3IDE3Ljg1IDUuNjc4ODIgMTguMTMgNS43NzUwNyAxOC4xNTYzVjE4LjE2NUw2Ljg0MjU3IDE3Ljk5ODhWMTEuOTE3NUM2Ljg0MjU3IDEwLjQ3MzggOC4wMjM4MiA5LjI5MjUyIDkuNDY3NTcgOS4yOTI1MkgyMC4wMzc2TDE5LjU0NzYgNS45ODUwMkMxOS41MTI2IDUuNzQ4NzcgMTkuMzkwMSA1LjU0NzUyIDE5LjE5NzYgNS40MDc1MkMxOS4wMTM4IDUuMjY3NTIgMTguNzc3NiA1LjIwNjI3IDE4LjU1MDEgNS4yNDEyN0w0LjcyNTA3IDcuMjk3NTJDNC4yNTI1NyA3LjM2NzUyIDMuOTIwMDcgNy44MTM3NyAzLjk5MDA3IDguMjk1MDJMNS4zMzc1NyAxNy4zMzM4Wk05LjQ2NzU3IDIxLjYzODhIMjMuMDQ3NkMyMy41Mjg4IDIxLjYzODggMjMuOTIyNiAyMS4yNDUgMjMuOTIyNiAyMC43NjM4VjE5LjczMTNDMjMuNTM3NiAxOS4yNTg4IDIyLjc0MTMgMTguNDg4OCAyMS45NTM4IDE4LjQxODhDMjEuMjM2MyAxOC4zNTc1IDIwLjc5MDEgMTguNTY3NSAxOS44Mjc2IDE5LjA1NzVMMTkuNzc5NSAxOS4wODE5QzE5LjI1NCAxOS4zNDkxIDE4LjYwMjggMTkuNjgwMiAxNy43NTM4IDIwLjAxMTNDMTUuNzMyNiAyMC43OSAxNC40NzI2IDE5LjQzMzggMTMuNTYyNiAxOC40NDVDMTMuMDYzOCAxNy44OTM4IDEyLjU5MTMgMTcuMzg2MyAxMi4wNDAxIDE3LjEzMjVDMTEuMjA4OCAxNi43NTYzIDkuNTgxMzIgMTguMDY4OCA4LjU5MjU3IDE5LjE4ODhWMjAuNzYzOEM4LjU5MjU3IDIxLjI0NSA4Ljk4NjMyIDIxLjYzODggOS40Njc1NyAyMS42Mzg4Wk0xOS43ODM4IDEzLjk5OTlDMTkuNzgzOCAxNC42NDc0IDE5LjI1ODggMTUuMTcyNCAxOC42MTEzIDE1LjE3MjRDMTcuOTYzOCAxNS4xNzI0IDE3LjQzODggMTQuNjQ3NCAxNy40Mzg4IDEzLjk5OTlDMTcuNDM4OCAxMy4zNTI0IDE3Ljk2MzggMTIuODI3NCAxOC42MTEzIDEyLjgyNzRDMTkuMjU4OCAxMi44Mjc0IDE5Ljc4MzggMTMuMzUyNCAxOS43ODM4IDEzLjk5OTlaIiBmaWxsPSJ3aGl0ZSIvPgo8L3N2Zz4=`

### Reproduce link

https://github.com/SheikhSajid/svgcheck-project

### Reproduce Steps

1. `yarn`
2. `yarn dev`
3. open `devtools` and check logs

**Comment by chenjiahan** [comment]
See: https://rsbuild.dev/guide/optimization/inline-assets
