### ISSUE TITLE
[Bug]: 【eslint】 An error was reported on vscode, but the compilation was successful without any error message.

### ISSUE THREAD

**Issue by runkobe24** [web-infra-dev/rsbuild#4180]
### Version

```sh
System:
    OS: Windows 11 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700
    Memory: 11.90 GB / 31.68 GB
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @rsbuild/core: ^1.0.14 => 1.1.9
    @rsbuild/plugin-css-minimizer: ^1.0.2 => 1.0.2
    @rsbuild/plugin-eslint: ^1.0.4 => 1.1.0
    @rsbuild/plugin-stylus: ^1.0.3 => 1.0.6
    @rsbuild/plugin-vue: ^1.0.2 => 1.0.5
```

### Details

Migrated from vue cli, this is the previous vue cli project. When there is an error message in vscode, an error message will pop up on the console and page：
![Image](https://github.com/user-attachments/assets/85fe6e0e-8a3c-4a0a-bdd3-61c810f26a1d)

-------------------------------------------------

The following is built using rspack：

![Image](https://github.com/user-attachments/assets/64a7c263-548b-460b-bf95-1987d74d8e57)

I hope that when there is an error message in vscode, the corresponding error message will appear on both the console and the page.

### Reproduce link

https://codesandbox.io/p/devbox/82rj27

### Reproduce Steps

yarn install 
yarn dev

**Comment by chenjiahan** [comment]
This is because Vue CLI uses an older version of [fork-ts-checker-webpack-plugin](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin), which can check type errors in `.vue` files.

However, this plugin has removed support for Vue in version [8.0.0](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/releases/tag/v8.0.0). If you need to type check .vue files, you can try one of the following methods:

1. Use `vue-tsc` instead, see https://github.com/rspack-contrib/rsbuild-plugin-type-check?tab=readme-ov-file#vue-components for more details.
2. Use `fork-ts-checker-webpack-plugin` 7.x version.

**Comment by chenjiahan** [comment]
Have you registered the plugin in rsbuild.config.ts?

**Comment by runkobe24** [comment]
> Have you registered the plugin in rsbuild.config.ts?

Added to rsbuild.config.ts

![Image](https://github.com/user-attachments/assets/8e931a34-f783-48b4-8494-b73b643c2b99)

**Comment by chenjiahan** [comment]
Can you provide an reproduction repo?

**Comment by runkobe24** [comment]
> Can you provide an reproduction repo?

This can be reproduced：

https://codesandbox.io/p/devbox/82rj27

----

![Image](https://github.com/user-attachments/assets/a586cfbb-3ac4-4be9-83a0-8c767be02a04)

**Comment by chenjiahan** [comment]
I think your fork-ts-checker-webpack-plugin is misconfigured.

Please refer to the `fork-ts-checker-webpack-plugin` documentation: https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/tree/v7.3.0?tab=readme-ov-file#vuejs and check the `Expand Vue.js set up instruction` example.

**Comment by runkobe24** [comment]
> I think your fork-ts-checker-webpack-plugin is misconfigured.
> 
> Please refer to the `fork-ts-checker-webpack-plugin` documentation: https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/tree/v7.3.0?tab=readme-ov-file#vuejs and check the `Expand Vue.js set up instruction` example.

nb！ Errors can already appear in the console, but the browser page does not appear.

**Comment by chenjiahan** [comment]
> browser page does not appear

Do you mean the error overlay? This is expected, Rsbuild's error overlay does not currently show type errors. We may support this in the future.

**Comment by runkobe24** [comment]
> > 浏览器页面未出现
> 
> 您指的是错误覆盖吗？这是意料之中的，Rsbuild 的错误覆盖目前不显示类型错误。我们可能会在将来支持此功能。

Yes, I hope it can be supported as soon as possible. I have been tinkering with it for a while and am ready to migrate it completely. 
 thank! 😊

**Comment by chenjiahan** [comment]
Get, it's an independent feature, so I will close the current issue.
