### ISSUE TITLE
[Bug]: load vue file error

### ISSUE THREAD

**Issue by tym3515** [web-infra-dev/rsbuild#4203]
### Version

```sh
mac
chrome
vue2
```

### Details

http://localhost:60645/lazy-compilation-using-builtin:swc-loader%3F%3FclonedRuleSet-3.use%5B0%5D!

大部分组建都是加载成功的，只有少部分文件会偶现加载失败，失败的文件的加载路径就不对了，不是本地的localhost地址，而是http://localhost:60645/lazy-compilation-using-builtin:swc-loader%3F%3FclonedRuleSet-3.use%5B0%5D!  开头的一堆长url

![Image](https://github.com/user-attachments/assets/0a4aa0e3-96bb-409b-a44e-0d9a04d95ff0)

![Image](https://github.com/user-attachments/assets/0862089b-d885-4414-81f5-9592f09181b2)

### Reproduce link

。。。

### Reproduce Steps

only

**Comment by tym3515** [comment]
抱歉这个无法提供，因为是我们的项目代码，在简单demo里面无法复现，也许只有项目文件比较多的时候会出现

**Comment by tym3515** [comment]
您也许可以根据这个链接地址(http://localhost:60645/lazy-compilation-using-builtin:swc-loader去排查，因为很明显这个url是错误的，我们本地用的不是这个端口和路径

**Comment by chenjiahan** [comment]
Are you using https://rsbuild.dev/config/dev/lazy-compilation?

You can disable the `lazyCompilation` and try again.
