### ISSUE TITLE
[Bug]: When specifying the index.html file path, modifying the html internal data rejects hot update

### ISSUE THREAD

**Issue by lessten1211** [web-infra-dev/rsbuild#4209]
### Version

```sh
System:
    OS: macOS 15.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 89.89 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 131.0.6778.140
    Safari: 18.1
  npmPackages:
    @rsbuild/core: ^1.1.8 => 1.1.10 
    @rsbuild/plugin-react: ^1.0.7 => 1.1.0
```

### Details

When I specify the index.html file and modify the content in index.html, HRM does not take effect after saving and must be refreshed.
I tested that vite is an HRM that supports index.html files.

### Reproduce link

https://github.com/lessten1211/lessten1211.github.io/tree/main/rsbuild-test

### Reproduce Steps

Regardless of the path to the index.html file specified, if the content in the html is modified after opening the page, there will be no HRM after saving, and the page will not be updated until it is refreshed.

**Comment by chenjiahan** [comment]
Thanks for the feedback, we will fix this in the next release.
