### ISSUE TITLE
[Bug]: rsbuild的vue3+ts模版中使用pnpm i安装后报错[webpack-dev-middleware] Error: Unmatched version @rspack/core@1.1.7, @rspack/binding@1.1.6, @rspack/binding-darwin-x64@1.1.6

### ISSUE THREAD

**Issue by luoying1** [web-infra-dev/rsbuild#4219]
### Version

```sh
"devDependencies": {
    "@rsbuild/core": "^1.1.8",
    "@rsbuild/plugin-vue": "^1.0.5",
    "typescript": "^5.7.2"
  }
```

### Details

[Bug]: rsbuild的vue3+ts模版中使用pnpm i安装后报错[webpack-dev-middleware] Error: Unmatched version @rspack/core@1.1.7, @rspack/binding@1.1.6, @rspack/binding-darwin-x64@1.1.6

### Reproduce link

11

### Reproduce Steps

11

**Comment by 9aoy** [comment]
Rspack v1.1.7 is an unavailable version and has been deprecated. We are already working on this problem urgently,  and for Rsbuild users, you can temporarily override the rspack version to 1.1.6.

see https://github.com/web-infra-dev/rspack/issues/8767

**Comment by 9aoy** [comment]
Rspack 1.1.8 has been released. Since rspack 1.1.7 has security risks, it is recommended that you check your system for any unusual activity. 🌹 

https://github.com/web-infra-dev/rspack/releases/tag/v1.1.8
