### ISSUE TITLE
[Bug]: Module not found: Can't resolve <path>

### ISSUE THREAD

**Issue by deizianens** [web-infra-dev/rsbuild#4227]
### Version

```sh
System:
    OS: macOS 15.1.1
    CPU: (8) arm64 Apple M2
    Memory: 128.75 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 131.0.6778.205
    Safari: 18.1.1
  npmPackages:
    @rsbuild/core: ^1.1.8 => 1.1.10
    @rsbuild/plugin-react: ^1.0.7 => 1.1.0
    @rsbuild/plugin-svgr: ^1.0.6 => 1.0.6
```

### Details

When executing the application,  `Module not found: Can't resolve` error appears. 
This error doesn't appear when using @rsbuild/core v1.0.19.

![Image](https://github.com/user-attachments/assets/b224cc97-d4df-49cd-b6b2-cbbb8af47e38)

### Reproduce link

https://github.com/deizianens/rsbuild-mfe/tree/main

### Reproduce Steps

Enter lib folder
`cd lib`

Install dependencies
`yarn`

Build
`yarn build`

Enter mfe folder
```
cd ..
cd mfe
```

Install dependencies
`yarn`

Run
`yarn dev`

**Comment by chenjiahan** [comment]
The paths are incorrect.

![Image](https://github.com/user-attachments/assets/197c5b2d-b21f-41d0-8e39-caea6cb9d86e)

Should be `../../../../assets` instead of `../../../assets`.

**Comment by deizianens** [comment]
Hello @chenjiahan, I have two questions about it:

1. Path is correct on Logo.tsx file, since assets folder is on the same level as scr folder, as it is on image.
2. Why it works without errors when i'm using @rsbuild/core v1.0.19?


<img width="1304" alt="Image" src="https://github.com/user-attachments/assets/65717a5a-d60f-4ee4-a2f8-21a5dcac8406" />

Can you please help me answers these questions?

**Comment by chenjiahan** [comment]
1. This is because the rollup build does not handle path changes correctly
2. The current resolve behavior is aligned with Node.js, and I guess there was a bug in the old version of Rspack resolver that has been fixed.

**Comment by deizianens** [comment]
I just wonder why that works with Vite and Webpack latest versions but does not work with Rsbuild/core latest. Thanks for you answer @chenjiahan, I will take a look on rollup to fix that.
