### ISSUE TITLE
[Feature]: Path Aliases add `jsconfig.json` support

### ISSUE THREAD

**Issue by a81n9** [web-infra-dev/rsbuild#4228]
### What problem does this feature solve?

[Path Aliases](https://rsbuild.dev/guide/advanced/alias#using-tsconfigjsons-paths-configuration) currently only supports `tsconfig.json`'s `paths` configuration.
It is recommended to support the `paths` configuration in `jsconfig.json`.

### What does the proposed API look like?

Path Aliases add `jsconfig.json` support

**Comment by chenjiahan** [comment]
Hi, you can try this: https://rsbuild.dev/guide/migration/cra#reading-jsconfigjson

**Comment by a81n9** [comment]
> Hi, you can try this: https://rsbuild.dev/guide/migration/cra#reading-jsconfigjson

Thank you for your reply
