### ISSUE TITLE
[Bug]: Unocss transformerVariantGroup not work

### ISSUE THREAD

**Issue by a81n9** [web-infra-dev/rsbuild#4231]
### Version

```sh
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i3-10100 CPU @ 3.60GHz
    Memory: 4.99 GB / 15.75 GB
Browsers:
    Edge: Chromium (128.0.2739.63)
    Internet Explorer: 11.0.19041.4355
npmPackages:
    @rsbuild/core: ^1.1.8 => 1.1.10
    @rsbuild/plugin-vue: ^1.0.5
```

### Details

In this way [https://rsbuild.dev/guide/basic/unocss](https://rsbuild.dev/guide/basic/unocss)
Unocss `transformerVariantGroup` not work

```js
import { defineConfig, presetUno, transformerVariantGroup } from 'unocss'

export default defineConfig({
  content: {
    filesystem: ['./src/**/*.{html,js,ts,jsx,tsx,vue,svelte,astro}'],
  },
  presets: [presetUno()],
  transformers: [transformerVariantGroup()], // not work
})
```

```html
<div class="bg-red text-(center white xl)">Rsbuild</div>
```

![Image](https://github.com/user-attachments/assets/7120d106-9efc-4182-9549-36259eddf2e4)

### The effect of not using `transformers` is as follows:

```html
<div class="bg-red text-center text-white text-xl">Rsbuild</div>
```

![Image](https://github.com/user-attachments/assets/c47b1f58-af38-4e79-b025-d880b92e7f5c)

### Reproduce link

https://codesandbox.io/p/github/rspack-contrib/rsbuild-codesandbox-example/main

### Reproduce Steps

```html
<div class="bg-red text-(center white xl)">Rsbuild</div>
```

**Comment by chenjiahan** [comment]
This might be an issue with UnoCSS, since Rsbuild only uses UnoCSS as a PostCSS plugin.

Can you file an issue to the [unocss](https://github.com/unocss/unocss) repository?

**Comment by a81n9** [comment]
Yeah, I already did that
