### ISSUE TITLE
[Feature]: Error overlay for type error

### ISSUE THREAD

**Issue by alefduarte** [web-infra-dev/rsbuild#4232]
### What problem does this feature solve?

It seems that rsbuild currently does not support an overlay for type errors, which is a feature I was really hoping to see. 
I've recently migrated from Vite, and the absence of a type overlay feels like a step backward; currently, type errors are only displayed in the console. If this is not feasible, could you suggest a plugin that might provide this functionality?
If this is on the roadmap, do you have any updates on when we'll get this?
Thank you very much!!

### What does the proposed API look like?

same as the existing config
 ``` js
dev:{
   client:{
       overlay: true
   }
}
```

**Comment by chenjiahan** [comment]
Maybe Rsbuild can expose a plugin hook to allow `@rsbuild/plugin-type-check` to render type errors to the error overlay. @9aoy cc

**Comment by chenjiahan** [comment]
This feature has been supported by https://github.com/rspack-contrib/rsbuild-plugin-type-check/releases/tag/v1.2.0
