### ISSUE TITLE
[Bug]: HTML head tags are injected twice on a custom template

### ISSUE THREAD

**Issue by dylancetin** [web-infra-dev/rsbuild#4251]
### Version

```sh
System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M1
    Memory: 400.33 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Brave Browser: 131.1.73.101
    Safari: 17.4.1
  npmPackages:
    @rsbuild/core: ^1.1.12 => 1.1.12
```

### Details

When using a template html file like showed on rspack docs

https://rsbuild.dev/guide/basic/html-template#injecting-tags

The build and dev injects tags twice.

Output on "npm run build":
```
<html>
  <head>
    <title>Rsbuild App</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script defer src="/static/js/index.88c81cf4.js"></script>
    <title>Rsbuild App</title>
    <meta charset="UTF-8" />
    <script defer src="/static/js/index.88c81cf4.js"></script>
  </head>
  <body class="font-sans">
    <div id="root"></div>
  </body>
</html>
```

Expected output:
```
<html>
  <head>
    <title>Rsbuild App</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script defer src="/static/js/index.88c81cf4.js"></script>
  </head>
  <body class="font-sans">
    <div id="root"></div>
  </body>
</html>
```

Things i tried:
1. inject: "body" causes it to inject twice but now in the body
2. inject: "head" makes no difference
3. "<%= htmlPlugin.tags.headTags %>" removing this in the template with "head" solved the issue
4. "<%= htmlPlugin.tags.bodyTags %>" removing this in the template with "body" solved the issue only with script tag but "<title>Rsbuild App</title><meta charset="UTF-8">" are still duplicate 

### Reproduce link

https://github.com/dylancetin/rspack-bug-report.git

### Reproduce Steps

git clone https://github.com/dylancetin/rspack-bug-report.git
cd rspack-bug-report
npm install
npm run build

**Comment by inottn** [comment]
Try setting `inject: false` to see if it meets your expectations.

**Comment by dylancetin** [comment]
yeah @inottn it solves it. i dont even know how i missed that 

thanks
