### ISSUE TITLE
[Bug]: Expected '>', got 'style'

### ISSUE THREAD

**Issue by jieyuming** [web-infra-dev/rsbuild#4267]
### Version

```sh
system: window11
browers: google
npm: 1.1.12
```

### Details

vue2项目，在js和vue文件里面，用jsx语法写html，
提示报错： Module build failed: Expected '>', got 'style'
源码示例：
return {
              data:{...item,...item.data},
              align: 'center',
              colKey: item.code,
              fixed: item.isFixed==1?'left':'', //固定项
              title: (h, { colIndex }) => <div style="text-align:center">
                <div>{name}</div>
                <div class="unit">{unit}</div>
              </div>,
              cell: (h, { row, col }) => {
                let cell = row[col.colKey] 
                let value = _this.setEmpty(cell && cell instanceof Object?cell['dataValue']:cell)
                return (
                  <div class="custom-cell">{
                    value
                  }</div>
                );
              },
            }

### Reproduce link

https://codesandbox.io/p/github/rspack-contrib/rsbuild-codesandbox-example/main?file=%2Frsbuild.config.mjs

### Reproduce Steps

import { pluginVue2 } from "@rsbuild/plugin-vue2";
const { pluginVue2Jsx } = require("@rsbuild/plugin-vue2-jsx");

尝试使用pluginVue2Jsx 插件，还没没效果
Reproduce link 默认是react的项目，我随意贴上去，不然提交不了

**Comment by chenjiahan** [comment]
I'm curious about why this issue was closed, can you provide some information? Because I saw a similar issue https://github.com/web-infra-dev/rsbuild/issues/4267

**Comment by coderwyd** [comment]
You can try adding a `lang="jsx"`.
