### ISSUE TITLE
[Bug]: Expected '>', got 'size'

### ISSUE THREAD

**Issue by wang-yi-bit64** [web-infra-dev/rsbuild#4275]
### Version

```sh
System:
    OS: Windows 11 10.0.26100
    CPU: (16) x64 AMD Ryzen 7 4800U with Radeon Graphics
    Memory: 1.28 GB / 15.37 GB
  Browsers:
    Edge: Chromium (131.0.2903.14)
    Internet Explorer: 11.0.26100.1882
  npmPackages:
    @rsbuild/core: ^1.1.13 => 1.1.13 
    @rsbuild/plugin-less: ^1.1.0 => 1.1.0
    @rsbuild/plugin-react: ^1.1.0 => 1.1.0
```

### Details

![Image](https://github.com/user-attachments/assets/c3416257-3c04-47a1-9f04-13504779e034)

启动项目的时候报错，` 无法解析  
dynamic.setDefaultLoadingComponent(() => <Spin size="large" className={styles.globalSpin}/>)
然后报错 

### Reproduce link

https://github.com/wang-yi-bit64/rsbuild-test-dva

### Reproduce Steps

npm i && npm serve

**Comment by chenjiahan** [comment]
I'm curious about why this issue was closed, can you provide some information? Because I saw a similar issue https://github.com/web-infra-dev/rsbuild/issues/4267
