### ISSUE TITLE
[Bug] css module path with spaces does not work as expected, rspack works by the way

### ISSUE THREAD

**Issue by JounQin** [web-infra-dev/rsbuild#4278]
https://github.com/JounQin/rspack-css-modules-spaces

```jsonc
{
  "@rspack/cli": "^1.1.8",
  "@rspack/core": "^1.1.8",
  "@rsbuild/core": "^1.1.13"
}
```

When running `pnpm dev:rspack`, the generated class name is `rspack-repro-_src_space_folder_render_module_css-text` which works as expected, but for `pnpm dev:rsbuild`, it's `src-space folder-render-module__text-DF713n` in html and `.src-space\ folder-render-module__text-DF713n` in `.css` file.

And it's not possible to escape spaces into html.

https://stackoverflow.com/questions/50812118/is-it-possible-to-use-the-space-character-in-css-class-names

The original `el.classList.add(styles.text)` throws:

https://github.com/JounQin/rspack-css-modules-spaces/blob/4d081a81dafb914b63d3800e06cc3bb62032224c/src/render.js#L5

```log
Uncaught (in promise) InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('src-space folder-render-module__text-DF713n') contains HTML space characters, which are not valid in tokens.
    at Module.render (render.js:6:1)
    at index.js:2:1
```

**Comment by JounQin** [comment]
Just find out it's actually `css-loader`'s issue, it can also be reproduced with `webpack` and `rspack`:

https://github.com/JounQin/rspack-css-modules-spaces/commit/aba4f74dacc33c72cf0438780736ad1ba1497c40#diff-72c0c573b2c8e6a48f39d5398d801b197415040d87363a982bc57dbc024d3d75R23-R44

**Comment by chenjiahan** [comment]
Thanks, as this has been reported to the css-loader repo, I will close the current issue.
