### ISSUE TITLE
[Document]: unocss already support rspack by @unocss/webpack

### ISSUE THREAD

**Issue by g-mero** [web-infra-dev/rsbuild#4285]
### What problem does this feature solve?

See https://github.com/unocss/unocss/pull/4173.

Maybe the docs should be update. This provided a much easier way to use unocss.

### What does the proposed API look like?

Update docs https://rsbuild.dev/guide/basic/unocss.

**Comment by chenjiahan** [comment]
Thanks for the feedback! We have updated the UnoCSS documentation and example.
