### ISSUE TITLE
[Feature]: Restart devserver when config file(`rsbuild.config.js`) changed

### ISSUE THREAD

**Issue by zoolsher** [web-infra-dev/rsbuild#477]
### What problem does this feature solve?

Now developers have to restart the CLI when they want to update config like entries

### What does the proposed API look like?

auto restart the devserver

**Comment by chenjiahan** [comment]
Yeah this will impact the developer experience, and we will support this feature soon.

**Comment by chenjiahan** [comment]
Released in v0.0.21
