### ISSUE TITLE
[Bug]: _swc_helpers_define_property__WEBPACK_IMPORTED_MODULE_2__ is not defined

### ISSUE THREAD

**Issue by Lzzzs** [web-infra-dev/rsbuild#491]
### 版本信息

```sh
System:
    OS: macOS 13.5
    CPU: (8) arm64 Apple M1
    Memory: 160.64 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 119.0.6045.123
    Safari: 16.6
  npmPackages:
    @rsbuild/core: ^0.0.20 => 0.0.20 
    @rsbuild/plugin-react: ^0.0.20 => 0.0.20
```

### 问题详情

生产环境打包之后访问报错：
`react-dom.production.min.js:121 ReferenceError: _swc_helpers_define_property__WEBPACK_IMPORTED_MODULE_2__ is not defined`
![image](https://github.com/web-infra-dev/rsbuild/assets/74575471/b9329bfb-2bcc-495f-84c7-f00d0d7384a5)

**开发环境一切正常**

我目前不太清楚咋去复现这个问题，所以没写链接，sorry

### 复现链接

null

### 复现步骤

1. yarn build
2. 部署到云服务器

**Comment by chenjiahan** [comment]
信息有点少，能提供更多信息嘛😂  比如一个可复现问题的 URL，或者产物压缩包什么的

**Comment by Lzzzs** [comment]
我看看能不能复现下～

**Comment by Lzzzs** [comment]
请问下，`preview `命令可以配置启动的 URL 吗，文档没有看到有地方提及
![image](https://github.com/web-infra-dev/rsbuild/assets/74575471/e4fdfb2d-e012-4c85-9156-fb873203570e)

**Comment by chenjiahan** [comment]
@Lzzzs 你是希望实现类似 dev.startUrl 和 rsbuild dev --open 类似的功能嘛？目前 preview 不支持噢，我们可以加一下

**Comment by Lzzzs** [comment]
**类似于 dev.host，我可以自己定义 preview 的 host**。因为我目前是打包之后的代码有问题，但是项目配置了 dev.host，用 preview 只有固定的 host，没办法看生产包的问题，需要每次发到云服务器上看问题

**Comment by Lzzzs** [comment]
还有个问题就是，可以通过某个配置将底层 SWC 变成 Babel 吗。因为我现在初步怀疑是 SWC 的问题，因为之前用 Modern builder 做迁移的时候，并没有这个问题

**Comment by chenjiahan** [comment]
> 类似于 dev.host，我可以自己定义 preview 的 host

这个可以支持，我们加一下 @9aoy 

> 通过某个配置将底层 SWC 变成 Babel 吗

可以用 Babel 插件：https://rsbuild.dev/zh/plugins/list/plugin-babel.html

**Comment by Lzzzs** [comment]
请问下，打包之后的产物这个变量没有未定义，我把这段相关代码注释了再打包，这个报错就消失了，这种是SWC的问题吗，还是说有其它的问题

![image](https://github.com/web-infra-dev/rsbuild/assets/74575471/efb8d9d0-dd05-4d95-b828-e813973f3ec4)


![image](https://github.com/web-infra-dev/rsbuild/assets/74575471/abd8761b-898b-41cd-8e52-0da919f58ed3)

**Comment by chenjiahan** [comment]
看起来是 Rspack 或 SWC 层面的问题，这个变量在 build 后应该被 magle 压缩的，截图里没有被压缩掉。

昨天我们发布了基于 Rsbuild 0.0.22，基于最新的 Rspack 0.3.12，你可以升级试一下哈。如果升级不能解决的话，就需要想办法提供一个复现 demo 了。

**Comment by Lzzzs** [comment]
发现了一个新的错误，demo：https://github.com/Lzzzs/rsbuild-error

步骤：
- pnpm dev
- 打开浏览器就可以看到报错

报的是一个库的错误，但是据我观察，应该是 rspack 的问题，虽然这个 demo 是用 rsbuild 搭的，我也同样用 rspack 搭了一个，在相同的代码也同样会报错。而且，我有其它的业务代码用 rspack也有类似的错误

报错截图：
![image](https://github.com/web-infra-dev/rsbuild/assets/74575471/b790eaca-1776-4451-856a-18f328919494)
![image](https://github.com/web-infra-dev/rsbuild/assets/74575471/25882600-9524-4c68-954c-d2ba2af0153e)

**Comment by chenjiahan** [comment]
@Lzzzs 可能是这个问题：https://github.com/web-infra-dev/rspack/issues/4662

我们今天会发布一个新版本，到时候再试试

**Comment by Lzzzs** [comment]
我用 rspack对齐了一遍配置，升级到了rspack 的 0.3.13，还是存在这个问题，我需要去 rspack 那边提个 issue 吗

**Comment by chenjiahan** [comment]
嗯嗯，这种情况可以直接提一个 Rspack issue ❤️

**Comment by Lzzzs** [comment]
已经解决了哈，谢谢你～ issue 我先关了

**Comment by chenjiahan** [comment]
related issue: https://github.com/web-infra-dev/rspack/issues/4669

**Comment by MIreland** [comment]
So I'm seeing this issue on a recent build on RC `1.0.1-rc.5`

<img width="692" alt="image" src="https://github.com/user-attachments/assets/d6f9ddc5-0aa4-4bc8-ba3b-83439facf8bd">


Would someone mind relaying what the solution/resolution was?
