### ISSUE TITLE
[Feature]: dev-server add overlay

### ISSUE THREAD

**Issue by angular-moon** [web-infra-dev/rsbuild#552]
### 这个功能解决了什么问题？

在开发时能在界面上及时的看到构建的错误信息

### 你期望的 API 是什么样子的？

```typescript
dev:{
   client:{
       overlay: true
   }
}
```

**Comment by chenjiahan** [comment]
Thanks for the feedback, we will consider adding an overlay for Rsbuild.

**Comment by fi3ework** [comment]
I'd like to claim this feature if no one is working on it so far. This feature looks interesting. 😋

**Comment by chenjiahan** [comment]
Great 🎉
