### ISSUE TITLE
[Bug]: not found page with react router dom

### ISSUE THREAD

**Issue by hunghg255** [web-infra-dev/rsbuild#627]
### Version

```sh
System:
    OS: macOS 13.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 2.30 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 119.0.6045.159
    Safari: 16.6
  npmPackages:
    @rsbuild/core: ^0.0.18 => 0.0.18 
    @rsbuild/plugin-react: ^0.0.18 => 0.0.18
```

### Details

https://github.com/web-infra-dev/rsbuild/assets/42096908/61388962-33f0-4bda-b326-c6c966f85a54

### Reproduce link

Error from version 0.0.18

### Reproduce Steps

1. load home
2. load /sign-in

**Comment by hunghg255** [comment]
maybe relates to dev server

**Comment by 9aoy** [comment]
@hunghg255 What is your rsbuild config like?

**Comment by hunghg255** [comment]
> @hunghg255 What is your rsbuild config like?

my config is initial. issues with react-router-dom when reloading with a path

**Comment by ChenXplorer** [comment]
hash 路由切换路由没问题，history路由切换出现问题，服务disconnect

**Comment by inottn** [comment]
You can try setting historyApiFallback to true~

**Comment by chenjiahan** [comment]
Rsbuild 0.1 has improved the support for html fallback, please upgrade and try 😄

**Comment by hunghg255** [comment]
oke, thank all, it works for me
