### ISSUE TITLE
[Bug]:An infinity loop in HMR occurs when saving the Unocss code

### ISSUE THREAD

**Issue by sixdjango** [web-infra-dev/rsbuild#654]
### Version

```sh
Macos:14.1.1 (23B81)
Chrome: 119.0.6045.159
Npm: 9.6.7
Rsbuild: 0.1.0
```

### Details

An infinity loop in HMR occurs when saving the Unocss code
<img width="323" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/100112640/033fbe85-5603-4870-a42e-ec6bcb0f06ee">

### Reproduce link

https://github.com/sixdjango/rsbuild-unocss

### Reproduce Steps

change Unocss code as needed,  then save it.

**Comment by chenjiahan** [comment]
@9aoy please help to check this issue

**Comment by 9aoy** [comment]
Rsbuild outputs dist files to disk, so when fileSystem `**/*` is set, it contains the dist file and always finds it updated 😂 
<img width="1052" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/22373761/ffede78e-7780-4005-8054-ea80c26eb283">

**Comment by chenjiahan** [comment]
This can be better:

```ts
export default defineConfig({
  content: {
    filesystem: [
      'src/**/*.{html,js,ts,jsx,tsx,vue,svelte,astro}',
    ]
  },
})
```

**Comment by chenjiahan** [comment]
Watch less files is good for the performance, just like Tailwind CSS:

![image](https://github.com/web-infra-dev/rsbuild/assets/7237365/e272d3f5-3c8f-4e87-a14c-09b9711d40d7)

**Comment by sixdjango** [comment]
sorry, this's my fault. But think you!🫡

**Comment by chenjiahan** [comment]
We can provide a guide for UnoCSS @9aoy
