### ISSUE TITLE
[Feature]: Provide an umd plugin

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rsbuild#70]
### What problem does this feature solve?

Provide an umd plugin to help users building umd outputs.

### What does the proposed API look like?

```js
pluginUmd({
  // maybe some options
});
```

**Comment by chenjiahan** [comment]
1. Disable the default split chunks config.
2. Configure library, librartTarget, umdNamedDefine and other options.

**Comment by imccode** [comment]
这个插件预计什么时候上线

**Comment by chenjiahan** [comment]
@imccode I will implement this plugin in this week.
