### ISSUE TITLE
[Bug]: pnpm installs rsbuild project dependencies styled-components throws an error while npm/bun works fine.

### ISSUE THREAD

**Issue by veaba** [web-infra-dev/rsbuild#736]
### version info

```sh
System:
    OS: Windows 11 10.0.22631
    Memory: 4.83 GB / 31.85 GB
  Browsers:
    Edge: Chromium (119.0.2151.72)
  npmPackages:
    @rsbuild/core: ^0.1.2 => 0.1.2
    @rsbuild/plugin-react: ^0.1.2 => 0.1.2
```

### Detail

`pnpm install ` catch `styled-components` errors info.

![pnpm image](https://github.com/veaba/rsbuild-pnpm-npm/raw/main/images/pnpm.png)

### Link

https://github.com/veaba/rsbuild-pnpm-npm

###  Setup

1、test pnpm `pnpm@8.6.11`

```shell
pnpm install
pnpm run dev 
```
The console catches styled-components error messages.

2、test npm `npm@9.5.0`
```shell
npm install
npm run dev
```
it's ok.

**Comment by chenjiahan** [comment]
This issue provides some background infomation for this: https://github.com/web-infra-dev/rspack/issues/4770

In Rsbuild, you can use the node polyfill to resolve this issue, ref: https://rsbuild.dev/plugins/list/plugin-node-polyfill

**Comment by chenjiahan** [comment]
Fixed in https://github.com/web-infra-dev/rspack/issues/4770
