### ISSUE TITLE
[Bug]: Failed to resolve crypto

### ISSUE THREAD

**Issue by Lzzzs** [web-infra-dev/rsbuild#766]
### 版本信息

```sh
System:
    OS: macOS 13.5
    CPU: (8) arm64 Apple M1
    Memory: 126.69 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 119.0.6045.199
    Safari: 16.6
  npmPackages:
    @rsbuild/core: 0.1.0 => 0.1.0 
    @rsbuild/plugin-react: 0.1.0 => 0.1.0
```

### 问题详情

pnpm dev 之后报错，build 一样报错

![image](https://github.com/web-infra-dev/rsbuild/assets/74575471/9dc0815e-0dcb-4409-9256-347f864fcc1b)

### 复现链接

https://github.com/Lzzzs/rsbuild-error

### 复现步骤

1. pnpm dev
2. 终端报错

**Comment by chenjiahan** [comment]
crypto is a Node.js module, you need to use https://rsbuild.dev/plugins/list/plugin-node-polyfill

**Comment by Lzzzs** [comment]
Thanks~
