### ISSUE TITLE
[Feature]: Https default config

### ISSUE THREAD

**Issue by Lzzzs** [web-infra-dev/rsbuild#768]
### 这个功能解决了什么问题？

我记得之前 Rsbuild 是支持直接将 https 设为 true 就会开启 https 服务。现在没办法用这种方式了吗，我看文档是需要自己配置密钥和证书

### 你期望的 API 是什么样子的？

```ts
server: {
  https: true
}
```

**Comment by chenjiahan** [comment]
之前有基于 [devcert](https://github.com/davewasmer/devcert) 提供自动生成的 HTTPS 证书，但是这种方式只能覆盖部分场景，而且 devcert 也不维护了。

因此推荐手动传入 HTTPS 配置，可以参考 https://web.dev/articles/how-to-use-local-https 这篇文章
