### ISSUE TITLE
[Feature]: Support for Tailwind CSS and UnoCSS

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rsbuild#77]
### What problem does this feature solve?

- https://github.com/unocss/unocss
- https://github.com/tailwindlabs/tailwindcss

### What does the proposed API look like?

Both of these two tools are easy to integrate, so we may not need to provide Rsbuild plugins for them, just provide some guides can be enough.

**Comment by sixdjango** [comment]
<img width="323" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/100112640/4dc0708c-c2c4-4a35-8a64-102f5ea8797b">
Hot update infinite loop when I save the code for unocss

**Comment by chenjiahan** [comment]
@sixdjango Can you create a new issue for this~

**Comment by 9aoy** [comment]
add using UnoCSS guide https://github.com/web-infra-dev/rsbuild/pull/674
