### ISSUE TITLE
[Feature]: Provide type declaration for PluginSolidPresetOptions

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rsbuild#783]
### What problem does this feature solve?

Provide type declaration for PluginSolidPresetOptions, the `solidPresetOptions` is `any` now.

```ts
export type PluginSolidPresetOptions = {
  // TODO: complete the type declaration
  solidPresetOptions?: any;
};
```

https://github.com/web-infra-dev/rsbuild/blob/main/packages/plugin-solid/src/index.ts#L3-L6

### What does the proposed API look like?

Ref: https://www.npmjs.com/package/babel-preset-solid

**Comment by lalalazero** [comment]
Hi~ I'd like to have a try for this.

**Comment by chenjiahan** [comment]
That would be great! ❤️
