### ISSUE TITLE
[Bug]: server.proxy.context type is incorrect (can be a function)

### ISSUE THREAD

**Issue by hverlin** [web-infra-dev/rsbuild#797]
### Version
`rsbuild 0.1.6`

### Details

https://www.npmjs.com/package/http-proxy-middleware `context ` option can be a function. 
```ts
export default defineConfig({
    server: {
        proxy: [
            {context: (pathname: string) => !pathname.startsWith(`/${appBasePath}`),}
        ]
    }
})
```

https://www.npmjs.com/package/http-proxy-middleware#context-matching:~:text=For%20full%20control%20you%20can%20provide%20a%20custom%20function%20to%20determine%20which%20requests%20should%20be%20proxied%20or%20not.

> For full control you can provide a custom function to determine which requests should be proxied or not.
```js
const filter = function (pathname, req) {
  return pathname.match('^/api') && req.method === 'GET';
};

const apiProxy = createProxyMiddleware(filter, {
  target: 'http://www.example.org',
});
```

---

The type declared by rsbuild is different:
https://github.com/web-infra-dev/rsbuild/blob/0d0716013912c203b2c0e0e15be8c9219e1616b4/packages/shared/src/types/config/server.ts#L6-L13

I have also noticed that the bundled `http-proxy-middleware` is not using the latest [version](https://github.com/chimurai/http-proxy-middleware/releases/tag/v2.0.6) of `http-proxy-middleware`, any reasons for it?

**Comment by chenjiahan** [comment]
Thanks for the feedback 😄 We will upgrade http-proxy-middleware and fix the type issue.
