### ISSUE TITLE
[Feature]: support modify bundler config by tools.bundler

### ISSUE THREAD

**Issue by 9aoy** [web-infra-dev/rsbuild#880]
### What problem does this feature solve?

tools.bundler can both works in rspack and webpack mode

### What does the proposed API look like?

like tools.webpack / tools.rspack

**Comment by xc2** [comment]
hello, would you please try the latest rsbuild version?

`tools.webpack`, `tools.rspack`, `tools.webpackChain` are all supported since `0.1.6` though they are not documented yet.

**Comment by chenjiahan** [comment]
Yes, `tools.rspack` is [documented](https://rsbuild.dev/config/tools/rspack), while `tools.webpack/webpackChain` are currently internal APIs for `@rsbuild/webpack`.

**Comment by chenjiahan** [comment]
I think the `tools.bundler` config is mainly used by Modern.js, as Modern.js needs to support both Rspack and Webpack. So we can just let Modern.js to implement it in the `@modern-js/uni-builder`, Rsbuild users can just use `tools.rspack`
