### ISSUE TITLE
[Feature]: Assets retry supports dynamic chunks

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rsbuild#91]
### What problem does this feature solve?

Currently the assets retry only supports initial chunks, we need to provide supports for dynamic chunks.

### What does the proposed API look like?

No extra configurations.

**Comment by lalalazero** [comment]
there's indeed some error when import() `bar.js` request, I need to do something like `import(/* webpackChunkName: "bar" */ './Bar')` which works, with only `import('./Bar')` couldn't work, does this what you mean ?

**Comment by chenjiahan** [comment]
We need to provide asset retry for all dynamic chunks, so webpackChunkName should not affect the results.

**Comment by lalalazero** [comment]
Hi~ 
I tried with block `bar.js` request and the retry plugin still works well. (since it listens to the `error` event, I wonder in what case it would fail ?)
![image](https://github.com/web-infra-dev/rsbuild/assets/20458239/0482d4c2-f835-4a9a-8c87-99018ab7e1ed)

I'm not sure if I understand this issue, though I'd like to help but I guess I need more guides.

**Comment by chenjiahan** [comment]
You are right 😂 I thought that async chunk would not trigger retry, but in fact it can be triggered in the existing implementation.

So this issue is a non-existent problem and can be closed. Thanks for your time to verify it 😄

**Comment by lalalazero** [comment]
😄  great! I'm glad I helped a tiny bit~ 🍻

**Comment by 9aoy** [comment]
I found that assets can be retried for dynamic chunks, but at this time, it is not establish a relationship with the original resource. Originally import would throw error, and cannot get the resource information in the callback of the original dynamic import request.

```
import ('./test').then(a => {
  console.log('a', a); // can't get it here
});
```

<img width="893" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/22373761/10a33974-e3a6-4dfa-b2e6-3743cea53d7b">

![20240123-111134](https://github.com/web-infra-dev/rsbuild/assets/22373761/1472471c-c47c-4e3c-ae4c-67ab4d7881db)

**Comment by chenjiahan** [comment]
@SoonIter is working on this 😄

**Comment by chenjiahan** [comment]
@SoonIter is implementing the solution in https://github.com/web-infra-dev/rsbuild/pull/2086

@SoonIter can you share some details of this?

**Comment by nanianlisao** [comment]
I previously looked into a general solution, similar to [webpack-retry-chunk-load-plugin](https://github.com/mattlewis92/webpack-retry-chunk-load-plugin). I think the advantage of this solution is that it's more compatible

**Comment by SoonIter** [comment]
> However, it's more invasive to the original process, which feels somewhat uncontrollable, and that's why I find it intimidating.

@nanianlisao  Yes, there has not been found a better way to achieve than to change the webpack runtime code logic e.g: `__webpack_require__.e` currently, just as what [webpack-retry-chunk-load-plugin](https://github.com/mattlewis92/webpack-retry-chunk-load-plugin) does. 

Fortunately, this solution has been widely practiced within my company, and the acceptance degree of our users is relatively high.

In recent months, rspack has just achieved relevant hooks to modify webpack runtime codes. https://github.com/web-infra-dev/rspack/pull/5370, my pr is based on these hooks.

What we do is to try our best to write the runtime code of this part and control the invasiveness as stable as possible. This should be a best-effort feature, and it cannot have too much impact on the core features of user's code. So, feel free to contribute any test cases of this feature to make it better together :D
