### ISSUE TITLE
[Feature]:  我认为我们需要给rsbuild增加一个copy命令，来实现自动复制终端network url

### ISSUE THREAD

**Issue by wChenonly** [web-infra-dev/rsbuild#946]
### 这个功能解决了什么问题？

对于rspack，内部使用了webpack-dev-server来启动服务，我在开发一个[插件](https://github.com/rspack-contrib/rspack-plugin-cli-copy)    来实现此功能，但是对于rsbuild，是基于rspack的，因此我觉得在rsbuild内部实现比较好。

### 你期望的 API 是什么样子的？

"dev": "rsbuild dev --copy",

类似下图
<img width="407" alt="image" src="https://github.com/web-infra-dev/rsbuild/assets/37658262/982dc88e-2bda-4738-97c9-bb681be10834">

如果可以的话，我来实现这个

**Comment by chenjiahan** [comment]
大部分场景直接配置 [startUrl](https://rsbuild.dev/config/dev/start-url) 或使用 dev --open 就可以满足，拷贝 URL 是不是属于比较小众的场景呢

**Comment by wChenonly** [comment]
> 大部分场景直接配置 [startUrl](https://rsbuild.dev/config/dev/start-url) 或使用 dev --open 就可以满足，拷贝 URL 是不是属于比较小众的场景呢

这个主要是在手机端 混合开发的时候，会经常用，之前vuecli是有这个，然后vite是写了插件处理的

**Comment by chenjiahan** [comment]
了解，如果开发了 Rspack 插件，那有需要的用户可以在 Rsbuild 里注册这个 Rspack 插件，这样就避免重复开发了

**Comment by wChenonly** [comment]
> 了解，如果开发了 Rspack 插件，那有需要的用户可以在 Rsbuild 里注册这个 Rspack 插件，这样就避免重复开发了

那也可以，我是没有看到Rsbuild如何注册Rspack插件

**Comment by chenjiahan** [comment]
嗯嗯，看这里：https://rsbuild.dev/zh/guide/basic/configure-rspack
