### ISSUE TITLE
Synchronous and check modern.js builder changes

### ISSUE THREAD

**Issue by 9aoy** [web-infra-dev/rsbuild#97]
init rsbuild & rsbuild/webpack from https://github.com/web-infra-dev/modern.js/commit/4d9ee16194fc3666179a8c93cc7f5fe114c5c28e. 

We need to check and synchronize all changes starting from this commit.

**Comment by chenjiahan** [comment]
TODO: https://github.com/web-infra-dev/modern.js/pull/4585

**Comment by chenjiahan** [comment]
TODO：https://github.com/web-infra-dev/modern.js/pull/4849

**Comment by chenjiahan** [comment]
TODO：https://github.com/web-infra-dev/modern.js/pull/4855
