### ISSUE TITLE
[Feature]: dev was the clean-up of dist deliberate ?

### ISSUE THREAD

**Issue by zhousg** [web-infra-dev/rsbuild#978]
### What problem does this feature solve?

After packaging, the product is cleaned up when dev is started again

### What does the proposed API look like?

Is it possible to provide an api such as `clear`

**Comment by chenjiahan** [comment]
Rsbuild already provides an option for this 😄: https://rsbuild.dev/config/output/clean-dist-path

**Comment by zhousg** [comment]
After closing 'build' does not clean up

**Comment by chenjiahan** [comment]
Yes, if user only want to clean up when starting dev, this should works:

```js
export default {
  output: {
    cleanDistPath: process.env.NODE_ENV === 'development',
  },
};
```

**Comment by zhousg** [comment]
oh control yourself，ok
