### ISSUE TITLE
[Bug]: html.inject false not works 

### ISSUE THREAD

**Issue by 9aoy** [web-infra-dev/rsbuild#987]
### Version

```sh
rsbuild 0.2.5
```

### Details

 I set inject false and use custom template. expect script only inject once, but actually inject twice

rsbuildConfig: 
```ts
    rsbuildConfig: {
      html: {
        inject: false,
        template: './static/index.html',
      },
    },
```

template:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>custom template</title>
    <%= htmlWebpackPlugin.tags.headTags %>
    <script src="//example.com/assets/a.js"></script>
  </head>
  <body>
    <div id="test-template">xxx</div>
    <div id="root" />
    <%= htmlWebpackPlugin.tags.bodyTags %>
  </body>
</html>
```

![20231218-151553](https://github.com/web-infra-dev/rsbuild/assets/22373761/4af18b42-36be-492d-a7f0-b6081a03d5e7)

### Reproduce link

https://github.com/web-infra-dev/rsbuild/blob/0759599e6d280b72a4a7bbc293be4c15b9a5316c/e2e/cases/html/inject/index.test.ts

### Reproduce Steps

- cd e2e
- pnpm test:rspack html/inject
- view dist/index.html content

**Comment by xc2** [comment]
confirmed. would you please assign to me if there's no one working on it at the moment.

**Comment by 9aoy** [comment]
> confirmed. would you please assign to me if there's no one working on it at the moment.

@xc2 Of course, thanks for your willingness to fix this~

**Comment by xc2** [comment]
will fix by today(+0800).

**Comment by xc2** [comment]
ready for review, please check
