### ISSUE TITLE
[Feature]: Provode .mjs artifact 

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rsbuild#99]
### What problem does this feature solve?

Provode .mjs artifact for ESM imports.

### What does the proposed API look like?

Both CommonJS and ESModule should be supported.

**Comment by chenjiahan** [comment]
@10Derozan cc

**Comment by fi3ework** [comment]
Quotes from 1.0 roadmap

> Before the release of v1.0, we need to finish the ESM support for all packages

Given Rsbuild is a quite new project, we have more choices on this topic based on Vite's valuable experience.

1. **Only ship ESM dist to NPM**. This might be too bold as we have given up users who can't migrate to ESM project.
2. **Only ship async API from rebuild and @rsbuild/shared in CJS version**. API is for upper-level framework, so this won't break anything as the ecosystem will grow up after 1.0, also this could push the upper-level to embrace ESM. When we migrate to ESM only in the future, we won't blocked from dropping sync API support.

Also, there's a risk of loading duplicated modules from ESM and CJS from the same source module distributed in CJS and ESM. A thin ESM wrapper to support ESM would be a more secure method.

**Comment by chenjiahan** [comment]
It would be very nice if we could use the ESM wrapper to keep compatible with CJS users.

Add some information for this:

- Rspack does not yet have full ESM loader support (https://github.com/web-infra-dev/rspack/issues/5735)
- our packages have exported some constants (such as version), which may not be converted to async API.
- All Modern.js packages are still use the CJS API..
